### ISSUE TITLE
Escape quotation marks in text block inputs

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#1009]

**Comment by zfi** [comment]
Any details on this issue?

**Comment by MatzElectronics** [comment]
Yes, sorry!  If you type a " or a % into the string-type block, it will break on compile.  They need to be escaped.  Fix in demo, needs testing.

**Comment by MatzElectronics** [comment]
Tested & failed, % is somehow adding in triplicate...

**Comment by MatzElectronics** [comment]
Tested and verified.
