### ISSUE TITLE
Enhance "Request Password Reset" success response

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#101]
On the Forgot Password feature's __Request Password Reset__ page, when a user enters a valid email address and selects the _Confirm_ button, the response simply clears the field, taking the user back to this:

![image](https://cloud.githubusercontent.com/assets/1266318/13226973/235fdbce-d949-11e5-93dd-e030b6e1e05e.png)

Please enhance this page's response to instead display a green notification bar under the "Request password reset" header (right where the red error response would be) that says:

> A password reset email was sent to < email_address >.  Please look for the message in that email account's inbox (and spam box) and follow the message instructions to reset the password.

;where < email_address > is the address that they had entered.

**Comment by michel-cf** [comment]
Is this still needed, even though the user is redirected to a separate confirmation page?

**Comment by PropGit** [comment]
If it does send them to a separate confirmation page, this item is not needed because the point was to give some definitive feedback (which I wasn't seeing before).
