### ISSUE TITLE
Highest/lowest value of block broken

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#1010]

**Comment by zfi** [comment]
Any details on this issue?  Considering creating a Snipe label for subject-only issues.

**Comment by MatzElectronics** [comment]
The operator that was used for this block appears to be a SPIN operator, and does not work in C.  It's an easy fix - just need to alter the generated C.

**Comment by mrodriguez-parallax** [comment]
Highest/Lowest Block compares two values and correctly outputs the highest or lowest value.
