### ISSUE TITLE
Make pin block displays strangely after it's been uncollapsed

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#1011]
![image](https://cloud.githubusercontent.com/assets/19737272/25165997/fe98537a-248d-11e7-9501-6c593499e996.png)

**Comment by MatzElectronics** [comment]
Ugh - this is a bug in Blockly's core... :(

**Comment by mrodriguez-parallax** [comment]
Block passed testing. Does not show a series of repeating numbers after uncollapsed.
