### ISSUE TITLE
Block Request - Add in/decrement block to S3 menu

### ISSUE THREAD

**Issue by CarolHazlett** [parallaxinc/BlocklyProp#1015]
![first round](https://cloud.githubusercontent.com/assets/8153013/25300796/90d99a10-26cc-11e7-905a-5d3440ce1dbb.jpg)
![many squares](https://cloud.githubusercontent.com/assets/8153013/25300797/90dc28ac-26cc-11e7-8482-cca9ccd2996b.jpg)
I would like to be able to increment a variable in order to make designs that repeat in increasing sizes. An example is a repeating square with each one a little bigger than the next. I could then substitute the time for making the length of the sides with a variable that could be incremented. There are a lot of applications this would work for with the Scribbler.

**Comment by MatzElectronics** [comment]
We have this block, so we can just add it to the menu

**Comment by MatzElectronics** [comment]
No available in demo.  Closing.
