### ISSUE TITLE
"Request Password Reset" doesn't send email

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#102]
On the __Request password reset__ page, entering a valid (registered) email address and clicking the _Confirm" button supposedly transmits an email, but none is ever received.

If there is an error contacting the SMTP server, please make the response indicate an error like, "Error: unable to send password reset email at this time; please try again later or contact the system administrator."

**Comment by michel-cf** [comment]
Currently sending emails is done asynchronously to have fast response times for the user. This does also mean that I can't show any results from sending the email.

Should this be changed?

**Comment by PropGit** [comment]
I see.  No, I was assuming that the communication with the email server was the issue; but I think you've determined it was a database problem that seems to occur some time after reboot.  Let's leave it as is for now regarding email.

But, if there's an additional error situation you can trap and display a meaningful message, that would be best because I think it wasn't displaying an error.  This may have been simply because of the other elusive problem that prevented me for registering and/or using an account within our domain where email responses are currently limited to.  In fact, I'm almost sure of that.  This issue can safely be closed by you if you feel that same.
