### ISSUE TITLE
lsm9ds1 IMU get tilt along specified axis compile error

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#1023]
returns error: ...'__imuS' undeclared:
More details here: http://forums.parallax.com/discussion/166580/lsm9ds1-imu-get-tilt-along-specified-axis-returns-error-imus-undeclared-first-use

**Comment by mrodriguez-parallax** [comment]
Blockly outputs an error when using IMU blocks. Blockly assigns a second variable without being asked to do so.  It created an accel2 for each axis, they are located on line 26 through 28. In my blocks I never created an accel2. 

https://github.com/parallaxinc/BlocklyProp/issues?q=is%3Aissue+is%3Aopen+label%3A%22Requires+Verification%22



![image](https://cloud.githubusercontent.com/assets/20686764/26705256/e7a57fca-46e9-11e7-979a-f9f092c45e00.png)

**Comment by MatzElectronics** [comment]
Fixed, but there is a new, unrelated error address inside of a new issue.  Closing this one.
