### ISSUE TITLE
S3 C condense blocks

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#1026]
There are blocks specific to the Scribbler that are otherwise identical to other C blocks.  The goal is to minimize the total number of block definitions and remove duplicates.

**Comment by MatzElectronics** [comment]
spin_integer
scribbler_loop
scribbler_loop_limited
math_angle?
others...?

**Comment by zfi** [comment]
Can the candidate blocks get listed here before they are removed from code? Yeah, like those..

**Comment by MatzElectronics** [comment]
Yup - As I find them I'll add them

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by MatzElectronics** [comment]
Also, most of the scribbler_if_... blocks - after they've all been transmogrified.

**Comment by wstodghill** [comment]
Did we lose the Sony Remote?

**Comment by MatzElectronics** [comment]
Shouldn't have, but I'll check.

**Comment by MatzElectronics** [comment]
It appears I did nuke it - I'll bring it back.  Thanks for the catch!

**Comment by wstodghill** [comment]
Thank you - Just starting to play a bit - Looks great so far! Clean...

**Comment by MatzElectronics** [comment]
Oh good, thank you!

**Comment by MatzElectronics** [comment]
Status update: some of these will be okay to condense right away - they are directly mapped to new blocks with the Transmogrifier.  Others will have to slowly work themselves out as people open and re-save their projects.

**Comment by wstodghill** [comment]
Graphing and grayscale are still not available on the S3, correct?

**Comment by MatzElectronics** [comment]
Grayscale should be...

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by MatzElectronics** [comment]
Got this as far as safely possible.  Closing.
