### ISSUE TITLE
Register page is insecure

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#103]
The Register page is insecure.

![image](https://cloud.githubusercontent.com/assets/1266318/13233379/4e7478b4-d968-11e5-8516-be1cf5c5d3fc.png)

**Comment by michel-cf** [comment]
As you can see in the url, it works using https. Any warnings the browser gives is because we are working with a self signed certificate in the demo environment.

**Comment by PropGit** [comment]
Ugh, sorry, you're right.  I should have realized that.
