### ISSUE TITLE
Adjust results block's dead battery threshold

### ISSUE THREAD

**Issue by mrodriguez-parallax** [parallaxinc/BlocklyProp#1036]
Pull back dead battery recommendation threshold for Activity Bot's Display Calibration results block. The results block outputs comment that batteries are dead on Activity Bot while bot still at 7V.

**Comment by MatzElectronics** [comment]
For @AndyLindsay

**Comment by MatzElectronics** [comment]
@AndyLindsay was the low battery level adjusted in a recent revision of abdrive?

**Comment by MatzElectronics** [comment]
Included in newest Simple Libraries update.  Closing.

**Comment by zfi** [comment]
@MatzElectronics Is there a commit ID or the PR in Simple Libraries for this? Or is this already baked into the current release of the library?

**Comment by MatzElectronics** [comment]
Baked in ;)

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>
