### ISSUE TITLE
Feature request: view in grayscale

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#1039]
Why?
- So when we do a textbook for this it can be in black & white
- Teachers printing worksheets
- Individuals with disabilities?

Also
- Because I think it will be easy to implement

**Comment by JohnKauffman** [comment]
Also useful when printing code to paste onto poster with a trace students make with marker. When trace is displayed on wall, other students can see the code. We have been doing this to date: screenshot, paste to Word, crop/enlarge, print. We are getting OK-enough results but proper B/W would be more readable.

**Comment by MatzElectronics** [comment]
This is now working, but I'm keeping it buried until we map the colors to an "equivalent" grayscale value and create a menu option to toggle it.  In demo, just add &grayscale=1 to the URL in your browser.

**Comment by MatzElectronics** [comment]
Feature exists and is working using a "secret" URL tag.  Now depends on non-volatile user settings/preferences #997.  Closing.
