### ISSUE TITLE
Register page doesn't accept period (.) in email address? (or some other problem)

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#104]
Received error "A problem occurred" when _Register_ is clicked.  This may have to do with entering a period (.) in the email address's username field; not sure.  The same error occurred when a plus (+) was entered instead of the period.

What "problem occurred?"  I can't tell, the error message is too generic.

![image](https://cloud.githubusercontent.com/assets/1266318/13233903/ee4885ea-d96a-11e5-90ee-30c2e8828996.png)

NOTE: After doing this, the email can not be registered anymore because "Email already used" appears during attempt; so the above attempt must have stored the email address in the database, but because the operation failed in some way, the user is now stuck.

**Comment by michel-cf** [comment]
Probably a Cloud-session sleeping database connection problem.
