### ISSUE TITLE
Javascript errors when creating a new project

### ISSUE THREAD

**Issue by paragitadmin** [parallaxinc/BlocklyProp#1048]
The browser is reporting the following JavaScript errors after a new project is created. The errors appear after the editor canvas is rendered. 

```
13:16:41.085 XML Parsing Error: no root element found
Location: http://172.16.133.240:8080/blockly/frame/framec.jsp
Line Number 1, Column 1:  framec.jsp:1:1
```
```
13:16:41.092 uncaught exception: Blockly.Xml.textToDom did not obtain a valid XML tree.  (unknown)
```
```
13:16:41.562 SecurityError: Failed to load worker script at "https://s3.amazonaws.com/aws-blockly-cdn.parallax.com/democdn/ace/worker-xml.js"  (unknown)

        
```

**Comment by MatzElectronics** [comment]
I wonder if the db needs to contain a default value for the code field - mysql can do that, right?  Give it that 42+6 string (empty xml file)?

**Comment by zfi** [comment]
Yes, that is possible but the issue here is that there is JavaScript code trying to reference an invalid data structure. Whatever is responsible for loading that data structure isn't getting it done or is quietly failing during the attempt. Let's look at that before we add more database overhead.

**Comment by MatzElectronics** [comment]
Fix tested and verified.
