### ISSUE TITLE
S3 - drive a turn motor block - label clarification?

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#1049]
![drive_a_turn block](https://cloud.githubusercontent.com/assets/8891440/26337770/e2cdd99e-3f40-11e7-95de-cd814b51cd87.JPG)

Been playing and have a question. Based on tests, the setting of the degrees (+ or -) determines CW or CCW rotation. That means that the wording in the block is a bit misleading. Shouldn't it say...

drive a turn
that is (degrees + or -) ..............................._This should include the symbols_
around a radius in "inches" of..................._"inches" is the drop down selection_
at speed (%)

**Comment by MatzElectronics** [comment]
Ok.  Sounds good.  Could you test negative numbers in both the degrees and
radius inputs, and see if what your recommending still holds true?  If so
I'm happy to make that change.

Thanks!

**Comment by wstodghill** [comment]
@MatzElectronics - will do and report back. Thanks for all you do!

**Comment by wstodghill** [comment]
@MatzElectronics - Here are the results...

If the forward moves the S3 in the direction of the light sensors and backward moves the S3 in the direction of the tail wheel, then...

positive (+) degrees and positive (+) radius = forward CW turn
positive (+) degrees and negative (-) radius = forward CCW turn
negative (-) degrees and positive (+) radius = backward CCW turn
negative (-) degrees and negative (-) radius = backward CW turn

**Comment by MatzElectronics** [comment]
@wstodghill should go ahead with that label change?

**Comment by MatzElectronics** [comment]
Or we could do what you suggest, AND add "(+/-)" right after to radius to indicate that it can be negative...?

**Comment by MatzElectronics** [comment]
And once the tutorials get re-published, maybe an addition of a try this where you experiment with the sign in both boxes?

**Comment by wstodghill** [comment]
@MatzElectronics - I think we could make the degrees wording say...
![message1](https://cloud.githubusercontent.com/assets/8891440/26649477/c7a27d24-460b-11e7-8d48-bcced838b911.JPG) adding 
![message2](https://cloud.githubusercontent.com/assets/8891440/26649492/d033f1c0-460b-11e7-9152-a28d41d34f4a.JPG) That should clear it up. 

I love the idea of adding a try this to the tutorial!

**Comment by MatzElectronics** [comment]
I opted for just putting (+/-) on both, indicating that they can be pos or neg, but for more info, users can go to the help and/or tooltip.

**Comment by wstodghill** [comment]
@MatzElectronics - great!
