### ISSUE TITLE
Login page is insecure

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#105]
The Login page accessed from the _Login/Register_ link is at an insecure address.  The address is blocked out in the image below as it's our dev server, but it's sitting at: http://< our_dev_server >/blockly/login.jsp:

![image](https://cloud.githubusercontent.com/assets/1266318/13259328/ba75a620-da0b-11e5-9263-5a0f3fdfcb44.png)

**Comment by PropGit** [comment]
Note: I can not tell if the login overlay (that appears when trying to access a project without first being logged in) is over a secure connection or not.

![image](https://cloud.githubusercontent.com/assets/1266318/13259421/2021579e-da0c-11e5-913f-02c5c4069267.png)

**Comment by michel-cf** [comment]
The login page can not use https because that would mean the user is only authenticated on https pages, not on http pages.

Because of this, the login form sends it request to blocklyprop-auth over https.

So, while the form is shown insecure, your credentials are never transmitted over an insecure connection.

**Comment by PropGit** [comment]
Okay, I see; I had a slight misunderstanding, but now I get it.

So why is the Register page different?  It is an https page.

**Comment by michel-cf** [comment]
Because the register page doesn't log you in. The same for the password reset request/confirm and email confirm.

**Comment by PropGit** [comment]
Good, that's what I was hoping you'd say.  This issue is working properly then; it is resolved as being due to a misunderstanding only.
