### ISSUE TITLE
Values / System blocks not visible for non-PAB board types

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#1050]
@MatzElectronics this block does not appear under the "other" board types. I didn't check the FLiP or other boards.

**Comment by zfi** [comment]
As designed

**Comment by kgracey** [comment]
This exposes it to the public users without documentation, I believe. I thought the opposite approach was the plan: use other board type so it can be used by the requesting person (JM) until we document it, at which time it's added to all board types.

**Comment by MatzElectronics** [comment]
Closing - moving the discussion to internal docs/Slack
