### ISSUE TITLE
Allow BIN and HEX values in array setup.

### ISSUE THREAD

**Issue by JonMcPhalen** [parallaxinc/BlocklyProp#1053]
Microcontrollers are focused on IO, and IO is easier to deal with using binary numbers.  To that end, it seems like any block that requires a number should allow binary, hex, or decimal input. Parallax uses indicated binary (%) and hex ($), so this should not be a big problem, should it?

Here's an example:

![image](https://user-images.githubusercontent.com/4042568/27255751-ffa7e500-5359-11e7-8542-cd666976809a.png)

Without binary input, the array **fill block** requires a comment. IMHO, code should be as self-documenting as possible, and a step in this direction is the use of binary notation when sending patterns to IO pins.

Blockly is a visual system -- binary and hex notation allow us opportunities to "visualize" values (especially the former).

Link to project:
-- http://demo.blockly.parallax.com/blockly/projectlink?id=1011&key=87823807-1709-45b0-b2bf-037a7c03a236

**Comment by wstodghill** [comment]
As per my comment on the BlocklyProp Facebook page - this example code is very interesting (IMO) and demonstrates the unlimited potential in BlocklyProp!

**Comment by MatzElectronics** [comment]
There are two ways to solve this - by adding a drop down menu to the block that allows the user to specify what they are filling the array with (hex, bin, dec, musical notes?), or allowing 0x and 0b prefixes.  The former option would allow us to add something like musical notes and allow us to keep the strict regex that scrubs the user's input.  The latter option would allow multiple types to be added at the same time, but would be restricted to bin, hex, and dec numbers.  Thoughts?

**Comment by JonMcPhalen** [comment]
I'm okay with the prefixes so I can mix types if needed. Musical notes are a specialty thing, and should not blow up fundamental programming.

**Comment by MatzElectronics** [comment]
@JonMcPhalen you can now use '0x' and '0b' prefixes for hex and bin respectively.
