### ISSUE TITLE
The Demo BlocklyProp Beta Site is down! 

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#1059]
Can't log it on Saturday night 06/24/2017.

**Comment by zfi** [comment]
Login attempts on the Demo site were failing when the authentication request was submitted to the Cloud Session service and the service was refusing the connection. The BlocklyProp service detected the error and generically failed the login attempt without providing any details.

The Cloud Session service is now accepting connections again and login attempts are once again functional.

**Comment by PropGit** [comment]
Thanks @zfi.

**Comment by zfi** [comment]
Looking at what caused the service to start blocking. Creating an issue in the Cloud Compiler project.

**Comment by wstodghill** [comment]
@zfi and @PropGit - Thanks all. Working in Louisiana.

 Now that you have an issue set somewhere else to keep an eye on this, should this one be closed?

**Comment by zfi** [comment]
Added issue to the Cloud Compiler project to provide a monitor port.
https://github.com/parallaxinc/Cloud-Compiler/issues/15

Closing this issue.
