### ISSUE TITLE
Reset Requested page is missing green success bar on the success message

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#106]
The Reset requested response page should have the "Please check your email" message shown with a green background, like on the email confirmation request page.  Here's what it looks like now:

![image](https://cloud.githubusercontent.com/assets/1266318/13259739/8bd4ccb8-da0d-11e5-8ae3-1c90d55c6f4d.png)

**Comment by michel-cf** [comment]
Changed

**Comment by PropGit** [comment]
Verified.
