### ISSUE TITLE
Binary Array Starting with 0

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#1061]
I encountered a problem while working with the array element block where an array starting with 0 will automatically delete every digit up until a non zero digit is reached.

![capture1](https://user-images.githubusercontent.com/20099916/27648602-f442b176-5be3-11e7-9700-e5557d2eead6.PNG)

![capture2](https://user-images.githubusercontent.com/20099916/27648611-f99a0052-5be3-11e7-91bc-e17a8dd4464b.PNG)

For example here I had an 8 bit segment 00110111 typed in but the code and block produced 110111. 
`  if (11 < 16 && 11 >= 0) digits[11] = 110111; `

However on the learn.parallax blockly documentation for the 7 segment display, the blocks actually display the leading 0's.

![capture3](https://user-images.githubusercontent.com/20099916/27648996-3d76d948-5be5-11e7-9bf9-9deb4a18921c.PNG)

Is there something that was changed or something I am missing with these blocks?

**Comment by CarsonGracey** [comment]
Not a bug, I was using the decimal block that is default in respect to array blocks. The binary block does work as intended.

**Comment by zfi** [comment]
@MatzElectronics I am going to assume that our users are going to encounter this from time to time. If a decimal value isn't going to work here, can the receiving block's affinity be set to not allow a decimal block to attach?

**Comment by wstodghill** [comment]
@CarsonGracey - great to have you back for Summer. Congrats on your graduation and school next fall! You've gotten more done in a few days at Parallax than I get done in a month.

**Comment by MatzElectronics** [comment]
I'm not entirely sure - but I've been wondering about this in a couple of
other places as well.  If not, we should at least be able to sense
potential problems and display a warning icon.  Thanks for reopening.

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by PropGit** [comment]
Maybe the warning is the best solution because an array can logically hold numerical data that is interpreted (viewed) in any base, right?  Which means it's not illegal nor unadvisable to use a decimal block; however, a decimal block with leading zeros and containing just zeros and ones is a good indicators that the user is unintentionally using a decimal block as a binary block.

**Comment by MatzElectronics** [comment]
Closing - I'm going to call this a documentation issue.  Closing
