### ISSUE TITLE
Blocks vertically above their initializer throw "missing initializer"

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#1068]
This happens when a block needs an initializer and is in a function definition block that is placed vertically higher in the workspace than the start of the main program.

**Comment by MatzElectronics** [comment]
Solving this will involve doing a block search in the block generator (not the propc generator) and passing the result of that down instead of relying on the propc generator to look for the initializer within the propc definition staging arrays.

**Comment by MatzElectronics** [comment]
I'm finding a solution here - just a matter of working through it...  I'll push to demo when drafted.

**Comment by CarsonGracey** [comment]
Tested and Verified.
