### ISSUE TITLE
Variable values don't update when unpausing the graph

### ISSUE THREAD

**Issue by CGracey** [parallaxinc/BlocklyProp#1069]
The graph function correctly updates the variables (on the right) but when the graph is paused then unpaused. However, the variables stay at the same values from when the graph was paused even though the lines continue to correctly update. 

For example, I paused the graph when "pwmGraph" was at 90, unpaused the graph and made "pwmGraph" go down to 0 as you can see from the line in the second picture but the variables on the right didn't update.

![capture](https://user-images.githubusercontent.com/20099916/27926980-1ce3d95a-623f-11e7-98dd-185ab14f634f.PNG)

![capture2](https://user-images.githubusercontent.com/20099916/27926986-21ee6884-623f-11e7-9142-5a6d751e9466.PNG)

**Comment by MatzElectronics** [comment]
Thanks for the catch!  I'll try to figure out what's going on.

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by MatzElectronics** [comment]
Tested and verified
