### ISSUE TITLE
Graph doesn't record data

### ISSUE THREAD

**Issue by CGracey** [parallaxinc/BlocklyProp#1070]
Working on a project and roughly every 5 minutes the graph won't display the line data. The variables on the right are still constantly updating so the serial terminal is working. It looks like reloading the page solves the problem but it comes back a few minutes later.

Here are the graph blocks in question:

![capture2](https://user-images.githubusercontent.com/20099916/27929294-32df7108-6247-11e7-8de1-de7331850465.PNG)

![capture](https://user-images.githubusercontent.com/20099916/27929171-ae99a7ec-6246-11e7-86af-e376a68aac59.PNG)

**Comment by MatzElectronics** [comment]
Carson, could you give me a bit more detail on this error?  Does it just
disappear even though its been running, or it this what happens have it's
been closed and reopened?  Is this is demo or production (or COPPA)?

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by MatzElectronics** [comment]
Tested and verified
