### ISSUE TITLE
Disabled block still runs

### ISSUE THREAD

**Issue by CGracey** [parallaxinc/BlocklyProp#1073]
Exactly what the title says. I disabled the block below in a project but the block operated as if it were enabled. Also, the block didn't produce any C code in the project. So it was disabled, didn't produce any code in blockly, yet it still ran normally. This happened on Google Chrome build 59.0.3071.115 and the production build of Blockly.

Steps to reproduce:

1. Disable the block
2. Save the project
3. Reload the page

That's all, you will see that the bug appeared if the blocks inside the disabled block are not yellowed out. (see below)

![capture](https://user-images.githubusercontent.com/20099916/28033654-c75d7a54-6563-11e7-87bf-459bae4df9ba.PNG)

Steps to fix:

1. Enable block
2. Disable block

It is important to note that I haven't found a permanent fix as every time the page is reloaded while the block is disabled, it goes back to the picture above.

EDIT: I was also using the graphing block when doing this and the code from said block ONLY executed when I closed the graph, not while the graph was open.

Link to the project for those interested: http://blockly.parallax.com/blockly/editor/blocklyc.jsp?project=8651#

**Comment by MatzElectronics** [comment]
I can't seem to replicate this behavior - can anyone else give it a try?

**Comment by MatzElectronics** [comment]
Added if (!this.disabled) inside of the propc generators.  Seems to have corrected these types of issues.
