### ISSUE TITLE
S3 double-check all tooltips and help links

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#1074]

**Comment by CarsonGracey** [comment]
I'll be sure to get on this when I get back from Irvine next week

**Comment by CarsonGracey** [comment]
All tooltips appear to be fine but a few help links need to be updated.

There is no help link for the reset block http://learn.parallax.com/s3-blocks/factory-reset 

![capture1](https://user-images.githubusercontent.com/20099916/28799899-39ef8caa-75ff-11e7-89ef-f8a3e5009c86.PNG)

There is a help link but it doesn't include this block on the page http://learn.parallax.com/support/reference/scribbler-3-robot-block-reference/actions/motors 

![capture2](https://user-images.githubusercontent.com/20099916/28799902-3e1102fa-75ff-11e7-837b-e3a9796ad5d1.PNG)

No help link for the microphone block http://learn.parallax.com/s3-blocks/microphone

![capture3](https://user-images.githubusercontent.com/20099916/28799998-a2a01d5a-75ff-11e7-8090-d401859ed0a0.PNG)

This one has no right click help option

![capture4](https://user-images.githubusercontent.com/20099916/28801676-718b40fc-7607-11e7-9c14-3cb35ba3cda7.PNG)

This one has a help link but the block isn't on the page http://learn.parallax.com/support/reference/scribbler-3-robot-block-reference/simple-scribbler/simple-sensors 

![capture5](https://user-images.githubusercontent.com/20099916/28803486-cd407b38-7611-11e7-95d3-065125833449.PNG)

Other than those everything looks good.

**Comment by CarsonGracey** [comment]
While checking those I came across a few more that require updates.

These three blocks don't have a help page either: http://learn.parallax.com/s3-blocks/io 

![capture](https://user-images.githubusercontent.com/20099916/28895655-1fde905a-778e-11e7-9be3-84d9fc85a70e.PNG)

The servo blocks have a help page but still aren't included in it: http://learn.parallax.com/support/reference/scribbler-3-robot-block-reference/actions/motors 

![capture2](https://user-images.githubusercontent.com/20099916/28895661-24400dae-778e-11e7-8861-23ef0292c033.PNG)

Doesn't have a help option, should go to this page: http://learn.parallax.com/support/reference/scribbler-3-robot-block-reference/sensors/line 

![capture3](https://user-images.githubusercontent.com/20099916/28895666-27be5f08-778e-11e7-8d3b-097b9d8149de.PNG)

Currently redirects to the wrong page, should be same as above: http://learn.parallax.com/support/reference/scribbler-3-robot-block-reference/sensors/line 

![capture4](https://user-images.githubusercontent.com/20099916/28895671-2b1a6688-778e-11e7-9f3f-e5a18277be5e.PNG)

**Comment by MatzElectronics** [comment]
Okay, @CarsonGracey please recheck the blocks you highlighted, they should all be working now.

**Comment by CarsonGracey** [comment]
All the blocks have correct links/tool tips now.

**Comment by MatzElectronics** [comment]
Tested and verified
