### ISSUE TITLE
Prevent, or convert, a number printed as text in a terminal text block

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#1075]
I just accidentally created this:

![image](https://user-images.githubusercontent.com/1266318/28046800-12d206f8-659b-11e7-89d5-52f6fd356d04.png)

which causes compiler warnings:
```
single.c: In function 'main':
single.c:25:5: warning: passing argument 1 of 'print' makes pointer from integer without a cast [enabled by default]
/opt/parallax/Workspace/Learn/Simple Libraries/TextDevices/libsimpletext/simpletext.h:275:5: note: expected 'const char *' but argument is of type 'int'
```

and unintended terminal output:

![image](https://user-images.githubusercontent.com/1266318/28046855-721ae684-659b-11e7-9f71-de6f920e5675.png)

Can we either prevent a numeric variable block from being placed in a Terminal print text block (probably not) or can we detect that and automatically convert the numbers to text?

**Comment by MatzElectronics** [comment]
I think we actually can prevent it from connecting.  It knows that it's a variable of type int, and we can designate the output of a block to be a string or a number, and allow or disallow connections accordingly.

**Comment by MatzElectronics** [comment]
Was able to mostly satisfy this...will prevent 99% of cases where a user tried to attach a block that is not of the proper type, and the variable blocks can now self-detect their type and behave accordingly.  Please test.

**Comment by MatzElectronics** [comment]
Tested and verified
