### ISSUE TITLE
Uploading blocks to different board types should return an error

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#1077]
When uploading block files to different board types, ex. Activity Board to FLiP Board, it should return an error message that says something along the lines of "Error: Attempted block upload from incompatible board type." Currently all that happens is the page just goes blank until it is refreshed which returns the project to normal.

**Comment by zfi** [comment]
A couple of question about this process; Is the board type contained within the exported block file? On Import, is there already code to identify the board type defined in the import file?

**Comment by MatzElectronics** [comment]
Normally it does provide exactly that warning - and if it isn't right now,
then something is broken. l'll take a look.

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by MatzElectronics** [comment]
This appears to be working now.  Tested and verified.

**Comment by CarsonGracey** [comment]
Not sure if it's just my end but there is still no error on chrome for me, the page still goes blank.

**Comment by CarsonGracey** [comment]
Looks like I was on production, coppa has it working.
