### ISSUE TITLE
Register confirmation email doesn't use same BlockyProp domain

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#108]
The account registration confirmation email uses different BlockProp domain that what was used to access BlockyProp.  The domain in this example is the short dev server IP address, instead of the longer dev domain we've switched to.  The link still works, but I wanted to draw attention to this in case it was unintentional and in case it would mean a problem for our public launch of BlocklyProp.

![image](https://cloud.githubusercontent.com/assets/1266318/13260525/aeff774e-da10-11e5-9d93-433603737520.png)

**Comment by michel-cf** [comment]
Although it was not intensional, I was aware of this. Both the email templates should be reviewed and updated before we go public.

**Comment by PropGit** [comment]
Okay.  I'll make a separate issue for that.
