### ISSUE TITLE
COPPA registration birthday doesn't work for Aug-Dec

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#1086]
No matter the year/age when registering for COPPA, the parent email input disappears if you select a a month between August and December.

![capture](https://user-images.githubusercontent.com/20099916/28281761-fb58a148-6adc-11e7-92f2-65ee8b2949f0.PNG)

This still happens if you are under 13.

![capture1](https://user-images.githubusercontent.com/20099916/28281820-321e4dea-6add-11e7-88d6-b86497452df3.PNG)

When you try to register without the parent email while having the month set between aug and dec, it asks for a sponsor email address still.

**Comment by MatzElectronics** [comment]
Should be available for testing after 11:45

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by CarsonGracey** [comment]
Verified working on demo
