### ISSUE TITLE
Email confirm link doesn't work for emails with plus (+) trick

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#109]
The email confirmation email's link doesn't work for emails that used the plus (+) trick. This seems to be because something is stripping the "+" from the email address and replacing it with a whitespace (space?) character in the Email field of the __Please confirm__ page:

![image](https://cloud.githubusercontent.com/assets/1266318/13260993/f3f39dec-da12-11e5-86d8-5724e17d8643.png)

This all works if the user simply replaces that space character in the email field with a "+".

**Comment by michel-cf** [comment]
Escaped the "+" sign so it is interpreted correctly by the browser
