### ISSUE TITLE
Register page allows different users to use the same screen name

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#110]
The Register page (process) allows different users to specify the same screen name as any other registered user on the system.  This should not be allowed because 1) it can cause confusion when viewing the list of shared projects, and 2) it can allow a user to impersonate another.

Please make the register page display an error "Screen name already registered.  Please choose a different screen name." when the screen name for a new account matches that of an already existing account; similar to how email addresses are checked against existing accounts.

**Comment by michel-cf** [comment]
They need to be unique now (I there are currently doubles in the database, you might need to change them before you will get the error message)

**Comment by PropGit** [comment]
Verified, they need to be unique.
