### ISSUE TITLE
Frequency of save message

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#1104]
Currently the save project reminder waits 20 minutes to show up to remind you to save your project. If you close out of it, the notification comes back every 60 seconds until you actually save the project. Maybe this could be changed to 3 or 5 minutes so it's not constantly appearing if you have no reason to save the project. Also, the time counter stays at 20 minutes even if the time goes up. With the 5 minute delay between notifications it could update with 25 min, 30 min, etc.

![capture](https://user-images.githubusercontent.com/20099916/28478343-d9cea986-6e0c-11e7-8c12-88234f77cd03.PNG)

**Comment by MatzElectronics** [comment]
Great ideas!  I'll see what I can do.

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by CarsonGracey** [comment]
One more thing I've noticed is the initial 20 minute reminder is showing up as early as 10 minutes after I save the project. I've had this happen multiple times now.

**Comment by MatzElectronics** [comment]
@CarsonGracey please test in Demo.

**Comment by MatzElectronics** [comment]
Tested and verified
