### ISSUE TITLE
Prevent new screen name that is equivalent to user's view of their own screen name

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#111]
Once logged in, the view of projects shows the user's one project's screen name as "yours".

1. This means it becomes an item that must be translated to different languages; probably not what we want to deal with.
  * If it must remain, or is desired to remain in this fashion, please change it to say "me" instead
  * Else, please allow it to simply continue to show the user's screen name instead of being dynamically changed to first-person interpretation
1. If it's still going to remain a dynamically first-person interpretation, please make a rule that new accounts can not use a screen name that matches that... it new screen names cannot be "yours" or "me"
  * This is where language translation really causes a problem also.  Recommend to simply get rid of the dynamic first-person interpretation and just always display the actual account's screen name regardless of whether they are logged in or not.

**Comment by michel-cf** [comment]
Removed "yours" and left the users screenname

**Comment by PropGit** [comment]
Verified addressed.
