### ISSUE TITLE
BUG - Save As on Live Beta BlocklyProp

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#1110]
When I use the "Save as" command in the drop-down menu on the Live Beta BlocklyProp site, values in milliseconds are changed to seconds once the project is saved. 

Just tested. The same thing happens on the DEMO site.

**Comment by MatzElectronics** [comment]
Thanks for the catch!  I'll see what I can do.

**Comment by zfi** [comment]
Wait. What? An issue is reported, assigned and commented on in under 3 minutes - on a Saturday?

**Comment by wstodghill** [comment]
@zfi  -  ;-) 

@MatzElectronics  - The problem is a bit more serious. When I correct and save the project - exit to the home page and my projects and reopen the program - the error (time corrected from seconds to milliseconds) has returned and is present in the newly opened code

**Comment by kgracey** [comment]
I had the same problem. KG

**Comment by MatzElectronics** [comment]
@wstodghill Can you try replacing the wait blocks entirely and then see if you can replicate the problem?  I can't seem to replicate it on a new project, but it's possible that projects created before the s3 to c transition are affected by this...

**Comment by MatzElectronics** [comment]
@zfi Found it - and I need your help to fix it.  We need it to set the type field for the project to PROPC (and save it that way in the DB) once an old SPIN project has been opened and transmogrified.  A second trip through the Transmogrifier is doing a few strange things...

**Comment by zfi** [comment]
Let me repeat that back to you. The project is stored in the DB as a SPIN project. When the project is loaded, we want to change the project type from SPIN to PROPC and save that back to the db - after it has traversed the transmogrifier.  But only in those projects that are currently typed as SPIN projects.

Am I understanding that correctly?

**Comment by MatzElectronics** [comment]
Correct.  Or at a minimum make sure that when it gets resolved by the user
to make sure that field is set to PROPC

**Comment by wstodghill** [comment]
I did a test and got the same results - hard refresh also returned wait to seconds (even after saving as ms.

Glad y'all have it narrowed down.

Thanks for all you folks do!

**Comment by MatzElectronics** [comment]
@zfi I think I devised a test within the daoImpl that will prevent this error from occurring - so let's try that before we go monkey with the db.  I'll PR it in soon.

**Comment by MatzElectronics** [comment]
@wstodghill give this a try on demo - it should work better now.

**Comment by wstodghill** [comment]
@MatzElectronics - Works!

**Comment by MatzElectronics** [comment]
Thanks!
