### ISSUE TITLE
Simple Libraries need to be updated

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#1115]
I appears that production does not have the latest/appropriate version of Simple Libraries.  I will work with @AndyLindsay and @zfi to straighten this out.

**Comment by zfi** [comment]
What is the correct version for production deployment?

**Comment by PropGit** [comment]
As of now, it's v1.2.0.

**Comment by MatzElectronics** [comment]
They appear to be there!  Will keep this open through testing.

**Comment by zfi** [comment]
@MatzElectronics can this issue be closed now?

**Comment by MatzElectronics** [comment]
Yup :)
