### ISSUE TITLE
Password requirements are very loose

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#112]
Password requirements seem very loose.  Here's an example where an account could be created with just a single letter as the password (this was verified; the account is active and works with that password).

![image](https://cloud.githubusercontent.com/assets/1266318/13266048/02a9100c-da2b-11e5-80ee-fd802cfdc33a.png)

What are the _validated_ password requirements?

Can we (should we) make them more standard; 8+ characters at the very least?

If we enhance this, we need to also specify the password requirements in small text near the password fields.

**Comment by michel-cf** [comment]
Currently policy is being enforced

**Comment by michel-cf** [comment]
Password policy enforcement added using http://www.passay.org/

Current requirement: 8 or more characters.
More complex rules can be added if required.

**Comment by PropGit** [comment]
It seems to be allowing only 8-character passwords now; no more and no less.

When I enter a 7-character or a 9-character password, the following is the response; otherwise, making it 8-characters works successfully.

![image](https://cloud.githubusercontent.com/assets/1266318/13338728/303f8c72-dbd8-11e5-82d6-c6d72d71932e.png)

**Comment by michel-cf** [comment]
Changed to between 8 and 255 characters

**Comment by PropGit** [comment]
Verified it must be 8 or more characters.
It accepts a 256 character password (not limited to 255) but I didn't check beyond that and I am not creating an issue for it. :-)
