### ISSUE TITLE
Remove Extraneous quote symbol from Change log URL

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#1121]
Minor problem, the change log URL at the bottom of the blockly.parallax.com homepage has extra characters at the end returning a 404.

Currently is: https://github.com/parallaxinc/BlocklyProp/releases%22

Should be: https://github.com/parallaxinc/BlocklyProp/releases

**Comment by MatzElectronics** [comment]
Found it.  It will go up with my next PR.  Thanks!

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by CarsonGracey** [comment]
Verified
