### ISSUE TITLE
Terminal: Keypresses ignored when text box does not have focus

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#1125]
Keypresses don't result in characters transmitted in the Terminal unless the text box has focus.

User must click on the text box first, before pressing keys, else nothing will be transmitted to the Propeller.

Can we:
1. Set focus on the text box upon opening the terminal overlay?
2. If focus is moved elsewhere and a keypress is made, set focus on text box and emit the pressed key into the text boxe's keypress buffer?

**Comment by MatzElectronics** [comment]
I have mixed feelings about this - because the current behavior is
intentional.  I am open to discussing it.  Others thoughts?

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by zfi** [comment]
Personal opinion: Setting focus to a window that I just opened is what I expect to see. But if I move the focus away from that window, I do not expect the window to steal focus unless I am being alerted of an impending conflagration.

**Comment by PropGit** [comment]
@zfi - agreed.

In this case, I think focus is indeed set to the window that just opened, but the text box (on that window) that displays data from the Propeller does not have focus.  If the user has just downloaded an application to the Propeller that they expect to interact with via the terminal and keyboard, any key presses don't do anything unless they first click into the text box.

@MatzElectronics - What's the intention that it be left unfocused?

**Comment by PropGit** [comment]
Follow-up: It's like going to a login page on a website, but the focus is not on the username field... typing does nothing and the user has to click into the username field first.  I grumble every time I see that.

**Comment by PropGit** [comment]
If we're trying to save the user from bad effects, this is understandable.  Was that the intention?  It just seems like an unnecessary extra step to put the user through each and every time they need to use it that way.

**Comment by MatzElectronics** [comment]
Okay - this all sounds good, thanks!

**Comment by PropGit** [comment]
You're welcome.

**Comment by CarsonGracey** [comment]
I tested this on @MatzElectronics Guess my number program in demo: http://demo.blockly.parallax.com/blockly/editor/blocklyc.jsp?project=1117# 

It looks like the terminal still has to be focused on with the cursor to type in it.

**Comment by MatzElectronics** [comment]
Ok, thanks - back to the drawing board...

**Comment by CarsonGracey** [comment]
So it looks like the terminal does become focused on as I see a cursor appear for an instant. However, when text is printed the focus is no longer on the terminal.

**Comment by CarsonGracey** [comment]
After putting a terminal receive block first, the cursor still shows up in the terminal but it actually can't be typed in.

**Comment by PropGit** [comment]
I just verified this is still working for me, even after a cacheless refresh.

The Propeller application has to be sitting (waiting) at the "Terminal receive..." block in order for your terminal-typed characters to appear (and for the Propeller to capture them).

The characters will still reach the Propeller (regardless) as you can see by monitoring the red LED on the FLiP, PAB WX, or other dev hardware.

**Comment by PropGit** [comment]
Here's a project I used for testing.
![image](https://user-images.githubusercontent.com/1266318/29191436-8efc160c-7dd2-11e7-8935-73a9bf8d45d0.png)

It produces this output (below).  First "Toggling 0" appears on-screen... then I type "asdf"<ENTER> and it outputs a blank line (not sure why) and then displays what I typed "asdf" followed by the next "Toggle #" line.

![image](https://user-images.githubusercontent.com/1266318/29191451-957b4746-7dd2-11e7-9ff7-1d945c76111a.png)

**Comment by PropGit** [comment]
I still need to click into the black field before typing.

**Comment by MatzElectronics** [comment]
I'm struggling with this one A LOT...

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by MatzElectronics** [comment]
Oh!!!!  I think I got it!!!!  @CarsonGracey please give it another go.

**Comment by CarsonGracey** [comment]
Works perfectly for me now, the code waits for a terminal receive whether it's before or after a terminal print.

**Comment by MatzElectronics** [comment]
Tested and verified.

**Comment by zfi** [comment]
@MatzElectronics deserves a beer and our gratitude for his fortitude.

**Comment by MatzElectronics** [comment]
I'm more of a hard-liquor kind of guy...  I don't drink often, but when I
do... ;)

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by PropGit** [comment]
Woohoo!  Good job, Matt!
