### ISSUE TITLE
Project List vs. Community Projects vs. Your Projects vs. My Projects

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#113]
The concept of "all projects" vs. the "user's projects" is displayed in multiple ways.  We need to be consistent across all uses.

On the landing pages, on the page header, the terms used are __Project list__ (for all projects, I assume), and __Your projects__ (for the user's projects).  But in the BlockyProp editor itself, the _Projects_ menu lists these as __Community projects__ and __My projects__, respectively.

For the first, we'd prefer "__Community projects__" everywhere it appears.
For the second, we'd prefer "__My projects__" everywhere it appears.

**Comment by michel-cf** [comment]
Changed

**Comment by PropGit** [comment]
Verified.
