### ISSUE TITLE
Enhance the Confirm Navigation dialog?

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#114]
Can we enhance the Confirm Navigation dialog further?

In this case (example below), a community project is opened by a different user, then, without changing anything, the user tries to go back to Community projects, but a Confirm Navigation dialog appears.  I understand way- this project has suddenly been cloned for them personally... it's waiting for them to save it or discard it.

![image](https://cloud.githubusercontent.com/assets/1266318/13266682/13943178-da2e-11e5-8999-7ceab321ea82.png)

Can the __Confirm Navigation__ title be changed?

How about the button names?

Or is there a way to snub the message in this particular case since the project was essentially just "viewed" by clicking on a project from the main page and logging in via the prompt.  NOTE: The other path to get here is to click on the __Project list__ link and select another user's project, then click Open Project on the page following it... without clicking on "Clone," it seems we're just "viewing" the project, but that's not really the case because a click of Save must save it somewhere withing the user's context.

**Comment by michel-cf** [comment]
The only thing that can be changed in that dialog is the line "The project has been changed since the last save".
I could check why it shows the dialog even if no changes were made. (It should check if the current xml generated by blockly matches the last one saved)

Opening some else project and saving it will duplicate it into the current users project context. You can not change some else's projects.

**Comment by PropGit** [comment]
Okay, yes, please check why it shows the dialog even if no changes were made.

**Comment by michel-cf** [comment]
It shows the dialog for old projects, from before the recent Blockly upgrade.
With the new Blockly, id's are introduced.

Projects that are created with the new version, or old one's that have been edited. Now contain id's and don't have this problem.
