### ISSUE TITLE
Auto-Save timer-based dialog shows up even when no longer logged in

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#1145]
Scenario:
- make a change to the active project
- put the computer to sleep for 18+hours (or choose a lesser time beyond auto-log-off timer period)
- wake the computer up
- __Save project reminder__ immediately appears saying "It has been 1125 minutes since you last saved your project.  Save now?"
  - Your time indication will vary
- Click the Save button.
- It _appears_ to save, but your account has long been automatically disconnected (logged out)

NOTE: Before writing this, the dialog showed up a second time, telling me it's been 5 minutes since I saved.  Clicking Save now makes another dialog appear asking "Do you want to leave this site?  Changes you made may not be saved."  This is further indication that the account is really disconnected from the cloud system, but most users will not understand that.

Solution:
- Only display auto-save dialog if the user is still logged in
- If auto-save event occurs (and the user is not logged in), display a "You've been automatically logged out due to inactivity."  (this second part should actually be a separate independent feature).

**Comment by PropGit** [comment]
This relates to #509.

**Comment by MatzElectronics** [comment]
Correct.  There are two possible solutions to this.  Have the Javascript
autosave and kick out of the page after a specified amount of inactivity,
and/or build a rest endpoint that provides the remains time in the session
and behave as described above, but more intelligently.

**Comment by MatzElectronics** [comment]
To add to this - the save timer is also showing up in the "demo" mode when you have chosen "try this"/anonymous.

**Comment by paragitadmin** [comment]
I think we have addressed this issue with a couple of features/configurations. The session timer has been extended to 8 hours, so going to a lunch no longer times out your session. The UI also has a monitor embedded in it to prod the user if their session has been inactive for 20 minutes or so.

Can this issue be closed?

**Comment by MatzElectronics** [comment]
Let's close it.  Maybe still some room for improvement, but super low
priority...

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>  |  Licenses
<http://www.tspc.oregon.gov/lookup_application/LDisplay_Individual.asp?id=07080L3B270>
