### ISSUE TITLE
Add MOTD panel

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp#1154]
Add a panel to the site to display important messages for issues such as system maintenance or issue triage messaging. The pane should be placed below the top menu and above the pane editor. The pane should appear on all pages.

**Comment by MatzElectronics** [comment]
Super easy!  How would you like to feed it content?  I can set up a GET request and grab HTML to fill it - either by a REST service or a URL that contains content that is easy for us to change on a whim... let me know and I'll build it.

**Comment by PropGit** [comment]
If it's possible, we need to make this automatically adjust for the context too (different MOTD for Demo than for Production than for Dev VM than for BlockyPropSolo, etc.)

**Comment by zfi** [comment]
My inclination is to drive this feature from the database and code it on the server side with servlet code.

**Comment by MatzElectronics** [comment]
Okay - let me know when you have a hook ready, and I'll get the REST (ha!)

**Comment by zfi** [comment]
There are no hooks. This is just server-side .jsp code.

**Comment by MatzElectronics** [comment]
Tested and verified.
