### ISSUE TITLE
Public Launch: Review email templates

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#116]
Review email templates before public release.  

Confirm with Parallax.

**Comment by michel-cf** [comment]
Current templates sent to Parallax for review

**Comment by PropGit** [comment]
I updated and returned the templates; however, they still need to be updated to reflect the official public URL for the launch.

**Comment by DarkmatterVale** [comment]
This was fixed yesterday, correct?

**Comment by michel-cf** [comment]
There is a difference between being able to send emails out and what they contain. But we reviewed and changed the url's for production.
