### ISSUE TITLE
Browser detection/warning

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#1161]
Currently we are only actively supporting Chrome and Firefox.  MS Edge is now the default for Win10 machines, and I've watched many teachers inadvertently open BlocklyProp with it, only to then have issues.

I think two things should be done -
 - Alert/Modal warning users with a non Chrome/Firefox browser is detected
 - Spend a bit of time (not a ton...) determining what it would take to make BP more cross-compatible.

**Comment by zfi** [comment]
It appears that the Blockly core does support IE10 and Edge. 

https://groups.google.com/forum/m/#!topic/blockly/o3pERaRQhSg

Perhaps we should be looking at the wrapper layer?

**Comment by MatzElectronics** [comment]
Yeah - the problems are not in the core, that much I can see.  I'm gettings complaints about localhost loopback and get/post/xmlhttp/cross-site scripting stuff mostly, so it's possible that when we switch over to a websockets-only client, it might just be a lot closer to compatible...

**Comment by MatzElectronics** [comment]
I thinking just a basic js alert on the log in page will suffice for the time being.

**Comment by zfi** [comment]
We should also document the things that break when using Edge so they can be addressed. As it is, this is an elephant and there is nowhere to start.

**Comment by MatzElectronics** [comment]
Alert box added.

**Comment by MatzElectronics** [comment]
Tested and verified, closing.  We will address problems specific to those browsers with specific issues when we have the bandwidth to deal with them.
