### ISSUE TITLE
Terminal contents not cleared when terminal modal is closed

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#1162]
The contents of the terminal persist and come back when the terminal is re-opened.

**Comment by zfi** [comment]
What is the expected behavior? When the terminal is closed, is it supposed to discard it's content?

**Comment by MatzElectronics** [comment]
I found the error and will apply it soon.

**Comment by MatzElectronics** [comment]
@CarsonGracey Should be fixed after 11:45

**Comment by CarsonGracey** [comment]
Tested and verified
