### ISSUE TITLE
Re downloading a project doesn't clear terminal

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#1163]
The terminal no longer clears between project downloads to both RAM and EEPROM. Here I downloaded the project 3 times which is why the bottom line keeps writing.

![capture](https://user-images.githubusercontent.com/20099916/29530165-5d1c273e-8657-11e7-9691-e3e1f9c2daa7.PNG)

It will continue to print over all previous terminal messages unless you add a ``` clear screen ``` block at the beginning of the program.

**Comment by PropGit** [comment]
I think this is a duplicate of #1162 .

**Comment by CarsonGracey** [comment]
Looks like it is, I'll close this one.
