### ISSUE TITLE
Project Deleted in demo

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#1178]
I had a saved project (from under an hour ago) and it looks like the whole thing disappeared except for part of a repeat block when I refreshed the page.

![capture2](https://user-images.githubusercontent.com/20099916/29791667-a02e0236-8bf2-11e7-9023-54b5656c5feb.PNG)

**Comment by MatzElectronics** [comment]
Can you tell me what blocks where in your project before?

**Comment by CarsonGracey** [comment]
I'm not exactly sure but all the RGB-LED blocks and the ColorPal init block and ColorPal save to a single variable block. Looks like the ColorPal block menu is empty as well.

![capture3](https://user-images.githubusercontent.com/20099916/29791906-86e97372-8bf3-11e7-978d-2b2eeee12a5f.PNG)

**Comment by MatzElectronics** [comment]
This may be due to old code new code in-between refreshiness...closing, but ready to tackle if it crops back up in a new project.
