### ISSUE TITLE
Help search bar doesn't update according to category of help displayed

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#118]
The Help system's search bar doesn't update to reflect what category of help is being displayed.  For example, here the BlocklyProp category has been and is now shown, but __Help__ is still shown in bold (and is not a link), preventing the user from click back to the main help landing page.

![image](https://cloud.githubusercontent.com/assets/1266318/13269934/8c480750-da3f-11e5-8576-cea2f4ce5235.png)

**Comment by michel-cf** [comment]
They aren't real categories but shortcuts to the 3 start pages. Sadly, due to the way the help system is set up, it's very hard (to impossible, depending on how the help pages will be written and organized) in which category you are looking.

I will change **Help ** into a link.

**Comment by michel-cf** [comment]
**Help** is now a link.

For the previously mentioned reasons, highlighting is not really feasible. If this should be added anyway, please reopen.

**Comment by PropGit** [comment]
Verified.
