### ISSUE TITLE
S3 - "drive to" Block Increment Settings - Please Check

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#1189]
I am having increment issues with the "drive to" block. Works in inches, but I notice no change in other settings.

Could some one else please check this?

**Comment by wstodghill** [comment]
Okay - More experiments done! Using the block simply - I get good results. 

Question - why does this code -  **drive to - Plot y = x^2** - work as I would expect? - http://blockly.parallax.com/blockly/editor/blocklyc.jsp?project=11237

But, why does this code - **drive to - Plot y = x^2 (more curve like)** - not work as I would expect?
http://blockly.parallax.com/blockly/editor/blocklyc.jsp?project=11240#

**Comment by wstodghill** [comment]
Okay, I now know that using the drive to block there is no distinction in C between inches and tenths of inches. Don't know why I did not check that earlier!

Still playing with idea...

**Comment by MatzElectronics** [comment]
Hi!

There is a subtle difference between tenths of an inch and inches - it's a factor of ten (100,000 / 1933) vs. (10,000 / 1933)

I think since you are squaring, you might be running into integer limits - we need to experiment with this some, because the code is hard to reverse-engineer - for example, if the hard limit here is a 16-bit integer, hard limits will get hit really quickly.  If they are 32-bit integers, we have some breathing room, but it's still possible to exceed them, especially when you are squaring numbers...

Keep playing - let me know if you find a pattern to where it starts failing.
Thanks!

**Comment by MatzElectronics** [comment]
If it's 32 bit - the hard limit for inches as they are currently programmed would be 21474.  Tenths would be 10 times that.

If it's 16-bit, i'm not sure I would expect this thing to work well at all :)

I can change the multipliers to gain some headroom, but it would lose precision - that's the tradeoff there.

**Comment by MatzElectronics** [comment]
Sorry, one more thing - there might be some other factors at play in the Trig that happens under the hood, too...  ugh.

**Comment by MatzElectronics** [comment]
It is 16 bit signed, but I wrapped it with a new function that takes 32 bit signed inputs, so hopefully that allows it to be used to it's maximum range (32767 encoder ticks)

**Comment by MatzElectronics** [comment]
@wstodghill can you check the ranges on this?

**Comment by wstodghill** [comment]
@MatzElectronics - The code posted above still does not function. Sorry, it took so long to check this. 

drive to - Plot y = x^2 or (x * x) - works as I would expect - http://blockly.parallax.com/blockly/editor/blocklyc.jsp?project=11237

But, drive to - Plot y = x^2 or (x * x - which should be more curve like) - does not work as I would expect!
http://blockly.parallax.com/blockly/editor/blocklyc.jsp?project=11240#

**Comment by wstodghill** [comment]
This is really old - I honestly have not checked it recently. Anyone know if I need to check it. If so, I will and then maybe we can close this...

**Comment by zfi** [comment]
We can close it now and reopen it if needed.

**Comment by wstodghill** [comment]
Thanks.
