### ISSUE TITLE
Editor's "BlocklyPropClient available" is still a link

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#119]
The editor's "BlocklyPropClient available" item that appears when the client is installed, running, and connected, is still a clickable link that targets the client download.

That's kind of confusing.  Maybe make it non-linked text when the client is available?

**Comment by michel-cf** [comment]
Done

**Comment by PropGit** [comment]
Verified done- it is now no longer a link when in the "BlockyPropClient available" state.
