### ISSUE TITLE
Enhance BlocklyProp Client link's information

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#120]
The link for the dynamic _BlocklyPropClient not available_ item on the editor displays an overlay to download the client software.

![image](https://cloud.githubusercontent.com/assets/1266318/13271234/93c8736c-da48-11e5-9451-3f29495627a2.png)

![image](https://cloud.githubusercontent.com/assets/1266318/13271296/fb2b036c-da48-11e5-91b3-016291b70d6f.png)

This looks great, but to clarify things for different situations, please add some details to explain things.  This text, below, can appear right between the __BlocklyPropClient__ header and the download button for the client system.

>To download code to your Propeller, BlocklyProp requires that the BlocklyPropClient software is installed and connected on your computer.
>  * If BlocklyPropClient is already installed, run it and click the "Connect" button, then return to this editor
>  * If BlocklyPropClient is not installed, download and install it using the link for your computer type below

**Comment by michel-cf** [comment]
Done using a textile page to enable usage of markup

**Comment by PropGit** [comment]
Verified - the dialog looks great!
