### ISSUE TITLE
Inconsistent Block Names

### ISSUE THREAD

**Issue by CGracey** [parallaxinc/BlocklyProp#1201]
![capture](https://user-images.githubusercontent.com/20099916/30496283-c2bc2a5c-9a03-11e7-892c-dde9aa349652.PNG)

These blocks should probably all be "highest to lowest" or "lowest to highest" so they are all consistent with each other. I prefer lowest to highest but it doesn't matter much as long as they are all the same.

**Comment by wstodghill** [comment]
@CGracey - nice catch! Thanks for all you do!

**Comment by CGracey** [comment]
Thanks @wstodghill I just try to find every small issue I can

**Comment by MatzElectronics** [comment]
Tested and verified
