### ISSUE TITLE
Cannot duplicate EEPROM text block

### ISSUE THREAD

**Issue by mrodriguez-parallax** [parallaxinc/BlocklyProp#1205]
Duplicating the EEPROM text block only creates a small area of pixels that do not amount to anything readable.

![screen shot 2017-09-20 at 4 42 56 pm](https://user-images.githubusercontent.com/20686764/30672716-fe349d4e-9e22-11e7-91b8-f48d54b12c29.png)

![screen shot 2017-09-20 at 4 43 13 pm](https://user-images.githubusercontent.com/20686764/30672719-0236581a-9e23-11e7-94e3-48d32510968e.png)

Unreadable text or pixels
![screen shot 2017-09-20 at 4 43 52 pm](https://user-images.githubusercontent.com/20686764/30672722-069e6ac8-9e23-11e7-9c4a-d46ea3051d67.png)

**Comment by MatzElectronics** [comment]
Okay - I think this is largely the result of using older blocks.  I added code to prevent the error you saw.
