### ISSUE TITLE
BlocklyProp S3 Save Issue - Change in units when saved - SOLVED?

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#1209]
In this code - http://blockly.parallax.com/blockly/editor/blocklyc.jsp?project=12557 seconds and milliseconds change when saved. If I set the wait to 1000 ms and save - it becomes 1000 seconds. If I make it 1 second and save - it becomes 1 ms.

I know this code is using some old blocks, but other than the issue listed, it works great!

**Comment by wstodghill** [comment]
This code - http://blockly.parallax.com/blockly/editor/blocklyc.jsp?project=12576 - was written by starting a project using "other" board and then saving the blocks - then uploading them to a new S3 project - Seems to work as well and no saving issues! 

The issue may have been the use of ancient blocks in the previous program, but I did not want to lose this idea that works so well. 

One last note - I plan on updating this further to included every sensor in the Sensor menu for the S3 - that means adding Stall, Sony Remote, Microphone, and Button. Fun stuff.

**Comment by MatzElectronics** [comment]
This actually does have to do with older projects...if you download your code and upload it into a new project, you shouldn't have the problem any longer.

**Comment by wstodghill** [comment]
Thanks! Let's close this one!
