### ISSUE TITLE
servo PIN disable block in abdrive360

### ISSUE THREAD

**Issue by AndyLindsay** [parallaxinc/BlocklyProp#1218]
The servo PIN 12 disable block currently generates 

  servo360_disable(12);

It should instead generate

  servo360_enable(12, 0);

**Comment by MatzElectronics** [comment]
Really?  What are the arguments for the servo360_enable() function?

**Comment by AndyLindsay** [comment]
1 is enabled, 0 is disabled.  Currently, servo360_enable(pin, 0) stops sending servo signals, but everything else continues.  When servo360_enable(pin, 1) is called, it brings it back to life.

**Comment by MatzElectronics** [comment]
Got it!

**Comment by AndyLindsay** [comment]
Verified and closed.

**Comment by AndyLindsay** [comment]
http://demo.blockly.parallax.com/blockly/my/projects.jsp#1266
