### ISSUE TITLE
demo - abdrive360 compiler errors without servo360.h in projects

### ISSUE THREAD

**Issue by AndyLindsay** [parallaxinc/BlocklyProp#1219]
NOTE: I updated name to "...without servo360.h" it's certainly more closely related than ping.  See next post for more info.  

I do not get the compiler errors reported here in SimpleIDE under the same circumstances.  

This program works:

```
// ------ Libraries and Definitions ------
#include "simpletools.h"
#include "ping.h"
#include "abdrive360.h"

// ------ Global Variables and Objects ------
int item;



// ------ Main Program ------
int main() {

  //
  item = ping_inches(0);
  freqout(4, 1000, 3000);
  drive_goto(64, 64);

}
```

After removing the item = and Ping))) distance inches PIN 0, blockly has these errors.

```
Required libraries: abdrive360, simpletools
Library compile order: None needed
/opt/parallax/Workspace/Learn/Simple Libraries/Motor/libservo360/cmm/libservo360.a(servo360_connect.o): In function `_servo360_connect':
(.text+0xa): undefined reference to `_pulse_in'
/opt/parallax/Workspace/Learn/Simple Libraries/Motor/libservo360/cmm/libservo360.a(servo360.o): In function `_servo360_run':
(.text+0x9): undefined reference to `_cog_run'
/opt/parallax/Workspace/Learn/Simple Libraries/Motor/libservo360/cmm/libservo360.a(servo360.o): In function `_servo360_end':
(.text+0x32): undefined reference to `_cog_end'
/opt/parallax/Workspace/Learn/Simple Libraries/Motor/libservo360/cmm/libservo360.a(servo360.o): In function `.L8':
(.text+0x1e7): undefined reference to `_get_state'
/opt/parallax/Workspace/Learn/Simple Libraries/Motor/libservo360/cmm/libservo360.a(servo360.o): In function `.L8':
(.text+0x213): undefined reference to `_get_state'
collect2: ld returned 1 exit status
```

Here is the program that generates the compiler errors:

```
// ------ Libraries and Definitions ------
#include "simpletools.h"
#include "abdrive360.h"

// ------ Global Variables and Objects ------
int item;



// ------ Main Program ------
int main() {

  //
  freqout(4, 1000, 3000);
  drive_goto(64, 64);

}
```

**Comment by AndyLindsay** [comment]
Maybe it needs #include "servo360.h" at the main file level, and maybe above #include "abdrive360.h".  For example this does compile:

```
// ------ Libraries and Definitions ------
#include "simpletools.h"
#include "servo360.h"
#include "abdrive360.h"



// ------ Main Program ------
int main() {
  servo360_connect(26, 27);

  //
  freqout(4, 1000, 3000);
  drive_speed(64, 64);
  pause(1000);
  drive_speed(0, 0);

}
```

**Comment by MatzElectronics** [comment]
Okay - I added the call to servo360.h - I might need to make adjustments if it needs to be above "abdrive360.h"

**Comment by kgracey** [comment]
Ya guys are killin’ it!

KG

**Comment by AndyLindsay** [comment]
Thanks for trying that.  It is correctly adding the #include, but it didn't fix the problem.

This is quite the mystery because it doesn't happen in SimpleIDE.

The compiler is complaining about not being aware of simpletools.  I just tried adding include simpletools to all .c files on the chance that that might fix it.  Will wait for an update cycle and then test.

**Comment by zfi** [comment]
It appears that the variables are referenced in the libservo360.a library. Where  are the unreferenced variables noted above actually implemented?

**Comment by AndyLindsay** [comment]
They are all variables pointing to function that are implemented in the simpletools library.  I tried adding #include "simpletools.h" to all files in both projects (libabdrive360 and libservo360), but that did not appear to have any effect either.   However, when  I add a function call to some other library that also uses simpletools, it all starts working.

SimpleIDE correctly compiles the program without the function call.  Here is the output of a correct compile (of the program that blocklydemo does not compile).

Project Directory: C:/Users/Parallax/Documents/SimpleIDE Tests/

SimpleIDE Version 1.1.0
C:/Users/Parallax/Documents/SimpleIDE/Learn/Simple Libraries/
C:/Users/Parallax/Documents/SimpleIDE/ Updated on: 2017-07-30

propeller-elf-gcc.exe -v GCC 4.6.1 (propellergcc_v1_0_0_2408)
propeller-elf-gcc.exe -I . -L . -I C:/Users/Parallax/Documents/SimpleIDE/Learn/Simple Libraries/Utility/libsimpletools -L C:/Users/Parallax/Documents/SimpleIDE/Learn/Simple Libraries/Utility/libsimpletools/cmm/ -I C:/Users/Parallax/Documents/SimpleIDE/Learn/Simple Libraries/TextDevices/libsimpletext -L C:/Users/Parallax/Documents/SimpleIDE/Learn/Simple Libraries/TextDevices/libsimpletext/cmm/ -I C:/Users/Parallax/Documents/SimpleIDE/Learn/Simple Libraries/Protocol/libsimplei2c -L C:/Users/Parallax/Documents/SimpleIDE/Learn/Simple Libraries/Protocol/libsimplei2c/cmm/ -I C:/Users/Parallax/Documents/SimpleIDE/Learn/Simple Libraries/Robotics/ActivityBot360/libabdrive360 -L C:/Users/Parallax/Documents/SimpleIDE/Learn/Simple Libraries/Robotics/ActivityBot360/libabdrive360/cmm/ -I C:/Users/Parallax/Documents/SimpleIDE/Learn/Simple Libraries/Motor/libservo360 -L C:/Users/Parallax/Documents/SimpleIDE/Learn/Simple Libraries/Motor/libservo360/cmm/ -I C:/Users/Parallax/Documents/SimpleIDE/Learn/Simple Libraries/TextDevices/libfdserial -L C:/Users/Parallax/Documents/SimpleIDE/Learn/Simple Libraries/TextDevices/libfdserial/cmm/ -o Project Name.elf -Os -mcmm -m32bit-doubles -fno-exceptions -std=c99 Project Name.c -lm -lsimpletools -lsimpletext -lsimplei2c -labdrive360 -lservo360 -lfdserial -lm -lsimpletools -lsimpletext -lsimplei2c -labdrive360 -lservo360 -lm -lsimpletools -lsimpletext -lsimplei2c -labdrive360 -lm -lsimpletools -lsimpletext -lsimplei2c -lm -lsimpletools -lsimpletext -lm -lsimpletools -lm
propeller-load -s Project Name.elf
propeller-elf-objdump -h Project Name.elf
Done. Build Succeeded!

**Comment by AndyLindsay** [comment]
This patch seems to make it possible for the demo.blockly server to compile applications.  

https://github.com/parallaxinc/Simple-Libraries/commit/d1632648d5b327c3c51d96c6403e886af762d9b8

**Comment by AndyLindsay** [comment]
Test Fix 04 demo - abdrive360 compiler errors without servo360.h in projects

parallaxinc/BlocklyProp#1219

Try a forward declaration in one of the c files

**Comment by AndyLindsay** [comment]
Test Fix 04 demo appears to work with minimal impact on other functions, program size, etc.  I'm leaving this issue open until the command lines from SimpleIDE and BlocklyProp can be adjusted to be consistent with each other.
