### ISSUE TITLE
Help page: update style of buttons

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#123]
Please add a #AECEE5 blue fill to the buttons, like this example:

![image](https://cloud.githubusercontent.com/assets/1266318/13366013/609178a8-dc8d-11e5-9246-8e1654003a63.png)

**Comment by DarkmatterVale** [comment]
I fixed this in commit d9aba23f0fe1b6a124885fcef96c6c1afc6310ca in BlocklyProp-docs.
