### ISSUE TITLE
Limit screen name character set

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp#1232]
The site appears to permit any ASCII character in the screen name when the user registers. For example, an account was recently created with the screen name: 'Nikki:)' I don't see this as overly useful and likely to be abused at some point.

Please limit the character set for screen names to the set [a-z] [A-Z] [0-9] [.-_]

**Comment by MatzElectronics** [comment]
Good idea!

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by MatzElectronics** [comment]
Tested and verified
