### ISSUE TITLE
Need fully featured serial communication block

### ISSUE THREAD

**Issue by mrodriguez-parallax** [parallaxinc/BlocklyProp#1239]
Current serial initialize block does not have an option to select a mode. (True, True open drain,  Inverted,  Inverted open source) at different baud rates.

![screen shot 2017-11-07 at 10 44 54 am](https://user-images.githubusercontent.com/20686764/32511506-ccc01698-c3a8-11e7-84a5-ee33dfd71097.png)

**Comment by MatzElectronics** [comment]
Tested and verified
