### ISSUE TITLE
S3 ADC block not working

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#1240]
![image](https://user-images.githubusercontent.com/19737272/32575093-e607c5c6-c487-11e7-939d-048bea617750.png)

**Comment by mrodriguez-parallax** [comment]
**Check analog** block is compiling. Test was conducted using the same code blocks. Results are below and I'll go ahead and close the issue unless there are other aspects regarding the issue that need more testing.

![2017-12-14_09-16-11](https://user-images.githubusercontent.com/20686764/34006063-df9e32d8-e0b1-11e7-8148-6304fc747824.png)

![2017-12-14_09-16-36](https://user-images.githubusercontent.com/20686764/34006067-e6261b3e-e0b1-11e7-9ae5-b57511cbad31.png)


![2017-12-14_09-17-14](https://user-images.githubusercontent.com/20686764/34006075-ecfd3398-e0b1-11e7-9082-162f8ee77392.png)

![2017-12-14_09-17-45](https://user-images.githubusercontent.com/20686764/34006082-f0e404e6-e0b1-11e7-8dfc-285e0874b546.png)

**Comment by MatzElectronics** [comment]
Can you output it to the terminal and check that it's reading an analog
voltage 0-5v?

On Dec 14, 2017 9:37 AM, "mrodriguez-parallax" <notifications@github.com>
wrote:

*Check analog* block is compiling. Test was conducted using the same code
blocks. Results are below and I'll go ahead and close the issue unless
there are other aspects regarding the issue that need more testing.

[image: 2017-12-14_09-16-11]
<https://user-images.githubusercontent.com/20686764/34006063-df9e32d8-e0b1-11e7-8148-6304fc747824.png>

[image: 2017-12-14_09-16-36]
<https://user-images.githubusercontent.com/20686764/34006067-e6261b3e-e0b1-11e7-9ae5-b57511cbad31.png>

[image: 2017-12-14_09-17-14]
<https://user-images.githubusercontent.com/20686764/34006075-ecfd3398-e0b1-11e7-9082-162f8ee77392.png>

[image: 2017-12-14_09-17-45]
<https://user-images.githubusercontent.com/20686764/34006082-f0e404e6-e0b1-11e7-8dfc-285e0874b546.png>

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/parallaxinc/BlocklyProp/issues/1240#issuecomment-351782868>,
or mute the thread

**Comment by MatzElectronics** [comment]
Last bug is in the c library.  Forgot to add "return" to the function that calculates the value.

**Comment by zfi** [comment]
Where is the C library? What function is missing the 'return' statement?

**Comment by MatzElectronics** [comment]
I haven't put in the PR to it yet.  It's inside
SimpleLibraries>Robotics>libs3, been too busy to get to this fix...

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by zfi** [comment]
Ok thanks. Sometimes you write things here that look like a "notes to self" more than something that others can take action on.

**Comment by MatzElectronics** [comment]
I will start prefacing with note-to-self :)

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by MatzElectronics** [comment]
Tested and verified
