### ISSUE TITLE
Compile/Download Results Should Scroll

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#1245]
We need the Compile/Download Results window to automatically scroll when there's information appearing below the bottom edge.

**Comment by PropGit** [comment]
From @zfi:

The scrolling feature should be a property that is set on the window; scroll_bar_enable = true; or some such thing.

**Comment by MatzElectronics** [comment]
The bar gets created, but you have to add some JS to force it to auto scroll to the bottom...I think I have some code that does that in the terminal, so I'll look at what it will take to copy that over for the compile dialog.

**Comment by PropGit** [comment]
Thanks @MatzElectronics

**Comment by MatzElectronics** [comment]
This needed to be handled in two different places (one for BPC, one for BPL), and I missed one of them the first time around.  Should be fixed now.

**Comment by MatzElectronics** [comment]
Tested and verified with BPC.  Process is different on BPL.  May only be possible to see it if we generate a really long compile error on a chromebook...

Closing.
