### ISSUE TITLE
Consider simplifying Compile/Results Window Output

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#1246]
The amount of information provided during download may be too extensive (goes past bottom edge of view).  Perhaps simplification is in order.  This should be considered along with Issue #1245.

**Comment by PropGit** [comment]
From @zfi: 

The result window should be a simple as possible if the results are successful. However, if the compile fails, we want to provide enough information to help identify the cause of the failure. This implies that the Cloud Compiler doesn't actually reply to the compile request until the compile has completed. And at that point, we should know if we can send a short success message or a mini core-dump.

**Comment by PropGit** [comment]
To both enhance and simplify the user's experience with the Compile Result display, I'll make changes to Cloud Compiler and Blockly Prop to achieve the following:

1. Upon user activation of a compile operation (clicking either the Compile, Load RAM, or Load EEPROM buttons), the BlocklyProp client side ("browser") output's "Compile..." to the results display, then it calls the Cloud Compiler system.  
    1. This serves as real-time status of what it's attempting to do as well as a placeholder for the results (seen below).  If there's a noticeable delay between calling the Cloud Compiler and results coming back (as there sometimes is), this shortens the user's perceived time of delay.  If there's no response (as sometimes happens) the user isn't left with just a blank screen.
![image](https://user-images.githubusercontent.com/1266318/32924207-4e592f3e-caf0-11e7-87a2-2cc193c94c28.png)
1. When Cloud Compiler responds, the display updates with either "Succeeded." or "Failed!" followed by all the details, as shown below:
![image](https://user-images.githubusercontent.com/1266318/32924219-6494b03e-caf0-11e7-8438-b25936908c4c.png)
![image](https://user-images.githubusercontent.com/1266318/32924266-a2bb9062-caf0-11e7-9eb1-843e3e7d3751.png)

In practice, this works very nicely and the timing of message appearance should as well.  Most BlocklyProp users should see "Compile... Succeeded." each time they compile.  Only when there is a failure is there more to read about the compiler status.  

A successful compile is followed by loader progress if they are loading to RAM or EEPROM.  The loader progress messages will be simplified further as well, in a different issue.

**Comment by MatzElectronics** [comment]
Is there any way to show the size of the final compile?  both in kB and %
of 32kB?

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by PropGit** [comment]
Something like this?  **Compile... Succeeded. (Size: 16.0 kB - 50%)**

**Comment by MatzElectronics** [comment]
Yes!

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by wstodghill** [comment]
This is a fine improvement for "ordinary folks," like me!

**Comment by PropGit** [comment]
Thanks @wstodghill

**Comment by PropGit** [comment]
@MatzElectronics - Stopped in my tracks: While implementing your request for a final compile size (Propeller Application Image size), I suddenly realized I can't easily determine that value because the output is in .elf format, not Propeller .binary format.  To do that, we'll have to parse the .elf and calculate the resulting Propeller Application Image size.  We can do it, but it will take some more time, so I'll move this request to a different issue.

**Comment by MatzElectronics** [comment]
Okay - works for me, not super high priority, so I'll take it when I can
get it,
Thanks!
Matt

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by PropGit** [comment]
This is in demo now.

**Comment by PropGit** [comment]
Verified. Done.
