### ISSUE TITLE
Add Help to Editor

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#125]
Can we add the link to Help on the titlebar of the Editor?

**Comment by DarkmatterVale** [comment]
@PropGit Where would you like it placed?

**Comment by PropGit** [comment]
Even thought it'd be inconsistent with where it is on all the other pages, because of the way the editor's titlebar is organized, I think it'd make sense to place it to the right of the _View_ menu.

**Comment by michel-cf** [comment]
Open in new window doesn't seem to work, probably due to the page leave check. Will need to be fixed using JS.
