### ISSUE TITLE
Remove temporary patch for Servo360 compiler issue

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#1256]
Once Cloud Compiler v1.0.1 ( [commit 1c24edae](https://github.com/parallaxinc/Cloud-Compiler/commit/1c24edae3b3a77d248af44dedc22e6d6b8523d14) ) is validated, remove temporary patch code that made Servo360 compile properly.

**Comment by MatzElectronics** [comment]
Just let me know when!
Thanks!

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by PropGit** [comment]
It should be on Demo now.  Since I can't think of another way to validate, the next step is to remove the temporary patch code, deploy to Demo, and recompile Servo360 projects to verify they now work _without_ the workaround patch.  Then we've completed this issue.

**Comment by MatzElectronics** [comment]
Patch has been commented out, should be ready to test.

**Comment by PropGit** [comment]
Looks good.  The code no longer emits with the temporary patch.
Is there another test that we need to perform, or is this proof?

![image](https://user-images.githubusercontent.com/1266318/33352097-1e98f584-d45c-11e7-8c8b-2f2b5da42310.png)

![image](https://user-images.githubusercontent.com/1266318/33352103-22972688-d45c-11e7-97f0-2dc91be72e5f.png)

**Comment by MatzElectronics** [comment]
Does it compile without an error?

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by PropGit** [comment]
Yes.
![image](https://user-images.githubusercontent.com/1266318/33352314-279de396-d45d-11e7-9604-0469a521ab66.png)

I believe this is a project that would have failed to compile with the previous Cloud Compiler system, too.  So it looks to me like we've proven it works unless you can think of something else.

**Comment by MatzElectronics** [comment]
Yay!  Let's close it!

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by PropGit** [comment]
Thank you!
