### ISSUE TITLE
Blocks with PIN menus need to have the option to set PIN using value/variable blocks

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#1264]
Request to allow a constant or variable input for I/O pin on this block so it can be used more constructively.

**Comment by MatzElectronics** [comment]
Got it - can add "other" to the list of pins, when selected, changes to an input that accepts a block.

**Comment by MatzElectronics** [comment]
This would well in other places, like servos, etc.

**Comment by MatzElectronics** [comment]
Applied to Servo, Audio-Freqout, and Analog/Pulses blocks for now.

**Comment by MatzElectronics** [comment]
Still need to remove block warning when "other" is chosen, because there is no way to determine the pin, and therefore check for an initialize block...

**Comment by MatzElectronics** [comment]
Tested and verified
