### ISSUE TITLE
Register page should clearly indicate when screenname needs to be different

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#127]
Related to Issue #110, the error message shown when a screenname is not unique is too vague:

![image](https://cloud.githubusercontent.com/assets/1266318/13443972/89899168-dfb8-11e5-9fb7-6334f6d69560.png)

Please enhance the non-unique Screenname error to be "Screenname already registered. Please choose a different screenname."

**Comment by DarkmatterVale** [comment]
Verified this has been fixed.

![screen shot 2016-03-10 at 7 34 50 pm](https://cloud.githubusercontent.com/assets/6094957/13689498/324145d6-e6f7-11e5-94a9-85dc7332d973.png)

**Comment by michel-cf** [comment]
I think the original problem was not with checking the screenname but probably some other failure, as I've had this error message since I added the screenname duplicate detection.
