### ISSUE TITLE
Navigating to last project page breaks navigation - Demo

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp#1283]
Clicking on the  '>>' icon to move to the last page takes one to never-never land. 

![screen shot 2017-12-08 at 13 55 20](https://user-images.githubusercontent.com/8442260/33786839-8ca4306e-dc1f-11e7-8e85-bfc8010ad9e1.png)

The page renders with no projects and no nav buttons. This does not appear to happen if the 'records per page' setting 50 or 100.

![screen shot 2017-12-08 at 13 59 12](https://user-images.githubusercontent.com/8442260/33786961-09f334a2-dc20-11e7-9420-e09405bc7e97.png)

**Comment by MatzElectronics** [comment]
I can't seem to replicate this.  I'm wondering if a force-refresh may resolve it...

**Comment by MatzElectronics** [comment]
Now I can - and yup.  Grrr...
This uses a bootstrap library that I'm finding myself not liking very much, and if we add functionality, I think it's going to break further.  I think this needs to be re-imagined generally anyway, including search, etc...

**Comment by MatzElectronics** [comment]
This was part of the old demo code, and with the change to 0.100, this goes away.  Closing.
