### ISSUE TITLE
Strange behavior when Activity Bot uses `Robot drive distance`

### ISSUE THREAD

**Issue by joshuaSmith2021** [parallaxinc/BlocklyProp#1309]
As I was experimenting with making the ActivityBot turn, I noticed that when I used the `Robot drive distance` block to turn the robot would return to its starting point, which I found counterproductive as it prevented more forward movement.

The bug in progress is shown in the following YouTube video.

[![Parallax ActivityBot Turn Bug
](https://img.youtube.com/vi/1P9f9e16PP0/0.jpg)](https://www.youtube.com/watch?v=1P9f9e16PP0)
Click on thumbnail to view video

**Comment by MatzElectronics** [comment]
Could you please include a link to the program causing the issue? Are sure
the program is shared.  Thank you!

**Comment by joshuaSmith2021** [comment]
[http://blockly.parallax.com/blockly/editor/blocklyc.jsp?project=20029](http://blockly.parallax.com/blockly/editor/blocklyc.jsp?project=20029)

**Comment by MatzElectronics** [comment]
@AndyLindsay can speak more to the timeline for fixing this, but there are a couple things you can try.  First, try using either robot drive speed ONLY or robot drive distance ONLY.  The two different types of blocks tend to conflict with each other.  There is a fix in the works, but I don't know how soon it will get posted.  The other thing that might work is to use a robot drive stop block with a small (100 ms?) delay between using robot drive speed and robot drive distance blocks.

**Comment by AndyLindsay** [comment]
Fixed and ready for testing.  

https://github.com/parallaxinc/Simple-Libraries/issues/164

Also, see the 11th post in http://forums.parallax.com/discussion/167891/bug-robot-drive-speed-and-robot-drive-distance-don-t-mix

**Comment by AndyLindsay** [comment]
This can be closed.
