### ISSUE TITLE
Register page not displaying properly

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/BlocklyProp#132]
Whenever I select the "Register Now!" link on the Log In/Register page, I am successfully transferred to the Register page. However, it does not display properly.

![screen shot 2016-03-05 at 3 51 49 pm](https://cloud.githubusercontent.com/assets/6094957/13550376/63c29f30-e2ea-11e5-8342-b6fa87fd8783.png)

**Comment by michel-cf** [comment]
What url do you use and what browser? It works fine for me.

**Comment by DarkmatterVale** [comment]
Browser: Safari 9.0.3 (11601.4.4)
Link: https://blockly.parallax.com/blockly/register

**Comment by michel-cf** [comment]
We need to change the cdn url to use the load balancer. @PropGit Can you get this done?

**Comment by michel-cf** [comment]
Fixed by changing cdn url in properties file

**Comment by PropGit** [comment]
Thanks @michel-cf.
