### ISSUE TITLE
BlocklyProp code blocks are sometimes not selectable

### ISSUE THREAD

**Issue by dgately** [parallaxinc/BlocklyProp#1332]
When I have several coded BlcklyProp blocks in the editor view, after some clicking and moving of blocks, some blocks become un-selectable. After reselecting other blocks, the un-selectable block becomes once more 'selectable'. See the attached video for steps to report. This is happening on a MacBook Pro, running Safari on OS version: macOS High Sierra 10.13.2.

[BlocklyPropEditor Bug 2.zip](https://github.com/parallaxinc/BlocklyProp/files/1607864/BlocklyPropEditor.Bug.2.zip)

**Comment by MatzElectronics** [comment]
I'm purely guessing here, but are the programs this is happening in somewhat large?  Or do they use a specific set of blocks (serial communication, colorPal by chance?)  I'm on the edge of worried about how many onchange events are being employed, and if we are pushing the envelope a bit with what the JS in a browser is reasonably capable of.  For example, clicking a block automatically generates two onchange triggers, which then can propogate through every block, with each block generating at least two more events...so they cascade pretty quickly.

On my todo list is putting the code in onchange handlers in conditionals to prevent them from running when they don't need to...

**Comment by dgately** [comment]
RE: I'm purely guessing here, but are the programs this is happening in somewhat large? No... The program is the one in the video, which contains 4 blocks. The one block that appears to have the issue is a GPS block...

**Comment by MatzElectronics** [comment]
Does this issue occur in Chrome or Firefox?

**Comment by MatzElectronics** [comment]
@dgately please re-test.  This may be related to the CSS issue in #1331

**Comment by MatzElectronics** [comment]
Seems okay, unable to replicate after css fix some time ago.  closing
