### ISSUE TITLE
"Email confirm request" doesn't send confirmation email

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/BlocklyProp#134]
After registering, I get the default message to look for a confirmation email in my inbox. It has been over 24 hours since I first registered. Following registration, after a few hours with no confirmation email sent (I checked my spam, inbox, etc), I attempted to login with the credentials I set which promptly failed. I selected the "Email not confirmed?" link, entered the email address I put into the registration box earlier, and waited. After multiple attempts at this over the past day, I have still not received any emails.

I am running Safari 9.0.3 (11601.4.4).

**Comment by michel-cf** [comment]
I was waiting for this one. We are still running sandboxed for the email system. Until Amazon clears us to go public, it's restricted to a few email addresses.

**Comment by PropGit** [comment]
Yes, this is the reason we said not to share the existence of the system with others yet, because the system can not send out emails until Amazon let's us do so.  Jim is working with them on expanding the service to reach others outside of Parallax.

**Comment by DarkmatterVale** [comment]
Oh, ok. Thank you for the explanation!

**Comment by PropGit** [comment]
@DarkmatterVale - We now have the email system working.  You will have to try to log in, then click the confirm email link when it fails, go through the email confirmation process, then you can log in.
