### ISSUE TITLE
Can not log in through Safari browser

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#135]
Log in always fails when using the Safari browser (at least versions 8.0.3 through 9.0.3).

To verify, we tested on two computers, one of which was very clean, and also noted that Chrome (on the same two computers) could log in with the same account without any error.

Note: Internet Explorer 11 also logs in just fine.

**Comment by DarkmatterVale** [comment]
@PropGit I just tested this and I was able to successfully login on Safari 9.0.3 on my Mac.

**Comment by PropGit** [comment]
@DarkmatterVale - That's interesting.  I'll try again.  What version of OS X are you using?

**Comment by DarkmatterVale** [comment]
I am running OS X 10.11.3

**Comment by michel-cf** [comment]
Works for me

**Comment by DarkmatterVale** [comment]
I just tested this and I am not able to login through safari, but I had no issues logging in through Chrome.

The only error message I get on the console:

![screen shot 2016-05-04 at 4 26 31 pm](https://cloud.githubusercontent.com/assets/6094957/15028096/02aa5c42-1215-11e6-9430-fb2ee2149e09.png)

**Comment by michel-cf** [comment]
Index.jsp is changed to index. Did you use a bookmark to go there?
Op 4-mei-2016 10:26 PM schreef "Vale" <notifications@github.com>:

**Comment by DarkmatterVale** [comment]
I can login fine now
