### ISSUE TITLE
Bad link in staging confirmation page

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#1351]
The Confirmation response page on Staging has a bad link at the end of the message.

![image](https://user-images.githubusercontent.com/1266318/34900895-cc62940c-f7b8-11e7-96e7-c5d36159ecd3.png)

**Comment by zfi** [comment]
The word 'here' should be the target of the hyperlink. Corrected the rouge double quote error.

**Comment by PropGit** [comment]
Verified fixed.
