### ISSUE TITLE
Update tool-tip for check PIN block

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#1356]
The current __check PIN__ blocks' tool-tips appear like this:
![image](https://user-images.githubusercontent.com/1266318/35017130-66189afa-fad0-11e7-8dd7-e24a72f0137c.png)
![image](https://user-images.githubusercontent.com/1266318/35017272-f75508fa-fad0-11e7-9cdf-1cb4a1ead9a9.png)

However, those descriptions are missing an important detail.  Please update them to say this:

>check PIN (dropdown): Set I/O pin to an input and get its state; high = 1, low = 0.

>check PIN (programmable): Set I/O pin of inserted value to an input and get its state; high = 1, low = 0.

**Comment by mrodriguez-parallax** [comment]
Verified new tool tip descriptions are updated to.

check PIN (dropdown): Set I/O pin to an input and get its state; high = 1, low = 0.

check PIN (programmable): Set I/O pin of inserted value to an input and get its state; high = 1, low = 0.


![2018-05-23_10-04-24](https://user-images.githubusercontent.com/20686764/40439737-b7093d44-5e70-11e8-80da-75692ba428e3.png)



![2018-05-23_10-03-46](https://user-images.githubusercontent.com/20686764/40439720-a0aebb14-5e70-11e8-9128-e0c4fe299ab0.png)
