### ISSUE TITLE
Cognew block does not accept a number in the argument socket

### ISSUE THREAD

**Issue by cbradyatinquire** [parallaxinc/BlocklyProp#136]
cognew block rejects the number block

**Comment by cbradyatinquire** [comment]
(recall that there was an idea of making this block come with a default value of 128 (i think), and load up like the delay block with that number placed in the socket)

**Comment by DarkmatterVale** [comment]
https://github.com/parallaxinc/BlocklyProp/pull/128 addresses all of the requests that were made during the call (excluding the comments regarding restricting the method calls & how that works)
