### ISSUE TITLE
MOTD not updating on Chrome browser on MacOS

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp#1361]
An update to the MOTD file was not rendering on my Chrome browser. Instead, it continued to display the older message issued about 12 hours ago. I tried CMD-R to refresh, but no success. I had to go into the Chome settings and clear the cache before the new message would appear.

The change did appear on both Firefox and Safari after refreshing the screen. Ideally, the new message should transition immediately.

**Comment by MatzElectronics** [comment]
Any update here?

**Comment by zfi** [comment]
This appears to be working correctly now. Closing.
