### ISSUE TITLE
Restrict password characters

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp#1366]
The character set used in account passwords are currently unrestricted. I am recommending that this change to the range of of characters from 0x33 to 0x7E.

**Comment by PropGit** [comment]
I think you meant 0x21 (dec 33) to 0x7E (dec 126).  Thank you for suggesting standard _special_ characters.

Also, can we (and shouldn't we) also accept space characters as well (0x20), so people can use multi-word passwords?

**Comment by PropGit** [comment]
How do we handle the limitation of the character set after people already have accounts with unlimited characters.  We can't scan to see if they've used characters outside of the 0x21 (or 0x20) to 0x7E range... so once we limit it via front-end code, they won't be able to log in and will have to do a Forgot Password option.

Also, when we do this we should add a tip near the field that tells them what characters are allowed. (a-e, A-E, 0-9, and special characters like ", #, &, and punctuation like !, ?, ", .)

**Comment by MatzElectronics** [comment]
We are currently only limiting the registration field, not the login one,
so old account with strange chars can still log in.

**Comment by PropGit** [comment]
Thanks @MatzElectronics.

**Comment by PropGit** [comment]
Due to implementation and testing of Issue #1536, this issue appears to be done as well.  Closing.
