### ISSUE TITLE
Production and Demo no longer properly "Share project using link"

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#1367]
@MatzElectronics @zfi 

On Production, using the Project Details' "Share project using link" feature no longer works.  The link provided either returns a "Project Not Found" error, or a "... resource is not available" error:

![image](https://user-images.githubusercontent.com/1266318/35346401-04e39470-00e7-11e8-8992-e0f2ee1e7a4e.png)

Here's the link I tried in this example:  http://blockly.parallax.com/blockly/projectlink?id=22501&key=1f719d78-0358-4dd3-8cf3-780f466ba2cc

It doesn't matter whether the user trying the link is logged in, or anonymous, and it doesn't matter whether the project is Private or Shared.

On Demo, the behavior is different, but still unsuccessful; it simply returns the user to the home page instead of displaying an error.

**Comment by MatzElectronics** [comment]
We *might* be able to fix this in the servlet/daoimpl for "projectlink"

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>  |  Licenses
<http://www.tspc.oregon.gov/lookup_application/LDisplay_Individual.asp?id=07080L3B270>

**Comment by MatzElectronics** [comment]
A little more background.  There are literally 3 or more copies of the
editor littered throughout the filesystem.  I've only maintained two of
them, but this sharelink is pointing to a third which is calling framec,
which is no longer used (so it's been deleted).

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>  |  Licenses
<http://www.tspc.oregon.gov/lookup_application/LDisplay_Individual.asp?id=07080L3B270>

**Comment by PropGit** [comment]
I think that was the editor that doesn't require login first to get to, and was what we used initially to demonstrate the look and feel of Blockly on-the-fly.  Apparently, it was needed for this share with link feature.

**Comment by MatzElectronics** [comment]
Yup.

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>  |  Licenses
<http://www.tspc.oregon.gov/lookup_application/LDisplay_Individual.asp?id=07080L3B270>

**Comment by MatzElectronics** [comment]
More thoughts - I'd like to see the same endpoint that is used by the
standard editor to retrieve a project take "key" as an optional argument,
and if the key is valid, served the project (shared or not)  That's how
this is supposed to work anyway, so I think it's a matter of bringing that
code into the endpoint that serves the project.  Then, we don't need to
maintain yet another editor page...

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>  |  Licenses
<http://www.tspc.oregon.gov/lookup_application/LDisplay_Individual.asp?id=07080L3B270>

**Comment by PropGit** [comment]
Yes, that sounds like a perfect solution.

**Comment by zfi** [comment]
My notes from this indicate that we should create the shared link at the time the project is created. The checkbox for sharing the link becomes an enable/disable toggle. The shared link should allow an anonymous user to view the project but not edit it. A logged in user can view it, edit it and save it. The save operation in this case is what we currently call a 'clone project' operation.

There should be (or used to be) two copies of the editor, one for demo/read-only and another for use by a logged in user. That's all I know about the editors.

**Comment by MatzElectronics** [comment]
@zfi, I'm going to split your last comment off into a new issue - creating the share key at the time of project creation and retrieving it via an endpoint

**Comment by MatzElectronics** [comment]
tested and verified. closing.

**Comment by MatzElectronics** [comment]
Reopening - @zfi and I are working on a different endpoint method for retrieving projectlink projects.

**Comment by mrodriguez-parallax** [comment]
Able to share link in another tab - no issues found
