### ISSUE TITLE
Going to the FUNCTION category causes a "ghost" to be left on 

### ISSUE THREAD

**Issue by cbradyatinquire** [parallaxinc/BlocklyProp#138]
(Probably a duplicate issue)
To reproduce -
Go to the Functions category.
Go to another category - "ghost' images of the first 2 of the 3 functions blocks will show 'behind' the blocks of the newly-selected category.

**Comment by DarkmatterVale** [comment]
Thank you for reporting this! It is not a duplicate, but it is a known issue.

**Comment by PropGit** [comment]
Strangely, in my tests, the first two blocks of Functions is left "ghosted" and the third disappears.
