### ISSUE TITLE
Error prevents further project creation

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#139]
It appears that a syntax error in a previous compile [ [Cloud-Compiler Issue#7](https://github.com/parallaxinc/Cloud-Compiler/issues/7) ] may have led to failure to create future projects.  After that compile error, any new C or Spin project results in this (below) when the _Finish_ button is clicked.

![image](https://cloud.githubusercontent.com/assets/1266318/13647010/fb30c136-e5e6-11e5-8e01-0b83a8be24bb.png)

NOTE: Existing project can still be opened and edited, but compiling them leads to NaN:
![image](https://cloud.githubusercontent.com/assets/1266318/13647075/4ad97ab6-e5e7-11e5-8539-4fc3da3e9c62.png)

**Comment by PropGit** [comment]
UPDATE: This may have something to do with a problem happening with the Cloud-Session server.

**Comment by PropGit** [comment]
UPDATE: Same problem occurred today.  
  * A restart of Cloud-Session service did not solve it.  
  * Refreshing the Chrome browser cache did not solve it.  
  * The only thing that seemed to fix it was actually closing the Chrome browser and then opening a new browser tab and logging in again.  After that, compilations worked again.

**Comment by michel-cf** [comment]
Seems to be the same problem as #148

**Comment by PropGit** [comment]
Have not seen this problem occur again.  Closing issue.
