### ISSUE TITLE
Make LCD initialize generate global debug_lcd pointer

### ISSUE THREAD

**Issue by AndyLindsay** [parallaxinc/BlocklyProp#1391]
The LCD initialize emits the pointer declaration and variable declaration together in main: 
...
int main()
{
  serial *debug_lcd = serial_open(17, 17, 0, 19200);
  ...

If the debug_lcd pointer could instead be declared globally, it would allow BlocklyProp programmers to access the Serial LCD from more than just the main function.  Perhaps the LCD initialize block could emit something like this instead: 
...
serial *debug_lcd;
...
int main()
{
  debug_lcd = serial_open(17, 17, 0, 19200);
  ...

Link to the forum discussion summarized here:
https://forums.parallax.com/discussion/168162/issue-with-writing-lcd-in-my-function

**Comment by PropGit** [comment]
@AndyLindsay - I saw the thread as well before reading this.

Can you verify for me that this _is not_ related to the fix we applied to resolve out-of-order library inclusions?  I believe it is not related, and instead is an issue with how the pointer is declared, as you stated.

**Comment by mrodriguez-parallax** [comment]
LCD generates global debug lcd pointer verified

![2018-05-23_10-17-57](https://user-images.githubusercontent.com/20686764/40440313-924b6d72-5e72-11e8-8002-4318994caeeb.png)

`serial *debug_lcd;



// ------ Main Program ------
int main() {
  debug_lcd = serial_open(17, 17, 0, 19200);

  writeChar(debug_lcd, 22);
  pause(5);

}
