### ISSUE TITLE
BADGE:  OLED cursor and text style block allows only rows 0 and 1 (correct for LARGE text, not for small)

### ISSUE THREAD

**Issue by cbradyatinquire** [parallaxinc/BlocklyProp#140]
This block is a challenge.  It needs to present different chooser options depending on whether the SMALL or LARGE text option is selected.

An option would be to make separate blocks for printing SMALL or LARGE text.  Then the row/column options could be non-dynamic. And in that case the options that are present in the block now would be the correct ones (i think) for the LARGE block.

**Comment by PropGit** [comment]
@michel-cf - Is providing two different sets of available rows in the list something we can achieve with the same morphing technique we used on other blocks to combine multiple blocks into one?

**Comment by DarkmatterVale** [comment]
Yes, this is something I can achieve with the same morphing techniques used on other blocks.

**Comment by DarkmatterVale** [comment]
@cbradyatinquire I apologize for not getting to this sooner. I am learning about the morphing techniques right now and I will keep this updated with my progress on the block.

**Comment by DarkmatterVale** [comment]
After some experimenting, I have determined that I am going to need the test server instance up and running to work on this.
