### ISSUE TITLE
Improve validity of generated HTML

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#1402]
After running the rendered HTML of the editor through a validation service and seeing over 125 errors, perhaps we should clean it up a bit :)

**Comment by MatzElectronics** [comment]
Halfway there, but still roughly 100 invalid tags/structures to go...

**Comment by zfi** [comment]
@MatzElectronics can you email your workflow for this and I will continue the work. We really need clean HTML.

**Comment by MatzElectronics** [comment]
Coming back to this issue - 

I'll focus on the editor first.  Here are some definitive tasks that we can start with:
 - remove inline javascript and move it to editor.js or blocklyc.js.  This includes "onchange", "onclick", and "onmouseup" attributes
 - investigate moving inline svgs to image files (first option), css (second option), or javascript (third option)
 - convert all custom attributes to valid ones (preface them with "data-")
 - simplify ids and classes, css
 - combine/condense nested <span> tags where possible

Also, this should be done with the goals of validity, internationalization, and accessibility.

**Comment by MatzElectronics** [comment]
@zfi, to answer your question about workflow - there isn't one per se, just run the HTML through a validator online, identify groups of things that aren't valid, grind through and fix them.

**Comment by MatzElectronics** [comment]
@zfi I figured out how to get <!DOCTYPE html> to work on the editor!  It turns out blockly is injecting itself into a zero pixel high element.  For some reason, in quirks mode, this didn't matter.  With a CSS addition and some JS to make sure it reacts to screen size changes appropriately, I think we can fix that at least!

**Comment by zfi** [comment]
Closing this issue as it now appears that our HTML is valid.
