### ISSUE TITLE
Get Shareable Link - appears broken

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#1416]
Trying to share a project by using the feature "Get Shareable Link" and it failed, producing this error:

HTTP Status 404 - /blockly/frame/framec.jsp
type Status report
message /blockly/frame/framec.jsp
description The requested resource is not available.

In case it helps, the project is this one http://blockly.parallax.com/blockly/editor/blocklyc.jsp?project=36074

**Comment by MatzElectronics** [comment]
This is a duplicate of #1367.  Demo contains a fix.
