### ISSUE TITLE
Request to minimize new project "description" field

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#1417]
Educators are having trouble creating projects because the large description box makes the buttons on the bottom not appear until scrolling down. Suggest reducing the size of this box to 25% of current size.

**Comment by PropGit** [comment]
Good idea.
Verified in Demo now.

**Comment by wstodghill** [comment]
@kgracey, @PropGit, @MatzElectronics 

The new project description box size is a great improvement (IMO). It will help users remember (including me) to set the privacy/share settings and to save! Nice improvement.

**Comment by MatzElectronics** [comment]
Tested and verified, closing
