### ISSUE TITLE
Make ActivityBot 360 the default option in Robot initialize

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#1419]

**Comment by MatzElectronics** [comment]
Tested and verified.

**Comment by wstodghill** [comment]
@MatzElectronics,

Seems to be some issues with this block! Selecting Arlo or Differential Drive (all can be checked), but the block remains ActivtyBot or ActivityBot 360.

![robot block](https://user-images.githubusercontent.com/8891440/40513924-d9f558f4-5f6c-11e8-9907-da63fda1354b.JPG)

**Comment by MatzElectronics** [comment]
Ok, thanks for letting me know.  I'll get on it shortly.

Thanks!

**Comment by MatzElectronics** [comment]
Try a force refresh...let me know if that clears it up...
