### ISSUE TITLE
Filter blocks based on board type of project

### ISSUE THREAD

**Issue by cbradyatinquire** [parallaxinc/BlocklyProp#142]
Per discussion, a goal (eventually) is to have the blocks that are presented to the user be matched to those that make sense for the board-type selected at the time of project creation.

**Comment by kgracey** [comment]
As we continue with this project this issue is more important to be resolved. David Carrier will soon be joining us with S3 blocks which shouldn't be confused with the ActivityBot, for example. What's the status of being able to implement this feature?

**Comment by DarkmatterVale** [comment]
At the moment, it is not possible to separate the blocks based on the board; I'm not sure what Michel's status on this feature is...
