### ISSUE TITLE
Servo diff drive broken

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#1427]

**Comment by zfi** [comment]
@MatzElectronics, How does one test the change you pushed up? I'm not understanding the connection between the servo diff drive broken and the more granular pause measurement.

**Comment by MatzElectronics** [comment]
Sorry - two separate issues in one fix - this also addressed #1424.
As for testing, prior to the patch, if you tried to select Servo Diff Drive from the Robot Initialize block, the dropdown would freeze on both selections, and the editor broke (JS errors), since I forgot to provide a condition for it in some relevant functions when I created those functions.
Testing is a just placing a Robot Initialize Block and ensuring that you can select servo diff drive.

**Comment by mrodriguez-parallax** [comment]
Verified user can select diff drive in servo select block without issues.
