### ISSUE TITLE
Detection of board.  Default to correct serial option

### ISSUE THREAD

**Issue by cbradyatinquire** [parallaxinc/BlocklyProp#143]
One of the GREAT things about SimpleIDE (even compared to the propeller IDE) is that the serial-port chooser almost always chooses the correct port (and in Simple IDE, doesn't even offer the incorrect serial ports).  In BlocklyProp, the chooser does not default optimally (at least in my experience on MAC)

**Comment by PropGit** [comment]
In SimpleIDE, the app registers for device change messages, and if one appears (or disappears), it makes a decision about which port to select.  This is better than ignoring device changes all together, but @michel-cf will have to determine if it's possible to employ the same kind of behavior through the browser (I don't know if it's possible).

NOTE: SimpleIDE's behavior is a compromise; it is not really how we'd prefer to see it done.  Our preference is the "AUTO" mode we employ in our legacy software (BASIC Stamp Editor and Propeller Tool).  I'd be happy to describe the behavior when we address this issue.

**Comment by DarkmatterVale** [comment]
This will probably have to be done from the client, not on the cloud (the cloud still uses the client to communicate with the device ports). I'm not sure if Python can achieve the same thing that has been achieved in SimpleIDE, or if the client can communicate data back to the cloud.

**Comment by MatzElectronics** [comment]
As @DarkmatterVale stated above, this is a function of the client, not the browser.
