### ISSUE TITLE
Blockly changes a function name after saving and reloading.

### ISSUE THREAD

**Issue by mrodriguez-parallax** [parallaxinc/BlocklyProp#1447]
Created a function and left it as default name My function, then I created a second function and left it as default My function 2. After saving and reloading the program, Blockly changed both function calls to function 2.

![2018-06-05_15-14-10](https://user-images.githubusercontent.com/20686764/41005614-21ddb43a-68d3-11e8-8443-dbdf1279fe00.png)

**Comment by PropGit** [comment]
Verified.

Also, I found that if I create the first function, then drag out the **run function " my function "** block, then create a second function, the already-existing **run function " my function "** block immediately changes to **run function " my function2 "**.

This appears to be an order of operations thing.  Perhaps it's updating the menu (which is invisible the moment you click and drag the new function block) to set the name of the first **run function** block equal to the new function block, then adds in the old **run function** block to the menu.

The former thought may not be right... it only changes the original **run function** blocks.

This, of course, leads to surprisingly broken code and unexpected times.

**Comment by MatzElectronics** [comment]
This is actually core code.  I'll see if I can tweak it.

**Comment by MatzElectronics** [comment]
I'd like to see if when we do a core upgrade, which really needs to be soon, if this gets fixed by that.

**Comment by zfi** [comment]
Just a reminder, we should not touch the Blockly core code but instead override it in code that sits above the core code.

**Comment by zfi** [comment]
Yes, I was referring to the blockly core project that Google is maintaining. My comment about touching this core code was a response to @MatzElectronics  comment ealier in the thread where he is thinking about tweaking it. I just wanted to be clear on exactly what we are "tweaking". 

The update that needs to happen is the update our internal fork of the Google blockly project and then merge that into the CDN. That is not a currently assigned task. I am working on getting that scheduled.

**Comment by PropGit** [comment]
Thanks.  If there's something we can't seem to enhance via override, then we _could_ attempt to first update our fork to their latest, fix the code, and do a PR to upstream Blockly to see if they'll absorb it.  If they don't, this remains an easily breakable feature that spells maintenance headaches we don't want.

**Comment by MatzElectronics** [comment]
This appears to be fixed in newer versions of the blockly core.

**Comment by MatzElectronics** [comment]
Tested and verified, closing.
