### ISSUE TITLE
Add TCP to WX Scan Block

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#1448]
The blocks called WX Connect HTTP in the advanced menu (communicate). The other block is WiFi Print TCP (as option). What seems to be missing is the WX Scan block (has no TCP option). It seems like we just excluded the list of four options from Scan that are present in Print @MatzElectronics @jeffam70 

Can you update the repository? Matt is not aware which branch we're building from (101 or 100?).

**Comment by PropGit** [comment]
We need to update branch .101 now. The former, .100 is the previous release.

Regardless, I don't have access to deploy a new version of Blockly.

**Comment by MatzElectronics** [comment]
In place - testing of all WX blocks is in another issue.  Closing.
