### ISSUE TITLE
Increment block broken

### ISSUE THREAD

**Issue by cbradyatinquire** [parallaxinc/BlocklyProp#145]
In Programming
---->Math
----->Decrement

Creating a block to increment a variable, e.g., "counter" leads to the C code

++counter

No semicolon.

(And is the ++ correctly placed here?  shouldn't it be

counter++;

?

[Same issue with decrement.  compiler catches the error]

**Comment by DarkmatterVale** [comment]
I will fix this...

The ++ can be placed in either position; one is called a pre-increment operator and the other is called a post-increment operator. If it is a pre-increment operator, it is completed before the rest of the statement is completed (i.e. ```if ( arr[++counter] == 5 )``` will increment counter before evaluating the rest of the expression.

**Comment by PropGit** [comment]
Pre- and post- decrement/increment may be too advanced a concept for the audience, although we _could_ create pre-decrement/pre-increment and post-decrement/post-increment blocks to serve both... or a single block where pre/post and decrement/increment are selectable.  I still think it may be too complicated for this purpose.

Thoughts?

I'm leaning towards us just sticking with pre- decrement/increment judging from common uses.  Anyone have a compelling reason to do just post, or support both pre/post options?

**Comment by cbradyatinquire** [comment]
Ok - let me step back for a minute.
The Increment/Decrement block is a COMMAND block (not a value block).  that is, it has the UI that suggests it is an operation, not a function returning a value.

There is a coherent use of this concept, which simply means  "In/decrement the value of the variable...." [var]

Which to me would correspond to the line

var++;
or
var--;

The difference between pre- and post- in/decrementing is (I believe) really ONLY relevant when the operation is seen to RETURN A VALUE, as in Vale's example:

 arr[++counter] == 5 

HERE the incrementing of the variable "counter" is actually a kind of SIDE EFFECT of the value-reporting function "++counter" whose return value is fed in as an index to the array.

THIS use (where increment is a value-returning function with a side effect) is what seems to me to be an advanced usage.

In contrast, INCREMENTING or DECREMENTING itself, as an alternative to

counter = counter + 1;

seems to me to be elementary.  It is in fact preferable (conceptually) to 

counter = counter + 1;

in my mind, because that idea is (in my experience) difficult for kids who are not yet used to seeing the equals sign as an ACTION SYMBOL rather than an assertion of static equality.  That is, to make sense of 

counter = counter + 1;

I have to view as saying "Make (the new value of) counter, (the old value of) counter + 1"  and NOT "counter is equal to one more than itself" (i.e., a statement of static equality).  This is hard for kids that haven't been exposed to the notion of function.


SO... I would argue for 

counter++; 

and KEEPING the block type as a command block (not suggesting that it returns a value which could be fed into another function as an argument).

**Comment by DarkmatterVale** [comment]
I agree with @cbradyatinquire  assessment. @PropGit What do you think? Are you alright with the proposed solution?
