### ISSUE TITLE
Badge: IR Receive not working (and not presented well for blockly prop user base)

### ISSUE THREAD

**Issue by cbradyatinquire** [parallaxinc/BlocklyProp#147]
IR receive block appears to (1) ask for a variable as argument and (2) return a variable. 

It is not clear (to users)  how this is intended to work.  
Based on the C primitive that backs this block, I believe it is supposed to take a char buffer as the argument and return an integer (length) as the return value.

BUT I can't test this, as I don't see how to make a char buffer in the blockly prop environment, and 

[NOTE:  Send DOES work, as tested by receiving through a board programmed with the SimpleIDE]

**Comment by DarkmatterVale** [comment]
I will let you know as soon as I have figured out how to create one (or if it is not possible) and how to do it.

With respect to how the block is intended to work, I think an explanation will have to be provided in documentation. Do you believe that will suffice or do you think a change to the block will be required to simplify it?

**Comment by DarkmatterVale** [comment]
@cbradyatinquire What do you think of my proposed solution?

**Comment by cbradyatinquire** [comment]
Do you mean, the documentation solution? 
I think that's our only solution unless we figure out a good way to translate the CONCEPT into the blocks metaphor.
Ideas from the group on THAT?

**Comment by DarkmatterVale** [comment]
@cbradyatinquire Has this been fixed?

**Comment by cbradyatinquire** [comment]
I may not be seeing merged code (wed 05/18/16 at 2:00 PM central time).  

Per the above, I think that we have a simple-ish solution (see below) that we should implement and publish.  Then, we should think about a solution that fits better with what we learn are our users' mental models about this (passing a var as an argument to be filled is totally foreign to a blocks-based logic, I think).

For the simple-ish solution, working within the Blockly UI constraints (as I infer them from using the system), I think we might still be able to do something like what i'm attaching as a screenshot here.

While I don't deny this is a BIT awkward, I believe the awkwardness is due to the pattern of the code itself, rather than to the blocks presentation.  So, I do think we should publish something like this and get a sense of how users think about it.

<img width="372" alt="screen shot 2016-05-18 at 2 16 38 pm" src="https://cloud.githubusercontent.com/assets/769072/15371942/8ac00110-1d03-11e6-8bb1-4e5942f64b14.png">
