### ISSUE TITLE
Can't Delete Project

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#1487]
When I try to delete project 47422 - see http://blockly.parallax.com/blockly/editor/blocklyc.jsp?project=47422 - I get the error message attached. 
![delete](https://user-images.githubusercontent.com/8891440/41908147-a6d43890-7908-11e8-8080-c59e91d19b8b.JPG)

**Comment by PropGit** [comment]
When I try to access that project it tells me it does not exist.  Maybe it's still marked private?

**Comment by wstodghill** [comment]
It is now saved as public, but I still cannot delete it.

**Comment by PropGit** [comment]
Thanks @wstodghill 
I think we'll have to dig in to figure out what's happening here.  

@MatzElectronics @zfi - any ideas?

**Comment by zfi** [comment]
The last update changed how a shared project worked. The delete project operation now needs to address the possibility of a shared project record before the base project is removed. This is a bug.

**Comment by zfi** [comment]
PR #1488 should be staged on Demo by 10:30 PST and will be ready for testing.

**Comment by PropGit** [comment]
@wstodghill - Will you test this at your earliest convenience on your project?

**Comment by wstodghill** [comment]
@PropGit - works on DEMO BlocklyProp, but not on Beta BlocklyProp - same error as above.

**Comment by wstodghill** [comment]
@PropGit - Finally got one to delete today - just kept trying. Still can't delete #47442, #47937, and #47939. Could one of you delete these? They are marked public now.

**Comment by zfi** [comment]
The updated code is only on the Demo server. Now that we have verification that it works as intended we can include the update in the next release.

**Comment by wstodghill** [comment]
Thanks @zfi

**Comment by wstodghill** [comment]
@MatzElectronics - This still does not work on the live BlocklyProp site. Still unable to delete http://blockly.parallax.com/blockly/my/projects.jsp#47937 and http://blockly.parallax.com/blockly/my/projects.jsp#47939 

When I try, I still get...
![delete error](https://user-images.githubusercontent.com/8891440/44262989-c1befc00-a1e2-11e8-9d59-ca8a9137390b.JPG)
