### ISSUE TITLE
Feature request: Add screen orientation option to OLED command block

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#1491]
http://forums.parallax.com/discussion/168050/can-or-will-the-oled-initialization-block-be-modified-to-include-screen-rotation#latest

This was somewhat touched on in an earlier post explaining why the Blockly OLED Init block only offers 5 parameters while in the code view there were 6, the 6th one being for which edge of the OLED was the top. Currently that value is locked at 2, the edge opposite the pins is the top. The Code view is read only and so cannot be changed.
Is there anything in the works to expand the Initialization block to 6 parameters? Or is the only way to import the code view into SimpleIde and make the change there? That would require an extra source code to be maintained.

**Comment by MatzElectronics** [comment]
#1547 added these options to the command block.

**Comment by Steph-Parallax** [comment]
Help update - add items to OLED Command block. Be sure to explain this changes origin for next write but does not rotate existing image on display.

**Comment by MatzElectronics** [comment]
Done, closing.
