### ISSUE TITLE
WX Scan Doesn't Recognize WX Initialize 

### ISSUE THREAD

**Issue by CGracey** [parallaxinc/BlocklyProp#1494]
By default if a WX block is used without WX Initialize the error ```  // ERROR: WX is not initialized! ``` shows up in the code section.

This has a reverse interaction with the WX Scan block. For example, when WX scan is alone in the project (no WX init block) it still produces the code:

```C
// ------ Libraries and Definitions ------
#include "simpletools.h"

// ------ Global Variables and Objects ------
int wxHandle;
int item;



// ------ Main Program ------
int main() {

  wifi_scan(POST, wxHandle, "txt%d%c", &item, &item);

}
```

When it should produce:

```C
// ------ Libraries and Definitions ------
#include "simpletools.h"

// ------ Global Variables and Objects ------
int wxHandle;



// ------ Main Program ------
int main() {

  // ERROR: WX is not initialized!

}
```

The reverse happens when you add a WX init block to the project.

![capture](https://user-images.githubusercontent.com/20099916/42541912-421b6188-8459-11e8-96d5-7f9b9f8110e8.PNG)

Incorrectly displays the error when an init block is present in the project.

```C
// ------ Libraries and Definitions ------
#include "simpletools.h"
#include "wifi.h"

// ------ Global Variables and Objects ------
int wxHandle;
int item;



// ------ Main Program ------
int main() {
  wifi_start(31, 30, 115200, WX_ALL_COM);

  // ERROR: WX is not initialized!

}
```

**Comment by MatzElectronics** [comment]
Just submitted a PR for this - it should be in place for re-testing soon.

**Comment by MatzElectronics** [comment]
Fix verified.
