### ISSUE TITLE
RGB Set Block for WX Badge

### ISSUE THREAD

**Issue by CGracey** [parallaxinc/BlocklyProp#1508]
![capture2](https://user-images.githubusercontent.com/20099916/43291021-d2e4ad72-90e4-11e8-9711-54b04ca286fe.PNG)

Currently, this block just uses the 4 WS2812 LEDs on the badge, and it accepts any value into the LED number selection. 

The input should be limited from 1-4, four being the furthest left and one being the furthest right LED. But also since it can accept variables, if the variable's value is greater than 4 it would probably be good to just give a warning and/or default to 4.

**Comment by MatzElectronics** [comment]
Can I close this?

**Comment by PropGit** [comment]
Maybe I missed something, was a warning created?

**Comment by MatzElectronics** [comment]
No.  Currently warnings are reserved for situations where what you are
doing is not going to work/compile/etc.  If a user chooses a too big
number, it still works.  Plus, a user adding Led s would see a warning even
when they're doing nothing wrong...

**Comment by MatzElectronics** [comment]
Can we close this?

**Comment by MatzElectronics** [comment]
Closing.
