### ISSUE TITLE
RBG Set LEDs Block Produces "Undefined" After Comment Block

### ISSUE THREAD

**Issue by CGracey** [parallaxinc/BlocklyProp#1509]
There's an interaction with the comment block and set LEDs block where if they are both present in a project, all the blocks under the Set LEDs block won't produce any code and will instead just produce the code "undefined".

![blocksreal](https://user-images.githubusercontent.com/20099916/43342310-1f9d964e-9197-11e8-8d71-07f68a0809a2.PNG)

The blocks above will produce this code while the set LEDs block is active:

```C
// ------ Libraries and Definitions ------
#include "simpletools.h"
#include "badgewxtools.h"
#include "ws2812.h"
#define RGB_COUNT 4

// ------ Global Variables and Objects ------
ws2812 *ws2812b;
int RGBleds[4];



// ------ Main Program ------
int main() {
  badge_setup();
  ws2812b = ws2812b_open();

  // Comment Block
  undefined
}
```

However when the set LEDs block gets disabled (below), it no longer makes itself and and all the blocks below it generate "undefined"

```C
// ------ Libraries and Definitions ------
#include "simpletools.h"
#include "badgewxtools.h"
#include "ws2812.h"
#define RGB_COUNT 4

// ------ Global Variables and Objects ------
ws2812 *ws2812b;
int RGBleds[4];



// ------ Main Program ------
int main() {
  badge_setup();
  ws2812b = ws2812b_open();

  // Comment Block
  ws2812_set(ws2812b, RGB_PIN, RGBleds, RGB_COUNT);

}
```

There may be other blocks that have this interaction but I haven't found any yet. One last note - disabling the comment block doesn't resolve the issue, only disables the set LEDs block does.

**Comment by MatzElectronics** [comment]
Should be fixed after 2:15.  Please check.

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>  |  Licenses
<http://www.tspc.oregon.gov/lookup_application/LDisplay_Individual.asp?id=07080L3B270>

**Comment by CGracey** [comment]
Tested and Verified.
