### ISSUE TITLE
WX and Terminal in BlocklyProp

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#1510]
I am successfully programming the ActivityBot 360 wirelessly using the WX module using Simple IDE and BlocklyProp. I can use the Parallax Serial Terminal with Simple IDE to run the "Welcome" program and print Hello! in the Parallax Serial Terminal.

I have not been able to print on the Terminal in BlocklyProp. For instance, this code...
![blocklytest](https://user-images.githubusercontent.com/8891440/43797325-a64b9df4-9a4c-11e8-8c1e-d78d52dce06d.PNG)

results in this error message...
![terminal failure](https://user-images.githubusercontent.com/8891440/43797347-b5baabae-9a4c-11e8-997e-007810e39001.PNG)

Does this have to do with communication rate or might I have something else mis-set, or is it a bug? Ideas?

I must admit I do not fully understand the Internet protocol very well! ;-) Sure is fun though!

**Comment by PropGit** [comment]
Sorry about that - this is because that feature isn't finished in the BlocklyProp Client software.  It supports wireless programming but not wireless debugging currently.

**Comment by wstodghill** [comment]
@PropGit - Good to know - At lease I'm not the Bug! ;-)

**Comment by MatzElectronics** [comment]
I'm going to close this - the issue/work is in the BP-Client/Launcher-web repo.
