### ISSUE TITLE
Touchpads A and B - C library code has issue

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#1512]
Unable to access bit0 and bit7 of the BlocklyProp "any buttons" command, regardless of touchpad sensitivity added. C library?

**Comment by VonSzarvas** [comment]
bits.... 
are you using BadgeWX or Hackable Electronic Badge as the target ?

**Comment by VonSzarvas** [comment]
Ken-- did the demo link I sent over work for detecting the passive buttons directly?
http://demo.blockly.parallax.com/blockly/projectlink?id=1984&key=c299121d-ad3f-4ab1-ac88-9933a25c996f




If that works, but the "any buttons" doesn't, then maybe the any-buttons byte is not getting updated with the passive buttons status.... could be a badgewxtools lib thing.

**Comment by MatzElectronics** [comment]
There is only a tiny bit more wiggle room in the code here.  Any more than that would require a hardware change to the badge itself.  I am going to modify the block a bit to simplify the menu and change the default to something more sensitive.

**Comment by MatzElectronics** [comment]
Did the best I could with it, not much wiggle room.
