### ISSUE TITLE
Memory contacts in Badge WX type (in demo)

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#1514]
Sample program does not compile http://demo.blockly.parallax.com/blockly/editor/blocklyc.jsp?project=1994. Too many errors to go through them. Maybe get a look and start knocking them out since these blocks are potentially very useful (if they are what I think, from DEFCON 24 badge Spin code).

**Comment by MatzElectronics** [comment]
Please re-test

**Comment by MatzElectronics** [comment]
Fix verified.
