### ISSUE TITLE
Save as PropC

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#1518]
It's generating the C code upon opening file instead of grabbing the C code and saving it directly.

**Comment by MatzElectronics** [comment]
I think I fixed it, needs testing.  Try saving a badge WX file as propc and see if it still blows up.  I was wrong, if the fix works, it was a 1 line code change :)

**Comment by MatzElectronics** [comment]
Moving to next milestone.  While done, docs are not, plus the save-as that includes a board type, that would allow this feature to be accessed, is still a bit buggy.

**Comment by MatzElectronics** [comment]
Ready for full-fledged testing.

**Comment by zfi** [comment]
How do we test this? Are there any docs that describe what the process is and what is the expected behavior?
