### ISSUE TITLE
Sony Remote Block

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#1527]
Request to add the Sony remote control block.

**Comment by kgracey** [comment]
The Sensor category. . .it's a legit sensor for this purpose and easy to tuck into this release.

**Comment by MatzElectronics** [comment]
Please test.

**Comment by kgracey** [comment]
Works! Tested with this code http://demo.blockly.parallax.com/blockly/editor/blocklyc.jsp?project=2047#
