### ISSUE TITLE
New user account login fails after password change

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp#1533]
We have a few reports of new users unable to log in after they complete a password change on the site. There is evidence in the database that the accounts were created but remained unconfirmed.  It is possible to reset an account password on a registered but unconfirmed account.

It seems that it would be prudent to add a message to the Change Password page, including a link to the Resend Account Confirmation page when the server encounters a password reset request on an unconfirmed account.

**Comment by PropGit** [comment]
Duplicate:  https://github.com/parallaxinc/BlocklyProp/issues/1445
Related: https://github.com/parallaxinc/BlocklyProp/issues/1439

**Comment by zfi** [comment]
Closing as a duplicate. Issue resolved in PR #1534
