### ISSUE TITLE
Password Restrictions

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#1536]
From zfi:

> This is just an FYI concerning user passwords on the BlocklyProp sites. The mechanism that encrypts the user passwords in BlocklyProp supports only ACSII characters less than ACSII-128. This can be an issue for users that are expecting complete UTF-8 support. Until (or if)  this is resolved, we should ensure that there is documentation on the password restrictions wherever we keep such documentation.

I'm submitting this issue suggesting either of the following, with the first being highly recommended regardless of whether or not the second is performed:

1. Give exact password requirements and limitations right next to the password field on the registration page and login page.  Right now, the only requirement shown is "Password should be at least 8 characters long."
2. Enhance the encryption system to support UTF-8 encoded characters; ie: typical Unicode range in us

I don't recall seeing Unicode ranges allowed in any sites that require passwords in my day-to-day use, so the actual need to implement # 2 is a question that should be considered.

**Comment by MatzElectronics** [comment]
Please check.  Should be there now.

**Comment by PropGit** [comment]
Don't see it.  

![image](https://user-images.githubusercontent.com/1266318/45495267-c619fe80-b727-11e8-87d1-3c1992a691af.png)

**Comment by PropGit** [comment]
@zfi - is Demo's Jenkins pulling from 1.0 branch yet?

**Comment by zfi** [comment]
There was an issue where the build system was deploying the 1.0 code base but the Demo install script was installing the 0.101 version because that is the version number (major.minor) specified in the translations file. This is a fail-safe to ensure that the build and deployment systems agree on what they are publishing. If they cannot agree, the deploy system redeploys the previously successful deployment.

Now that the systems agree again, you see that we are running 1.0.440 on Demo. I did verify that the new code pushed up last night is in this release. The password fields are not behaving as expected.

**Comment by Steph-Parallax** [comment]
Clarification of specific highlighting behavior desired:
Submit button looks disabled until 8th character is entered. If an invalid character is entered, or an attempt to submit is detected, highlight in red. When 8 valid characters are entered, submit button looks available and highlight is green.

**Comment by Steph-Parallax** [comment]
@MatzElectronics Let's get this finished to the above desired behavior. Do any of the issues raised in #1366 have an effect here; or can these be cleared together?

**Comment by zfi** [comment]
One minor detail when the passwords do meet or exceed 8 characters; the first password box turns green while the second box remains grey.  Not sure if that is an "as designed" or not. 

![screen shot 2018-10-10 at 16 42 43](https://user-images.githubusercontent.com/8442260/46772206-a684e000-ccab-11e8-9cc8-ecd3c32e7bab.png)


The character parser for the password field is accepting values from ASCII 32 (space) through ASCII 126 (z) which includes all sorts of symbols.
```
for(var t = 0; t < passValue.length; t++) {
    if(passValue.charCodeAt(t) < 32 || passValue.charCodeAt(t) > 126) {
        passWarn = true;
    }  
}
```
This appears to work as designed. Can the [Profile->Change](http://demo.blockly.parallax.com/blockly/profile) Password page receive the same treatment? AFAIK, it is the only other place where we persist the user password.

**Comment by PropGit** [comment]
Verified.  PASSED!

* [**PASSED**] The listed desired behavior
  >Submit button looks disabled until 8th character is entered.

  appears proper (see below): the _Register_ is disabled until there's at least 8 characters typed into the _Password_ field.
![image](https://user-images.githubusercontent.com/1266318/47742620-434af580-dc3a-11e8-9266-bf25a0454063.png)

* [**PASSED**] The blue highlighted field (denoting focus) changes to green when at least 8 characters are typed in:
  ![image](https://user-images.githubusercontent.com/1266318/47742988-2236d480-dc3b-11e8-812a-4421cc8adb70.png)

* [**PASSED**] but if less than 8 are entered and focus leaves the field, it turns grey and a warning hint appears:
  ![image](https://user-images.githubusercontent.com/1266318/47743053-4b576500-dc3b-11e8-8952-1ed79e186921.png)
  Note that it does not highlight in red (although the desired description is ambiguous about this, so I'm going to assume the current behavior is fine.

* [**PASSED**] When an invalid character is entered, the highlight turns red and a red descriptive error appears.
  ![image](https://user-images.githubusercontent.com/1266318/47743901-54493600-dc3d-11e8-9647-574ab36d145e.png)
I tried entering almost every character from ASCII 2 through ASCII 31, and ASCII 128 through ASCII 160, then random characters in the ASCII 161 through ASCII 255 range.

* [**PASSED**] Password fields accept the 94 characters reported above (plus a forgotten 95th character, "\")
