### ISSUE TITLE
CSS broken on user profile page

### ISSUE THREAD

**Issue by paragitadmin** [parallaxinc/BlocklyProp#1539]
Styles are not getting applied correctly on this page after the user logs in.

http://blockly.parallax.com/blockly/profile

**Comment by MatzElectronics** [comment]
Should be fixed.

**Comment by zfi** [comment]
Confirmed. Closing the issue.

**Comment by Steph-Parallax** [comment]
@zfi Do you need any additional info about which files changed in order to get this into production?

**Comment by zfi** [comment]
Actually, yes. I can't seem to locate the pull requests associated with this issue. That would be very helpful.

**Comment by MatzElectronics** [comment]
#1541, this commit: https://github.com/parallaxinc/BlocklyProp/pull/1541/commits/edb98d36e807db7a6d6742142ce70b068c294400
