### ISSUE TITLE
WX Scan Multiple block doesn't change target

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#1540]
It's possible to select multiple targets from the WX Scan Multiple block, but they never _stick_ and the code is left only with POST, even if POST wasn't selected.

![image](https://user-images.githubusercontent.com/1266318/45449820-155e2180-b68b-11e8-8c31-0dd513d9faa9.png)

... and after you click away and back again:
![image](https://user-images.githubusercontent.com/1266318/45449863-46d6ed00-b68b-11e8-8301-9e9e0ece7b71.png)

Code generated:

![image](https://user-images.githubusercontent.com/1266318/45449874-4d656480-b68b-11e8-8795-18b9dd8ba460.png)

**Comment by MatzElectronics** [comment]
Ready to be re-tested.

**Comment by PropGit** [comment]
Still not seeing a difference.  Maybe Demo is not updating?

**Comment by zfi** [comment]
Demo is now updating from the 1.0 branch of the CDN.

**Comment by PropGit** [comment]
Tested and verified.
