### ISSUE TITLE
Problem with servo360 library - BUG?

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#1552]
From [http://forums.parallax.com/discussion/168974/problem-with-servo360-library#latest]

Roy Eltham posts,

> I have a bot driving around using the 360 feedback servos. Using abdrive360 with just drive_speed to move/turn and stop. I am using simpleIDE with the latest Learn folder libraries, but the same thing happens in BlocklyProp (since it uses the same libraries).
> 
> If the bot gets stuck against a wall while going forward (or backward) such that the wheels can not turn, then the servo360 code gets stuck constantly trying to turn the servos. Even if you do drive_speed(0,0), it just ignores that. No other drive_speed() calls will work. In order to get things unstuck you have to pickup the bot so the wheels can turn, and they will turn a bunch in the direction it was going when it got stuck. I've tried a bunch of different things to resolve this, including turning feedback off and back on, disabling and enabling the servos, and using servo360_getAngle followed by servo360_angle to make it stop trying to go. The angle functions sort of work to stop the problem, but after calling them (even once) the drive_speed calls become erratic and odd.
> 
> I looked over the abdrive360 and servo360 code a bunch and there doesn't appear to be any way for me to resolve this without changing the library code.
> 
> Also, there is no way that I could find to reset/disconnect the servos once you have called drive_init/Servo360_connect functions. I thought maybe I could detect that the bot is stuck and then reset things, but that's not an option either...
> 
> Any help on this would be greatly appreciated!

Thanks for taking a look.

**Comment by reltham** [comment]
This should probably go in the Simple Libraries github issue tracker.

**Comment by AndyLindsay** [comment]
The first attempt at correcting this behavior is discussed on the forums [here](http://forums.parallax.com/discussion/168974/problem-with-servo360-library), and a correction that does not involve any block changes is [here](https://github.com/parallaxinc/Simple-Libraries/commit/cebfb57548649b34b416de7a0641b7e64a8427bb).

**Comment by AndyLindsay** [comment]
Updated in library.
