### ISSUE TITLE
Infrequent login trouble

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#1556]
I'm not sure if this should be noted here or in cloud session.

On occasion, I've woken up my VM from sleep (from a previous day) and hit refresh and logged in on the Demo site that was leftover from a previous session.  When I log in, I see something like this (which just happened):

![image](https://user-images.githubusercontent.com/1266318/46297446-8a699c00-c551-11e8-9a88-9135199d241d.png)

Then, if I strip the URL down the the domain, it refreshes just fine and clearly indicates that I'm logged in and can browse around and view projects.

**Comment by zfi** [comment]
@PropGit, do you have the stack trace from this event? That would be very useful. If not, I can recreate the event locally.

I suspect that, when you update the URL, the browser is getting a new session ID. What I do not know for sure is if the authentication token is getting expired when the session id is expired.

**Comment by zfi** [comment]
Linked the SQL timeout issue to this issue. The session is expiring and not being detected in at least one code branch. The SQL error is an artifact of the session timeout.

**Comment by zfi** [comment]
The servlet request handler is trying trying to determine if the session is still authorized. When it makes the attempt on a session id that has aged out, the service layer throws an UnknownSessionException exception. This exception is not trapped at any level in the servet and is then rendered as a stack dump.

**Comment by zfi** [comment]
The goal for testing this is to login into the BlocklyProp site; navigate to any page and then let the browser sit for 12 or more hours before attempting any further navigation. 

Verification process:
* Navigate a browser to http://demo.blockly.parallax.com.
* Log in to the Demo BlocklyProp.
* Let the browser sit at least 12 hours or overnight.
* Click on any of the project links, menu links or the Parallax logo.
* The browser should be redirected to either the login page or the home page.
* The browser should *NOT* display a stack dump on the browser page.

**Comment by zfi** [comment]
Verified that this is no longer failing after a 36 hour wait period.
Closing the issue.
