### ISSUE TITLE
Project details' "BlocklyProp" header leads to nowhere

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#156]
On the Project details page...
![image](https://cloud.githubusercontent.com/assets/1266318/13679629/9b4c505a-e6a9-11e5-9c10-47484e901e1b.png)

...the __BlocklyProp:__ header is a link to nowhere.

I don't know why it's a link (may be a leftover from before we had the titlebar) but it should probably just be changed to a normal, unlinked, header.

**Comment by michel-cf** [comment]
Is BlocklyProp in the title even necessary? This comes from the day where there was no menu, now the BlocklyProp logo and name is on the left side of the menu bar.

**Comment by PropGit** [comment]
Good point, @michel-cf.  Let's remove "BlocklyProp" from there completely.
