### ISSUE TITLE
Memory contact already stored block throws a compiling error.

### ISSUE THREAD

**Issue by mrodriguez-parallax** [parallaxinc/BlocklyProp#1562]
The Memory contact already stored block causes a compiling error. Simply adding it to your block code throws a compiling error.

![2018-10-04_15-39-03](https://user-images.githubusercontent.com/20686764/46507123-d59edb80-c7eb-11e8-8364-1fe1cc51d9b1.png)

**Comment by PropGit** [comment]
Merged with #1563 and closed.
