### ISSUE TITLE
Memory contact block causes compiler error

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#1563]
The **Memory contact** block causes compiler error.

this project:
![image](https://user-images.githubusercontent.com/1266318/46507465-75109e00-c7ed-11e8-9ee3-e517f62bad17.png)

creates this code:
~~~
// ------ Libraries and Definitions ------
#include "simpletools.h"
#include "badgewxtools.h"

// ------ Global Variables and Objects ------
char item[64];



// ------ Main Program ------
int main() {
  badge_setup();
  item = stored("Last, First");

}
~~~
causes this error:
>Compile... Failed!

-------- compiler messages --------
Included libraries: badgewxtools, simpletools
single.c: In function 'main':
single.c:16:8: error: incompatible types when assigning to type 'char[64]' from type 'int'

This has also been seen by @mrodriguez-parallax and reported as "Simply adding it to your block code throws a compiling error."

![2018-10-04_15-39-03](https://user-images.githubusercontent.com/20686764/46507123-d59edb80-c7eb-11e8-8364-1fe1cc51d9b1.png)

**Comment by PropGit** [comment]
This seems like it may be related to this issue #1561

**Comment by PropGit** [comment]
Also reported #1562

**Comment by paragitadmin** [comment]
Can we close this issue and follow this in issue #1562 ?

**Comment by PropGit** [comment]
How about we close the other one as this one provides more information.  I'll bring in some detail from the other one.

**Comment by zfi** [comment]
@mrodriguez-parallax: We moved your issue into this one since Jeff had expanded on the issue already.

**Comment by PropGit** [comment]
Verified fixed.
