### ISSUE TITLE
Comparisons of negatives with size of string fail

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#1565]
The C strlen() function must be returning an unsigned int (or something similar) because checking if a negative number is less than **length of string** fails (and should be true).

[Here's a project](http://blockly.parallax.com/blockly/projectlink?id=58518&key=e4471970-5a7f-4c54-8593-2c5914612590) that shows the expected followed by unexpected:
![image](https://user-images.githubusercontent.com/1266318/46566674-0bb98980-c8d8-11e8-9860-49b5ce9d1149.png)

It produces this output:
> true
false

**Comment by MatzElectronics** [comment]
What needs to be modified in the generated c to make this work?

**Comment by MatzElectronics** [comment]
Got it - try it now.  You'll have to put a six-character long string into variable "Str" first, otherwise strlen will return 0, and it would still return false.

**Comment by PropGit** [comment]
Verified that the problem is now solved.

>You'll have to put a six-character long string into variable "Str" first, otherwise strlen will return 0, and it would still return false.

Yes indeed.
