### ISSUE TITLE
String variable set block doesn't always cause proper definition

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#1568]
These two nearly-identical **String variable set** blocks produce very different declarations:
![image](https://user-images.githubusercontent.com/1266318/46567406-69090700-c8e7-11e8-9873-a37a1232d31b.png)
~~~
// ------ Libraries and Definitions ------
#include "simpletools.h"

// ------ Global Variables and Objects ------
char Str[64];
char NewStr[10];



// ------ Main Program ------
int main() {

  strcpy(Str, "Hello"); // Save string into variable Str.

}
~~~

**Comment by PropGit** [comment]
This combination (single **String variable set** block mutated to contain two string definitions) currently doesn't produce very different declarations, but rather produces no declaration of NewStr.  Maybe the code is being worked on as I type?

[This example project](http://demo.blockly.parallax.com/blockly/projectlink?id=2100&key=34271c76-85b5-4216-8fb1-8ab011bb1b4e):
![image](https://user-images.githubusercontent.com/1266318/46782256-638e3100-ccda-11e8-90c9-4907632b5b1d.png)
Produces this code:
// ------ Libraries and Definitions ------
#include "simpletools.h"

// ------ Global Variables and Objects ------
char Str[10 + 1];



// ------ Main Program ------
int main() {

  strcpy(Str, "Hello"); // Save string into variable Str.

}

**Comment by MatzElectronics** [comment]
Correct - variables aren't defined by that block.  Additionally, the block will have no effect on blocks variables of type "int".  I should be able to filter the dropdown menu on that block in the future, but I would contend that it is functioning as well as we can get it to currently without some other stuff (new core with better variable type handling) in place.

**Comment by MatzElectronics** [comment]
Our current core has no good way to track a variable's type on the fly (before code generation). A couple of attempts I've made in the past failed miserably and created more problems than solutions. The new core has a method for tracking type at the block level, well before code generation.

I suggest closing this, as it is the same root cause/issue as #1561.

**Comment by PropGit** [comment]
After discussion, I agree as well.  Closing.
