### ISSUE TITLE
String variable set block produces horribly incorrect declaration

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#1569]
This is probably related to Issue #1568.
Using two **String variable set** blocks without specifying an assignment for the first's variable, results in an **int** definition instead of a **char** array.

![image](https://user-images.githubusercontent.com/1266318/46567442-b71e0a80-c8e7-11e8-9600-c8f650874fba.png)
~~~
// ------ Libraries and Definitions ------
#include "simpletools.h"

// ------ Global Variables and Objects ------
int Str;
char NewStr[10];



// ------ Main Program ------
int main() {


}
~~~

**Comment by PropGit** [comment]
Thanks.  Didn't know about the mutator.  

There's still a bug now.

Here's my project for testing **get part of string** and my **User defined code** to replace it:
![image](https://user-images.githubusercontent.com/1266318/46592723-5541da00-ca7a-11e8-9ad7-babe27a89c2e.png)

This (as seen above) works properly; however, if I remove or disable the **get part of string** block, then the NewStr variable is mis-defined once again:
~~~
// ------ Global Variables and Objects ------
char Str[64];
int NewStr;
~~~

**Comment by PropGit** [comment]
The single-use warning is verified.
The block still produces invalid code, as seen here:
![image](https://user-images.githubusercontent.com/1266318/46781082-bb299e00-ccd4-11e8-8a3b-a8862c5e0dc4.png)
**Code is:**
![image](https://user-images.githubusercontent.com/1266318/46781090-c1b81580-ccd4-11e8-8e5e-d38083402825.png)
**Error is:**
![image](https://user-images.githubusercontent.com/1266318/46781115-d98f9980-ccd4-11e8-8cf9-1ccf7e525ab8.png)

**Comment by MatzElectronics** [comment]
@PropGit I would like to suggest that this is a different/new issue, and one that can't be solved quickly or immediately.  Currently, variable type (sting or int) detection only happens on *assignment*, so without anything assigned to that variable in the beginning of your program, it is assumed to be an int, and would fail in this use.

I would contend that the original issue is now fixed.

**Comment by zfi** [comment]
The block is declaring a string. It cannot be allowed to create a int in the code - ever - in my opinion. Can the block initialize the variable when it is declared? That would address the assignment limitation.

**Comment by MatzElectronics** [comment]
Not without a core upgrade, or adding a dropdown to the variable block itself.  One way to sort of do this now is to start your program with block that sets the variable in question to a dummy string.n

Our current core has no good way to track a variable's type on the fly (before code generation).  A couple of attempts I've made in the past failed miserably and created more problems than solutions.  The new core has a method for tracking type at the block level, well before code generation.

I suggest closing this, as it is the same root cause/issue as #1561.

**Comment by PropGit** [comment]
It does indeed work if the variable has been initialized elsewhere.  Closing after agreeing with discussion; looking forward to better variable and type handing once we can absorb the new core officially.
