### ISSUE TITLE
Create a "dictionary" of block colors

### ISSUE THREAD

**Issue by cbradyatinquire** [parallaxinc/BlocklyProp#158]
both for our internal discussion and for end-users' benefit, it would be good to have a dictionary of colors and what we take them to mean.

**Comment by DarkmatterVale** [comment]
@PropGit Has Parallax created a color scheme as of yet or is that still on the todo list?

**Comment by michel-cf** [comment]
According to #69 we were planning on making the color scheme a bit brighter. And to answer @DarkmatterVale question: no, there haven't yet been any decisions on what colors to use. I've tried to keep them the same within each category but there should be a management decision on what colors to use.

**Comment by PropGit** [comment]
@cbradyatinquire and @DarkmatterVale - please check the latest on Issue #69 and weight in if you feel compelled.  I'd like to settle the list of available colors there first, then we'll define the dictionary of block colors in this thread.

**Comment by michel-cf** [comment]
I added a central way to manage colors.
