### ISSUE TITLE
Scan String on Block changes after Save and Return - BUG?

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#1580]
On the DEMO site I have been tesing my AB360 Drive - Badge WX Controller Simple (client, number 2107 and host, number - 2106) to get it all in BlocklyProp - bugs were keeping it from working on the live site. 

It works now completely in BloclyProp (DEMO) with one bug.

When I save the Client Code (2107) for the AB360 and then return to the program - The Scan String Block changes. It needs to us the "start after text" mutator.

The portion of the "Working Code" (correct function) looks like this is Blockly...

![scan string](https://user-images.githubusercontent.com/8891440/47334965-801d5800-d64e-11e8-9b86-5dd924cdfba6.JPG)

It produces this C...

![scan string c](https://user-images.githubusercontent.com/8891440/47334981-8d3a4700-d64e-11e8-897a-12d6c75ec833.JPG)

When I save and return to the code (reopen), the Scan String Block changes to this "NonWorking Code" in Blockly...

![scan string after save and return](https://user-images.githubusercontent.com/8891440/47335003-aa6f1580-d64e-11e8-9b15-90e7ccd37e07.JPG)

or this C...

![scan string c after save and return](https://user-images.githubusercontent.com/8891440/47335028-ca063e00-d64e-11e8-869d-0c0fca32afb3.JPG)

As far as I can tell, this is all that prevents this from being complete in a Blockly only version. The code works when in the correct form and loaded to the AB360, but cannot be saved and returned to without constant modification at each re-opening.

**Comment by MatzElectronics** [comment]
Yup, that's a bug.  It's not saving the state of that, so I'll get it fixed. Thanks for finding this one!

**Comment by wstodghill** [comment]
@MatzElectronics - Got it! Works great now.  Thanks so much!

Closing
