### ISSUE TITLE
Password with leading/trailing spaces accepted but no entry can be gained

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#1583]
Leading (and probably trailing) space characters are accepted as a password, but accounts with such a password can not be logged into.

I successfully created an account with a password as shown below (note that there is a leading space): 
~~~
 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~
~~~
 and successfully confirmed it, but was unable to log in.

It seems that either some part of the password entry function is stripping leading (and probably trailing) spaces from the password, but then happily accepting it... or, it's accepting it as-is but some other password verification code (maybe the log in page) is stripping any leading/trailing space and failing to log in because of it.

**IMPORTANT**
The Register page, the [Profile>Change](http://demo.blockly.parallax.com/blockly/profile) page, and the Forgot Password's [Do password reset](http://demo.blockly.parallax.com/blockly/reset) page all accept a password with a leading (and presumably trailing) space, and also if a user successfully changes the account password (to one that includes a leading space) while logged in, the Profile>Change page accepts that password (with a leading page) to successfully _unlock_ the profile page (great!), however, once logged out, you can not log in with a password containing a leading (and presumably trailing) space character.

The above behavior seems to indicate the problem is just with the login page.

**Comment by zfi** [comment]
Can we all agree that white space in the password is undesirable? I'm not sure there is anything we can do with existing accounts that have passwords that contain white space. We can certainly tighten up the data scrubbing on those forms that offer a password field.

**Comment by PropGit** [comment]
I don't tend to do it, though I certainly have a few times for certain passwords.
Without allowing spaces inside of passwords (not necessarily leading/trailing) allows for the use of multi-word phrases as passwords.  That's the only reason I'd suggest supporting it.

**Comment by PropGit** [comment]
Most of the system we have coded already supports it... it just seems like the log in page does not (but the unlock page when going to one's profile supports it as-is).  This seems like a case of different code to do the same thing in different places.

**Comment by MatzElectronics** [comment]
I'll have to investigate this - we might have a .trim() applied somewhere that is stripping leading and trailing spaces off...

**Comment by PropGit** [comment]
@MatzElectronics - Yes, I think so, and it appears to be happening in perhaps just one place from what I tried.  Chat or Hangout if you want a verbal explanation.

**Comment by zfi** [comment]
With regards to the login process, I believe that the password is being trimmed of any white space by the Shiro package, long before any of the BlocklyProp code gets to take a look at it. I will next examine the user account registration process to determine if passwords are being treated differently in that code path.

**Comment by zfi** [comment]
@MatzElectronics Please reference my previous comment regarding the Shiro package. That is the server-side security management package that gets first shot at the password field before any of the BocklyProp server code sees it.

**Comment by zfi** [comment]
The point is that the Shiro package appears to be trimming leading and trailing white space from the password field before it is passed to the BlocklyProp server code. That also means that the hash value for the password that is persisted in the database is based upon the trimmed password value, and not the value presented at the login page.

I have not found anything that allows us to alter that behavior in Shiro. My recommendation would be to document the limitation, enforce it on the appropriate login and registration pages and move on.

**Comment by MatzElectronics** [comment]
Okay - I'll apply to .trim() to all of the password fields.

**Comment by zfi** [comment]
Hang on.. Trimming the field after the data has been entered will create confusion. If we're going to do anything, we need to make sure that the password cannot begin or end with a white space character. That can be an edit when the focus leaves the field or something that happens in real time while the password is being entered.

**Comment by zfi** [comment]
The user profile page still accepts passwords with leading and/or trailing white space.

**Comment by zfi** [comment]
I will copy the relevant Javascript code from the register.jsp page over to the profile.jsp page and tune for maximum compliance.

**Comment by zfi** [comment]
Having difficulty resolving how the code in the included profile.js affects the inline JavaScript  contained in the profile.jsp page. Let's defer this part of the issue to post 1.1 release.
