### ISSUE TITLE
Re-envision of project selection presentation and workflow

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#159]
Currently, selecting an existing project from the __Latest projects__ list on the main page...
![image](https://cloud.githubusercontent.com/assets/1266318/13679267/bcb3c41e-e6a7-11e5-805d-393046a857da.png)
...takes you immediately to the editor with the project's code within it.  This is great!
![image](https://cloud.githubusercontent.com/assets/1266318/13679319/0a9a7830-e6a8-11e5-84e4-9ecaac881caf.png)

But selecting a project from the __Community projects__ (or __My projects__) list...
![image](https://cloud.githubusercontent.com/assets/1266318/13679347/26eafa32-e6a8-11e5-8cbb-14c34a75c7d3.png)
...takes you first to the project's details page...
![image](https://cloud.githubusercontent.com/assets/1266318/13679374/43549156-e6a8-11e5-98bf-d5f282dd5ad2.png)
...and only after clicking the _Open project_ button does it take you to the editor.

I propose that we re-envision how this workflow proceeds and make it consistent.  I'm looking for thoughts from @cbradyatinquire and @DarkmatterVale on this too.

I can see advantages of taking the user to the project's details page and I like the visual "slide in / slide out" transition of project-click-to-details and _Back_-button-click-to-project-list moments.  When a user is scanning through a list of projects, trying to find something of interest, the project details are very beneficial in determining what this project does (provided they are well-written, of course) before they go to view the actual code.

However, the _Open project_ button is buried among 4 to 6 other buttons in a section labeled __Sharing__:
![image](https://cloud.githubusercontent.com/assets/1266318/13680525/cb967d86-e6ad-11e5-9f52-4129553b02ac.png)

This is confusing... the user thinks... "Okay, I clicked on a project... I see its description... now what?

Proposal: Perhaps it would be more clear how to see the code by moving the _Open project_ button to the right of the title, renaming it (making it larger), and coloring it?  Something like below (excuse the rough image work).  

And we should add some visual separation (IE: horizontal rule or just plenty of plain white space) between the actual __Sharing__ section of the project's details and the _Clone_, _Save_, and _Delete_ buttons.  Also, separate the dangerous button (_Delete_) from the rest.

![image](https://cloud.githubusercontent.com/assets/1266318/13681469/2bcf387e-e6b2-11e5-9fed-65027b06d971.png)

**Comment by PropGit** [comment]
@cbradyatinquire and @DarkmatterVale - do either of you have an opinion about this?

**Comment by DarkmatterVale** [comment]
Yes, I do have an opinion about this.

We need to make the process as simple as possible for the user, and having multiple different views for the same thing is very confusing. I think your solution is pretty good, although I believe the "Back" button should not be a button at all, but instead a large arrow. This makes it look more visually appealing (to me). What do you think @PropGit ?

**Comment by michel-cf** [comment]
I changed the layout a little. Please check if this is better.

**Comment by DarkmatterVale** [comment]
This looks much better, thank you!

**Comment by DarkmatterVale** [comment]
@PropGit @kgracey Do you agree? Is the current setup better?

**Comment by DarkmatterVale** [comment]
Can we close this?

**Comment by zfi** [comment]
Bump

**Comment by PropGit** [comment]
@DarkmatterVale @michel-cf - Yes, this looks so much better!  Thank you!

Verified fixed.

**Comment by PropGit** [comment]
This is now done.
