### ISSUE TITLE
DEMO Site Down?

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#1592]
When I try to log into http://demo.blockly.parallax.com/blockly/, I get...
![404](https://user-images.githubusercontent.com/8891440/47891507-81563e00-de21-11e8-9cea-8f86e8a065f2.JPG)

**Comment by paragitadmin** [comment]
Yes, it's been offline since about 10:30 Thursday morning. The build system managed to create a broken application file. We are working to resolve the issue but this is one is complicated.

**Comment by wstodghill** [comment]
@paragitadmin - Sorry to be slow on the uptake!

**Comment by wstodghill** [comment]
@paragitadmin - during this time is there any way to access programs in DEMO - are they lost too?

**Comment by paragitadmin** [comment]
The data on the Demo site is safe and intact. @zfi was able to get a working set of configuration files yesterday afternoon. We are now rolling through updates to get back to where Demo was last week. With any luck, Demo should be back online later today, just in time for a three day weekend.

**Comment by wstodghill** [comment]
@paragitadmin - ;-)

**Comment by wstodghill** [comment]
Yahoo! Works for me! Closing.
