### ISSUE TITLE
Audio>Text to Speech Menu bug - FLiP board type

### ISSUE THREAD

**Issue by Steph-Parallax** [parallaxinc/BlocklyProp#1595]
When using the FLiP board type, once you select the Audio > Text to Speech menu item it will not un-highlight even as you navigate to other menu items.

![image](https://user-images.githubusercontent.com/22827298/48172009-07a3d180-e2b3-11e8-8aa4-ca30a7ade9bd.png)

**Comment by PropGit** [comment]
Confirmed.  The Audio > Text to Speech menu is empty, which is probably somehow why it maintains the highlight.

Why is it empty?  Seems like a partial exclusion.

**Comment by MatzElectronics** [comment]
Now fixed.
