### ISSUE TITLE
Robot initialize block isn't always visibly accessible

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#1596]
The **Robot initialize** block is accessible with a clean editor (for example, drag it and one other to the editor space) but it is not draggable if you, for example, build the project shown below, from the Try This code on this page: https://learn.parallax.com/tutorials/robot/activitybot/blocklyprop-robotics-activitybot/navigate-touch/whisker-wheel-response

Then, as a last step, try to add the Robot initialize block.  It won't grab and move.  Here's a screenshot (my mouse pointer is a hand (not visible here), and I've held the left button down, but there's no moving the block, no feedback, nothing).
![image](https://user-images.githubusercontent.com/1266318/48221743-bc87ce00-e347-11e8-997a-f54dea91762f.png)

Then I saved it, went out to My Projects and opened it again... the Robot initialize block appears.
![image](https://user-images.githubusercontent.com/1266318/48221768-c9a4bd00-e347-11e8-9232-964b08063ab1.png)

Still, after this, the block on the menu itself is not selectable.

**Comment by PropGit** [comment]
Update:
The Robot initialize block as it appears in the last screenshot is a stack of blocks on top of each other, the number of which is probably the number of times I tried to grab it from the menu system.

Also, saving and then simply refreshing the browser tab makes the block visible in the editor.

**Comment by PropGit** [comment]
Another update:

The problem continues unless I delete each of the **Robot drive speed** blocks... then suddenly I can select the **Robot initialize** block.

I later tried with a clean project and found that ONLY the **Robot drive speed** block (being on the editor first) seems to cause this **Robot initialize** block to be undraggable.

**Comment by MatzElectronics** [comment]
This is the same "onchange" bug that afflicted a number of other blocks.
