### ISSUE TITLE
S3 Wait block stays on millisecond time unit, will not change to seconds or tenths.

### ISSUE THREAD

**Issue by mrodriguez-parallax** [parallaxinc/BlocklyProp#1597]
![2018-11-08_11-15-43](https://user-images.githubusercontent.com/20686764/48221819-e9d47c00-e347-11e8-9a24-f34d03b21c5c.png)

**Comment by PropGit** [comment]
@mrodriguez-parallax - What project type are you using and where is the **wait** block in the menu?  I can't find it.

**Comment by mrodriguez-parallax** [comment]
Its an S3 block project using the wait block.

**Comment by MatzElectronics** [comment]
@mrodriguez-parallax Unable to replicate - can you send me a link?

**Comment by PropGit** [comment]
I replicated on a new project only.

**Comment by MatzElectronics** [comment]
I found it - and should be an easy fix.  There is a forced call to the block's onchange that is no longer necessary (I think...).  Some testing will be required to verify the fix, and then I'll get it in.

**Comment by wstodghill** [comment]
Good catch @mrodriguez-parallax

**Comment by MatzElectronics** [comment]
Now fixed.
