### ISSUE TITLE
Shared project link doesn't allow compile

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#1598]
The shared project link is missing the &project=NNNNN content.  The current web app doesn't understand the id= part of the shared project link, causing a compile operation to fail unless you've already saved or save as'd the project (which updates the URL).

**Comment by zfi** [comment]
The server is generating a shared project link similar to this:
```
http://localhost:8080/blockly/projectlink?id=20&key=19d8aee7-3fd4-4690-bb1a-453d6ec3e09a
```
The URL includes a project ID as well as the hash that we use to look up the project. Can someone post an example link that does not match this pattern?

**Comment by zfi** [comment]
Here is what we're seeing on the browser when the shared project link is used to open a project:

![screen shot 2018-11-08 at 13 48 58](https://user-images.githubusercontent.com/8442260/48229507-2363b200-e35d-11e8-8f4c-99c4194cc220.png)

**Comment by MatzElectronics** [comment]
I'll add some code that looks for the project's id under the "id=" attribute if it's not found under "project=".  That appears to correct the issue.

**Comment by zfi** [comment]
Excellent. It is also possible for the project owner to disable the shared link at any time. That will cause the server to return a 404 error. Ideally, we would put up a page that says something nice, like that link is not available right now, check back later. I can make that a server side page unless it's stupid simple to do it client side.

**Comment by MatzElectronics** [comment]
Fixed in latest release.
