### ISSUE TITLE
S3 blocks: Drive distance, Drive to a location, and Drive a turn will not switch out of inches

### ISSUE THREAD

**Issue by mrodriguez-parallax** [parallaxinc/BlocklyProp#1605]
![2018-11-13_12-45-18](https://user-images.githubusercontent.com/20686764/48442082-fdb22080-e741-11e8-8e8b-c066a662a85b.png)

![2018-11-13_12-46-42](https://user-images.githubusercontent.com/20686764/48442145-2df9bf00-e742-11e8-92d1-67d4c69bccca.png)

![2018-11-13_12-47-17](https://user-images.githubusercontent.com/20686764/48442164-44077f80-e742-11e8-9e49-9d5270c9704b.png)

**Comment by MatzElectronics** [comment]
It's the onchange handler in the number block itself.  It is now complaining about a null event - something that may have been there before but now suddenly chokes.  Appears to be resolved in most recent update.  Onchange handlers now check for null events before trying to read them.
