### ISSUE TITLE
ADC0831 block not working

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#1607]
It's generating the wrong function name - carrying the generic name from other options in the block.

**Comment by zfi** [comment]
Verified that the code generated by the block is using the adc0831 routines.
```
// ------ Function Declarations ------
int read_adc0831(int __McsPin, int __MclkPin, int __MdoPin, int __MVr);
```

**Comment by zfi** [comment]
Closing issue
