### ISSUE TITLE
XBee Transmit blocks - different output

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#1610]
![screen shot 2018-11-24 at 3 31 45 pm](https://user-images.githubusercontent.com/9534148/48973878-9f692580-effe-11e8-9bdf-100d9324c70a.png)
Code generated by the two different XBee blocks:

```
// ------ Libraries and Definitions ------
#include "simpletools.h"
#include "fdserial.h"
#include "abvolts.h"

// ------ Global Variables and Objects ------
fdserial *xbee;
int analog;
int scaledAnalog;



// ------ Main Program ------
int main() {
  xbee = fdserial_open(15, 14, 0, 9600);
  ad_init(21, 20, 19, 18);
  // Lighting - XBee Transmitter
  // BlocklyProp #67652
  while (1) {
    analog = ((ad_in(0) * 500 / 4096));
    scaledAnalog = (mapInt(analog, 0, 500, 1, 12));
    dprint(xbee, "%d\r", scaledAnalog);
    dprint(xbee, "%d", scaledAnalog);
    pause(100);
  }

}
```

@MatzElectronics is it intentional? Spent many hours trying to find the issue with my code, and only the first block works. Bug, or am I supposed to know to add a \r formatter elsewhere in my code to make the second version behave like the first?

**Comment by kgracey** [comment]
Maybe a check-box enhancement would do the trick?

**Comment by kgracey** [comment]
@MatzElectronics @AndyLindsay and I spoke about the options. We prefer the "then a carriage return" checkbox at the end of all blocks for consistency. Please make that addition to both blocks.

**Comment by MatzElectronics** [comment]
Will do!

**Comment by MatzElectronics** [comment]
Would it be preferable to have the box checked by deafult for the XBee blocks?

**Comment by zfi** [comment]
Looks like this is addressed in PR #75 in the CDN repo. What are we looking for to verify the patch?

**Comment by MatzElectronics** [comment]
Correct code generation from all XBee transmit blocks for all possible menu options

**Comment by zfi** [comment]
Let's spell that out for whomever is testing this.

* XBee transmit (simple block)
  * text
  * decimal number
  *  hexadecimal number
  *  binary number
  *  ASCII character(s)

* XBee transmit (mutator block)
  * No send block
  * text
  * decimal number
  *  hexadecimal number
  *  binary number
  *  ASCII character(s)
 
Each item should produce a line of code that looks similar to the lines below. The format string will vary based on the data type specified.

```
  dprint(xbee, "%s\r", ("Some string here"));
```
or
```
dprint(xbee, "%d\r", 3);
```
Yes, unit testing this would be wonderful.

**Comment by paragitadmin** [comment]
The added checkbox to add a carriage return ('\r') corrects the imbalance reported between the stock XBee transmit block and the mutator XBee transmit block.
