### ISSUE TITLE
Repeat block with negative step value: request to add warning

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#1611]
Using the following program as an example:
![screen shot 2018-11-25 at 7 40 44 am](https://user-images.githubusercontent.com/9534148/48981117-5957a480-f086-11e8-9bef-f9ca08d215c8.png)
The repeat code counting down must have a negative number for it to work. PBASIC and other languages often do not. To remedy, add a small "warning" that checks the first number for a value greater than the second number and indicate "warning: counting down requires the step value to be a negative number" or something like this.

**Comment by zfi** [comment]
Added tracking issue in blocklyprop-cdn repo.

**Comment by zfi** [comment]
Please verify this works as expected. Use the BlocklyProp Solo site.

**Comment by zfi** [comment]
Verified that the warning message appears when the start value is less than the end value and the step is negative.
