### ISSUE TITLE
Update release(s)

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#1619]
https://github.com/parallaxinc/BlocklyProp/releases

...is way out of date.

**Comment by zfi** [comment]
I have added release notes to the repository for the latest v1.1 release. The release notes are now part of the deployment process. We should be in good shape going forward.

**Comment by zfi** [comment]
@MatzElectronics, can this issue be closed?

**Comment by zfi** [comment]
No response. closing issue.
