### ISSUE TITLE
Code Glitch following Comment - S3

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#1626]
In this working code http://blockly.parallax.com/blockly/editor/blocklyc.jsp?project=73306#, the change LED Block following a comment works, if I add a wait Block as shown...

![73305 with wait](https://user-images.githubusercontent.com/8891440/50378145-6c5f8500-05f0-11e9-9ce2-025f7d513d7c.JPG)

generating this C code...

![73305 with wait c](https://user-images.githubusercontent.com/8891440/50378149-7f725500-05f0-11e9-894c-82968969d0e9.JPG)

BUT, does not work correctly if the wait is removed - The left LED change appears in the C, but does not function, while the Center and Right LED work.

Like the wait (pause) the left LED command is included with the comment - as the shown in the screen -grab of the C code above. (I honestly do not know if the wait is working since it is short - I just know this fixed the code functionaly.

**Comment by zfi** [comment]
The issue here appears to be the trailing comma in the comment block. This is the generated code if the comma is removed from the comment. 

```
  // Jingle Bell Santa on S3
  // Jingle Bells, Jingle Bells
  pause(10);
  s3_setLED(S3_LEFT, S3_COLOR_00FF00);
```

If the pause block is removed and the preceding comment block ends with a comma character, you see the first element of the "change these LEDs" get pulled up into the comment line.

```
  // Jingle Bell Santa on S3
  // Jingle Bells, Jingle Bells, s3_setLED(S3_LEFT, S3_COLOR_00FF00);
  s3_setLED(S3_CENTER, S3_COLOR_FF0000);
```

and the same code with the trailing comma removed from the comment:

```
  // Jingle Bell Santa on S3
  // Jingle Bells, Jingle Bells
  s3_setLED(S3_LEFT, S3_COLOR_00FF00);
  s3_setLED(S3_CENTER, S3_COLOR_FF0000);
```

This leads to a new question, why is a trailing comma character in a comment line causing this?

**Comment by MatzElectronics** [comment]
I'm guessing that the code beautifier has some conflicting rules.  This looks like a side effect from a rule that keeps arrays definitions on a single line.  I'll need to teach it what comments look like apparently.

**Comment by MatzElectronics** [comment]
I think the best approach for now is to just trim off any trailing spaces...the beautifier is a bit tricky, and getting it wrong can have some nasty side-effects.

**Comment by zfi** [comment]
Does trimming trailing spaces (or perhaps generic white space?) correct the issue where the comma character appears to trigger the unwanted behavior? Does trim operation apply to the comment lines or all code lines?

**Comment by MatzElectronics** [comment]
I misstated that...I meant to say trailing commas.  They can be left alone in the user's entered text in the block, and trimmed off at code-generation time.

**Comment by MatzElectronics** [comment]
@wstodghill @zfi please retest in demo.  Thanks!

**Comment by Steph-Parallax** [comment]
Works now with a single comma ending a comment.
Fails again if you use more than one comma ending a comment! 

![comment-commas](https://user-images.githubusercontent.com/22827298/58993830-827a8f80-87a3-11e9-803f-cbc466f36d7b.png)

(I tested single and dual period, semicolon, closing parentheses, closing braces square and curly,  ampersand, asterisk, pound sign, >/, etc, basically swore politely with all the characters, and issues found)

**Comment by PropGit** [comment]
Well done, @Steph-Parallax!

**Comment by MatzElectronics** [comment]
oooh!  Good catch!,   I'll fix it, thanks!

**Comment by Steph-Parallax** [comment]
Tested in same code; fix verified. Thanks!
