### ISSUE TITLE
Missing chevron in 'Back' button on project details page

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp#1637]
In the version 1.1 release, the image resource is missing on the back button on the Project details page: 

![image](https://user-images.githubusercontent.com/8442260/51774108-f72b1800-20a5-11e9-953e-e941966a7251.png)

Should look like this:

![image](https://user-images.githubusercontent.com/8442260/51774133-0611ca80-20a6-11e9-9a87-6e646a425caf.png)

This appears to only happen with the Chrome browser. It does render correctly in Firefox.

**Comment by zfi** [comment]
This issue appears to have been resolved in the blockly-cdn repository, but I cannot find any reference to the correction. Closing this issue.

**Comment by MatzElectronics** [comment]
There was no active correction - I think a path breaks when not in
production (URL issue?)
