### ISSUE TITLE
Help & Reference in Drop Down Not Working

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#1638]
The Help & Reference link in the Drop Down menu on the live BlocklyProp site is not working...

Clicking on Help & Reference...
![help link](https://user-images.githubusercontent.com/8891440/51782162-75f57480-20e9-11e9-90aa-106093429cb7.JPG)

yeilds...

![not found](https://user-images.githubusercontent.com/8891440/51782173-9c1b1480-20e9-11e9-9fef-a6d328ed05b1.JPG)

**Comment by zfi** [comment]
Update function at blockly/language/en/_messages.js:1100 in the CDN repo to use a fixed URL (https://learn.parallax.com/ab-blocks) when running in on-line mode.

**Comment by zfi** [comment]
We have corrected code up on Demo. It appears to work correctly. Let's see what the jury says.

**Comment by PropGit** [comment]
Verified on Demo.

Question: The link of that menu item is https://learn.parallax.com/ab-blocks regardless of the project type at the time, and that seems to be redirected to a more general page supporting all project types.  Is that the intention?

**Comment by zfi** [comment]
This issue has been corrected and released to production.
Closing the issue.
