### ISSUE TITLE
Delayed login failure response

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#164]
Related to Issue #92, where the solution was to "... add a popup that will show: 'An unexpected error occurred. Please try again later or contact the webmaster.'"

When the system is experiencing trouble, the first response to this failure (at least as seen in Chrome, did not test in other browsers) is the "unsuccessful" message:
![image](https://cloud.githubusercontent.com/assets/1266318/13752237/0ac670fe-e9cb-11e5-90eb-6b57697c7564.png)

After trying a few times, the login screen switches back to its normal state (no error message) and clicking the _Login_ button (even multiple times) seems to have no effect at all.

However; if you refresh the page without cache (Ctrl+click Reload button), then (and only then) will the message _'An unexpected error occurred. Please try again later or contact the webmaster.'_ occur... and it will occur in series as many times as you had clicked the Login button previously.

Most users will never see this message, because it doesn't appear unless you do a special cache-less reload.

We need to find out why it doesn't appear at the expected time and fix it to appear in immediately response to the _Login_ button click should the server system be in a failed state were it can not possibly log a user in.

**Comment by michel-cf** [comment]
Anyone still having this problem?

**Comment by PropGit** [comment]
No, this exact symptom hasn't occurred since the change to the simplified login system.  That's not to say that it isn't still a problem should something happen that prevents actual logging in.

I think the safest thing is to convert the error dialog (with Chrome doesn't seem to be making up front and visible when we want it to) into an error message just like the light-red "Login was unsuccessful" message... that way we know the message _will_ appear if and when the same type of system error occurs.

**Comment by DarkmatterVale** [comment]
Can this be closed?

**Comment by PropGit** [comment]
No, I still want that error dialog converted to an error message.  As far as I know, that has not been done.

**Comment by zfi** [comment]
The login failures now have a number of feedback messages based on the actual failure condition. 

Closing.
