### ISSUE TITLE
Add blocks and library for the BME680 Air quality sensor

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#1652]

**Comment by Steph-Parallax** [comment]
In the Init block, can you please update the parameter order and labels to match the production units?

![28061](https://user-images.githubusercontent.com/22827298/58057689-afc80c00-7b1a-11e9-9fc8-a0a7c80ed82c.png)

**Comment by Steph-Parallax** [comment]
I added an additional alias for the Reference to support ab-blocks/air-quality; I had set it up as ab-blocks/BME680.

**Comment by mrodriguez-parallax** [comment]
![2019-06-05_13-32-40](https://user-images.githubusercontent.com/20686764/58988362-66bcbc80-8796-11e9-99ad-12ba4ea48caf.png)
BME pin reorder block passed testing.

**Comment by Steph-Parallax** [comment]
![28061a-crop](https://user-images.githubusercontent.com/22827298/59308687-7f294d00-8c56-11e9-9214-3d56d3787002.jpg)
Can the init block labels match the SPI pin labels?

**Comment by Steph-Parallax** [comment]
Label update verified
