### ISSUE TITLE
S3 motor drive block motion selector problem.

### ISSUE THREAD

**Issue by mrodriguez-parallax** [parallaxinc/BlocklyProp#1663]
**Drive block:** Backward motion must be selected first in order to able to choose Forward motion.
![2019-04-22_13-31-56](https://user-images.githubusercontent.com/20686764/56527797-126dbe00-6503-11e9-9fc2-69cb9dab27b6.png)

**Rotate block:** Rotate clockwise must be selected first in order to select a counter clockwise motion.
![2019-04-22_13-33-31](https://user-images.githubusercontent.com/20686764/56528052-742e2800-6503-11e9-975d-c42f826f0a8d.png)

**Comment by zfi** [comment]
@MatzElectronics : Is there something that requires what we would consider the defaults to be selected before the reciprocal  can be selected?

**Comment by MatzElectronics** [comment]
@mrodriguez-parallax  Please re-test.
