### ISSUE TITLE
Upload Blocks can give confusing result prompt

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#1664]
While testing Issue #1662, I attempted to upload an .svg file that apparently wasn't formatted properly, which resulted in the pink error message, "The selected file is not valid" and then (without closing the dialog) clicked on the __Choose File__ button again to select another .svg that I think was proper - the result is two messages indicating conflicting information:
![image](https://user-images.githubusercontent.com/1266318/57452590-1135d400-7219-11e9-9d90-9f0258ebb381.png)
The best I can tell is that the dialog's code is making success & error sections visible, and leaving the opposite in whatever state it was in (thus both are visible at the same time under this condition).  Note that it doesn't matter the order in which good and bad .svg files are loaded.

**Comment by MatzElectronics** [comment]
Good catch, thanks!  Should be easy to fix.

**Comment by MatzElectronics** [comment]
From #1667: [ While testing issue #1662 ]

After Replace'ng or Append'ng an svg to an existing project, further selection of the Upload Block File feature shows the Replace and Append buttons are still in the enabled state even though there is no file selected.

**Comment by MatzElectronics** [comment]
Please re-test

**Comment by MatzElectronics** [comment]
@PropGit please re-test

**Comment by PropGit** [comment]
@MatzElectronics - This is still broken.

**Comment by MatzElectronics** [comment]
@PropGit I just fixed this (I hope)

**Comment by PropGit** [comment]
Tested and verified fixed.  Thanks!
