### ISSUE TITLE
Uploaded .svg code with user-defined code is collapsed but checked as if expanded

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#1665]
While testing Issue #1662, I found that uploading a .svg that contained user-defined code results in said block(s) being collapsed, but *checked* as if they should be expanded.  For example, this appears first:
![image](https://user-images.githubusercontent.com/1266318/57453570-8d311b80-721b-11e9-8cfa-150f5bc1219e.png)

Then this (if user unchecks the box next):
![image](https://user-images.githubusercontent.com/1266318/57453573-91f5cf80-721b-11e9-9afd-c6a666ca5c48.png)

Then this (if user rechecks the box next):
![image](https://user-images.githubusercontent.com/1266318/57453579-97531a00-721b-11e9-81b0-ea1903e6f644.png)

I don't know if this is related to the updated code for Issue #1662 or not.

**Comment by PropGit** [comment]
Additionally, if the user imports and *appends* an .svg into a project with existing blocks of user-defined code, those blocks are collapsed (with the checkbox still checked).

**Comment by MatzElectronics** [comment]
@PropGit please re-test

**Comment by PropGit** [comment]
Retested - Failed in the same way as before.

Does the fix only require that Demo be refreshed, or does it require that I generate a new SVG?  I'm using [this project](http://demo.blockly.parallax.com/blockly/projectlink?id=2216&key=a438d586-611a-4672-898f-c4299002f22f) and the attached SVG.

[Project97335.zip](https://github.com/parallaxinc/BlocklyProp/files/3227880/Project97335.zip)

**Comment by MatzElectronics** [comment]
It will require a new file, or at least reserve the original file before
testing.

**Comment by PropGit** [comment]
I'm still getting the same failure, even if I... 1) *replace* an existing project with the original SVG, 2) Expand its user-defined code area, 3) Save the project, 4) Download a new blocks file (attached), and 5) *append* that new SVG into a different existing project.

[User-Defined Code.zip](https://github.com/parallaxinc/BlocklyProp/files/3228035/User-Defined.Code.zip)

**Comment by MatzElectronics** [comment]
Okay - I feel really bad about this - I didn't fully merge my code that
should fix this.  It should be in demo after 10:30. Again, I'm sorry about
that.

**Comment by PropGit** [comment]
Verified fixed.  

Definitely requires a new SVG to be saved; I'm assuming with the user-defined code already expanded, for this to work.   I didn't realize it was an issue with saving until we explored it in this thread.
