### ISSUE TITLE
Upload Blocks' Append feature doesn't work

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#1666]
[ While testing issue #1662  ]

The __Upload block file__ dialog's Append feature doesn't work.  Clicking on it only makes the dialog disappear but makes no changes to the project.

Tested on Demo using this svg file: [Random Number.zip](https://github.com/parallaxinc/BlocklyProp/files/3163521/Random.Number.zip)

**Comment by wstodghill** [comment]
I have used this feature a couple of times the last two days on the live site. Seems to work there.

**Comment by PropGit** [comment]
Sorry @wstodghill - we're working on a fix to a related problem and the fix temporarily broke Appends in Demo.  This issue relates only to Demo (at the moment).

**Comment by MatzElectronics** [comment]
@PropGit please re-test

**Comment by PropGit** [comment]
@MatzElectronics - Tested.  Fixed.  Thank you.
