### ISSUE TITLE
Get WiFi IP Address has error

### ISSUE THREAD

**Issue by VonSzarvas** [parallaxinc/BlocklyProp#1668]
Image shows test code. Last line causes the error.

Compile... Failed!

-------- compiler messages --------
Included libraries: badgewxtools, wifi, simpletools
single.c: In function 'wifi_ip_string':
single.c:27:7: error: expected declaration or statement at end of input
single.c:27:7: error: expected declaration or statement at end of input

![2019-05-14 19_04_45-BlocklyProp](https://user-images.githubusercontent.com/11635798/57717483-aa327800-767b-11e9-83a6-c8bb74036447.png)

Generated code
`// ------ Libraries and Definitions ------
#include "simpletools.h"
#include "badgewxtools.h"
#include "wifi.h"

// ------ Function Declarations ------
char *wifi_ip_string(int __mode);

// ------ Main Program ------
int main() {
  badge_setup();
  wifi_start(31, 30, 115200, WX_ALL_COM);
  // Allow the Badge WX to be programmed over WiFi
  high(17);
  wifi_mode(STA_AP);
  oledprint("Hello4");
  oledprint(wifi_ip_string(STA));

}

// ------ Functions ------
char *wifi_ip_string(int __mode) {
    int __ip[4];
    char __result = wifi_ip(__mode, __ip);
    char *ipStr;
    if (__result == 'E') {
      strcpy(ipStr, "Error          "); // Save string into variable ipStr.} else {sprint(ipStr, "%d.%d.%d.%d", __ip[0], __ip[1], __ip[2], __ip[3]);} return ipStr;}`

**Comment by VonSzarvas** [comment]
I can also confirm when removing the erroneous comment (or inserting a line-end just before the curly brace), then the code in BlocklyProp works fine. (I exported the file to SimpleIDE, removed the comment, and all was well!)

**Comment by MatzElectronics** [comment]
@VonSzarvas Go ahead and try it again

**Comment by AndyLindsay** [comment]
Tested, and works.
