### ISSUE TITLE
OLED blocks generate extraneous commas in source

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp#1669]
The following construct is causing the code generator to issue commas where they should not be on blockly.parallax.com (v1.1.455)

![image](https://user-images.githubusercontent.com/8442260/57960332-f7515c80-78bc-11e9-9951-9f959959b85b.png)

```
// ------ Libraries and Definitions ------
#include "simpletools.h"
#include "oledc.h"
#include "colormath.h"



// ------ Main Program ------
int main() {
  oledc_init(0, 0, 0, 0, 0, 2);
  while (1) {
    toggle(27);
    set_direction(27, 1);
    pause(200);
    oledc_fillCircle(0, 0, 0, oledc_color565(get8bitColor(, "RED"), get8bitColor(, "GREEN"), get8bitColor(, "BLUE")));
  }

}
```

The cloud compiler complains with an appropriate message:

![image](https://user-images.githubusercontent.com/8442260/57960420-7a72b280-78bd-11e9-9bd4-16cd86de12a3.png)

**Comment by MatzElectronics** [comment]
@zfi please re-test

**Comment by zfi** [comment]
The block is clearly emitting new - and syntactically correct code. The issue is resolved.
