### ISSUE TITLE
ePaper init makes WAV playback slow

### ISSUE THREAD

**Issue by Steph-Parallax** [parallaxinc/BlocklyProp#1672]
Testing ePaper blocks in Demo.  Just having the ePaper initialize block in a project causes the WAV play file output to play back slowly - like half speed or lower.  (The ePaper draw BMP image block isn't needed to trigger the bug, but that's how I discovered it. 

Imagine birdsong sounding like whalesong. This does not happen with the OLED and WAV play, just FYI.

**Comment by MatzElectronics** [comment]
This is a SimpleLibraries issue - but I figured it out.  The ePaper driver library had two functions in fcache...apparently that's a no-no :)
I'll push this update to the SimpleLibraries repo.

**Comment by MatzElectronics** [comment]
@Steph-Parallax please re-test

**Comment by Steph-Parallax** [comment]
Retested, it is working now. No more whale! @MatzElectronics

**Comment by MatzElectronics** [comment]
Thanks!  Closing.
