### ISSUE TITLE
New processor block warning if placed in repeat loop

### ISSUE THREAD

**Issue by Steph-Parallax** [parallaxinc/BlocklyProp#1674]
Can the new processor block throw a warning if it is placed inside a repeat block loop?  Currently, cores launched via the new processor block don't shut down, so the project would run out of cores after 7 loops max. Could be totally confusing for new programmers.

![new-processor-in-loop](https://user-images.githubusercontent.com/22827298/58211997-43781480-7ca2-11e9-9892-94fe95cc765f.png)

**Comment by MatzElectronics** [comment]
@Steph-Parallax I could use some help on the wording of this warning.

**Comment by Steph-Parallax** [comment]
CAUTION: New processor blocks don't belong in repeat loops! See Help Reference.

**Comment by Steph-Parallax** [comment]
Verified
