### ISSUE TITLE
scan string block doesn't work

### ISSUE THREAD

**Issue by lucas-yarnes** [parallaxinc/BlocklyProp#1678]
When I add the scan string block to my code, the text version that is produced by the block is a bunch of jibberish, and causes my code not to compile. And, as far as I can tell, there is no other way to convert a string into a decimal value in BlocklyProp.

The code:
 sscanAfterStr(G + mjc$2KIH2; O
    };
    5 #dR + , "hi", "%d", &received);

![code_snippet](https://user-images.githubusercontent.com/46794453/58510180-d232d880-815d-11e9-8498-68063b14532a.PNG)

My project:
http://blockly.parallax.com/blockly/projectlink?id=103885&key=67e4c688-ab87-45b3-8cc9-d0a7ac48a7a3

**Comment by PropGit** [comment]
@lucas-yarnes - Thank you for reporting this issue.  We'll fix this as soon as possible.

**Comment by PropGit** [comment]
In the meantime, I've created a user-defined block for you that does the job properly.

You can import this block (attached) by:

1. Unzipping the attached archive ("ScanStringForDecimal.zip") to a folder of your choice
2. In your BlocklyProp project, select the __menu > Upload blocks file__ option
3. Click on Choose File and select the "ScanStringForDecimal.svg" file you extracted above
4. Click on the Append button

The block will look like this:
![image](https://user-images.githubusercontent.com/1266318/58514123-eecb1280-8155-11e9-8ba9-75e28393c3c4.png)

And can be used by plugging in your input string variable, the search text variable, and the output variable as shown here (assuming *item* is your input string and *Result* is your output variable):
![image](https://user-images.githubusercontent.com/1266318/58514093-dbb84280-8155-11e9-9685-3cca567887ed.png)

Here's a link to the example project:
http://blockly.parallax.com/blockly/projectlink?id=103913&key=9277deb8-aac1-40c5-b7fc-79f9e5ff9351

*NOTE: I'm having trouble attaching the archive file.  I'll try to edit this response shortly.

**Comment by MatzElectronics** [comment]
Fix should now be in demo.

**Comment by PropGit** [comment]
Verified fixed in Demo.

@lucas-yarnes - in case you don't know, our [Demo system](http://demo.blockly.parallax.com) contains up-and-coming features (and sometimes experiments) and it a completely separate system from blockly.parallax.com.  Demo is available to the public, so you can use it right now to fix this problem in your project; however, Demo is often updated so it's not as stable as the main blockly system.

**Comment by PropGit** [comment]
@MatzElectronics - Is it possible to automatically adjust the type of variable applied to the block?  For example, if the user doesn't initialize the variable, then it ends up as an int and causes a compiler error when really it should just be a runtime logical error in this case:

![image](https://user-images.githubusercontent.com/1266318/58583421-cfd98880-8208-11e9-9517-1bcc040771f4.png)

Also, it's possible to select any variables in the block, regardless of their type, causing bad runtime results... such as, selecting **item** for the __store decimal number in__ field, which makes the code store an integer at the address of the start of a string.  The result is baffling and requires a careful eye.

**Comment by MatzElectronics** [comment]
Sort of, yes.  Now that we have a new blockly core, tracking variable types
is now possible.  It will, however, take some time to implement.  I'll
reference this issue in the standing issue for the variable typing task:
#1561

**Comment by PropGit** [comment]
Perfect, thank you.
