### ISSUE TITLE
Incorrect variable name when RXSerial "None" selected

### ISSUE THREAD

**Issue by VonSzarvas** [parallaxinc/BlocklyProp#1682]
With the serial block in production, Communicate/Protocols

RXSerial block defines:  fdserN_16
Serial transmit (dprint) block expects:  fdserNone_16 

Note- I've not tried TXSerial with the same block.

Here's the code snippet.

`// ------ Global Variables and Objects ------
fdserial *fdserN_16;

// ------ Main Program ------
int main() {
  fdserN_16 = fdserial_open(-1, 16, 0b0000, 9600);
  
  dprint(fdserNone_16, "%s%d%d", "$PMTK000*32", 13, 10);`

**Comment by MatzElectronics** [comment]
[https://github.com/parallaxinc/BlocklyProp-cdn/pull/130](https://github.com/parallaxinc/BlocklyProp-cdn/pull/130)
The print multiple block code (shared by all blocks with that functionality) was missing the specific replacers for serial RX/TX.

**Comment by MatzElectronics** [comment]
@VonSzarvas please retest in demo after 10:15 US Pacific

**Comment by VonSzarvas** [comment]
**Confirmed fixed in demo.** 
Thank you for the very fast support on this.


For extra info... I tried a simpler code snippet in both Prod and Demo and that behaved correctly in both versions. (Serial init block and Serial transmit block). So the issue only came up with complex code. I've not time to isolate the exact troublemaker now, but have saved the project should it be required later. Speculation... . the project includes 3 user-cogs, terminal, GPS and serial protocol objects. From what you mentioned Matt, I guess it could be some conflict between serial object instances, or an unlucky choice of user variable naming! 

All good now. Thanks again.

**Comment by MatzElectronics** [comment]
Thanks @VonSzarvas !  Closing.
