### ISSUE TITLE
System Failure: Error 503

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#169]
The BlocklyProp system has failed causing a 503 error message (shown on the Chrome browser console) and just a blank screen in the browser with no other status response.

![image](https://cloud.githubusercontent.com/assets/1266318/14001677/870a6da6-f104-11e5-940e-962d602b0f46.png)

I've restarted tomcat7 on the Cloud Session and also Blockly Prop servers.  No change.
I've rebooted each server (Database, Compiler, Session, Prop (which is also Auth).  No change.
I've had @cbradyatinquire and @DarkmatterVale test on their side.  No change

Servers themselves appear fine from the server console, but something is obviously very wrong and broken.

I don't have any further data to help me dig into this deeper- the system remains dead.

**Comment by PropGit** [comment]
UPDATE: The same error occurs when all Blocky servers are stopped, leading me to think this problem is  actually stemming from the load balancer(s).

**Comment by DarkmatterVale** [comment]
@PropGit This has been fixed, correct?

**Comment by michel-cf** [comment]
This was a server mis configuration, not a bug
