### ISSUE TITLE
BlocklyProp-client download page no longer auto-detects OS

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#1700]
Did we remove auto-detection of user OS on purpose?

**Comment by PropGit** [comment]
![image](https://user-images.githubusercontent.com/1266318/62371350-7ed86000-b4e9-11e9-8aa1-c8d383c866c7.png)

**Comment by MatzElectronics** [comment]
Which platform (demo, solo, production), and what OS is the above error from?

**Comment by PropGit** [comment]
I saw it first on Solo, then tested Production, but later realized they Solo is pointing to Production's BP Client delivery page... so in effect, it was Production both times.  I didn't try Demo.

This was while running on Win 7 Pro.

**Comment by MatzElectronics** [comment]
My mac is picking it up in production (and everywhere else):
![image](https://user-images.githubusercontent.com/19737272/62398768-7fdfb080-b52e-11e9-9a40-7e1170265fe5.png)

**Comment by zfi** [comment]
The client downloads appear to work as expected on blockly.parallax.com. @PropGit, are you not seeing proper behavior from blockly.parallax.com? Disregard what happens on Solo. The redirect is a temporary workaround.

**Comment by PropGit** [comment]
Okay, i just retested on all three... I can't explain it (and clearly had a screenshot) but it's working for me in every case now.

**Comment by MatzElectronics** [comment]
Gotta love the ghosts in the shell :)
