### ISSUE TITLE
Embeddable in Browser

### ISSUE THREAD

**Issue by Kinvert** [parallaxinc/BlocklyProp#1703]
We teach kids after school STEM classes.

Is this, or can you make this, embeddable in our website?

Students would be able to both view curriculum and develop in the same browser tab.

**Comment by MatzElectronics** [comment]
Good evening,

Usually an [iframe](https://www.w3schools.com/html/html_iframe.asp) would be the way to accomplish this...

Except that currently, for Mac and Windows, blocklyprop can only be used with HTTP (not HTTPS).  Since your site uses HTTPS, the iframe will generate an error and refuse to display the site.  We are nearing completion on a new client application that will allow HTTPS to be used (@PropGit - do you know approximately when?).

Once HTTPS is working, you may still need to adjust settings on your website to prevent CORS/CORB errors.

Here's an example you can try:
```
<!DOCTYPE html>
<html>
  <body style="margin:0px;">
    <div>
      <div style="float:left; border-right:2px solid #777; width:200px; height:100vh;">
        <h2>Course Curriculum</h2>
        <p>Your content here</p>
      </div>
      <div style="overflow:auto;">
        <iframe src="https://blockly.parallax.com" style="border:none; width:100%; height:100vh; padding:10px;">
          Your browser does not appear to support iframes.
        </iframe>
      </div>
    </div>
  </body>
</html>
```

**Comment by Kinvert** [comment]
Any chance you can remove that reference above? I changed the issue on our end. That is a private repo.

**Comment by MatzElectronics** [comment]
I'm happy to try, but I'm not sure what you are referring to...?

**Comment by chrisconlan** [comment]
Hey @MatzElectronics, you are right about us needing HTTPS to use your `iframe` in this site. We'll wait to hear from you that your HTTPS client is up.

**Comment by PropGit** [comment]
Hi @Kinvert and @chrisconlan ,

Is your school using Windows or Mac systems for students, or Chromebooks?  The BlocklyProp Launcher for Chromebook already works with HTTPS.

>We are nearing completion on a new client application that will allow HTTPS to be used (@PropGit - do you know approximately when?).

I'm trying to make this available by the end of this month; I have the Mac downloader problem solved, one existing issue that affects both Win and Mac, and a second involving proper builds for each system.

**Comment by chrisconlan** [comment]
Our student's are OS-agnostic, so we will wait on Windows and Mac support to implement this. Thanks.

**Comment by Kinvert** [comment]
Hopefully this would work on anything. But yeah our students tend to use Windows 7 and we could get Chrome Books if we needed at least for 'after school' classes.

**Comment by chrisconlan** [comment]
Any word in the HTTPS client for the iframe?

**Comment by PropGit** [comment]
Hi @chrisconlan and @Kinvert.  I am working out problems with the system and should have a working Windows and Mac version released within days (I expect next week).

In the meantime, have you tested the iframe technique and tried HTTPS using [the Chromebook app](https://chrome.google.com/webstore/detail/iddpgcclgepllhnhlkkinbmmafpbnddb)?

We know schools are in session now; what's your timeline for having this working for your after school STEM program?

**Comment by Kinvert** [comment]
We wouldn't have this used in schools until January. But by having it working soon we will be able to get everything rolling and have time to test it before January.

**Comment by PropGit** [comment]
Thanks. We'll keep you updated on our progress.
