### ISSUE TITLE
Averting string warnings for string variable set size

### ISSUE THREAD

**Issue by ataylor-parallax** [parallaxinc/BlocklyProp#1704]
This is a pretty obscure bug- I discovered it while using strings and arrays in the same project. This bug can lead to BlocklyProp freezing- you cannot move any blocks at all. As a side note, this bug also occurs in the solo version. Here's the steps:

Create a new project, it can be any board type
Place this block: 
![image](https://user-images.githubusercontent.com/53913268/63470627-ef580a00-c421-11e9-9c92-8a0edb7da0fb.png)
Place a variable in the first option box, this does not work without a variable or a variable in the 2nd box
Place this block anywhere: 
![image](https://user-images.githubusercontent.com/53913268/63470718-2a5a3d80-c422-11e9-8e41-5dcd59da46d1.png)
Right click this block and duplicate it
Click the settings button for this block in the top left
Add two numbers to the existing one under string lengths
This should initiate the bug. if you close the settings you can still move blocks, but upon moving the broken block once it freezes all blocks if it is not deleted.

A few notes about the details of this bug:

- If you place a new number above the original in the string lengths setting, it will initiate this bug after only adding one block
- If you delete the original number block and then add two, it initiates the bug
- Normally there is a warning exclamation point that appears next to the settings box when the string block is duplicated, saying to only use one of these blocks. This does not appear when the array block is present
- If the exclamation point is present, the bug will normally not occur, unless:
- You add the sting block and duplicate it before adding the variable or array block into your code
- If you place the first string block before adding the variable or array block into your code but duplicate it after, only one of the string blocks will show the exclamation point, and the bug still occurs.
- The broken-looking dropdown still works, kinda. It allows you to select variables, but if you have more than one it lets you select multiple.
Here's a picture of the broken block:
![image](https://user-images.githubusercontent.com/53913268/63471440-0a2b7e00-c424-11e9-81f5-f61f3a99f953.png)

**Comment by ataylor-parallax** [comment]
![Issue](https://user-images.githubusercontent.com/53913268/63472442-01887700-c427-11e9-987e-574bfad5c204.PNG)

**Comment by MatzElectronics** [comment]
@ataylor-parallax I think I got this fixed.  Please retest, thanks!

**Comment by MatzElectronics** [comment]
@ataylor-parallax Hold please - the system doesn't automatically update, so we'll wait for word from @zfi before testing...

**Comment by zfi** [comment]
You can test this on BlocklyProp Solo. Both sites share the same code for custom blocks.

**Comment by zfi** [comment]
@ataylor-parallax Can you test this issue again on the Solo site?

**Comment by ataylor-parallax** [comment]
Just tested this in Solo v1.3.477, and it is fixed. The warning appears and placing 3 numbers no longer triggers a bug.

**Comment by zfi** [comment]
Excellent news! Thanks for the verification.
Closing the issue.
