### ISSUE TITLE
Idea for Solo - Save to user cloud

### ISSUE THREAD

**Issue by VonSzarvas** [parallaxinc/BlocklyProp#1706]
What if user could approve solo.parallax.com access to a folder in their own Goo cloud account, and then load/save files direct ?

**Comment by zfi** [comment]
Support for "cloud" drives is on the roadmap. Google Drive is the low hanging fruit but we would like to include more before we release the feature.

**Comment by zfi** [comment]
Google drive is supported in Solo. 
Closing issue.
