### ISSUE TITLE
Solo - Link to BlocklyProp Client

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#1707]
Will Solo have a link to the BlocklyProp Client (like the live BlocklyProp site)? Or am I missing something that is there already?

**Comment by PropGit** [comment]
We removed the footer links intentionally and now the connection message at the top of the editor turns into a link when it is showing "Looking for BlocklyProp-Client" or "BlocklyProp-Client **not found**. Click here for instructions."

**Comment by wstodghill** [comment]
Okay! Cool, I guess I never opened Solo without first opening the client. SO - It appeared missing. Just tried it without the client running - works great!
