### ISSUE TITLE
Need more thorough logging

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#173]
The BlocklyProp system (as a whole, not just the BlocklyProp service itself) needs very thorough logging in order for us to find and address certain types of errors (those we are experienced with and those we are not).

Trying to find the source of the Cloud Session failure that prevents further log ins (on a frequent basis) seems close to impossible without insight from the system itself.

Please meticulously go through the system and add log message output for every notable process milestone (key steps in the system's processing of events).  With enough log file output, we can find the moment of failure for situations we can't foresee now, as well as those we've been on the hunt for.

In addition, log file entries are extremely valuable for our parsing and notification tools that will prove vital is maintaining the systems for the long run.

**Comment by DarkmatterVale** [comment]
I believe this has been satisfied?

**Comment by DarkmatterVale** [comment]
bump

**Comment by zfi** [comment]
There is error logging and some basic activity logging baked into the system now, would be great to have more detail. Maybe in version 2?

**Comment by zfi** [comment]
This was declared a priority1 issue. @PropGit (Jeff), Can you close this if you are satisfied with the state of the logging or perhaps reclassify the label if this is no longer urgent?

**Comment by PropGit** [comment]
Yes, I'm going to just reclassify the label.

**Comment by PropGit** [comment]
@zfi - I'd like us to review this and decide if it's resolved.  I don't believe it is.  Maybe we can give direct examples of a few places where more detail can be displayed?

**Comment by zfi** [comment]
Logging exists in all of the critical paths in the app. Closing the issue.
