### ISSUE TITLE
Update list of supported boards and I/O pins

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#174]
Parallax Education will provide the list here.

**Comment by michel-cf** [comment]
I received this list of boards. Now I need to know what I/O pins should be available to the user.

- Propeller Activity Board WX
- S3 Robot
- Hackable Electronic Badge

**Comment by PropGit** [comment]
The only boards initially considered official are:
  * Propeller Activity Board WX
  * S3 Robot
  * Hackable Electronic Badge

**Comment by DarkmatterVale** [comment]
Thank you! As soon as you post the values I will update the boards and send a PR.

**Comment by michel-cf** [comment]
Board list updated. Propeller Activity Board WX pins: 0 - 17, 26, 27 (pins for breadboard, servo, and 2 leds)

S3 Robot and HEB: currently all 32 pins. Will be updated once provided.

Also present: Other, with all 32 pins available for users of other boards.

**Comment by DarkmatterVale** [comment]
This has been finished; please reopen if it is still relevant.
