### ISSUE TITLE
Numeric dropdowns should allow variables

### ISSUE THREAD

**Issue by cbradyatinquire** [parallaxinc/BlocklyProp#178]
For example, Set LED state LED# [   ] 
Programmatically varying that argument would be powerful.

**Comment by michel-cf** [comment]
Changing from dropdown to field that accepts variables is not really possible.

That's why I have both:
![image](https://cloud.githubusercontent.com/assets/5745991/15009994/1d930340-11ea-11e6-99aa-72ca9a11e399.png)

**Comment by cbradyatinquire** [comment]
Cool - so we can follow that code as an example.

**Comment by DarkmatterVale** [comment]
@cbradyatinquire Would you like me to create a similar double-block for LED State then?

**Comment by cbradyatinquire** [comment]
yah — my only question is whether the LED state should have a variable-input for the second (true/false;1/0;HIGH/LOW) argument.

**Comment by DarkmatterVale** [comment]
Yes, I think it should have a variable input. In the event that a user would like to change the state of an LED based on the input of some sensor, the block would require a variable input (otherwise you would have to use a long if clause.

**Comment by DarkmatterVale** [comment]
@cbradyatinquire What would you like the default values that go inside the value inputs to be? 0 and high (for pin and value, respectively)?

**Comment by cbradyatinquire** [comment]
yah - i think that would be a good set of defaults.  but --> if i'm thinking right about this, this issue has to do with creating blocks that take variables.  So the BLOCK would just have sockets for pin# and value.  Then, the variable blocks that would fit in there are the big questions for me -> In particular, does a True/False fit into that second socket?  If yes, then it's odd to kids that are thinking HIGH/LOW; if no, then it's odd to kids that know HIGH LOW is "really" 0/1 or true/false.  Does an int fit in?  Etcetera.  

SO -> while I really want there to be a way programmatically to control the HIGH/LOW argument to this block, I imagine we might need a team meet to discuss.  

This is NOT a problem for the first argument-socket.  So FOR NOW maybe just doing blocks analogous to the screenshots that michel made above for the corresponding blocks for the Hackable Badge would be good

**Comment by DarkmatterVale** [comment]
I think we should discuss how to handle the high/low, true/false, 1/0 etc. at a team meeting.
