### ISSUE TITLE
Need a random number generator block

### ISSUE THREAD

**Issue by cbradyatinquire** [parallaxinc/BlocklyProp#179]
A block that creates a random number.  
Following the lead of other blocks-based environments, it might be good to have a block that picks a random INTEGER between [arg1] and [arg2].

It might also be good/necessary to have a random-float kind of block.  but the integer between LOW and HIGH might be the first need.

**Comment by kgracey** [comment]
Yes, it is related and we provided a code example for doing this in issue 249.
