### ISSUE TITLE
OLED print [Variable] should allow numeric values

### ISSUE THREAD

**Issue by cbradyatinquire** [parallaxinc/BlocklyProp#180]
It is going to be important to be able to convert numbers to strings.  

I would advocate for this being done for the user in the OLED print [Variable] block.  but it would be acceptable (and i could understand the argument for it) to make this OLED print block accept ONLY strings, if we had a block to convert a number to a string.

**Comment by DarkmatterVale** [comment]
@cbradyatinquire https://github.com/parallaxinc/BlocklyProp/pull/172 Fixes this issue.
