### ISSUE TITLE
Receive a message (IR) block problems

### ISSUE THREAD

**Issue by cbradyatinquire** [parallaxinc/BlocklyProp#181]
It's not clear (to me) how the Receive a message block is supposed to be used.  It takes a variable argument and returns a variable.  

See attachment for a screenshot of how it MIGHT be intended to be used (?)

Below is the code that is produced.   The code --> {{$var_type_test}}  is a giveaway to a problem in the compilation...
<img width="512" alt="screen shot 2016-05-03 at 8 42 58 pm" src="https://cloud.githubusercontent.com/assets/769072/15003321/516efc52-1170-11e6-96b5-c8d8a05f7c62.png">

== propeller c code ==
#include "simpletools.h"
#include "badgetools.h"

int another;
{{$var_type_test}} test;

int main() {
  badge_setup();
  while(1) {
    if (button( 0 )) {
      send( "hi there" );
    }
    else {
      another = receive( test );
      oledprint( another );
    }
  }
}
====

**Comment by DarkmatterVale** [comment]
I will review the block's code and get back to you about this.

**Comment by DarkmatterVale** [comment]
After reviewing the documentation, here is how the block is supposed to work:

1) "Variable" block input: This is the char array that the received string will be saved to. In your example, this is the test variable
2) The data sent back from the block is the length of the string saved

I think the name of this block needs a lot of work, and we might want to add another variable slot which will be used to hold the length of the string received. @cbradyatinquire What are your thoughts? I can "mold" this block many different ways; which do you think is best?

**Comment by cbradyatinquire** [comment]
I would love to test this with users.  We can do that as soon as the variable type issue is solved. 
I would try out:
Receive messageContents: (var spot)Length (var spot)
In my mind it would be conceptually ideal if these two were both presented as return values (even though the contents var is in c an argument and the length var is a return.
I know it's not so conventional to give labels for the vars, but I think this one is hard to present as an action sentence with clear blanks to fill in. 

Sent from Yahoo Mail on Android 
 
  On Sat, May 7, 2016 at 2:04 PM, Vale<notifications@github.com> wrote:   
After reviewing the documentation, here is how the block is supposed to work:

1) "Variable" block input: This is the char array that the received string will be saved to. In your example, this is the test variable
2) The data sent back from the block is the length of the string saved

I think the name of this block needs a lot of work, and we might want to add another variable slot which will be used to hold the length of the string received. @cbradyatinquire What are your thoughts? I can "mold" this block many different ways; which do you think is best?

**Comment by cbradyatinquire** [comment]
The receive block still does not produce valid code:  Here is the code produced by the blocks below.

>begin code>
#include "simpletools.h"
#include "badgetools.h"

int num;
{{$var_type_msg}} msg;


int main() {
  badge_setup();
  rgb( L, RED );
  while(1) {
    led( 0, 1 );
    pause(1000);
    led( 0, 0 );
    send( "hello" );
    num =  ;
    if (num >= 4) {
      rgb( L, GREEN );
    }

    pause(1000);
  }

}

>end of code>

<img width="535" alt="screen shot 2016-05-31 at 12 54 46 pm" src="https://cloud.githubusercontent.com/assets/769072/15684893/e204dd76-272e-11e6-9fd1-4ec33e508cd9.png">

**Comment by cbradyatinquire** [comment]
after the pull request, tested (mon june 6, 5:30 PM Central, code generation is not working -> Below are the blocks and c-code results.

<img width="516" alt="screen shot 2016-06-06 at 5 37 12 pm" src="https://cloud.githubusercontent.com/assets/769072/15840157/8ffe83c2-2c0d-11e6-9239-a69ca7385081.png">
<img width="382" alt="screen shot 2016-06-06 at 5 37 04 pm" src="https://cloud.githubusercontent.com/assets/769072/15840156/8ffb2092-2c0d-11e6-8a44-157b92b0d006.png">

**Comment by DarkmatterVale** [comment]
Grrr this block just doesn't want to work! I'll find the error and fix it... @cbradyatinquire I apologize for the length of time its taking to fix the issues.

**Comment by DarkmatterVale** [comment]
Ok, so I think I've identified the issues. I believe there are two separate things going on here:

1) Incorrect output when attached to blocks -> I believe this is caused because I have set the output of the block to be a Number (which is correct) but the default ordering for numbers messes this up.
2) The variable issue -> I am going to work on fixing the variable system this weekend (since it is a longer process and I have to work during the week)

I will send a PR for the incorrect output tonight or tomorrow morning.

**Comment by cbradyatinquire** [comment]
Hi 
It might be that Vale's commit was only supposed to fix a PART of this issue.  But as of Noon Central Time on 6/12, the issue persists.  Attached are two screenshots also sent via email.

<img width="268" alt="screen shot 2016-06-12 at 12 05 40 pm" src="https://cloud.githubusercontent.com/assets/769072/15992694/d0281a06-3097-11e6-9091-684a293f0099.png">
<img width="621" alt="screen shot 2016-06-12 at 12 05 26 pm" src="https://cloud.githubusercontent.com/assets/769072/15992695/d028ccda-3097-11e6-91ff-ca164e07e574.png">
