### ISSUE TITLE
Be able to create string variable (char arrays)

### ISSUE THREAD

**Issue by cbradyatinquire** [parallaxinc/BlocklyProp#184]
Right now when a program calls for a char array, the code conversion creates the placeholder

{{$var_type_<VARNAME>}}

this makes it impossible to create programs or test functionality that uses strings in any variable.

**Comment by DarkmatterVale** [comment]
Which blocks are you using to create this error?

**Comment by cbradyatinquire** [comment]
you can use IR Receive with any variable input to the right-hand argument
or, more simply, initialize a new variable by setting it equal to the string literal (which shows up as Hello in the Control category)

**Comment by DarkmatterVale** [comment]
Neither of those scenarios give me a {{$var_type_}} message, but I do see that the variables are not correctly handled. I believe this is an issue with the variable system that I will have to fix.

**Comment by cbradyatinquire** [comment]
oops.  the simpler one didn't work for me (to not-work) today.  but the more complicated one DID. can you retry by doing the following...

1) place the IR receive block
2) put the dummy ITEM variable in the right hand argument and the dummy ITEM =  block in the receiving left-hand endpoint.
3) change the left hand variable to a new variable ( "anint" in the below)  and the right-hand one to a new variable ("astr" in the below).

Resulting code is shown below.

#include "simpletools.h"
#include "badgetools.h"

int anint;
{{$var_type_astr}} astr;


int main() {
  badge_setup();
  anint = receive( astr );

}

**Comment by DarkmatterVale** [comment]
Ah, yes, I can reproduce that error. This issue is not related to the fact that the variables are always initialized as integers (which I will create a separate issue for), but it is due to the fact that you are attempting to reference a variable that has not been initialized. To fix the issue, you must first initialize the variable you are going to use.

I do not believe that a block can be auto-created, but maybe we can have the variable initialize itself? @michel-cf What do you think?

**Comment by cbradyatinquire** [comment]
Ok - another block that causes this error when no initialization occurs is the OLED print a variable block.

I tried initializing, and the code generated treated the var as an int.

To reproduce.

Choose the OLED print a variable.
Add a new variable i chose "astring"  to print.

Check that the {{ }} error occurs.

Then add an initialization step by choosing 

astring =  Hello ( the hello string literal)

Look at the generated code (copy-pasted below) - astring is now initialized to an int.

#include "simpletools.h"
#include "badgetools.h"

int astring;


int main() {
  badge_setup();
  astring = ("Hello");
  oledprint( astring );

}

**Comment by DarkmatterVale** [comment]
See issue #186 ... I'm going to have to figure out how to fix this (but it might be something Michel should look at because variables are built into the core of BlocklyProp)
