### ISSUE TITLE
Project contents are not saved (at least sometimes)

### ISSUE THREAD

**Issue by cbradyatinquire** [parallaxinc/BlocklyProp#185]
Although project metadata is saved, the project code comes up blank.

Steps.  
1) go through the project creation steps (from New Project, C)
2) add code
3) save project (note feedback that project is saved)
4) go back out of blockly prop (possibly required to log out / in)
5) go to my projects
6) select previously saved project, 
7) from meta-data page, select, view code.
[blank blocks creation screen]

NOTE: This does NOT always occur.
For example, in my projects (cbradyatinquire), there is a project that was made specifically to test this issue, (where the issue did NOT occur), yet the projects titled "may3" "may5" etc all exhibit the issue.

**Comment by michel-cf** [comment]
Retest with simplified authentication system

**Comment by cbradyatinquire** [comment]
I am still unable to save projects, with the build of 3PM Sat June 12

**Comment by michel-cf** [comment]
I never have this. Are you editing an existing project of your own or someone else? Was it a newly created project?
Where there any errors in the console (either while saving or opening the project)?

**Comment by cbradyatinquire** [comment]
it has happened to me consistently in testing the IR block (when i want to make 2 programs, one to receive one to send). the project NAME shows up in My Projects, but when i view the code, it gives me an empty screen.

the console output might be illuminating.  it shows

Navigated to http://blockly.parallax.com/blockly/editor/blocklyc.jsp?project=82
blocklypropclient.js:28Object {version: 0.3, server: "BlocklyPropHTTP"}

editor.js:22 Object {id: 82, name: "june12e", description: "adsf", type: "PROPC", board: "heb"…}

blockly_compressed.js:999 Uncaught Blockly.Xml.textToDom did not obtain a valid XML tree.

**Comment by cbradyatinquire** [comment]
here's the expansion of the uncaught exception:


blockly_compressed.js:999 Uncaught Blockly.Xml.textToDom did not obtain a valid XML tree.Blockly.Xml.textToDom @ blockly_compressed.js:999load @ framec.jsp:116loadProject @ editor.js:59init @ blocklyc.js:104init @ framec.jsp:100blocklyReady @ editor.js:51ready @ framec.jsp:123onload @ framec.jsp:133

**Comment by michel-cf** [comment]
Where you opening an older project? I renamed some blocks which makes the project code invalid, and will show an empty page.

BTW: I can't open your project as it is marked as private/default.

**Comment by cbradyatinquire** [comment]
Ok - 
I've made them "shared" (I assumed that "default" was 'shared') :)
I noticed the failure when i tried making projects within a single build, BUT i am not able to reproduce this right now - so it MAY be caused by compile failures or other really-invalid XML. 
So far, whenever i see the failure to load, it IS accompanied by the console's XML-invalid exception.

**Comment by PropGit** [comment]
@cbradyatinquire - Have you experienced this error in the last month's time?  I think the only time I've seen this recently is probably related to constant changing of the underlying block structure as I have not had it happen recently in the way you experienced.  It _may_ be fixed now through the other system efforts.

**Comment by cbradyatinquire** [comment]
i don't think i've seen this in over a month (or more)

**Comment by DarkmatterVale** [comment]
Can this be closed?

**Comment by PropGit** [comment]
Yes.  Closing.
