### ISSUE TITLE
All variables are created as integers

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/BlocklyProp#186]
We need char arrays, strings, etc.

**Comment by DarkmatterVale** [comment]
It appears that within BlocklyProp there is a block to declare a variable as one of many different types (https://github.com/parallaxinc/BlocklyProp/blob/93398ce9760a1d97e5058e7416ccec5b3571a102/src/main/webapp/cdn/blockly/generators/propc/variables.js). For some reason, it is not being implemented. @michel-cf Is there a specific reason you have not put these into production yet?

**Comment by DarkmatterVale** [comment]
I'm going to work on fixing this and a number of other math/array related issues this weekend (got a nice long plane ride ahead of me).

**Comment by cbradyatinquire** [comment]
Michel's fixes resolved many issues, but a variable initialized with a char array is still set as an int.  In the screenshot below, payPerm shows the problem:

<img width="267" alt="screen shot 2016-06-12 at 4 44 27 pm" src="https://cloud.githubusercontent.com/assets/769072/15994002/fc774cc4-30bc-11e6-968c-140bb080aa49.png">

**Comment by michel-cf** [comment]
I closed this one by mistake.

I fixed the use case you provided so you could use it. I saw declaring variables as a separate issue. (But I didn't notice that it was this one)
I was aware this would still be a problem.

**Comment by DarkmatterVale** [comment]
This has been fixed (although we had a little boolean scare today...).

**Comment by kgracey** [comment]
BOOOOOlean scare :)
