### ISSUE TITLE
Weird display issue with Freqout block

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/BlocklyProp#204]
It appears that the grey, transparent background does not go all the way out with the Freqout block. @michel-cf Do you know why this happens?

Below are screenshots of the issue. As you can see, the background does not go out past the end of the freqout block but it does with the much longer MMA7455 block.

![screen shot 2016-05-22 at 10 54 53 am](https://cloud.githubusercontent.com/assets/6094957/15454619/3d22037a-200c-11e6-8b03-20b687ced5bc.png)

![screen shot 2016-05-22 at 10 55 12 am](https://cloud.githubusercontent.com/assets/6094957/15454620/3ff9d8ac-200c-11e6-9005-f67bdc41b560.png)

**Comment by DarkmatterVale** [comment]
Could this be an issue because the other blocks within the category are not displaying properly?

**Comment by michel-cf** [comment]
When you encounter issues, please open your Browser debugger (Chrome recommended) to see any errors:

![image](https://cloud.githubusercontent.com/assets/5745991/15792660/f23462b8-29de-11e6-9c4d-c2d9c6dcdcdd.png)

**Comment by DarkmatterVale** [comment]
Thank you! I did that and identified the issue; the category works now.
