### ISSUE TITLE
New function issue

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/BlocklyProp#206]
I have identified a bug with the function blocks in Spin. Complete the following steps and you will be able to reproduce the error. I have also attached a screenshot to show the error.

![screen shot 2016-05-22 at 3 38 51 pm](https://cloud.githubusercontent.com/assets/6094957/15456080/c23f7fd4-2033-11e6-907c-a14614beb1ca.png)

Steps to reproduce:
1. Create a function and add an input
2. Call that function in the Cognew block
3. Create a new function, without an input

The method call you created in the Cognew block should have the name of the second method you created. This is incorrect, because it also contains and input.

**Comment by michel-cf** [comment]
Apparently this only is a problem if the user does not rename the function

**Comment by kgracey** [comment]
This issue can be closed. It is likely already supplanted by @dcarrier-parallax's efforts with newer Spin blocks.

**Comment by DarkmatterVale** [comment]
As requested by @kgracey this issue will be closed.
