### ISSUE TITLE
Text quotes are not working

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/BlocklyProp#210]
This can be seen in numerous blocks. @michel-cf Did the files get moved? If not, do you know why the text quotes could not be working?

![screen shot 2016-05-29 at 7 01 22 am](https://cloud.githubusercontent.com/assets/6094957/15632807/4a148080-256b-11e6-8a4d-c519cb866868.png)

**Comment by michel-cf** [comment]
See blockly - generators - propc - console for a working example

    Blockly.Blocks.console_print = {
        helpUrl: '',
        init: function () {
            this.setColour(colorPalette.getColor('protocols'));
            this.appendDummyInput("")
                    .appendField("Print")
                    .appendField(this.newQuote_(true))
                    .appendField(new Blockly.FieldTextInput(''), 'TEXT')
                    .appendField(this.newQuote_(false));
            this.setPreviousStatement(true, null);
            this.setNextStatement(true, null);
        },
        /**
         * Create an image of an open or closed quote.
         * @param {boolean} open True if open quote, false if closed.
         * @return {!Blockly.FieldImage} The field image of the quote.
         * @this Blockly.Block
         * @private
         */
        newQuote_: function (open) {
            if (open == this.RTL) {
                var file =     'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAKCAQAAAAqJXdxAAAAqUlEQV    QI1z3KvUpCcRiA8ef9E4JNHhI0aFEacm1o0BsI0Slx8wa8gLauoDnoBhq7DcfWhggONDmJJgqCPA7neJ7p934EOOKOnM8Q7PDElo/4x4lFb2DmuUjcUzS3URnGib9qaPNbuXvBO3sGPHJDRG6fGVdMSeWDP2q99FQdFrz26Gu5Tq7dFMzUvbXy8KXeAj57cOklgA+u1B5AoslLtGIHQMaCVnwDnADZIFIrXsoXrgAAAABJRU5ErkJggg==';
            } else {
                var file = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAKCAQAAAAqJXdxAAAAn0lEQVQI1z3OMa5BURSF4f/cQhAKjUQhuQmFNwGJEUi0RKN5rU7FHKhpjEH3TEMtkdBSCY1EIv8r7nFX9e29V7EBAOvu7RPjwmWGH/VuF8CyN9/OAdvqIXYLvtRaNjx9mMTDyo+NjAN1HNcl9ZQ5oQMM3dgDUqDo1l8DzvwmtZN7mnD+PkmLa+4mhrxVA9fRowBWmVBhFy5gYEjKMfz9AylsaRRgGzvZAAAAAElFTkSuQmCC';
            }
            return new Blockly.FieldImage(file, 12, 12, '"');
        }
    };

As we'll need the quotes at multiple location, it might be a good idea to put it in a share location.

**Comment by DarkmatterVale** [comment]
Good point...I will send a PR after changing it
