### ISSUE TITLE
Chromebook support with Blockly

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#228]
Hey there, 

It's a matter of minutes before we receive our first request from customers about using Blockly with Chromebooks. Take a look at the statsL http://futuresource-consulting.com/2016-05-K-12-Q1-Press-Release-2961.html

@PropGit (Jeff Martin, is this your name - if it's you how about just using your actual name so we know) and @michellampo this is a priority. 

How do we go about implementing Chromebook support? What's involved and who's job would it be?

Thanks, Ken

**Comment by michel-cf** [comment]
All code needs to be in the app for Chrome packaged apps (Chromebook). This results a couple issues:
- translating strings needs to be done differently
- generating blocks on the fly will never be possible, unless we create a very smart system

No javascript can be put in the html:
- I use this quite often at the moment, this all needs to be changed

It needs to be changed from a website where you log in and then have some functionality to an application where you have to login. So the entire interface needs to be rewritten.

The BlocklyPropClient will not be used in this version and as such will have to be implemented differently.  We'll have to check if loading in the propeller using the Chrome serial library works.

Result: except for Blockly and the block definitions, nearly everything will need to be rewritten.

**Comment by kgracey** [comment]
Thanks Michel. This seems like an effort for future consideration but one that must remain in our viewscape. At present I realize we have bigger issues with BlocklyPropClient’s functionality in general, not to be clouded by the addition of yet another task. We should also have Jeff involved in this kind of talk since he has the experience working with Parallax IDE in Chrome. He might even have another way of going about the particular task. 

The variety of operating systems is certainly posing big challenges for us lately. 

Ken Gracey  |  Parallax Inc.  |  Direct: (916) 625-3010 <tel:%28916%29%20624-8333>  |  www.parallax.com <http://www.parallax.com/>  |  @ParallaxKen <https://twitter.com/parallaxken>

**Comment by dcarrier-parallax** [comment]
Here is a project to run python code from node.js: https://github.com/extrabacon/python-shell
This would make possible to run the BlocklyPropClient on a Chromebook.

This still requires porting the GUI to a web interface and the serial calls to this API: https://developer.chrome.com/apps/serial

**Comment by DarkmatterVale** [comment]
Even though the Python code could be run is it possible to get access to the USB ports on the Chromebook using this library/program?

**Comment by zfi** [comment]
Serial I/O through the USB port for Chromebook Apps is supported. It is not supported from the web client.

**Comment by wstodghill** [comment]
@kgracey, @zfi 

What is the status on this? I am willing and able to test this...

**Comment by zfi** [comment]
@wstodghill  I started investigating this yesterday.

**Comment by wstodghill** [comment]
@zfi - mind reader? ;-)

**Comment by wstodghill** [comment]
Any news here for the curious?

**Comment by PropGit** [comment]
@zfi and I worked on a solution (Chrome Extension) a couple months ago that didn't pan out; it couldn't reliable control the serial port / USB port with the determinacy we need for Propeller communication.  We are revisiting this very soon after completing another couple tasks this month, to try out another couple solutions, 1) Dedicated Android-App project running on Chrome OS with v56+, 2) Multi-platform project that will do the same as # 1 for Chrome OS with the advantage of also natively supporting other platforms from the same source.

**Comment by wstodghill** [comment]
@PropGit - Thanks for the update!

**Comment by MatzElectronics** [comment]
Done!
