### ISSUE TITLE
OLED print and variable substitution

### ISSUE THREAD

**Issue by cbradyatinquire** [parallaxinc/BlocklyProp#233]
I believe that the code conversion is not handling strings or string-variables correctly (part of this might just be a consequence of the IR receive issue.

![Uploading Screen Shot 2016-06-12 at 12.05.40 PM.png…]()
<img width="621" alt="screen shot 2016-06-12 at 12 05 26 pm" src="https://cloud.githubusercontent.com/assets/769072/15992718/360963b6-3098-11e6-8abd-932e5a581a17.png">

**Comment by michel-cf** [comment]
Changed to:

![image](https://cloud.githubusercontent.com/assets/5745991/15993024/f23b26d6-30da-11e6-869c-66a6b5161205.png)

**Comment by DarkmatterVale** [comment]
@michel-cf Is this from my commit this morning?

**Comment by michel-cf** [comment]
@DarkmatterVale 
This does include your latest merge request but the print is a fix I did.

**Comment by DarkmatterVale** [comment]
Ah, ok. I was looking at the variables.
