### ISSUE TITLE
Show the Project Name in the editor environment

### ISSUE THREAD

**Issue by cbradyatinquire** [parallaxinc/BlocklyProp#235]
right now, there is no indication to the project author, of what project they are working on.

putting this up in the area above the Projects, View, and Help menus would be great.

it would also allow us to put in the conventional (*) in the project name to show that it has unsaved changes.

**Comment by michel-cf** [comment]
I'll add the project name, and if it is not your project, the project author.

Adding the (*) will be harder. I would need to continuously parse the blocks and compare it with the last saved data (what I now do when you leave the page)

**Comment by cbradyatinquire** [comment]
Omitting the * is fine (Certainly for now).
Project name (and if not yours, the author) is excellent.

**Comment by michel-cf** [comment]
![image](https://cloud.githubusercontent.com/assets/5745991/15994126/c517e696-30fb-11e6-8f5a-0d62a51eb112.png)

**Comment by cbradyatinquire** [comment]
cool - thanks
