### ISSUE TITLE
Deleting projects doesn't seem to work

### ISSUE THREAD

**Issue by cbradyatinquire** [parallaxinc/BlocklyProp#236]
If I try deleting the project titled "April30"

http://blockly.parallax.com/blockly/projects.jsp#30

i get a server error.

It's also interesting that even if I change the "sharing" status on this one to Private, it shows up in the community list.

<img width="649" alt="screen shot 2016-06-12 at 4 53 08 pm" src="https://cloud.githubusercontent.com/assets/769072/15994032/27dd2310-30be-11e6-9735-27f7a9ee189c.png">

**Comment by michel-cf** [comment]
I'll need to look in to that.

As for the:
> It's also interesting that even if I change the "sharing" status on this one to Private, it shows up in the community list.

That list are all the projects that you have access to.
- When you are not logged in: all public projects
- When you are logged in:
  - All public projects
  - All your projects
  - All your friends projects that have shared = Friends (current = default)
