### ISSUE TITLE
Sort by Date Modified, Platform, (and other features) in my projects and community projects

### ISSUE THREAD

**Issue by cbradyatinquire** [parallaxinc/BlocklyProp#239]
It would be a great addition to the usability of the my-projects and community projects to have some sorting/filtering.

A first one would be by date.

A second would be by board/platform

Tagging or keywording could add other ways of finding relevant stuff.  

This is important after launch, to help a community form.

**Comment by michel-cf** [comment]
I just created a merge request for some initial sorting capabilities
@PropGit @zfi
