### ISSUE TITLE
Project Creation Window still crashes

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/BlocklyProp#24]
Don't know why this happens, but if you create a project and then try to create another, on step 3 before you can click the submit button, it says: submitting.....

It stays like this forever and crashes the tab.

**Comment by DarkmatterVale** [comment]
I have done a little more testing, and what I have figured out is that every time you try and edit the project after it is created, the project window crashes. I don't know why, but I will try to check it out. Maybe it is meant to be like that for now?

**Comment by michel-cf** [comment]
I'll replace the wizard with a more documented expansive library.

Currently: https://github.com/amoffat/bootstrap-application-wizard

**Comment by DarkmatterVale** [comment]
That sounds like a great idea. Are you planning on keeping the same options in the new wizard?

**Comment by michel-cf** [comment]
In the progress of fixing this bug I've changed the wizard library to:
http://www.panopta.com/2013/02/06/bootstrap-application-wizard-2/

This one is much more complete and documented. Although it is possible that changes in it's source code are still required.

**Comment by DarkmatterVale** [comment]
Ok. I will leave this issue open for a little longer because we will need to test the implementation of the new wizard to make sure everything is correct for all operating systems.

Thanks for fixing this!

**Comment by DarkmatterVale** [comment]
Just tested the window and sadly it still crashes.

Maybe it is something in the code that is making the window wait for some event that will never be triggered?

**Comment by michel-cf** [comment]
Might be a good idea to wait until I merged this into the main branch. You
can test it on http://bptest.creatingfuture.eu/ though.

**Comment by DarkmatterVale** [comment]
HAHAHAHAHA.....Woops! Sorry! I thought you already merged it into the master branch.

Yes, it works fine.

**Comment by michel-cf** [comment]
Merged into master

**Comment by DarkmatterVale** [comment]
Awesome! Thanks!
