### ISSUE TITLE
Clean out invalid projects before public launch

### ISSUE THREAD

**Issue by cbradyatinquire** [parallaxinc/BlocklyProp#240]
Due to fixes in the code, there are a number of projects that are "invalid" in the sense that their blocks don't load in the editor (you get just a blank screen).

These should be cleaned out of the server so that the projects listings are all valid projects

I am guilty of having made many of these, but with delete not working, i can't clean them out.  An example that I *didn't* produce :) is ken's Ping test, project ID Number 59

http://blockly.parallax.com/blockly/editor/blocklyc.jsp?project=59

**Comment by kgracey** [comment]
I agree - can these be wiped out by any of us, or do they require Michel’s attention?

Ken Gracey
graceyken@gmail.com

**Comment by michel-cf** [comment]
I'dd prefer it if everyone would just quickly go through their own projects:
- delete what's not working
- make private or default what you want to keep but is not a good example (or delete it if you don't want it anymore)

I don't think it's my job to mess with other peoples projects. Not now, not ever.

**Comment by cbradyatinquire** [comment]
totally agree - i had missed the fact that PROJECT DELETE was now working.
-c
