### ISSUE TITLE
Cognew block omits method call name

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#241]
Hello, 

Prior to the latest release the use of a multicore block worked, as shown below:
![cjzy8vlugaa4bid jpg-large](https://cloud.githubusercontent.com/assets/9534148/16050795/d3de1e54-3211-11e6-918d-9e8cf0080fce.jpg)

Now, the multicore block seems to be missing the method name in the C code creation and looks like this:
![screen shot 2016-06-14 at 9 34 03 am](https://cloud.githubusercontent.com/assets/9534148/16050739/a0f086e4-3211-11e6-8a7f-a49516b4897d.png)

Not sure how we went backwards on this block and would like to see us restore the prior functionality please. Thanks, Ken

**Comment by michel-cf** [comment]
This seems to be as a result of #222

**Comment by DarkmatterVale** [comment]
Sorry for joining the conversation late...

I apologize for the confusion the change has caused. To implement a cog_end block, you must know the pointer the cognew method returns. For this reason, I added an output value for the cognew block, so this value can be stored and then used to end the cog. If I remove the change, I do not think we will be able to stop a cog (unless it stops itself). @kgracey Would you like me to go ahead and remove the cog_end block and bring back the original cognew block?

**Comment by kgracey** [comment]
@Vale I’ll have an update on this issue for you today. I’ve had to get together with Andy to sort it out, but we have an idea I think you can implement. Bottom line up front: we will need some volatile variables created when we do this so RAM can be shared cog-to-cog. Will return with an example!

Ken Gracey
graceyken@gmail.com

**Comment by kgracey** [comment]
Hey @DarkmatterVale, Andy and @cbradyatinquire and I discussed this issue quite extensively today. I even had to sleep on it last night - why am I so slow to figure some things out? Anyway, we think it would be best to revert back to the original cognew block which doesn't use the address pointer (and therefore has no way to stop the cog). 

The reason is that the address for cogID has several leaps of explanation involved to help a student understand it. These explanations are somewhat greater than the benefit actually derived from the ability to be able to stock cogs. 

Also, we're expecting that most Blockly programs won't excessively use cogs so the need to stop them is minimized.
