### ISSUE TITLE
Programming menu collapse and simplification

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#244]
(a) Remove Programming menu (following menus moved to top level)
(b) Create "Operators" and populate with content of Math and Conditions
(c) Content of Data Types moved the Variables menu (keeping Variables name)
(d) Contents of Multicore menu moved the Control menu (keeping Control name)

@cbradyatinquire speak up if you see an error in my notes! Thanks @michellampo 
KG

**Comment by cbradyatinquire** [comment]
This is consistent with my notes.  Only, I want to clarify one thing:  the now-top-level “Control” menu will include the current contents of “Control” as well as the current contents of “Multicore” 

So, before the change, we have a top-level Programming menu with {several sub-menus}

After the change, we have the following at Top Level

Control {including blocks from Control & Multicore)
Operators {including blocks from Math and Conditions}
Variables {including existing Variables blocks an the old Data Types blocks}
Functions {including what it currently includes}

-c

**Comment by michel-cf** [comment]
Functions and variables are special categories that are populated by code. I can't put other blocks in them.

**Comment by kgracey** [comment]
OK. 

Ken Gracey
graceyken@gmail.com
