### ISSUE TITLE
Remove Robot from Propeller Activity Board selection

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#245]
When Propeller Activity Board is chosen please remove the Robot menu from the choices. @michellampo KG

**Comment by michel-cf** [comment]
Don't you want the ActivityBot features when selecting the ActivityBoard?

**Comment by michel-cf** [comment]
@kgracey Confirmation required before I can do this

**Comment by kgracey** [comment]
No. 

Ken Gracey
graceyken@gmail.com
