### ISSUE TITLE
Volatile variable creation

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#247]
@DarkmatterVale since we're working on the multicore blocks we should also make sure that variables could be shared across cogs. I propose the creation of a new variable type based on these:
![screen shot 2016-06-15 at 2 24 24 pm](https://cloud.githubusercontent.com/assets/9534148/16097532/1a14c746-3303-11e6-81da-69be992fabba.png)
While we may need to change the name of these at some point in the future, how about the two new blocks being named:
shared_item=
and
=shared_item

and appearing in the same category as the item variable blocks. The kind of code they'd generate would be like this:

`volatile int shared_item;
`
Can you do this?

Thanks, KG

**Comment by kgracey** [comment]
@DarkmatterVale when you create this variable the scope of the variable must be global, so it has to be created outside of a main function, before any functions.

**Comment by DarkmatterVale** [comment]
@kgracey I'm not sure if I can do this. @michel-cf Can you comment on the feasibility of this?

**Comment by kgracey** [comment]
Andy, Vale and I spoke about this issue today. @DarkmatterVale pointed out some specific issues with being able to create two variable types (local and global). Provided all variables are declared up top in the program and without optimization, all variables declared can be volatile. There's an easy way to do this which brings in @PropGit or @michel-cf to implement. Changing the compilation options could be a better idea:

Project Directory: C:/Users/alindsay/Documents/SimpleIDE/My Projects/

```
SimpleIDE Version 1.0.2
C:/Users/alindsay/Documents/SimpleIDE/Learn/Simple Libraries/
C:/Users/alindsay/Documents/SimpleIDE/ Updated on: 2016-06-20

propeller-elf-gcc.exe -v GCC 4.6.1 (propellergcc_v1_0_0_2408)
propeller-elf-gcc.exe -I . -L . -I C:/Users/alindsay/Documents/SimpleIDE/Learn/Simple Libraries/Utility/libsimpletools -L C:/Users/alindsay/Documents/SimpleIDE/Learn/Simple Libraries/Utility/libsimpletools/cmm/ -I C:/Users/alindsay/Documents/SimpleIDE/Learn/Simple Libraries/TextDevices/libsimpletext -L C:/Users/alindsay/Documents/SimpleIDE/Learn/Simple Libraries/TextDevices/libsimpletext/cmm/ -I C:/Users/alindsay/Documents/SimpleIDE/Learn/Simple Libraries/Protocol/libsimplei2c -L C:/Users/alindsay/Documents/SimpleIDE/Learn/Simple Libraries/Protocol/libsimplei2c/cmm/ -o cmm/Welcome.elf -Os -mcmm -m32bit-doubles -fno-exceptions -std=c99 Welcome.c -lm -lsimpletools -lsimpletext -lsimplei2c -lm -lsimpletools -lsimpletext -lm -lsimpletools -lm
propeller-load -s cmm/Welcome.elf
propeller-elf-objdump -h cmm/Welcome.elf
Done. Build Succeeded!
```

Change the -Os to O0 and anything above Main does not need to be specifically declared as volatile and will be global. 

For Blockly, because specific C libraries manage memory efficiently (using local vars) this change doesn't actually limit memory to 32K bytes of global RAM. Even if it did, 32K bytes is enough for most all Blockly projects! 

If @michellampo is compiling library C code vs. the binaries this could pose a problem. It should compile from the .a library files. How are you doing this @michel-cf?

- comments please! KG

**Comment by kgracey** [comment]
I have a little more intelligence on this solution. I opened up a .side project in SimpleIDE "Roaming with Whiskers.c". At present, it compiles to 10,728 bytes:
![screen shot 2016-06-22 at 4 13 27 pm](https://cloud.githubusercontent.com/assets/9534148/16286633/9ab46688-3892-11e6-9cb3-bb8b190c7400.png)
Then I switched the compiler option to -O0 None which apparently makes all variables global:
![screen shot 2016-06-22 at 4 15 46 pm](https://cloud.githubusercontent.com/assets/9534148/16286655/be10b4c4-3892-11e6-96f7-3d609af5ddee.png)
The expense is a paltry 50 bytes of RAM, hardly worth thinking about. So, if we use this compiler switch we could have a much better way of sharing variables between cogs. 

Input please!
KG

**Comment by DarkmatterVale** [comment]
I like your solution better than messing with BlocklyProp's variable system. Also, the change in memory is very little so even in advanced programs this change should not be an issue. I think this is an awesome solution!

**Comment by kgracey** [comment]
Well, then the solution involves nothing from @DarkmatterVale and some work from @michellampo. 

Andy pointed out to me that this approach does not make all variables global, but makes all global variables volatile without having to add the volatile keyword. 

Ken Gracey

**Comment by DarkmatterVale** [comment]
The only downside to that solution I see is that the user will now not see the volatile declaration. @kgracey Do you think that it would be important for a user to see and understand the difference between normal and volatile variables? If so, then we should go with the solution that does not change compiling (and requires me to change the declaration of variables).

**Comment by kgracey** [comment]
Nope, at this stage I don’t think it’s important. Put yourself in a middle schooler’s situation. A typical class would have about 80% of students who try to do anything, but about 10% that really understand what these terms might mean, and maybe one of them that understands [or needs to know] real C coding practices. 

I think we should have Michel do the compiler switch stuff first and see how it works. Sure, there’s a bit of teaching opportunity lost by doing this by obscuring things. But the end result is that Blockly is even easier to use. 

Ken Gracey
graceyken@gmail.com

**Comment by DarkmatterVale** [comment]
Good point...

**Comment by michel-cf** [comment]
Changed, waiting for deployment.

**Comment by PropGit** [comment]
@michel-cf - Can you point me to the commit where this happened?

**Comment by michel-cf** [comment]
https://github.com/parallaxinc/Cloud-Compiler/commit/4ed8a8903e8f81aec845f8f19a4543b0ff9a4583
