### ISSUE TITLE
Random block creation

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#249]
We need to be able to create a random variable. Could we create a variable block called random?

```
#include "simpletools.h"

int myVal;
int myLimitedVal;

int main()
{
  srand(23);
 
  while(1)
  {
    myVal = rand();
    myLimitedVal = myVal % 100;
    print("myVal = %d, myLimitedVal = %d\n", myVal, myLimitedVal);
  }  
}
```
This block uses the modulus operator and returns values from 00 to 99. That should be enough for what we need to do with Blockly. 

Thanks @DarkmatterVale and @cbradyatinquire for the idea. - KG

**Comment by michel-cf** [comment]
Related to #179 (Duplicate?)

**Comment by DarkmatterVale** [comment]
My PR has not been merged yet, so it should not be in the latest build.
