### ISSUE TITLE
Find C libraries if already installed on the computer

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/BlocklyProp#25]

**Comment by michel-cf** [comment]
This is something for the BlocklyPropClient. I'll close this one and open it under that project.

[BlocklyPropClient issue 10](https://github.com/parallaxinc/BlocklyPropClient/issues/10)

**Comment by DarkmatterVale** [comment]
Oh, sorry.

Thanks for correcting the mistake.
