### ISSUE TITLE
"one-of" block

### ISSUE THREAD

**Issue by cbradyatinquire** [parallaxinc/BlocklyProp#251]
This is a related issue to the need for a  "random" block.
When we have a LIST (Enum) of possible values (e.g., the COLORS for the RGB led, but also could be used for things like "HIGH/LOW"), a good structure is a "one of" structure

In NetLogo, for example, one-of takes a LIST, and selects randomly from the list.

Conceptually, for learners, this is like DYNAMICALLY AUTOMATING the choice from a dropdown chooser.

As we make BlocklyProp more GENERATIVE and able to support creative coding, we need the ability to do things that are not purely deterministic.  And having huge ifelse statements based on a random INT is a very awkward approach -- it's even worse with blocks.

If the purpose or intent of this issue is not clear, ask, and i can make a visual mockup.

**Comment by DarkmatterVale** [comment]
This is going to be a more difficult block to make; is it high priority or can it wait a little while so I can sort out variable handling issues?

**Comment by cbradyatinquire** [comment]
Yes - this can wait.  I agree variable handling issues are higher priority.

**Comment by DarkmatterVale** [comment]
I don't really know how to implement this block. @cbradyatinquire Would you like to try to make the block?

**Comment by cbradyatinquire** [comment]
sure - though it might not be the first thing to do, due to the complexity & importance of getting it right.  it depends on / contributes to a set of "collections-like" functionality.  list-like things.  make a list, sort a list, iterate over a list, etc.  these are really fundamental pieces of functionality - if there are existing Propeller-C libraries that do this, we can borrow.  (?)

**Comment by MatzElectronics** [comment]
A few thoughts on implementing this.  If there is some kind of a mutator block that lets you add as many values as you want to use, and then a dropdown that gives you options like "Random one", "Maximum", "Minimum", etc.  Perhaps one block for strings, another for values...?  I agree, the code behind this thing on both the prop and in blockly would be a bit of a bear.

![image](https://cloud.githubusercontent.com/assets/19737272/18032756/2eb0d55e-6cc5-11e6-9ff4-458d3489be3f.png)

**Comment by MatzElectronics** [comment]
@cbradyatinquire @DarkmatterVale @kgracey I'd like to make an argument for closing this out - building this will be extremely difficult, and for the most part, the functionality can now be achieved in a number of different ways - for example, you could store stings and EEPROM, and grab a random one by grabbing an address randomly.  You could find the minimum or maximum by looping through and testing the values.  It may not be as convenient, and using EEPROM in the place of an array if a bit odd, but it does work.

Thoughts?  If I don't hear from anyone in a week, I'll close this out.

**Comment by DarkmatterVale** [comment]
I have similar views about this issue. Sounds like a good idea to put the work towards more pressing issues!
