### ISSUE TITLE
OLED small-and-large fix proposal

### ISSUE THREAD

**Issue by cbradyatinquire** [parallaxinc/BlocklyProp#253]
Given the importance of the OLED on the badge and the challenge of handling SMALL and LARGE text situations in one block (switching the options for ROW, COL dropdowns), I think it would be good (and maybe even BETTER) to have TWO blocks

Both blocks would remove the OPTION for LARGE-SMALL.  (So, there would be one block for large text; one block for small text)

The first block would be for LARGE text and would present the cursor options (ROW, COL) as they exist, appropriate for large text (8x2).  

The second block would be for SMALL text and would present the appropriate cursor options for small text.  (16x8)

Wording for the blocks could be (open to suggestion here...)

Setup to print LARGE text. Cursor at: Column [   ] Row [   ]
Setup to print SMALL text. Cursor at: Column [   ] Row [   ]

**Comment by DarkmatterVale** [comment]
I like the naming scheme you have chosen! I don't think I have any suggestions...
