### ISSUE TITLE
Make PIN Toggle needs default state

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#256]
The Toggle option (located under Input/Output>PIN States>Make PIN# high/low/**toggle**/input/reverse) needs to have a default state that sets the PIN to low or high. Without this, the PIN does know know whether to initialize in the high or low state.

### Make PIN high/low enabled, Toggle PIN disabled
#include "simpletools.h"

int main() {

  for (int n = 0; n < 10; n++) {
    high(26);
    pause(500);
    low(26);
    pause(500);
  }

}

![toggle disabled](https://cloud.githubusercontent.com/assets/20099916/16321489/fbd3aa72-3951-11e6-95dc-2cccf2c0c922.PNG)

### Make PIN high/low disabled, Toggle PIN enabled  
#include "simpletools.h"

int main() {

  for (int n = 0; n < 10; n++) {
    toggle(26);
    pause(500);
  }

}

![toggle enabled](https://cloud.githubusercontent.com/assets/20099916/16321303/f6b078e6-3950-11e6-967a-899c921aee9a.PNG)

Does not work, needs to have default state set to low (or high) such as,
![initial](https://cloud.githubusercontent.com/assets/20099916/16322932/b4700b76-395b-11e6-92bc-70f1c946c7fa.PNG)

**Comment by DarkmatterVale** [comment]
Ok so here is my change:

```
#include "simpletools.h"

int main() {
     low(26);

     for (int n = 0; n < 10; n++) {
          toggle(26);
          pause(500);
     }
}
```
becomes:
```
#include "simpletools.h"

int main() {
     low(26);

     for (int n = 0; n < 10; n++) {
          toggle(26);
          pause(500);
     }
}
```

The change will only be visible for pins that the user toggles. Further, this does not interfere with the user's ability to change the pin to high before he/she calls toggle. The code, if the blocks looked like:

![screen shot 2016-06-23 at 7 13 30 pm](https://cloud.githubusercontent.com/assets/6094957/16323160/9a8ad1a8-3976-11e6-96b5-9cd97aef5482.png)

would look like:
```
#include "simpletools.h"

int main() {
     low(26);

     high(26);
     for (int n = 0; n < 10; n++) {
          toggle(26);
          pause(500);
     }
}
```
