### ISSUE TITLE
Lack of clarity in login prompt

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#259]
When this login request was encountered we weren't certain whether it was generated from Blockly or the web browser. This happened on Google Chrome, a fix could be to make it say Blockly Login.

![authentication](https://cloud.githubusercontent.com/assets/20099916/16344377/1f599624-39f1-11e6-9bf7-564aca6ffb05.PNG)

**Comment by michel-cf** [comment]
What page where you trying to reach? The only requests that will give this popup are rest services that you don't open in a browser.

**Comment by CarsonGracey** [comment]
This happened when we had computers that were logged in to Blockly all night, on the Block Editor page. The notification was here in the morning.
