### ISSUE TITLE
Friends component

### ISSUE THREAD

**Issue by michel-cf** [parallaxinc/BlocklyProp#26]
Discussion and followup of friends component

Just a one minute brainstorm about the friends module:
There needs to be a new table, having a double relation with the users table (friend1, friend2).
- A since column so we'll later know when they became friends (this is currently not important)
- One of the friend will be the one who requests the relation, but it will only be in effect if the other one confirms, so, this confirmation to needs to be saved.

There needs to be a screen to invite people to be your friend, and one with open invitations. (Leave sending a friendship request and confirm e-mail for later)

To make use of the friends functionality screens will need to be added where you can view someone else's projects (public for non friends, public and non-private ones for friends)
A timeline and search between all friends is for a later day.

Don't forget: friendship works two ways. So if you look up friends you need to look in the table in both directions (friend1 -> friend2 as well as friend2 -> friend1)

**Comment by DarkmatterVale** [comment]
After a little thought, below is what I am thinking will have to be changed. This is just a start though. I am still thinking this through.

1) A new table exactly as you mentioned above
2) A change on the current interface for creating projects
    - A new checkbox will have to be created for sharing projects with only your friends. I am not sure yet what implications this will have on the php code, but I think the changes required will be minor.
3) A new link in the titlebar ( right to the left of My Account ) that, when clicked, will take the user to the friends page under My Account
4) Once on the friends page, 2 new tables will need to be created
    - The first table will show the user his/her friends
    - The second table will show the user a compiled list of all of the projects that have been shared with him/her

**Comment by michel-cf** [comment]
Looks good except for point 2:  A new checkbox will have to be created for sharing projects with only your friends. I am not sure yet what implications this will have on the php code, but I think the changes required will be minor.

Any projects that are not private are visible for friends. Public projects are visible for everyone. This eliminates the requirement for a visible for friend checkbox.

**Comment by DarkmatterVale** [comment]
Oh, I see what you are saying. That saves a lot of effort!

Do you think anything else should be changed? Do you have any other ideas?

**Comment by DarkmatterVale** [comment]
![friends page in my account](https://cloud.githubusercontent.com/assets/6094957/5789551/4fc14d5c-9e3e-11e4-9724-72c62e2d1d58.png)

This is one picture of the interface I am currently working on. Specifically, this picture shows the Friends tab under the My Account page. I know the table is incorrect; I'm working to get the table to be correct.

**Comment by michel-cf** [comment]
This is on hold for now, we won't complete this in the php version but implement it in the upcoming java version

**Comment by DarkmatterVale** [comment]
Thank gosh. Ok.

**Comment by DarkmatterVale** [comment]
I am going to close down my PR since the server has been changed from PHP to Java, and so my current additions are useless. Maybe I can resume working on this in the Java version if Michel is alright with it.

**Comment by MatzElectronics** [comment]
Suspending this feature. Closing.

**Comment by MatzElectronics** [comment]
Sorry - let's discuss this.  Although I like the idea of this to encourage hobbyist users, I'm not sure it's such a good idea in a school setting.  A teacher/classroom management portal would be better, and we don't really want to get into the social media game with kids (and the COPPA restrictions that come with it).  Thoughts?  I'd prefer to rethink this from the ground up and close this issue in favor of a more classroom-appropriate feature.

**Comment by zfi** [comment]
Closing issue.
