### ISSUE TITLE
Black blocks appearing under operators and values

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#260]
When running Google Chrome on both Mac and Windows, we had these black blocks that could be moved but would not stack with any other blocks. I assume this most likely because the website was just updated minutes ago. Neither produced any code and the problem disappeared once the page was refreshed.

![snip](https://cloud.githubusercontent.com/assets/20099916/16346487/7829183c-39fc-11e6-84f0-bbf32786fcd0.PNG)

![black](https://cloud.githubusercontent.com/assets/20099916/16346457/4d631f6c-39fc-11e6-89b4-062c0e0305cc.png)

**Comment by DarkmatterVale** [comment]
I *believe* I have figured out why this is happening, but it appears to be able to be caused by a number of different invalid pieces of code...
