### ISSUE TITLE
Duplicate true/false blocks

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#261]
There are two true/false blocks located in the Values tab since the site update.

![duplicate](https://cloud.githubusercontent.com/assets/20099916/16346740/dc94c7de-39fd-11e6-8241-c3af925a8b5b.PNG)

**Comment by DarkmatterVale** [comment]
I apologize for this issue; I had a mistake in the HIGH/LOW block. This should go away once my next PR is in.
