### ISSUE TITLE
random block causes compile errors

### ISSUE THREAD

**Issue by cbradyatinquire** [parallaxinc/BlocklyProp#262]
in the Friday 6/24 build of 1:30PM central US time, the random block fails

below is a minimal 'program' in block and c versions. 

For some reason, the random variable is considered boolean (and i think boolean isn't the correct type declaration keyword)

<img width="215" alt="screen shot 2016-06-24 at 1 52 18 pm" src="https://cloud.githubusercontent.com/assets/769072/16347563/ffdfeb8c-3a12-11e6-9e9f-904939f00c6a.png">
<img width="242" alt="screen shot 2016-06-24 at 1 52 31 pm" src="https://cloud.githubusercontent.com/assets/769072/16347566/0356a92c-3a13-11e6-910d-e0b72c37ee1c.png">

**Comment by DarkmatterVale** [comment]
The boolean declaration was another issue (which will be fixed in the next PR).
