### ISSUE TITLE
Set LED State block produces no C code (suppresses any C-code if used)

### ISSUE THREAD

**Issue by cbradyatinquire** [parallaxinc/BlocklyProp#264]
if this block is used in a program, the C-code view shows up empty.

<img width="264" alt="screen shot 2016-06-24 at 2 10 18 pm" src="https://cloud.githubusercontent.com/assets/769072/16348016/abb93330-3a15-11e6-8aed-bf0fd6ec2b1e.png">

**Comment by cbradyatinquire** [comment]
This does not work in the build of 6/27 evening.

**Comment by DarkmatterVale** [comment]
@cbradyatinquire Can you please be more specific? I see an issue with the HIGH/LOW block, but the Set State block appears to be fine...

**Comment by cbradyatinquire** [comment]
In case you didn't find the issue - I made a project "test LED pin state" that's public
it has the blocks below, and it produces no code. 

<img width="488" alt="screen shot 2016-06-28 at 8 23 24 am" src="https://cloud.githubusercontent.com/assets/769072/16416845/b89aaaba-3d09-11e6-8086-e71580388a15.png">

**Comment by DarkmatterVale** [comment]
@cbradyatinquire Actually that is a bug with the repeat block; I will post a separate issue for that.

With regards to the bugs with Set LED state, I corrected one issue, but I'm not sure if it is going to fix the issue. I was getting an extra ```,``` one line after the generated C code, and I'm not sure if that is an issue within the Set LED state block or a separate issue.

**Comment by DarkmatterVale** [comment]
This is going to take me some time to figure out; the program you provide does not work, but if I remove the Set LED state block from the if statement (and do not connect it to any other blocks), it works fine. But, if I add it to another block like this:

![screen shot 2016-06-28 at 7 03 55 pm](https://cloud.githubusercontent.com/assets/6094957/16435318/17889402-3d63-11e6-89e7-67e6a019009b.png)

I get:

```
#include "simpletools.h"
#include "badgetools.h"


int main() {
  badge_setup();
  while(1) {
    if (button(0)) {
    }

  }
  led(0, 1);
  led(0, 1);
  ,
}
```

**Comment by DarkmatterVale** [comment]
I've put in a few more fixes, but I'm not sure if it will fix the problem...

**Comment by DarkmatterVale** [comment]
I see this fixed in demo, can someone else verify?

**Comment by PropGit** [comment]
There is something wrong still.  May by related to later updates as on 7/21/16?

I created this program:  http://demo.blockly.parallax.com/blockly/projectlink?id=70&key=d8e98aaa-c37b-4c8f-ad90-03b764fd7915

That looks like this:
![image](https://cloud.githubusercontent.com/assets/1266318/17035817/4e634354-4f3e-11e6-9468-c0352a812c81.png)

And it generated this code:
![image](https://cloud.githubusercontent.com/assets/1266318/17035801/459e24fa-4f3e-11e6-8717-ad8eba44699d.png)


Which I thought may not compile properly, and I was right:
![image](https://cloud.githubusercontent.com/assets/1266318/17035792/345ed2fc-4f3e-11e6-936f-89cb5de85891.png)

**Comment by DarkmatterVale** [comment]
As with a few of the other issues I recently closed, I believe this change has been pushed to master, which you can see here https://github.com/parallaxinc/BlocklyProp/blob/master/src/main/webapp/cdn/blockly/generators/propc/hackable_electronic_badge.js#L82 and https://github.com/parallaxinc/BlocklyProp/blob/demo/src/main/webapp/cdn/blockly/generators/propc/hackable_electronic_badge.js#L82
