### ISSUE TITLE
Standard Servo Block accepts out of range numbers. 

### ISSUE THREAD

**Issue by RoxyH** [parallaxinc/BlocklyProp#266]
I was using the standard servo block and it accepted values that where out of range, beyond 180. Is it possible to limit the block so it only accepts values 0-180? 
- Roxy 

![snip2](https://cloud.githubusercontent.com/assets/20117435/16349128/c37102aa-3a0b-11e6-8e49-c81e87498e3e.PNG)

**Comment by DarkmatterVale** [comment]
Unfortunately, I do not believe this is possible. However, I can have the block generate a comment after the statement alerting the user that he/she has picked an invalid number of degrees.

@RoxyH What do you think of this solution?

**Comment by michel-cf** [comment]
We might be able to create a block using: https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks#angle_field

If a numeric value is entered (not a calculation or variable) we could do some validations: https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks#change_validator_javascript_only

**Comment by DarkmatterVale** [comment]
Great idea! I will send a PR for the first one later this weekend.
