### ISSUE TITLE
Joystick block code output revision

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#271]
Hey @DarkmatterVale: I think this one will be easy for you to repair. At present this Blockly code:
![screen shot 2016-06-24 at 3 39 56 pm](https://cloud.githubusercontent.com/assets/9534148/16352142/2230aaac-3a20-11e6-8856-c683ad12fd28.png)
Generates this code:
```
#include "simpletools.h"
#include "abvolts.h"

boolean y;


int main() {
  ad_init(21, 20, 19, 18);

  y = ad_volts(0);

}
```
but this code gives us a scaled 0-99 result with more current uses of Andy's libraries:
```
#include "simpletools.h"
#include "abvolts.h"

int y = 2048 + 40;

int main()
{
    y = ad_in(0);
    y = y * 100 / 4096;   
}
```
There are a number of changes here but I think they are quite clear. Can you implement this for both X and Y? Blake and Roxy really liked this approach. 
Thanks, KG

**Comment by DarkmatterVale** [comment]
Is it important to add the 1 ```int y = 2048 + 40;``` to the beginning of the compiled code?

**Comment by kgracey** [comment]
Yes, it scales the output down to a reasonable number.
