### ISSUE TITLE
Wave play back block generates wrong code

### ISSUE THREAD

**Issue by RoxyH** [parallaxinc/BlocklyProp#276]
![snip4](https://cloud.githubusercontent.com/assets/20117435/16395335/2893291a-3c6e-11e6-915d-6525cbc685c3.PNG)
These are the blocks used 

This is the code generated by Blockly
```
#include "simpletools.h"
#include "wavplayer.h"


int main() {

  const char filetechloop[] = {"techloop"};
  wav_play(techloop);
  wav_volume(10);
  pause(50000);
  wav_stop();

}
```

This is the corrected code 
```
#include "simpletools.h"
#include "wavplayer.h"
int main() {
  int DO = 22, CLK = 23, DI = 24, CS = 25;        // SD I/O pins
  sd_mount(DO, CLK, DI, CS);                      // Mount SD card

    const char filetechloop[] = {"techloop.wav"};
    wav_play("techloop.wav");
    
    wav_volume(10);
    pause(50000);
  }
```

-Roxy

**Comment by DarkmatterVale** [comment]
@RoxyH Should I also not declare ```const char filetechloop[] = {"techloop.wav"};``` since it is not used at all?

**Comment by kgracey** [comment]
@DarkmatterVale since @RoxyH is out of town for the rest of the week I'll answer. First, you are correct!

This is the minimum code (without the unused line you noted):

```
#include "simpletools.h"
#include "wavplayer.h"

int main() {
  int DO = 22, CLK = 23, DI = 24, CS = 25;        // SD I/O pins
  sd_mount(DO, CLK, DI, CS);                      // Mount SD card

    wav_play("techloop.wav");

    wav_volume(10);
    pause(50000);
  }
```

**Comment by kgracey** [comment]
@DarkmatterVale the blocks on demo.blockly.parallax.com are still generating the old, non-working code. Could you get another look at this one?

**Comment by DarkmatterVale** [comment]
Ah rip yes I will take another look this weekend.

**Comment by DarkmatterVale** [comment]
I think this has been fixed, can someone else verify?

**Comment by CarsonGracey** [comment]
Tested and Verified.

**Comment by DarkmatterVale** [comment]
This was merged in my most recent PR.
