### ISSUE TITLE
boolean substitution still around for random() block

### ISSUE THREAD

**Issue by cbradyatinquire** [parallaxinc/BlocklyProp#279]
the RANDOM block works when the value is directly printed 
but when it's stored to a variable, that variable is initialized with "boolean" type

**Comment by DarkmatterVale** [comment]
I found the issue with variable declaration (once again...) and I am confident this problem has finally been resolved.

**Comment by DarkmatterVale** [comment]
Can someone else verify this has been fixed?

**Comment by CarsonGracey** [comment]
Tested and Verified.

**Comment by DarkmatterVale** [comment]
This was fixed in a number of other commits and I believe it has already been pushed into master.
