### ISSUE TITLE
Using multiple of the same sensor

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/BlocklyProp#28]
Current issue with my ( and some of the original sensor blocks ) is that you can only reference/use one of each type.

I am not sure whether this can be easily fixed, or whether it will require a more advanced solution for certain blocks. I will do more investigating and reply when I have an answer.

**Comment by michel-cf** [comment]
Good point, although BlocklyProp will have some restrictions on what is possible, using multiple times a given sensor/actuator that require individual instances of some objects (I'm talking in spin language here, but the same applies for C) should be possible.

I propose we add a selectionbox to those blocks that require an object instance. We could then append the chosen id to the object name.

I think a case by case review is needed to find the best solutions.

**Comment by DarkmatterVale** [comment]
I think this is not an issue that we need to deal with right now. Other things are more important and we already have support for multiple of some sensors. So, for now I am going to close this.
