### ISSUE TITLE
print-a-number block should not print the variable name and "="

### ISSUE THREAD

**Issue by cbradyatinquire** [parallaxinc/BlocklyProp#280]
because we can print these prefix things directly using print-a-string it would be better for this block just to print a number alone.

**Comment by DarkmatterVale** [comment]
Can someone please verify this?

**Comment by cbradyatinquire** [comment]
Verified - this works as intended/expected.  Thanks!

**Comment by DarkmatterVale** [comment]
This was already merged into master, I'm not sure how long ago though...
