### ISSUE TITLE
TOGGLE command bug: another repair

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#282]
I created the following Blockly code:

![image](https://cloud.githubusercontent.com/assets/9534148/16404126/eab120d2-3cb0-11e6-8d70-ff7fabfbc0a0.png)

which created this code:

```
#include "simpletools.h"

// Describe this function...
void blink26() {
  while(1) {
    toggle(26);
    pause(100);
  }
}

// Describe this function...
void blink27() {
  while(1) {
    toggle(27);
    pause(105);
  }
}


int main() {
  low(26);

  low(27);

  cog_run(blink26, 128)cog_run(blink27, 128)
}
```
Two particular repairs need to be made to the Blockly output:

**FIRST:** This single line of code `cog_run(blink26, 128)cog_run(blink27, 128)` should be on two lines and is missing the semicolons. Right way:
```
cog_run(blink26, 128);
cog_run(blink27, 128);
```
**SECOND:** The two low commands (`low(26)` and` low(27)`) should be moved to the function calls, before the while loop. Note: the actual error lies in the SimpleTools.h library and I have submitted an issue tracker for it. However, I expect it to take a long time for them to fix this error so we'll work around it in Blockly for a while until they update the library. The correct code, reflecting these two changes is here:
```
#include "simpletools.h"

// Describe this function...
void blink26() {
  low(26);
  while(1) {
    toggle(26);
    pause(100);
  }
}

// Describe this function...
void blink27() {
  low(27);
  while(1) {
    toggle(27);
    pause(101);
  }
}

int main() {
  cog_run(blink26, 128);
  cog_run(blink27, 128);
}
```

**Comment by kgracey** [comment]
@DarkmatterVale we decided this is a much better way:

```
void blink27() 
{
  while(1) 
  {
    toggle(27);
    set_direction(27,1);
    pause(105);
  }
}
```

**Comment by PropGit** [comment]
Has this been retested yet?

**Comment by kgracey** [comment]
YES. This has been tested and verified.
