### ISSUE TITLE
Case Sensitivity

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#285]
We discussed that for the sake of consistency and simplicity, all words and letters in blocks should be lower case. All acronyms can be left capital. Here they all are:

**Control:** 
> [ ] Delay - delay
> [ ] Method - method

**Operators:** 
> [ ] Decrement/Increment - decrement/increment

**Values:**
> [ ] HIGH/LOW - high/low

**Input/Output:** 
> [ ] Make Pin# - make pin#
> [ ] Check PIN# - check pin# 
> [ ] Set the state of 1 pins starting at # 0 Values: p0: HIGH/LOW - set the state of 1 pins starting at # 0 values: p0: high/low 
> [ ] Freq PIN# Duration - frequency pin# duration
> [ ] Pulse-in PIN# Negative/Positive - pulse-in pin# negative/positive
> [ ] Pulse-out PIN# Pulse length - pulse-out pin# pulse length
> [ ] RC Charge/Discharge PIN# - RC charge/discharge pin#

**Communicate:**
> [ ] Print - print
> [ ] Serial init Baud - serial init baud
> [ ] Serial transmit - serial transmit
> [ ] Serial read byte - serial read byte

**Activity Board:**
> [ ] Save an int - save an int
> [ ] Get an int - get an int
> [ ] Save a float - save a float
> [ ] Get a float - get a float
> [ ] Save text - save text
> [ ] Get text - get text
> [ ] Mount an SD Card DO pin - mount an SD Card do pin
> [ ] Save an int, Filename, Starting, Ending - save an int, filename, starting, ending
> [ ] Get the stored SD Card int - get the stored SD Card int
> [ ] Save a float, Filename, Value, Starting, Ending - save a float, filename, value, starting, ending 
> [ ] Get a float, Filename, Starting, Ending - get a float, filename, starting, ending
> [ ] Get the stored SD Card - get the stored SD Card
> [ ] Save text, Filename, Text, Value, Starting, Ending - save text, filename, text, value, starting, ending 
> [ ] Get text, Filename, Starting, Ending - get text, filename, starting, ending
> [ ] Get stored SD Card text - get stored SD Card text
> [ ] Play file - play file
> [ ] Status - status
> [ ] Volume, Length of file - volume, length of file
> [ ] Stop - stop

**Sensor/Input:**
> [ ] ETape sensor, Pin, Put input value - ETape sensor, pin, put input value
> [ ] Initialize SCL Pin#, SDA Pin# - initialize SCL pin#, SDA pin#
> [ ] Read Store x-coords, Store y-coords, Store z-coords - read store-x coords, store y-coords, store z-coords
> [ ] Joystick A/D x/y-axis PIN# - joystick A/D x/y-axis pin#
> [ ] MX2125 X/Y-axis pin# - MX2125 x/y-axis pin#
> [ ] MMA7455 X-axis, Store X-axis, Y-axis, Store Y-axis, Z-axis, Store Z-axis - MMA7455 x-axis, store x-axis, y-axis, store y-axis, z-axis, store z-axis
> [ ] PAM7Q GPS, Baud - PAM7Q GPS, baud
> [ ] Get latitude/longitude/heading/altitude - get latitude/longitude/heading/altitude
> [ ] Get velocity units in MPH/KNOTS - get velocity in mph/knots
> [ ] Get # of satellites tracked - get # of satellites tracked
> [ ] Ping))), PIN# - Ping))) pin#
> [ ] PIR Sensor Pin - PIR sensor pin
> [ ] Enable RFID, Out pin - enable RFID, out pin
> [ ] Get/Disable/Close RFID - get/disable/close RFID
> [ ] Get a button pressed Pin# - get a button pressed pin#
> [ ] Sound impact, Run in cog# - sound impact, run in cog#
> [ ] Get sound impact data - get sound impact data
> [ ] Turn the sound impact sensor off - turn the sound impact sensor off

**Actuator/Output:**
> [ ] Servo PIN#, Degrees - servo pin#, degrees
> [ ] Servo speed Pin, Speed - servo speed pin, speed
> [ ] Servo set ramp Pin, Rampstep - servo set ramp pin, rampstep
> [ ] LCD init PIN#, Baud - LCD init pin#, baud
> [ ] LCD print Number - LCD print number
> [ ] LCD action Newline - LCD action newline

**Comment by DarkmatterVale** [comment]
Control:

[ ] Delay - delay
[ ] Method - method
Operators:

[ ] Decrement/Increment - decrement/increment
Values:

[ ] HIGH/LOW - high/low
Input/Output:

[ ] Make Pin# - make pin#
[ ] Check PIN# - check pin# 
[ ] Set the state of 1 pins starting at # 0 Values: p0: HIGH/LOW - set the state of 1 pins starting at # 0 values: p0: high/low 
[ ] Freq PIN# Duration - frequency pin# duration
[ ] Pulse-in PIN# Negative/Positive - pulse-in pin# negative/positive
[ ] Pulse-out PIN# Pulse length - pulse-out pin# pulse length
[ ] RC Charge/Discharge PIN# - RC charge/discharge pin#
Communicate:

[ ] Print - print
[ ] Serial init Baud - serial init baud
[ ] Serial transmit - serial transmit
[ ] Serial read byte - serial read byte
Activity Board:

[ ] Save an int - save an int
[ ] Get an int - get an int
[ ] Save a float - save a float
[ ] Get a float - get a float
[ ] Save text - save text
[ ] Get text - get text
[ ] Mount an SD Card DO pin - mount an SD Card do pin
[ ] Save an int, Filename, Starting, Ending - save an int, filename, starting, ending
[ ] Get the stored SD Card int - get the stored SD Card int
[ ] Save a float, Filename, Value, Starting, Ending - save a float, filename, value, starting, ending 
[ ] Get a float, Filename, Starting, Ending - get a float, filename, starting, ending
[ ] Get the stored SD Card - get the stored SD Card
[ ] Save text, Filename, Text, Value, Starting, Ending - save text, filename, text, value, starting, ending
[ ] Get text, Filename, Starting, Ending - get text, filename, starting, ending
[ ] Get stored SD Card text - get stored SD Card text
[ ] Play file - play file
[ ] Status - status
[ ] Volume, Length of file - volume, length of file
[ ] Stop - stop
Sensor/Input:

[ ] ETape sensor, Pin, Put input value - ETape sensor, pin, put input value
[ ] Initialize SCL Pin#, SDA Pin# - initialize SCL pin#, SDA pin#
[ ] Read Store x-coords, Store y-coords, Store z-coords - read store-x coords, store y-coords, store z-coords
[ ] Joystick A/D x/y-axis PIN# - joystick A/D x/y-axis pin#
[ ] MX2125 X/Y-axis pin# - MX2125 x/y-axis pin#
[ ] MMA7455 X-axis, Store X-axis, Y-axis, Store Y-axis, Z-axis, Store Z-axis - MMA7455 x-axis, store x-axis, y-axis, store y-axis, z-axis, store z-axis
[ ] PAM7Q GPS, Baud - PAM7Q GPS, baud
[ ] Get latitude/longitude/heading/altitude - get latitude/longitude/heading/altitude
[ ] Get velocity units in MPH/KNOTS - get velocity in mph/knots
[ ] Get # of satellites tracked - get # of satellites tracked
[ ] Ping))), PIN# - Ping))) pin#
[ ] PIR Sensor Pin - PIR sensor pin
[ ] Enable RFID, Out pin - enable RFID, out pin
[ ] Get/Disable/Close RFID - get/disable/close RFID
[ ] Get a button pressed Pin# - get a button pressed pin#
[ ] Sound impact, Run in cog# - sound impact, run in cog#
[ ] Get sound impact data - get sound impact data
[ ] Turn the sound impact sensor off - turn the sound impact sensor off
Actuator/Output:

[ ] Servo PIN#, Degrees - servo pin#, degrees
[ ] Servo speed Pin, Speed - servo speed pin, speed
[ ] Servo set ramp Pin, Rampstep - servo set ramp pin, rampstep
[ ] LCD init PIN#, Baud - LCD init pin#, baud
[ ] LCD print Number - LCD print number
[ ] LCD action Newline - LCD action newline

**Comment by CarsonGracey** [comment]
Tested and Verified.
