### ISSUE TITLE
Boolean type on variable assignment

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#286]
Discovered this when I tried to use wasShaken and placing it in a variable.

**Comment by DarkmatterVale** [comment]
Hi @MatzElectronics,

I am aware of the bug and a fix is present in #281. Thank you for the report though!

**Comment by kgracey** [comment]
Oh yeah, we all know about this little troublemaker. Vale has it under control.

**Comment by CarsonGracey** [comment]
Tested and Verified.
