### ISSUE TITLE
Some Dependencies not in Repository

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#287]
@michellampo - There are a number of references to a maven repository named e******.c******.propeller (obscured for safety). We don't know what it is requiring from there, but we're concerned that there are files held there that are required for building BlocklyProp and we really need to understand that and get those into a repository to manage it long-term.

Please inform us of the details and how we can proceed.

**Comment by michel-cf** [comment]
I don't think there were actual dependencies. But there BlocklyProp server was in the wrong group.
And Cloud-session-java-client and Cloud-compiler-java-client had references to my maven repository
