### ISSUE TITLE
Menu Reorginization

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#288]
In addition to the case sensitivity, we thought it would also be beneficial to reorganize the menu as well and the proposed changes are here.

### Original

-  Control
-  Operators
-  Values
-  Variables
-  Functions
-  Input/Output
   -  Pin States
   - Timing
- Communicate
   - Serial Terminal
   - Protocols
- Activity Board
   - Voltage
   - Memory
   - Audio
- Sensor/Input
   - ETape liquid level
   - HMC5883
   - 2-axis Joystick
   - Memsic 2-axis
   -  MMA7455
   - GPS PAM7Q
   - Distance: PING)))
   - PIR Motion -RFID
   - SF02 Laser
   - Sony Remote
   - Sound Impact Sensor
- Actuator/Output
   - Standard Servo
   - CR Servo
   - Serial LCD

### Changes:

- Move Pin States out of a sub menu
- Put Freq Pin and Audio into Audio
- Move RC charge/discharge, Voltage, and Pulse-in/out into Analog and Pulses
- Move Voltage and Audio from Activity Board menu to Output
- Change Actuator/Output to Servo
- Memory is its own menu with EEPROM and SD Card as its contents
- Delete Activity Board menu
- Rename Sensors/ Input to Sensors
- Move Serial LCD to Communicate menu

### Revised

- Control
- Operators
- Values
- Variables
- Functions
- Pin States
- Communicate
   - Serial LCD
   - Serial Terminal
   - Protocols
- Sensors
   - ETape liquid level
   - HMC5883
   - 2-axis Joystick
   - Memsic 2-axis
   - MMA7455
   - GPS PAM7Q
   - Distance: PING)))
   - PIR Motion -RFID
   - SF02 Laser
   - Sony Remote
   - Sound Impact Sensor
- Memory
   - EEPROM
   - SD Card
- Analog and Pulses
   - RC charge/discharge
   - Voltage
   - Pulse-in Pin
   - Pulse-out Pin
- Audio
   - Audio
   - Freq Pin#
- Servo
   - Standard Servo
   - CR Servo

**Comment by DarkmatterVale** [comment]
Where does the timing category now go? Or is it removed?

**Comment by CarsonGracey** [comment]
Tested and Verified.
