### ISSUE TITLE
Changing location of curly braces in generated code

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#289]
These blocks generate the code directly below. The current formatting works but is hard for beginners since the curly braces tend to not have their own line. The main reason this should be changed is so the code will be easier to read and understand.

![screen shot 2016-07-01 at 10 50 30 am](https://cloud.githubusercontent.com/assets/20099916/16529614/cc06b104-3f78-11e6-9dc8-c04fb3aeab4c.png)

### Blockly Generated
```C
#include "simpletools.h"

boolean loopCounter1;

// Describe this function...
void blink26() {
  loopCounter1 = loopCounter1 + 1;
  toggle(26);
  pause(100);
}

// Describe this function...
void blink27() {
  toggle(27);
  pause(105);
}


int main() {
  low(26);

  low(27);

  loopCounter1 = 0;
  cog_run(blink26, 128)cog_run(blink27, 128)while(1) {
    print("loopCounter1 = %d\n",loopCounter1);
    pause(100);
  }

}
```

### Formatted 
```C
#include "simpletools.h"

int loopCounter1;

// Describe this function...
void blink26() 
{
  while(1) 
  {
    loopCounter1 = loopCounter1 + 1;
    toggle(26);
    set_direction(26,1);
    pause(100);
  }
}

// Describe this function...
void blink27() 
{
  while(1) 
  {
    toggle(27);
    set_direction(27,1);
    pause(105);
  }
}

int main() 
{ 
  loopCounter1 = 0;
  cog_run(blink26, 128);
  cog_run(blink27, 128);
  while(1) 
  {
    print("loopCounter1 = %d\n",loopCounter1);
    pause(100);
  }

}
```

**Comment by michel-cf** [comment]
I have to disagree on this one. I always open curly brackets on the same line as the function/class/condition definition it's about.
They are both accepted by different groups of programmers, but my brain just goes crazy when you open curly brackets on new lines.

**Comment by kgracey** [comment]
Sure, I can see why you prefer it the way you do @michel-cf.

There are two reasons we think this is important. First, Blockly is a bridge to programming in C. Curly braces are notoriously difficult for people to handle - the starts and stops can be hard to find. Our audience for Blockly is as low as middle school (first time programmers). I am also a first-time C programmer and I can attest to the importance of the braces being on new lines. I have had numerous problems reading code without this formatting. 

The second reason is actually more important. For many years now we have created learn.parallax.com C code examples. The code examples nearly mirror our actual C examples on Learn. If the Blockly code looks similar, it's going to be a lot easier to connect a student to the greater Parallax ecosystem.

Pedagogy aside, the more students who are familiar navigating our resources the more financially successful Blockly (and Parallax, and Michel, and all developers!) will be for the long-term. So, we could say this is both for business and teaching reasons. 

I fully respect the difference of opinions on this subject. I've never read a C forum before but I bet this specific issue is the subject of ongoing religious battles on the internet! 

What do @cbradyatinquire and @DarkmatterVale and @PropGit think of this? I could be totally wrong, but I'm also not sure a majority would be totally correct in how we handle this. Heck, maybe Vale has technical challenges for not wanting to implement this, too. If it takes lots of time to format the code this way I'm happy to close this issue up quicker than the door of a stinky refrigerator! - Ken

**Comment by DarkmatterVale** [comment]
Personally, I have no opinion about this. I can code in both styles without any issues. Generally, I code in the style the other code is styled in. So, following that guideline, I agree that we should separate curly braces to match the other parallax code.

With regards to the difficulty implementing this change...It is not very difficult.

**Comment by michel-cf** [comment]
@DarkmatterVale I was going to look to add a code formatter in, then you don't need to change the blocks. (And in the future we might offer the choice of code style)

**Comment by DarkmatterVale** [comment]
Ah, ok...sounds like an interesting idea. I will hold off on completing this then; good luck!

**Comment by michel-cf** [comment]
Ready to be merged in demo

**Comment by CarsonGracey** [comment]
Tested and verified.

**Comment by DarkmatterVale** [comment]
Michel, can you please create a PR into the master branch for this?

**Comment by DarkmatterVale** [comment]
I just sent a PR
