### ISSUE TITLE
Fix SD Card Blocks

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/BlocklyProp#291]
Just a reminder to myself...

**Comment by DarkmatterVale** [comment]
I have redone the SD Card blocks to *hopefully* make them better. It is in demo, so please let me know what you all think of the changes and if any more are necessary.

**Comment by kgracey** [comment]
Okay! We’re ready to demo the SD card blocks on the demo.blockly.com site? I’ll go take a look!

Primary purpose would be storing and retrieving data, right? 

Ken Gracey
graceyken@gmail.com

**Comment by DarkmatterVale** [comment]
Since the automatic building is not enabled yet, I do not believe it has been pushed to production (but the next build of the demo branch will contain the updates).

Yes, that is correct. I modified the getting of the data to give the user access to each individual element of the arrays, as well as making the arrays global (instead of restricting them to a single method).

**Comment by kgracey** [comment]
Did the change of making all variables global make the SD card coding easier as well?

Ken Gracey
graceyken@gmail.com

**Comment by DarkmatterVale** [comment]
Hahaha, it ended up being about the same. I think though that even the small changes will be a lot better for the user (it simplifies each step a little bit I believe).

**Comment by zfi** [comment]
Good morning,

The automated build process is working but not in the manner you expected.
The Demo build checks for new commits every 15 minutes. It will build and
redeploy the updates to the Demo server if it sees any new commits. The
last update occurred about 22 minutes ago.

Jim

**Comment by kgracey** [comment]
This sounds perfectly useful to us! KG

**Comment by DarkmatterVale** [comment]
Ah, awesome! I just checked and the new SD Card blocks have been built and pushed out.

**Comment by zfi** [comment]
We will have to expose the Jenkins build server to the Internet in order to permit GitHib to send notifications to Jenkins. It will involve some firewall magic but it's doable. The polling option was plan 'B'.

**Comment by DarkmatterVale** [comment]
I'm gonna say this is fixed (since I created it as a very vague issue). Please create another issue if you have more specific requests for the SD Card blocks
