### ISSUE TITLE
Three replacement XBee blocks

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#301]
We can replace both Serial transmit blocks and the Serial read byte block with XBee setup, while both XBee transmit and Xbee receive need a variable attached to them. 
The setup block would create ```fdserial *xbee``` and also create ```xbee = fdserial_open(DO pin, DI pin, (fix last two parameters at 0, and 9600))```

```C
#include "simpletools.h"
#include "fdserial.h"

fdserial *xbee;                         //created with XBee setup (above main)
int n;

int main()
{
  xbee = fdserial_open(9, 8, 0, 9600);  //XBee setup
  while(1)
  {
    dscan(xbee, "%d", &n);              //XBee receive value
    print("n = %d\n", n);
  }
}
```

```C
#include "simpletools.h"
#include "fdserial.h"

fdserial *xbee;                        //created with XBee setup (above main)
int n = 0;

int main()
{
  xbee = fdserial_open(9, 8, 0, 9600); //XBee setup DO pin, DI pin (fix last two parameters at 0 and 9600)
  while(1)
  {
    dprint(xbee, "%d\n", n);           //XBee transmit value
  }
}
```

**Comment by DarkmatterVale** [comment]
Can you please clarify why the transmit block needs to be attached to a variable? Given your explanation, I believe it is a standalone block that does not return any data?

**Comment by kgracey** [comment]
I’ll go look at this right now. - KG

**Comment by DarkmatterVale** [comment]
I also think that the receive block does not need to be attached to a variable, as I can put the "storing variable" directly into the block

**Comment by kgracey** [comment]
I think I see the confusion. The Tx block doesn't need to be keyed into a variable, but it needs to accept one (or a constant) as the argument in the body of the block. Same for receive block, just as you noted above. This has me wondering: wouldn't the two approaches (a left keyed connection to a variable vs. dropping the var/value into the block) have the same result? Aren't they really doing the same thing?

**Comment by DarkmatterVale** [comment]
Yes, they do have the same result but there is one difference: I cannot pre-attach a block to a variable, while I can add value inputs and pre-fill those. By giving defaults the user can see, it reduces possible confusion and lets them easily get the block up and running without consulting anyone or any documentation.

**Comment by kgracey** [comment]
Gotcha. That makes sense to me. I'm happy with approach you are using.

**Comment by DarkmatterVale** [comment]
Awesome! I will have these into the demo branch ready to go in a little bit.

**Comment by kgracey** [comment]
Can't wait! You mean I'll actually get to play with them today? This is super exciting!

**Comment by DarkmatterVale** [comment]
You will have to get someone to build and deploy the demo branch, but that should be the only obstacle...

**Comment by kgracey** [comment]
From Jim E's email a few minutes ago it sounds like a sweeper comes by every 15 minutes, picks up new code you produce, and makes it live for all the monkeys like me to start using.

**Comment by DarkmatterVale** [comment]
Yea. I am testing the blocks right now...Once I am confident I didn't make any blaring mistakes, I will send a PR to demo for, as you said, the monkeys to test :D

**Comment by kgracey** [comment]
BTW, these blocks should go into the Communicate category and be called "XBee RF" unless you have a better counter-proposal.

**Comment by DarkmatterVale** [comment]
Would you like me to create a new category named "XBee RF" under the communicate category? I am currently putting them in communicat->protocols, and have named them "Xbee setup", "Xbee transmit", and "Xbee receive"

**Comment by kgracey** [comment]
Exactly. I have thought about whether or not we should have a separate “RF” category, but I think the XBee blocks fit best in the “Communicate” category for now, so that’s the best place to put them.

**Comment by DarkmatterVale** [comment]
Gotcha, I just merged into demo so you should see an update soon.

**Comment by zfi** [comment]
The build system polls GitHub every 15 minutes, beginning at the top of the
hour. I am configuring email motifications now so you have some feedback
from the process.

**Comment by kgracey** [comment]
I see some strange remnants of blocks in the Communicate menu. I'm wondering if these are partial remnants of errant XBee blocks (which should be visible, if not mistaken). 
![image](https://cloud.githubusercontent.com/assets/9534148/16715299/876cb13c-4690-11e6-8c80-1e81723268cc.png)

**Comment by DarkmatterVale** [comment]
Try clearing your cache; I'm seeing the blocks just fine on my end

**Comment by kgracey** [comment]
OK, that worked but I noticed two small things: 

1. Could you move the XBee blocks up a level (from Communicate / Protocols to Communicate) so they are on the same level as Serial LCD, Print and Protocols?

1. Rename Xbee to XBee (X and B are both caps) in the blocks.

Thanks! KG

**Comment by DarkmatterVale** [comment]
I do not think I can put blocks within an "upper category"; they have to exist within a subcategory. Would you like me to create an "XBee RF" category?

**Comment by CarsonGracey** [comment]
@DarkmatterVale, We could put them on the same category level as Serial LCD, Print, and Protocols and name it XBee.

**Comment by DarkmatterVale** [comment]
Gotcha

**Comment by DarkmatterVale** [comment]
Verified?

**Comment by kgracey** [comment]
Verified! Works beautifully!
