### ISSUE TITLE
Connection for Pulse-in and RC charge/discharge

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#304]
Both the Pulse-in and RC charge/discharge blocks should have their connection typed changed to be similar to that of a Ping))) block. This is because neither of them can equal a variable or have their inputs stored.

![pulse-in low](https://cloud.githubusercontent.com/assets/20099916/16626821/78024272-435f-11e6-96dd-9a57c82425b8.PNG)

![rc charge](https://cloud.githubusercontent.com/assets/20099916/16626830/7f9e7a0a-435f-11e6-9027-5cce20ceda12.PNG)

![ping cm](https://cloud.githubusercontent.com/assets/20099916/16626810/6cad6708-435f-11e6-9317-4eff9d72a706.PNG)

**Comment by DarkmatterVale** [comment]
Can someone else please verify this fix?

**Comment by CarsonGracey** [comment]
Tested and Verified.
