### ISSUE TITLE
Block request for ColorPal

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#306]
### ColorPal enable 
Adds these two lines of code and will be a function call block, looks like:

![close rfid](https://cloud.githubusercontent.com/assets/20099916/16630942/4dc809d0-4371-11e6-9833-df3df2b85b8c.PNG)

```C
#include "colorpal.h"                         // Include colorpal
colorPal *cpal;                               // Device identifier
```

### ColorPal get colors
Adds three lines of code that has the text: Get colors pin# [0-15] R [ ] G [ ] B [ ]
Looks similar to

![save an int](https://cloud.githubusercontent.com/assets/20099916/16631148/78b948d8-4372-11e6-80b7-4273169e4c29.PNG)

And the generated code would include the IO pin, open connection, and get readings

```C
int cpSIO = 6;                                // ColorPAL SIO -> Propeller P6
```

And in the main()

```C
coal = colorPal_open(cpSIO);                  // Open connection to ColorPAL

colorPal_getRGB(cpal, &r, &g, &b);            // Get red/green/blue readings
```

**Comment by kgracey** [comment]
Verified! This works - thank you!
