### ISSUE TITLE
Block modification for Functions - If - Return

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#307]
Hey @DarkmatterVale - I have an easy one for you. 

We are not really planning on using parameter pass / return to and from functions at this early stage of Blockly. The issue we created a while ago for global variables will make this possible without parameter passing. So, you can delete the Function - If - Return block and I'd like to replace it with this block:
![screen shot 2016-07-06 at 12 57 06 pm](https://cloud.githubusercontent.com/assets/9534148/16632280/4631508a-4378-11e6-8321-151df45d132b.png)
You can already imagine what this block does. If a condition is true then it creates the following code:
`return;
`
And that's all there is to it! This way we can exit a function in the middle quite easily. 
- Ken

**Comment by DarkmatterVale** [comment]
Can someone please verify?

**Comment by CarsonGracey** [comment]
Tested and Verified.

**Comment by CarsonGracey** [comment]
![if return2](https://cloud.githubusercontent.com/assets/20099916/17595953/203ff35c-5fa4-11e6-9d8b-fe43c71adffd.PNG)

Looks like this block had a second value input added by accident @zfi will fix this.

**Comment by DarkmatterVale** [comment]
The problem @CarsonGracey mentioned has been fixed by @zfi
