### ISSUE TITLE
Block elimination

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#308]
![to do return](https://cloud.githubusercontent.com/assets/20099916/16636533/8d11266e-438d-11e6-8dca-6ddc34e53994.PNG)

This block could be deleted because we hope to have global variable support so we won't have to pass parameters.

**Comment by DarkmatterVale** [comment]
I will have to confirm I can do this; Michel might have to tackle this one...

**Comment by kgracey** [comment]
Bump. @michellampo can you do this?

**Comment by DarkmatterVale** [comment]
I think @michel-cf will have to take this one...its a little above my pay grade :D

**Comment by DarkmatterVale** [comment]
bump

**Comment by zfi** [comment]
Must be at or below my pay grade. A patch will be on Demo shortly.

**Comment by kgracey** [comment]
We can lower your salary if needed. @zfi

**Comment by zfi** [comment]
Patch has been posted to Demo.
@kgracey:  lol

**Comment by CarsonGracey** [comment]
Looks good, verified.
