### ISSUE TITLE
Block rename

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#309]
![cognew method](https://cloud.githubusercontent.com/assets/20099916/16636589/e0b61234-438d-11e6-9e59-6c0794b5e638.PNG)

This block would be easier to use if the words said:
new core
function

**Comment by cbradyatinquire** [comment]
Hi - Ken ( @CarsonGracey ) - didn't you want to use "Process" as a synonym for "cog" (rather than "core")?
So


[[
new process

function
]]

?

**Comment by kgracey** [comment]
Yes, I do. 

I prefer “new processor” if that’s okay. 

Ken Gracey
graceyken@gmail.com

**Comment by cbradyatinquire** [comment]
ah, right - i mis-'spoke' 

[
new processor
function
]

**Comment by kgracey** [comment]
@CarsonGracey please test and verify.

**Comment by CarsonGracey** [comment]
Tested and Verified.
