### ISSUE TITLE
XAMPP install issue - Server setup wiki needs testing

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/BlocklyProp#31]
When trying to install XAMPP, a user had trouble getting it installed. Even though this is not a problem on our end, we should still test the wiki and make sure everything turns out like it should

**Comment by DarkmatterVale** [comment]
One person successfully tested the wiki and said they had no issues. It would be great if we had another person test this.....Any volunteers?

**Comment by michel-cf** [comment]
As we are going to a java server version, this is of no importance anymore
