### ISSUE TITLE
Block Deletion

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#310]
![sf02 laser](https://cloud.githubusercontent.com/assets/20099916/16636622/25de4570-438e-11e6-8844-f61e2265c04f.PNG)

This block could possibly be deleted because the SF02 laser is very expensive and is mostly used for commercial use.

**Comment by DarkmatterVale** [comment]
Can someone else verify this is fixed?

**Comment by CarsonGracey** [comment]
Tested and Verified.
