### ISSUE TITLE
Menu name change

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#311]
In the menu for demo.blockly.parallax.com, one sub menu is

Audio
>Audio
>Frequency Out

It would look better if it were changed to

Audio
>WAV Files
>Frequency Out

**Comment by DarkmatterVale** [comment]
I cannot merge this into demo because of conflicts and I cannot rebase from demo into my master because of other issues...so we are kinda stalemated until further notice...

**Comment by zfi** [comment]
Can you recreate the changes in a new branch on your repo and the do a PR for that branch? We should never be in a position where we cannot release code.
