### ISSUE TITLE
set LED State block invalid INITIAL state

### ISSUE THREAD

**Issue by cbradyatinquire** [parallaxinc/BlocklyProp#317]
the set LED State block is ALMOST working on Demo as of 7/7.  The hitch is that the block in its default state has "HIGH" as its value, whereas the two valid values are "high" and "low" - once you change that default value (to low and then back to high), the resulting C-code compiles.

**Comment by DarkmatterVale** [comment]
Oops I think this was caused when I changed the case of the high/low block as requested in another issue. I'll fix this...sorry!

**Comment by PropGit** [comment]
@cbradyatinquire - Can you verify that this is fixed on demo?

**Comment by cbradyatinquire** [comment]
Tested, NOT fixed - 
here is the code generated by the block in its default state:

#include "simpletools.h"
#include "badgetools.h"


int main()
{
    badge_setup();
    led(0, high);

}

This gives a compile error.

NOTE: it still is true that  when you change the value to "low" it works, and when you change BACK to "high" it works again.  But the INITIAL state is still broken.

**Comment by PropGit** [comment]
Thanks @cbradyatinquire.

@DarkmatterVale - Since this isn't fully fixed yet, please amend or cancel & replace PR #347 when appropriate.  Thanks!

**Comment by DarkmatterVale** [comment]
I will amend a commit as soon as I figure out the issue.

**Comment by DarkmatterVale** [comment]
@cbradyatinquire Ok so after more extensive testing I don't think I can 'fix' this. The issue I run into is the fact that the value I give the block (in this case 'high'), does not translate into a 1 or a 0. Instead, the displayed value is the same as the value within the block initially. How would you like me to proceed? Remove the high/low block and leave that value field empty?

**Comment by cbradyatinquire** [comment]
I think that there might be two options.  First, leaving it blank could work (but I expect that people will try to put other values in it (true/false, 0/1) - all of which will WORK (right?) but be odd and maybe bad for regularity of future coders' practice.

Second, in the block values code, if i remember correctly, there are always a series of pairs of values.  I had always assumed that those were repeated because we wanted the display value to always be the same as the 'behind the scenes' value.    Am I right about this?  and if so, are you saying there's a bug in Blockly?  (cause if this is working, another option would be to use "HIGH", 1; "LOW", 0 - so that the dropdown/chooser itself was making the substitution (on the initial block at least).

-c

**Comment by DarkmatterVale** [comment]
Yes, all of those will work. I agree that it may be be a little odd to use true/false or 0/1.

I'm not sure, but I believe the generator code for the high/low block is not being called at all. @michel-cf Is that correct? If it is not correct, do you have any idea why I am unable to properly set a high/low value?

**Comment by DarkmatterVale** [comment]
bump

**Comment by michel-cf** [comment]
I've just tested this out (first time using the HEB) and it all seems to work.

@DarkmatterVale What is the problem? What is missing?

**Comment by DarkmatterVale** [comment]
The value generated should not be ```high``` but instead it should be ```1```, which is what the value ```high``` translates to if you place the block yourself...

**Comment by PropGit** [comment]
Still needs fixing/verification before PR #414 is processed.

**Comment by CarsonGracey** [comment]
Tested and Verified.
