### ISSUE TITLE
Demo programs cannot be compiled and/or downloaded

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/BlocklyProp#32]
It has been brought to my attention that the demo programs cannot be compiled and downloaded. I do not know if this is a bug, or if this is the way it was meant to be.

**Comment by michel-cf** [comment]
Can you be specific on which programs? All? All C or all spin or just some?

**Comment by DarkmatterVale** [comment]
I am not sure. I believe it was a C demo.....

**Comment by michel-cf** [comment]
Closing because this is about a previous, now unsupported version
