### ISSUE TITLE
Reset password and Email Confirm Broken for OAuth accounts

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#323]
The Reset password and Email Confirmation pages do not work properly when the user enters an OAuth account email address in the field.  Currently it responds with a 500 error.

**Comment by michel-cf** [comment]
@zfi I mistakenly instructed you to only copy the app directory of cloud-session when deploying the new version.

This functionality depends on Failures.py in the root directory of the repository. Could you please deploy this and restart the Cloud-session server again? That should fix these problems.

**Comment by zfi** [comment]
@michel-cf  I just deployed the updated Failures.py to the DEMO stack and restarted supervisor.

**Comment by michel-cf** [comment]
Thanks, I just tested it and it now seems to work fine.
