### ISSUE TITLE
Second-layer categories

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/BlocklyProp#33]
I do not know what the status is on this, but I think this has been discussed as something that needs to be completed.

Michel, since this is a core function addition, I will just put you as the assigned individual.

**Comment by michel-cf** [comment]
In the newest version of Blockly subgroups are supported. A lot of refactoring will be needed to get this working though. (All block definitions and code generators)

**Comment by DarkmatterVale** [comment]
I will do all of the work in the generators and blocks if you can get the core function of this added.

**Comment by michel-cf** [comment]
Thats ok, but let me first try it out with a limited set of blocks to test if it works. No need for you to put in your time until I've got it working. If it works, it'll also give you an example of what changes are needed.

I'll probably have to re-implement the pointers system too.

**Comment by DarkmatterVale** [comment]
Ok. Let me know if you need any help!

**Comment by michel-cf** [comment]
Update: I've gotten the first blocks to work today. (Up till yesterday I couldn't see any thing in the workbench, actually, there was no workbench to see.)

Also the C generation for these blocks seem to work.

**Comment by DarkmatterVale** [comment]
Cool!! Do second layer categories for the blocks work? Are there any other updates to block "configuration"?

Is the code posted to Github? If it is not, I would really appreciate it if you could upload it to so I can take a look ( and avoid asking you 1,000,000 questions :) ).

**Comment by michel-cf** [comment]
Second layer will be for tomorrow, but there shouldn't be any problems.

I just checked it in (subgategories branch)

**Comment by DarkmatterVale** [comment]
Holy cow that is a lot of code!! There is no way I will be able to parse through and understand all of that.........When you finish would you mind posting a summary of the changes here?

I will keep looking around in it though to see how everything works......Thanks for posting the code!

**Comment by michel-cf** [comment]
It's a lot of little changes. If you just need to change a block, it's not a lot of work. It's a lot of times the same changes. (BTW: I haven't actually looked at the changes in the Blockly core)

Today I made a lot of progress by comparing all code with the examples. That improved the debugging especially because I combined that by switching to the Java version instead of uploading each time to bptest.creatingfuture.eu.

**Comment by michel-cf** [comment]
The most important changes:

-Blockly.propc = Blockly.Generator.get('propc');
+Blockly.propc = new Blockly.Generator('propc');

-Blockly.Language.PAM_7Q_Init = {
+Blockly.Blocks.PAM_7Q_Init = {

Something I need to test:
appendTitle is deprecated according to the browser console, and will have to be replaced by appendField.
The same for:
this.getTitleValue -> this.getFieldValue

**Comment by DarkmatterVale** [comment]
Hmmm......Ok. Once you get a stable version going, I will go over the blocks you have already converted and bring my blocks up to date.

Will this at all affect how the Generators' code?

**Comment by michel-cf** [comment]
Grouping on multiple levels is available with the upgraded Blockly version
