### ISSUE TITLE
Removing Exponent drop down from operators

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#333]
![cog](https://cloud.githubusercontent.com/assets/20099916/16737475/623514de-4746-11e6-8ef3-32d42f1b96e1.PNG)

This option from the drop down can be completely removed since C language does not even support exponential functions.

**Comment by kgracey** [comment]
Woops. Specifically, our Propeller C doesn’t seem to support it. And, I can’t think of a specific use of it for Blockly projects at this stage. This will change in the future, but for now we don’t need the exponent operator.
