### ISSUE TITLE
RFID Close

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#338]
![close rfid](https://cloud.githubusercontent.com/assets/20099916/16745551/31695bc4-476b-11e6-97a1-e8ac96d7e6a6.PNG)

This block currently produces the code ```rfid_close(rfidser* device);``` when it needs to be ```rfidser_close(rfidser* device);```

**Comment by DarkmatterVale** [comment]
In #290 you say it should be ```rfid_close```...Which one is correct?

**Comment by CarsonGracey** [comment]
In the simple library reference it says rfidser_close, that should be correct

**Comment by CarsonGracey** [comment]
Tested and Verified.
