### ISSUE TITLE
RFID Reader Block

### ISSUE THREAD

**Issue by Wierdowl** [parallaxinc/BlocklyProp#339]
While testing this block:
![screen shot 2016-07-11 at 2 23 36 pm](https://cloud.githubusercontent.com/assets/20117212/16747333/7321b770-4773-11e6-8a76-f7ebc92df7fd.png) 
I found that it generated this code:
```
#include "simpletools.h"
#include "rfidser.h"

int badge__;


int main()
{

    badge__ = rfid_get(rfid, 1000)
}

```
Which did not work, but when I changed it to this:
```
#include "simpletools.h"
#include "rfidser.h"

int badge__;


int main()
{

    badge__ = rfid_get(rfid, 1000);
}
```
Where I put in a semicolon after "badge__ = rfid_get(rfid, 1000)" and it started to work.-Blake

**Comment by kgracey** [comment]
We can close this issue because we're replacing it with another one today, @DarkmatterVale. So, blast this one away because @Wierdowl and I have a better solution now.

**Comment by PropGit** [comment]
Closing this issue as requested.
