### ISSUE TITLE
Comment Block

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#341]
It may be helpful to add a comment block, which would basically be a text block that would insert the code ```//Text```, since nearly everyone puts comments on their code, a block that could do that would be very helpful.

**Comment by michel-cf** [comment]
Are you aware that you can add comments to a block? Isn't that enough?

**Comment by CarsonGracey** [comment]
I just found that out after reading your comment but the only problem I personally see with that is that you have to click on the ? each time to view your comment instead of always having them open and easily visible.

**Comment by kgracey** [comment]
I think it's a request worthy of discussion. Strangely, I had also asked @michel-cf the same question a while back [maybe he remembers] in some other Issue. One of our interns had asked the same question about comments. A comment block would be easy enough to make, but allow them to be more visible in their appearance within the block code. 

I'd like to know what others think of this, too. I'm on the fence.

**Comment by PropGit** [comment]
Can we make a comment block (that only contains comments, as requested by this issue) that displays the comments by default, and leave the existing blocks' comment features hide the comment by default?  I think that'd be nice.

It'd also be great if there could be a button on the header that allows the user to show-all comments or hide-all comments in one simple step.

**Comment by kgracey** [comment]
That would be the most tidy solution if it were possible. If this isn’t easily accommodated or possible just let us know - we all know there are bigger issues that Michel is dealing with so you guys can factor this in as appropriate given our September release.

**Comment by michel-cf** [comment]
I can disable comment's altogether and we can make a block for it.
I don't think the other suggested solutions are possible.

**Comment by kgracey** [comment]
I think it could be best to handle things this way. My only reasons for thinking this way (so far) are that myself and two students couldn’t easily find the comments in the blocks, and therefore find them not too useful as designed.  

I think a comment block would be a good solution here so that the user comments are ALWAYS visible.

**Comment by kgracey** [comment]
@DarkmatterVale can you assign a comment block to yourself? It's an easy one - a big text field that turns into a comment! Like this:

`// Vale is going to build a rocket in his backyard and fly to Mars`

**Comment by DarkmatterVale** [comment]
Hahaha it's already assigned to me

**Comment by DarkmatterVale** [comment]
I believe this has been verified but can someone please give me a written "acknowledgment of verification" please?

**Comment by PropGit** [comment]
@CarsonGracey or @kgracey - Before verification, are we waiting for [the suggestion in Issue # 396](https://github.com/parallaxinc/BlocklyProp/issues/396#issuecomment-233367073) to be implemented first?

**Comment by DarkmatterVale** [comment]
#396 has been verified

**Comment by zfi** [comment]
The comment block needs a newline at the end of the comment string.

![2016-08-18_15-10-33](https://cloud.githubusercontent.com/assets/8442260/17792532/0f7047c2-6556-11e6-9a3b-b1431aad18e2.png)

#include "simpletools.h"

int main()
{

    // This is a comment// Second Linepause(1000);
    //
}

**Comment by CarsonGracey** [comment]
This is something that will need to be addressed in PR 1.

**Comment by DarkmatterVale** [comment]
Addressed in #583

**Comment by CarsonGracey** [comment]
Tested and Verified.
