### ISSUE TITLE
Menu name error in demo

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#359]
Under communicate instead of just XBee, it reads ???category.communicate.xbee???

**Comment by kgracey** [comment]
![screen shot 2016-07-12 at 2 21 39 pm](https://cloud.githubusercontent.com/assets/9534148/16812280/3ba0dafa-48e1-11e6-82cf-74abda4ee3ba.png)

**Comment by kgracey** [comment]
![screen shot 2016-07-13 at 10 18 14 am](https://cloud.githubusercontent.com/assets/9534148/16812294/5420a326-48e1-11e6-89a9-2f3aacd262f8.png)

**Comment by PropGit** [comment]
That means the translation string for the xbee block in the communication category was mistakenly left out.

**Comment by CarsonGracey** [comment]
Verified fixed.

**Comment by DarkmatterVale** [comment]
As soon as #301 gets verified I'll merge
