### ISSUE TITLE
S3 block: set motor speed text revision

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#361]
@dcarrier-parallax please modify this block:
![screen shot 2016-07-13 at 12 23 41 pm](https://cloud.githubusercontent.com/assets/9534148/16816528/16119d08-48f3-11e6-81c5-f7989801308f.png)
to:
![screen shot 2016-07-13 at 12 23 28 pm](https://cloud.githubusercontent.com/assets/9534148/16816536/1ad8b7c2-48f3-11e6-8366-36495df88e8c.png)
so that the input ranges are clear to the user. Please auto-scale this value to the 8-bit signed directional values too. I made this prototype example for you in Block Factory.

**Comment by dcarrier-parallax** [comment]
Added here: https://github.com/parallaxinc/BlocklyProp/commit/0fef1d8eef8064c8cd878ea0e2c088634187726a
