### ISSUE TITLE
Colored categories

### ISSUE THREAD

**Issue by michel-cf** [parallaxinc/BlocklyProp#363]
I found a new feature in Blockly, and implemented it on small scale:

![image](https://cloud.githubusercontent.com/assets/5745991/16819792/5fbc68b0-494e-11e6-953d-64704c0ad88b.png)

You can give categories a color, and it appears a small colored block next to the category name. And instead of the plain blue color, the defined color is used to highlight the selected category.

Do we want this?

**Comment by kgracey** [comment]
I think it’s pretty cool, actually. Other versions of Blocky (ArduBlock, MakeBlock, etc.) make good use of colors in this way. I like it!

**Comment by PropGit** [comment]
Me too!

**Comment by kgracey** [comment]
Well, that's TWO of us! Push this great idea to DEMO @michel-cf!

**Comment by michel-cf** [comment]
I merged it into demo. Please keep in mind that this is incomplete at this stage. But it shows how to implement it.

**Comment by DarkmatterVale** [comment]
They look great! @kgracey @PropGit Can you guys get me a list of what color you would like each category to look?

**Comment by PropGit** [comment]
Unless @kgracey says otherwise, I think it's already bee defined in Issue #226.

**Comment by michel-cf** [comment]
I used the main color for the blocks of that category. Sadly, you can't use colorpallete.js at this location.

**Comment by DarkmatterVale** [comment]
Can we merge @michel-cf's current work into master? I'm gonna vote yes, so only one more person needs to verify

**Comment by kgracey** [comment]
Yes :)

**Comment by DarkmatterVale** [comment]
@michel-cf Can you create a PR & merge it?

**Comment by michel-cf** [comment]
It's only a minimal implementation and the other categories in the C editor and all of them in the Spin editor still need to be configured.

**Comment by PropGit** [comment]
Please create another issue to finalize the colors if the current work is
being merged in .

**Comment by DarkmatterVale** [comment]
Ah, I was going to create a PR but I saw that the branch was rebased to demo (I presume to fix the merging problems I am also seeing). Instead of attempting to clean the branch up, I'm going to take the changes and reapply them on my branch as well as create colors for the remaining categories.

**Comment by CarsonGracey** [comment]
Tested and Verified.

**Comment by DarkmatterVale** [comment]
Closed via #414
