### ISSUE TITLE
S3 block: Print block request

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#366]
@dcarrier-parallax I am now stuck with testing because I am unable to discern the values of the sensors (line, obstacle, light, etc.) with LEDs only as feedback. Please let me know when you have a working Print block. I expect the initial implementation to be very simple: strings or integers should be fine.

**Comment by dcarrier-parallax** [comment]
Added here: https://github.com/parallaxinc/BlocklyProp/commit/88771128d4cdefdf6ef8804dd4a1368e29998a23
