### ISSUE TITLE
S3 block: Sound and repeat

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#368]
![s3 sound](https://cloud.githubusercontent.com/assets/20099916/16820976/ad4bece0-4908-11e6-8bc2-ca1bea648b2a.PNG)

Theoretically, these blocks should play ascending notes while repeating, ascending 1 Hz per repeat starting at 0 Hz. But instead they do not repeat at all and play the Hz (item, 0, 25) where 25 should be a duration in milliseconds but is instead being played as a sound.

```Spin
CON
  _clkmode = xtal1 + pll16x
  _xinfreq = 5_000_000

VAR
  long Frequency

OBJ
  scribbler    : "Block_Wrapper"

PUB Setup
  Start


PUB Start

  Frequency := 0
  repeat until (Frequency == 3000)
    Frequency := Frequency + 1
    Scribbler.PlayNote(Frequency, 0, 25)
```

**Comment by kgracey** [comment]
For @dcarrier-parallax

**Comment by dcarrier-parallax** [comment]
Duplicate of: https://github.com/parallaxinc/BlocklyProp/issues/374, caused by crash of Block_Wrapper.spin
