### ISSUE TITLE
IOS Support

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/BlocklyProp#37]
Ipad, Ipad mini, Iphone, Ipod, etc.

**Comment by DarkmatterVale** [comment]
This will take a lot of work, especially if we want everything to be in a single app including the UI. If possible, I would think that this would be best completed by creating a mobile version of Michel's main website, then creating an app that handles the downloading of the file.

**Comment by michel-cf** [comment]
If Parallax can provide the native code to compile and load code, we could use something like Cordova to create an application where we communicate between a browser component containing Blockly and a native part for compiling and loading.

This could result in a single codebase for the html, css, js while building for both Android and IOS. (If compilers and loaders are available for both)

**Comment by DarkmatterVale** [comment]
Yes, Cordova would be a great way to accomplish this.

The loader for IOS is another repo here in Parallax's organization account. I am not sure of its status, but hopefully it will work by the time we need it
