### ISSUE TITLE
ColorPal block include file has extra semicolon (;) causing trouble

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#371]
@DarkmatterVale this one is for you. Here's my code:

![screen shot 2016-07-14 at 9 48 23 am](https://cloud.githubusercontent.com/assets/9534148/16847490/27c56bf2-49a6-11e6-8b0a-df53c5d2b532.png)
```
/* SERIAL_TERMINAL USED */
#include "simpletools.h"
#include "colorpal.h";

int red;
int green;

int blue;

colorPal * cpal;
int cpSIO = 0;


int main()
{
    cpal = colorPal_open(cpSIO);
    while (1)
    {
        colorPal_getRGB(cpal, & red, & green, & blue);
        print("red = %d\n", red);
    }

}
```

It has two issues that need to be addressed:

1. The additional carriage return between `int green;` and `int blue;` should be removed.
2. The `#include "colorpal.h";` should have the semicolon removed so it will compile.

**Comment by DarkmatterVale** [comment]
Extension of #306

**Comment by DarkmatterVale** [comment]
The second of the issues you specified is a bug in variable handling; I will create a separate issue for it

**Comment by DarkmatterVale** [comment]
After completely destroying some branches, I got this into demo...

**Comment by kgracey** [comment]
This issues is verified and fixed. Can be closed.
