### ISSUE TITLE
ColorPal block: forward declarations and function locations

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#372]
@DarkmatterVale I imagine this request will apply to a number of blocks, but we can start here and make this one correct. Take a look at this code:
![screen shot 2016-07-14 at 11 16 14 am](https://cloud.githubusercontent.com/assets/9534148/16850125/84d8e646-49b2-11e6-93ce-722392aeb06e.png)
Which produces the following C code:
```
/* SERIAL_TERMINAL USED */
#include "simpletools.h"
#include "colorpal.h";

int red;
int green;

int blue;

// Describe this function...
void checkColor()
{
    while (1)
    {
        colorPal_getRGB(cpal, & red, & green, & blue);
    }
}

colorPal * cpal;
int cpSIO = 0;


int main()
{
    cpal = colorPal_open(cpSIO);
    cog_run(checkColor, 128);
    while (1)
    {
        print("red = %d\n", red);
    }

}
```
This is the code we would like to see:
```
/* SERIAL_TERMINAL USED */
#include "simpletools.h"
#include "colorpal.h"

void checkColor();

int red;
int green;
int blue;

colorPal * cpal;
int cpSIO = 0;

int main()
{

    cog_run(checkColor, 128);
    while (1)
    {
        print("red = %d\n", red);
    }
}

// Describe this function...
void checkColor()
{
    cpal = colorPal_open(cpSIO);
    while (1)
    {
        colorPal_getRGB(cpal, & red, & green, & blue);
    }
}
```
The correct code has the following changes:
(1) The functions (checkColor) should be at the bottom.
(2) A forward declaration was added up top for the function.
(3) The ColorPal initialization should actually be in the checkColor function (take a look at where it is located in the blocks). For some reason it was somewhere else. 

If the forward declaration (2) is difficult to create, that's okay. We can approach this another way by simply putting the functions at the bottom, after main(). It's your call and should be determined on the complexity of coding required to make the forward declaration happen.

**Comment by DarkmatterVale** [comment]
Ok some of these are pretty big issues that are going to need a little bit of time to address. Are all 3 high priority?

**Comment by kgracey** [comment]
Sure, but how can we make this easier? I'm happy to omit the request for forward declarations if you can move the functions to after main(). Does this make things any easier?

**Comment by CarsonGracey** [comment]
This is what @kgracey meant

```C
/* SERIAL_TERMINAL USED */
#include "simpletools.h"
#include "colorpal.h"

int red;
int green;
int blue;

colorPal * cpal;
int cpSIO = 0;

// Describe this function...
void checkColor()
{
    cpal = colorPal_open(cpSIO);
    while (1)
    {
        colorPal_getRGB(cpal, & red, & green, & blue);
    }
}

int main()
{

    cog_run(checkColor, 128);
    while (1)
    {
        print("red = %d\n", red);
    }
}

```

**Comment by DarkmatterVale** [comment]
I'm gonna need a little guidance here because I'm not sure I can make ```cpal = colorPal_open(cpSIO);``` go into the checkColor() function. I believe however, that the program still works if ```cpal``` is initialized before ```cog_run(checkColor, 128);```? Would it be alright to leave ```cpal = colorPal_open(cpSIO);``` at the beginning of ```main()```?

**Comment by kgracey** [comment]
If it compiles, putting it at beginning of main() is fine. Yes!

**Comment by DarkmatterVale** [comment]
Please let me know if you like the new look more.

**Comment by CarsonGracey** [comment]
Tested and Verified.
