### ISSUE TITLE
"Save as" feature for code iterations

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#373]
Maybe there's another way to handle this problem, let me know. 

Blake is making a fairly complex project - an XBee wireless alarm system with a transmitter and receiver. A PIR alarm sends a message to the receiver where an alarm is sounded. A future version will include an RFID reader (scan your tag in 10 seconds or else). 

Blake is making frequent iterations to his code along the way and needs ability to revert to prior versions because his code works, then breaks, then works again, and breaks again. Version control isn't an option I'm sure - and we don't need it - but what about a simple Save as function? Is this a possibility @michel-cf?

![img_8431](https://cloud.githubusercontent.com/assets/9534148/16852364/ac4d3b78-49bc-11e6-9496-08b893a8554c.jpg)
. 

![img_8430](https://cloud.githubusercontent.com/assets/9534148/16852242/18fbe72a-49bc-11e6-821a-ea28110b3e7a.jpg)

**Comment by zfi** [comment]
If we think of it terms of "undo" levels, it might be possible.

**Comment by kgracey** [comment]
Or a "clone" type of function? I guess that's the same end result as a Save As. If Google fixes the "Omit Blocks" feature then this be helpful too.

**Comment by michel-cf** [comment]
Clone is already available in the project view: (bottom right)

![image](https://cloud.githubusercontent.com/assets/5745991/16879347/82f22f46-4ab0-11e6-8cdc-bbdea346104a.png)

**Comment by kgracey** [comment]
@michel-cf - I think this could probably serve the intended purpose for us. It's a matter of training people to look for it, though, since Save As is a default human instinct at the stage. We will start with the clone feature and see if people adopt it. You can close this issue (or drop it to low importance).
