### ISSUE TITLE
RGB OLED: Block Request

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#376]
This is the first of many OLED block requests to come. It will automatically include the library ```"oledc.h"``` along with those listed at the bottom.

![oled](https://cloud.githubusercontent.com/assets/20099916/16857072/8930326a-49d2-11e6-9419-94d83bde7cc7.PNG)

This block will set up the Color OLED screen and generate the code:

```C
oledc_init(CS, D/C, DIN, CLK, RES, 2);
```

The 2 will always be constant since it is rotation.

Also, since medium and large fonts each require their own libraries, they need to be added in the initialize block. Both large and small fonts will include Sans (Console), Serif (Typewriter), Script (Handwriting), and Bubble (Outline). There must be one only one large font chosen, and only one medium font. There is only a single small font so there won't be any option for it.

### Large Font Libraries:
Sans ```#include "oledc_fontLargeSans.h"```
Serif ```#include "oledc_fontLargeSerif.h"```
Script ```#include "oledc_fontLargeScript.h"```
Bubble ```#include "oledc_fontLargeBubble.h"```

### Medium Font Libraries
Sans ```#include "oledc_fontMediumSans.h"```
Serif ```#include "oledc_fontMediumSerif.h"```
Script ```#include "oledc_fontMediumScript.h"```
Bubble ```#include "oledc_fontMediumBubble.h"```

If anyone wants to further edit this on block factory for any reason here is the link: https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#nz79zv

**Comment by MatzElectronics** [comment]
In addition, I would add "None" to the Medium and Large font selection - I don't believe it makes a memory difference on the current version of GCC in use, but it will on a newer version if/when it gets updated.

**Comment by michel-cf** [comment]
Due to the long length I propose to put the font selections on a second line: https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#3vdymi

**Comment by DarkmatterVale** [comment]
@CarsonGracey Where should I put the block? Does a new category "OLED" in Communicate work?

**Comment by kgracey** [comment]
Yes, that's the best place.

**Comment by kgracey** [comment]
Sounds great, like the S3 drive blocks.

**Comment by MatzElectronics** [comment]
The "None" option got missed... I think it should be there.  Selecting no large font could save almost 3KB of program space, and no medium font about 2KB once the never GCC compiler begins being used.

**Comment by CarsonGracey** [comment]
I agree that would be very helpful to add at the top of the fonts list and maybe set it to a default that doesn't include any of the medium or large font libraries.

**Comment by DarkmatterVale** [comment]
Gotcha I'll add it right away.

**Comment by DarkmatterVale** [comment]
Just updated

**Comment by MatzElectronics** [comment]
Thanks!  Unfortunately I'll be changing the structure of this soon :(  The
fonts are taking up too much memory, so I'm going to write a program that
loads them all into EEPROM, and the library will just grab them from
there.  More info to come...

Thanks!
Matt

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by PropGit** [comment]
@MatzElectronics - Will your changes be _today_?  Next week?  Need to know if we should verify this as fixed (for now) so as not to hold up PR's that reference it.

**Comment by MatzElectronics** [comment]
I'd like them to be today, but early next week is more realistic.

For now, I'd work on any blocks that are non-text related and on building
the mechanism that allows the color picker to be used as those this will
not be affected by any changes I make.

**Comment by kgracey** [comment]
Can we get any OLED blocks working in entirety today with the prior code submitted?

**Comment by kgracey** [comment]
I’m out of phase with the exact issue at this stage - do Carson, Vale and MattM know what needs to be accomplished? Are we all on the same page?

**Comment by MatzElectronics** [comment]
For the init block, we just need to remove the font setting stuff, and just let it run the oledc_init funtion:

![image](https://cloud.githubusercontent.com/assets/19737272/17064139/df695080-4fef-11e6-863c-0ab81696b5d2.png)

Here is the block factory for it:
https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#q973p5

**Comment by DarkmatterVale** [comment]
The block has been updated

**Comment by CarsonGracey** [comment]
The block almost works but I forgot to add a very important detail, this block needs to add the library
```C
#include "oledc.h"
```

**Comment by MatzElectronics** [comment]
Okay, don't hate me, but when I update the library next week, I'd like to
reorder the pins on this block to match the pins on the module itself.
Currently, this is the order:

CS, D/C, DIN, CLK, RES


I'd like to change it to:


DIN, CLK, CS, D/C, RES


Please let me know if this it too much of a problem, and we can discuss it
further.  I think this change will make it a lot easier to hook up because
then they will most likely end up in sequence...  And then we could default
them to:


7,8,9,10,11


Thoughts, concerns?  Again, this wouldn't change until I upload a new
version of the library...

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by zfi** [comment]
Issued PR #423 to, in part, reorder the OLED initialization parameters.

**Comment by CarsonGracey** [comment]
Tested and Verified.
