### ISSUE TITLE
Spin generator has extra 'Setup' method, adds other methods after VAR block

### ISSUE THREAD

**Issue by dcarrier-parallax** [parallaxinc/BlocklyProp#380]
The Spin interpreter tokenizes methods in the order they appear, and does not run a named method first.

The Spin generator creates a Setup method that calls a Start method that contains the code that should run first, but if blocks create other methods, they are added after the VAR black, instead of at the end of the file.

**Comment by paragitadmin** [comment]
The Spin code is being phased out. No need to correct this issue now.
