### ISSUE TITLE
RFID Blocks: Updated Code

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#382]
The current RFID blocks are string-oriented and we would like them to be decimal so we've come up with an excellent solution that is all integer based. In short, here is the entire working code:
```
#include "simpletools.h"                      // Include simpletools
#include "rfidser.h"                          // Include rfidser

int rfidEn = 2;                               // Reader /ENABLE pin to P2
int rfidSout = 1;                             // Reader SOUT pin to P1

rfidser *rfid;                                // Set up device ID
int rFval;

int main()                                    // Main function
{
  rfid = rfid_open(rfidSout, rfidEn);         // Open reader, start reading

  while(1)                                    // Main loop
  {
    char *str = rfid_get(rfid, 1000);         // Wait up to 1 s for card
    //print("id string = %s.\n", str);          // Print ID.
    sscan(&str[2], "%x", &rfVal);
    if(rfVal == 237) rfVal = 0;
    //print("id value = %d.\n\n", rfVal);       // Print ID.
  }  
}
```
The blocks needed are the following:
RFID enable (arguments are enable and Sout pins) for this code up top:
```
#include "rfidser.h"                          // Include rfidser

int rfidEn = 2;                               // Reader /ENABLE pin to P2
int rfidSout = 1;                             // Reader SOUT pin to P1
rfidser *rfid;                                // Set up device ID
```
along with this in main()
 ` rfid = rfid_open(rfidSout, rfidEn);         // Open reader, start reading`
and the following replacement code generated from the "get RFID's sensor value and store it in [item]" block
```
    char *str = rfid_get(rfid, 1000);         // Wait up to 1 s for card
    //print("id string = %s.\n", str);          // Print ID.
    sscan(&str[2], "%x", &rfVal);
    if(rfVal == 237) rfVal = 0;
    //print("id value = %d.\n\n", rfVal);       // Print ID.
```
At the same time, the "item" variable would be created up top as well: 
`int rival;`

Omit the print statements of course - they're just there so you can try the whole code if desired. Really, the only thing new about this block are the lines of code which turn the byte string into a decimal value. Can this be done in a manageable way @DarkmatterVale?

**Comment by kgracey** [comment]
No changes to the disable RFID and close RFID blocks.

**Comment by DarkmatterVale** [comment]
Yes, this is pretty easy to do.

**Comment by CarsonGracey** [comment]
Tested and Verified.
