### ISSUE TITLE
Hide [account] > Public Profile Menu Until Friends and Projects Feature Created

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#383]
The __account > Public Profile__ menu presents a mostly blank page.
![image](https://cloud.githubusercontent.com/assets/1266318/16884585/15882e46-4a7f-11e6-9ad0-042ea012709f.png)

Please hide the Public Profile menu option until further development makes it useful.

**Comment by CarsonGracey** [comment]
It looks like the public profile menu option is still appearing in demo.

**Comment by DarkmatterVale** [comment]
PR?

**Comment by PropGit** [comment]
Done.  Merged into master already.
