### ISSUE TITLE
Make "Forgot..." and "...confirmed" Links Available on First Log In Screen

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#384]
The log in screen:
![image](https://cloud.githubusercontent.com/assets/1266318/16884689/9dbd9c74-4a7f-11e6-8469-b64bd005fd71.png)

forces the user to fail a log in attempt before being presented with the "Forgot your password?" and "Email not yet confirmed?" links.
![image](https://cloud.githubusercontent.com/assets/1266318/16884701/b4eac958-4a7f-11e6-9b1b-eded263e61a5.png)

Please make these links available on the initial log in screen as often the user knows ahead of time that he/she has forgotten the password or didn't receive the email confirmation.

**Comment by CarsonGracey** [comment]
Tested and Verified.

**Comment by PropGit** [comment]
I concur.

**Comment by DarkmatterVale** [comment]
Can we get a PR for this into master?

**Comment by PropGit** [comment]
Done 10/21 along with many other new features.
