### ISSUE TITLE
Comment block causes compile error

### ISSUE THREAD

**Issue by cbradyatinquire** [parallaxinc/BlocklyProp#396]
The screenshots below give an example of this bug in blocks & code:

<img width="175" alt="screen shot 2016-07-17 at 4 35 37 pm" src="https://cloud.githubusercontent.com/assets/769072/16903192/cf61d970-4c3c-11e6-9061-868cd2cf850b.png">

<img width="282" alt="screen shot 2016-07-17 at 4 36 04 pm" src="https://cloud.githubusercontent.com/assets/769072/16903193/d4158994-4c3c-11e6-8242-6567c954d9d7.png">

**Comment by michel-cf** [comment]
Having seen this block for the first time, this block is confusing to me. Can't we add some text in front of the input field to show this is a comment block?

**Comment by zfi** [comment]
+1
A first read of the blocks led me to believe that "hello there" was a function call, not a comment.

**Comment by DarkmatterVale** [comment]
What text would you like me to add?

**Comment by kgracey** [comment]
How about naming the block “Add Comment” and give it a big free-form text field on the right?

Ken Gracey
graceyken@gmail.com

**Comment by CarsonGracey** [comment]
Verified works, could use the change mentioned by @kgracey

**Comment by DarkmatterVale** [comment]
Gotcha.

**Comment by DarkmatterVale** [comment]
Fixed

**Comment by DarkmatterVale** [comment]
The issues have been resolved in the most recent PR to the demo branch. I believe the issue should be finally there...

**Comment by CarsonGracey** [comment]
Tested and Verified.
