### ISSUE TITLE
Compile empty project is marked as successful

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp#399]
Discovered that the compiler does not complain when asked to compile an empty project.  Under normal conditions, the compiler will complain about such things. Perhaps we should be nice and suggest that there is nothing to compile?

![screen shot 2016-07-18 at 12 29 17](https://cloud.githubusercontent.com/assets/8442260/16927689/7f9d1bdc-4ce3-11e6-9722-40aacb8342ba.png)

**Comment by michel-cf** [comment]
A C project without any blocks contains underlying code, and as such is fine to compile.
@cbradyatinquire @PropGit @kgracey @DarkmatterVale What do you all think?

```#include` "simpletools.h"

int main()
{

}
```

**Comment by kgracey** [comment]
Hmm. Maybe it compares the underlying code and then says "Nothing to compile".

**Comment by zfi** [comment]
I had that in mind when I encountered this situation. A gentle reminder that we have no code to work with. Does the app maintain a list or collection of blocks in the project? If the list is empty, there is no need to round-trip to the cloud compiler.

**Comment by PropGit** [comment]
What this issue comes down to is, there's no code to execute and there will be no visible effect from the Propeller if it were compiled and downloaded to the Propeller.

Still, I like the idea of a "Nothing to compile" message if the top-level code is devoid of any executable code; however, it may be nontrivial for the BlocklyProp app to determine this.

**Comment by michel-cf** [comment]
A basic version of this has now been implemented.

**Comment by PropGit** [comment]
Verified.

**Comment by DarkmatterVale** [comment]
Can we get a PR for this into master?

**Comment by DarkmatterVale** [comment]
bump

**Comment by PropGit** [comment]
@DarkmatterVale - Please see direct email'd question; we need a tip on how to do this without carrying tons of baggage.

**Comment by DarkmatterVale** [comment]
This was merged into master during the demo merge over the weekend so we can close this.
