### ISSUE TITLE
RGB OLED: Draw Rectangle/Round Rectangle

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#400]
This block will be able to draw and fill rectangles and round rectangles. The color list that will need to be included are referenced in #398 

![rectangle](https://cloud.githubusercontent.com/assets/20099916/16928509/e51e936a-4ce7-11e6-9eb3-23e5d9fe4ec7.PNG)

The first drop down will have the options rectangle, and round rectangle. It will also be able to create four different functions.

rectangle, checkbox: 

```C
oledc_fillRect(int x, int y, int w, int h, int color);
```

rectangle, no checkbox: 

```C
oledc_drawRect(int x, int y, int w, int h, int color);
```

round rectangle, checkbox: 

```C
oledc_fillRoundRect(int x, int y, int w, int h, (w+h)/20, int color);
```

round rectangle, no checkbox: 

```C
oledc_drawRoundRect(int x, int y, int w, int h, (w+h)/20, int color);
```

Here is the link to the block in block factory: https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#46yukp

**Comment by cbradyatinquire** [comment]
Are we going to have PARALLEL blocks for the (non-RGB) OLED?  These would be VERY cool to have.

**Comment by kgracey** [comment]
Do you mean a block that has two X,Y sets plus an offset for a parallel line of the same color?

**Comment by MatzElectronics** [comment]
Careful!

Rounded rectangles take one more parameter - the radius of the rounded corner.  One idea is to make it a fixed amount (maybe 10 or 20% of the average side length?).

**oledc_fillRoundRect(int x, int y, int w, int h, (w+h)/20, int color);**

**Comment by CarsonGracey** [comment]
Thanks @MatzElectronics, I fixed that in my code to be 20% fixed value.

**Comment by MatzElectronics** [comment]
Sounds good - won't hurt to experiment with it... anything from (w+h)/20 to (w+h)/60...whatever looks best.

**Comment by MatzElectronics** [comment]
@cbradyatinquire - We could, some of the drawing primitives exist in the badge code (pixel, line), but others don't, so those functions either need to be added or generated by the blockly code - that being said, the code is inside of this OLED library to do just that.

**Comment by cbradyatinquire** [comment]
@kgracey, no i meant parallel functionality in monochrome for the badge OLED
@MatzElectronics - cool: thanks

**Comment by kgracey** [comment]
Aha, yes! We need to meet up with you about the HEB so we can contribute to those blocks as well as the others. It would be helpful to know where we’ve been, where we are, and where we need to go. 

I was thinking that you, Roxy, Carson and I could meet up on Wednesday - would that work?

Ken

**Comment by zfi** [comment]
Coded and verified locally.

**Comment by CarsonGracey** [comment]
Tested and Verified.
