### ISSUE TITLE
RGB OLED: Draw Triangle

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#401]
This block will be able to draw and fill triangles. The color list that will need to be included are referenced in #398

![triangle](https://cloud.githubusercontent.com/assets/20099916/16929070/cf861cb4-4cea-11e6-91d2-72d9249cbe59.PNG)

The user with be able to input an x and y value for each of the three points. There is also a checkbox for a total of two functions.

triangle, checkbox:

```C
oledc_fillTriangle(int x0, int y0, int x1, int y1, int x2, int y2, int color);
```

triangle, no checkbox:

```C
oledc_drawTriangle(int x0, int y0, int x1, int y1, int x2, int y2, int color);
```

Here is a link to the block in block factory: https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#k7yi3z

**Comment by zfi** [comment]
This block is really wide relative to the other blocks. I had to widen out my browser to see the tail end of it. 

![2016-07-29_08-51-51](https://cloud.githubusercontent.com/assets/8442260/17254550/22bc88e6-556a-11e6-82a4-72de3a01f4bc.png)

**Comment by PropGit** [comment]
@CarsonGracey and @zfi - To tighten this up, maybe this will work well?
![image](https://cloud.githubusercontent.com/assets/1266318/17261689/f9c682da-558b-11e6-98b6-bf0c5ee09326.png)

or switch to something like this?
![image](https://cloud.githubusercontent.com/assets/1266318/17261620/952b1750-558b-11e6-9a49-bd0345425441.png)

NOTE: To shrink vertical height, I'd prefer individual points' x and y coordinates to be inline, but couldn't figure out how to make that in Block Factory; may not be possible?

**Comment by CarsonGracey** [comment]
@PropGit That looks better and I agree that each (x, y) set should be inline. It is not possible to do with Block Factory but it is something that can be manually edited in the JavaScript code.

**Comment by PropGit** [comment]
@CarsonGracey - That's great... it'd shrink the tall version from 7 lines to 4.

Please indicate which one @zfi should try implementing... the single-line, slightly thinner block, or a shorter version of the tall, thinner block.

**Comment by PropGit** [comment]
@zfi - I don't know if this link will persist, but here's [the single-line version](https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#8jkn2c) I built (still in need of underlying work):

**Comment by zfi** [comment]
You guys are getting a horizontal block. I can come back to this later or someone else can rearrange the code if it's that important.

**Comment by kgracey** [comment]
I concur that the in-line block looks best - very tidy, clean, understandable and not that long.

**Comment by zfi** [comment]
The block geometry has been updated. I omitted the "(x,y) points" text but I can add it in if needed.

**Comment by zfi** [comment]
Please reference PR #504.

**Comment by CarsonGracey** [comment]
Tested and Verified.
