### ISSUE TITLE
RGB OLED: Draw Pixel

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#402]
This block will be able to draw a single pixel. The color list that will need to be included are referenced in #398

![pixel](https://cloud.githubusercontent.com/assets/20099916/16929500/e8030b24-4cec-11e6-81f8-50ffcc8dc345.PNG)

The two inputs will be the x and y coordinates at which the pixel will be drawn and its color. It will generate the code:

```C
oledc_drawPixel(int x, int y, int color);
```

Here is the link to the block in block factory: https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#jppgaq

**Comment by zfi** [comment]
Code for this issue has been submitted as PR #453. This code is now using the embedded Blockly color picker.

**Comment by CarsonGracey** [comment]
Tested and Verified.
