### ISSUE TITLE
RGB OLED: Draw Line

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#403]
This block will be able to draw a line. The color list that will need to be included are referenced in #398

![line](https://cloud.githubusercontent.com/assets/20099916/16929717/d6bda634-4ced-11e6-809d-c0be7e4a5c6f.PNG)

The inputs will be the first and second points of the line along with the color. It will generate the code:

```C
oledc_drawLine(int x0, int y0, int x1, int y1, int color);
```

Here is the link to the block in block factory: https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#wxdr96

**Comment by DarkmatterVale** [comment]
Are the colors numbered 0 for WHITE, 1 for PINK, etc?

**Comment by CarsonGracey** [comment]
Tested and Verified.
