### ISSUE TITLE
RGB OLED: Set Text Size

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#407]
Sets the size of the font to be used. Range is from 1 to 3. Size (1) is 5x7 (6x8 spacing) pixels, size (2) is 11x15 (12x16 spacing) pixels and size (3) is 15x23 (16x24 spacing) pixels.

![text size](https://cloud.githubusercontent.com/assets/20099916/16932163/83d073e6-4cf9-11e6-89de-997e3f04973b.PNG)

The produced code will be:
```C
oledc_setTextSize(char s);
```

Here is the link to the block in block factory: https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#6gx399

**Comment by zfi** [comment]
Update code in the block to use the new font size constants in the oledc header file, referenced in the SimpleIDE Library PR #31 - Update font size constant names

**Comment by CarsonGracey** [comment]
The updated block is Tested and Verified.
