### ISSUE TITLE
Graphic for Blockly landing page

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#408]
@michel-cf and others - could we replace the wall of text on the Blockly landing page with a graphic? Students don't read the text and the Learn.parallax.com site will have written tutorials. We could start with this and change/improve as launch is closer. 
![blocklyprop071916](https://cloud.githubusercontent.com/assets/9534148/16972095/ace8d9dc-4ddd-11e6-9d21-90256b205e90.png)
![blocklyprop-screen](https://cloud.githubusercontent.com/assets/9534148/16972097/b01dd1f2-4ddd-11e6-9896-93de2905ce77.png)

**Comment by zfi** [comment]
Can the graphic treatment be minimized so as to not impact the load time for the home page? We should keep the load time to about 100ms, 200ms max.

**Comment by kgracey** [comment]
Sure - what kind of file size would be appropriate?

**Comment by kgracey** [comment]
Checked with JenJ and she says she's already optimized this graphic, so we can use it. Valid concerns; let's see how it works in practice.

**Comment by zfi** [comment]
The home page load time is holding at about .8 seconds when tested from endpoints using DSL (slow) to fiber. Go ahead and drop in the graphics and I will retest.

**Comment by wstodghill** [comment]
I think this looks great and it loads instantly, but I do use a cable modem.

**Comment by DarkmatterVale** [comment]
I am also getting a super fast load.

**Comment by kgracey** [comment]
Done for now.
