### ISSUE TITLE
S3 Sound Block

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#409]
@dcarrier-parallax, 
I talked with @kgracey about this block and we came up with a few changes to make it easier to use. 

![sound](https://cloud.githubusercontent.com/assets/20099916/16993304/9b2af02a-4e57-11e6-88d3-8db862185201.PNG)

The first thing would be to set the range of the sound to ~2,000 Hz, because anything higher than this doesn't really increase the pitch, the sound just because more distorted coming out of the S3 speaker. 

Next, we didn't really understand why there was an option for playing two different tones at once so for the sake of the user it would be better to replace the second tone option with volume where a value or variable could be plugged in, leaving the block with:

Play a tone of (1 to 2,000) Hz
Set the volume (1 to 10) 
For a duration of (1 to 8,000) ms

**Comment by dcarrier-parallax** [comment]
Because the blocks accepts variables, I cannot limit the input range, but I can clip it at 2,000 Hz, so that anything higher will play a 2,000 Hz.

Polyphony is part of the educational materials we use, (See: Chapter 8: Frequency and Sound on page 245 of What's a Microcontroller) but I could also make a monotone block, to take up less space.

Volume is available in the Scribbler object, but I have not tested it yet.  I will test it, then add it, if it appears to be functional.  I will likely add it as a separate block, to reduce the amount of space it takes in a program.

**Comment by kgracey** [comment]
Understood. I’m aware of polyphony and mixed frequencies, but this is a first robot experience so we need to keep it simple. All three people who’ve initially worked with the dual-frequency blocks found them unnecessarily confusing. In keeping with the idea that the tool explains itself and that the target audience is familiar with single frequencies from their music courses (i.e. my trumpet range is "200 Hz to 1200 Hz from the tuner we use”) one frequency is best. This way they can relate the inputs in the block to something they have a chance of easily recognizing. 

We could have a dual-frequency block, too. Once you get the volume part working, could you make a two-frequency block as well? This gives us an option. While it’s technically the same as putting zero (0) in one block with both frequencies, the difference to a student is significant.

**Comment by wstodghill** [comment]
Volume set would be a great help in a class setting (and in the evening when I am experimenting at home when everyone is sleeping!) . As David mentioned it is available or was in the S2 Spin Object (which is the one I know). Is there a new S3 spin object somewhere for me to take a look at? I would love to understand better how to contribute BlocklyProp development for the S3.

**Comment by kgracey** [comment]
@dcarrier-parallax agreed with Whit+ and countless others who want volume control. Please provide access to volume for us. @wstodghill I'll send you the S2 code base via e-mail.

**Comment by wstodghill** [comment]
@kgracey I assume you mean S3 code base.

**Comment by kgracey** [comment]
I do, but I believe we haven’t actually renamed it “S3” at this point.

**Comment by wstodghill** [comment]
@kgracey understood.

**Comment by CarsonGracey** [comment]
Tested and Verified.

**Comment by DarkmatterVale** [comment]
Can we get a PR into master so we can close this issue?

**Comment by DarkmatterVale** [comment]
Demo merge this weekend pulled this into the master.
