### ISSUE TITLE
Serial Terminal NaN

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#420]
After reloading a program which displays text onto serial terminal the serial terminal would not open. Instead I would get a message that said "NaN" on a white background.

**Comment by PropGit** [comment]
@CarsonGracey - Can you duplication this now?  Is it possible it was due to a problem as I reported in Issue #509?

**Comment by MatzElectronics** [comment]
Closing - It appears to be a duplicate to #509
