### ISSUE TITLE
S3 blocks: reorganize the menu

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#421]
@dcarrier-parallax please rearrange the S3 block menus as follows:

Main menu (all first-order, visible upon entry)

Control
Operators
Values
Variables
Pin States
Motors (move the "set left" and "set right" motor blocks from Scribbler 3 / Actions to here)
LEDs (move the "set the" LED color from Scribbler 3 / Actions to here)
Sound (move the "play a tone" blocks from Scribbler 3 / Actions to here)
Sensors (move all of these fro Scribbler 3 / Actions to here)
  Line Sensors
  Obstacle Present
  Ambient Light
  Wheels Currently Stalled
  Reset Button

The "Untested blocks" is okay where it is for now.

**Comment by dcarrier-parallax** [comment]
Those menu items are mostly generic Spin blocks.  If the user selects the "S3 Robot" as the board type, the menu will contain all of the generic Spin blocks, plus the blocks unique to the Scribbler 3.

I have not messed with the board type filtering yet, so you may see blocks that do not match the board type, but that will be corrected before we release the Scribbler 3.

As for the menu, we need to first define the menu for generic Scribbler blocks, then add in the menu items for the Scribbler 3.  The Scribbler 3 items can be in the root of the menu, but considering all of the features in the Scribbler object, we have the potential to create many more blocks, so it would be good to categorize the current blocks, so we do not need to reorganize the existing blocks as we add new ones.

**Comment by kgracey** [comment]
Right, gotcha on how the blocks are presented based on the choice of board (or robot, in this case). 

As this is certainly a work in motion I do expect that future revisions will occur to the block structure heiarchy. At present, we are creating tutorials that refer to specific locations of blocks within the menu so we need them to settle into place so we can continue working. The S3s arrive third week of August and we have only two weeks for tutorials. For some reason, my formatting was removed in the first issue above so you may not have understood my request. As I intended to make it, here's a more verbose explanation which allows the addition of more blocks (probably in the Motors and Sensors categories):

Control
Operators
Values
Variables
Pin States
Motors (move the "set left" and "set right" motor blocks from Scribbler 3 / Actions to here)
LEDs (move the "set the" LED color from Scribbler 3 / Actions to here)
Sound (move the "play a tone" blocks from Scribbler 3 / Actions to here)
Sensors (move all of these fro Scribbler 3 / Actions to here)
> Line Sensors
> Obstacle Present
> Ambient Light
> Wheels Currently Stalled
> Reset Button

Let me know if this clarifies the request @dcarrier-parallax.

**Comment by wstodghill** [comment]
I have not seen it yet, but will there be a comment block. I know that this might not be used by students, but it would be great for example programs and teaching. 

Will the ability to disable a block and collapse block be available in all the boards and at least the S3 uses? Again, I can see great benefit for these functions for education purposes - we just need to teach folks how to use them!

**Comment by wstodghill** [comment]
Per my comment above - Just found this on @kgracey's Color identifier and transmitter, community project over at the Demo site. 

Here is a clip.
![describe clip](https://cloud.githubusercontent.com/assets/8891440/17081075/b2c39728-510e-11e6-8fc4-3164a68cc10f.PNG)
How is this done. I have not found that feature in any of the choices. It is exactly what I was looking for... It could be used as a point to a specific S3 Spin Object method that is related to the block... This would be really handy for teaching.

**Comment by wstodghill** [comment]
I'd like to say a word about a sub-set of the S3 blocks that has similar functionality to the old GUI program maker (plus a bit - like the volume control and more) This would be for new users and "seem" less complex. The full set of blocks could be used by selecting the advances user option. This would grow to blockly access to all the methods (or most all) in the S3 Spin Object. S2 users would have other limits on access. IN  the novice subset advanced features could be "grayed" out as an enticement and preview of things to come!

Also, when we are finally up. Will users be able to save to their own computer - will this be in Spin?. When they open a program, I assume it will open the browser and show blockly code. Will there be a way to move between blockly and Spin - similar how the old GUI functioned?

**Comment by kgracey** [comment]
This issue is outdated by other changes that have been made to the menu.
