### ISSUE TITLE
RGB OLED: Clear Screen

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#423]
This will be the next OLED block request the will clear the entire screen by drawing a black rectangle.

![clear screen](https://cloud.githubusercontent.com/assets/20099916/17068351/4452d7a4-5005-11e6-8bac-da4ff58df2b2.PNG)

Generated code:

```C
oledc_clear(0, 0, oledc_getWidth(), oledc_getHeight() );
```

Link to block in block factory: https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#sj5cte

**Comment by MatzElectronics** [comment]
Sure, it should look like this:

oledc_clear( 0, 0, oledc_getWidth(), oledc_getHeight() );

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by CarsonGracey** [comment]
I'll edit that in, thanks!

**Comment by zfi** [comment]
Issued a patch in PR 423 for this issue. It's ready for Demo.

**Comment by CarsonGracey** [comment]
Tested and Verified.
