### ISSUE TITLE
Lost BlocklyProp Link

### ISSUE THREAD

**Issue by CarolHazlett** [parallaxinc/BlocklyProp#425]
I can no longer access BlocklyProp. I was getting to it by launching BlocklyPropClient, clicking on "connect" and when server started, clicking on launch web browser. Now all I get is a blank screen. What am I doing wrong now?

**Comment by DarkmatterVale** [comment]
Hmmmm...I'm also getting a blank page for the main BlocklyProp site. It appears to be an unrelated issue. In the meantime, here is the link to BlocklyProp's demo site which is still up and running http://demo.blockly.parallax.com/blockly/ and the

**Comment by michel-cf** [comment]
Duplicate: #426
