### ISSUE TITLE
Main BlocklyProp website is down

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/BlocklyProp#426]
Is anyone else getting a blank page when attempting to go to http://blockly.parallax.com ?

**Comment by cbradyatinquire** [comment]
Yes (8:45 AM Central 7/23)

**Comment by wstodghill** [comment]
Still down here (9:40 p.m. Central 7/23).

**Comment by zfi** [comment]
The site is back on-line. There is an occasional memory event that is causing the heap to become exhausted. I will open that as a separate issue.
