### ISSUE TITLE
Generated code viewer

### ISSUE THREAD

**Issue by michel-cf** [parallaxinc/BlocklyProp#43]
Add highlighting to generated code viewer. (Making sure to maintaining read only mode)

Options:
* highlight.js
* Ace editor

Ace editor has an online system to create custom highlights. As we will have to create a custom highlight for Spin this might be the best option.

This has been discussed on the Parallax Propeller Forum but I didn't find anyone that actually made the spin highlighter for any of these systems.

**Comment by DarkmatterVale** [comment]
Interesting idea. Would this be used to highlight code just like in PropellerIDE ( functions are a color, variables another, etc )?

**Comment by michel-cf** [comment]
Yes, I'd like to get as close to it as possible. Reading the generated code with highlighting makes it more easy to read. And it will also ease the transition to the code editor for when users want to 'grow' from BlocklyProp to the PropellerIDE.

I think the normal C highlighter should suffice for the Prop-C version.

**Comment by DarkmatterVale** [comment]
Another good one might be Prismjs.

I have been messing around with this, and I it works pretty well, but I cannot get my code to display on screen. For some reason, I cannot use anything but a <textarea></textarea> block to hold the C code. If I use anything else, the code just won't show up. Do you have any ideas as to why this is happening?

**Comment by DarkmatterVale** [comment]
After some work, I am making some progress. I can display the converted code in the text area, but as stated above, I am unable to display anything if I do not use a text area. Michel, do you have any ideas as to why I might be having this issue?

I will attach a picture to this comment soon....

**Comment by DarkmatterVale** [comment]
This has been completed and is working very well.
