### ISSUE TITLE
User-defined functions with inputs don't compile (Spin project).

### ISSUE THREAD

**Issue by drpiccioni** [parallaxinc/BlocklyProp#432]
When I try to compile drpFunctionTesting (which includes three user-defined functions), I get:

**Propeller Spin/PASM Compiler 'OpenSpin' (c)2012-2014 Parallax Inc. DBA Parallax Semiconductor.
Version 1.00.71 Compiled on Nov 15 2014 08:45:10
Compiling...
/tmp/tmpjbCqVk/single.spin
|-Block_Wrapper.spin
  |-scribbler.spin
/tmp/tmpjbCqVk/single.spin(6:26) : error : Expected BYTE, WORD, or LONG
Line:
  {{$var_type_blink_us}} blink_us
Offending Item: blink_us**

If I alter my project to call only the functions that don't have arguments (TURN LEDs RED and TURN LEDs OFF), the project is compiled and even runs on my S2.  I have only gotten the compile error when the project calls the function with an argument (MAYBE BLINK).  I get the same message if the called function has numerical or a Boolean argument.

**Comment by kgracey** [comment]
Thanks Richard - we’re aware of this as the motor blocks are in a state of transition until Wednesday. Thanks for reporting (and continue to do so, especially from Wednesday on).

**Comment by michel-cf** [comment]
I believe @dcarrier-parallax removed the possibility to use arguments with functions in spin

**Comment by dcarrier-parallax** [comment]
I removed the non-functional argument support in the 'procedures.js' file, but this error is in the 'spin.js' file, on line 134.

**Comment by zfi** [comment]
Is it OK to remove this block? 

![2016-08-16_14-58-07](https://cloud.githubusercontent.com/assets/8442260/17717285/003f62f0-63c2-11e6-9ce3-b5e40754afda.png)

**Comment by kgracey** [comment]
Yes

**Comment by zfi** [comment]
The 'if value return value' block has been removed. Has the original issue been addressed by these changes?

**Comment by PropGit** [comment]
Fixed by @dcarrier-parallax, noted above, and @zfi in an unknown commit.
