### ISSUE TITLE
Save-As?

### ISSUE THREAD

**Issue by drpiccioni** [parallaxinc/BlocklyProp#433]
Any hope for a Save-As capability?  My testing efficiency would be a lot higher if didn't have to start each new project from scratch.  Thanks!

**Comment by kgracey** [comment]
Yes, our team is monitoring the GitHub requests and will sort/prioritize feature requests carefully as we move forward. Thanks for making this request. KG

**Comment by michel-cf** [comment]
You can always clone a project (yours, or someone else's) from the project view

**Comment by PropGit** [comment]
Since this has been a request, in passing, multiple time, we should seriously consider an option to "Save As" right from the Blockly editor as that's where people are often finding the need to do so.

**Comment by wstodghill** [comment]
"Save As" would me more what folks are used to. I did discover the Clone option, and made it work but I felt I was experimenting with something I did not really understand and not sure what would actually happen. "Save As" is used in so many other places that folks will "get it" and how it works... Thanks!

**Comment by kgracey** [comment]
Agreed - Jeff is keeping this on our internal Feature List so it can be factored into the UI design at the right time.

**Comment by wstodghill** [comment]
Great! Will try it out and let you know. Thanks for your hard work on this!

**Comment by michel-cf** [comment]
Can this be closed?

**Comment by DarkmatterVale** [comment]
No this cannot be closed because a PR needs to be sent to the master branch

**Comment by michel-cf** [comment]
Why are you struggling all the time with that master branch. Why don't wait until we get a tested version and then push everything to master at once? (If needed with an acceptance stage in between)
Then you can close all the tickets when they are validated in demo.
This way of merging everything individually (, and out of order) just introduces more chance for merge issues.

**Comment by wstodghill** [comment]
Michel,

So sorry - it is just my ignorance of how GitHub works - I will try to find a better way of communicating - I just don't know how. Looking to help - not mess things up!

Will try to get a better understanding of how I should use GitHub. Sorry again.

Whit+

The Rev'd T. Whitfield Stodghill, III
www.saintalbansepiscopal.org

**Comment by DarkmatterVale** [comment]
@wstodghill He was talking to me not you.

@michel-cf For a number of reasons including:

1. Messed up history
2. Features/commits we don't want on master on demo (if we merge demo into master then this cannot be avoided)
3. If the system is used *properly*, then it is much faster to get features to production quickly

**Comment by PropGit** [comment]
@DarkmatterVale and @michel-cf - Please continue this side discussion in Issue #549.

**Comment by drpiccioni** [comment]
Just so you know: In demo, Save-As creates a copy of the current project with the same name as the current project, even though a new name is entered.

**Comment by PropGit** [comment]
@michel-cf - This feature is getting closer, but still has unexpected and undesired behavior.

__Save As__
- appears to duplicate the last-saved version of the original,
- doesn't update the name in the database, and
- appears to revert the editor back to the last-saved version of the original (although it's actually now the new Saved-As version with the old code and the old name)

__To test this__
- Open an existing project
- Make an obvious change
- _Do not_ click __Save__!
- Click __Save As__ and modify the title, then click OK
- Note how the page refreshes, the Project Title remains the same (old title) and the obvious change you made is now gone (so sad); the project looks like the original
- Make a _very different_ obvious change
- Click Save
- Go to My Projects
- Notice how there are two exactly-named projects
  - The first is the untouched original
  - The second is the Saved-As version, without the new name, without the obvious change, and with the very different obvious change.

**Comment by PropGit** [comment]
Tested. Verified correct.

**Comment by wstodghill** [comment]
Thanks for fixing this! Seems to work perfectly. I also made the programs that were inaccessible available and I could delete them again! Great work!

**Comment by PropGit** [comment]
@wstodghill - You're welcome.  Yes, thank you @michel-cf!  This feature seems to work great now.
