### ISSUE TITLE
demo.blockly.parallax.com is down

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#435]
As the title states http://demo.blockly.parallax.com/ has been down since 12:00 PM PST. I don't believe anything is being merged at the moment and google chrome (Version 51.0.2704.103 m) is "Waiting for available socket..."

EDIT: Even after flushing all sockets in chrome://net-internals/#sockets the problem persists.

**Comment by zfi** [comment]
Restarted the Tomcat service after harvesting log files.

**Comment by CarsonGracey** [comment]
Looks like that fixed it, thanks!

**Comment by CarsonGracey** [comment]
@zfi, the website is loading but projects are taking between 1-5 minutes to load or aren't loading at all.

**Comment by zfi** [comment]
The errors I am finding in the log files indicate that we may have insufficient system memory on this test server. I relaunched the site on a larger server. Let's see if a larger memory pool helps calm these issues.

**Comment by zfi** [comment]
Twenty four hours of operation and no system level issues. There was a crash page reported earlier but it was an issue with the DB interface code. I think the site is stable again.

**Comment by CarsonGracey** [comment]
I haven't had any problems for two days so we can close this issue for the time being.
