### ISSUE TITLE
RFID Block

### ISSUE THREAD

**Issue by Wierdowl** [parallaxinc/BlocklyProp#436]
On the RFID Enable Block:
![screen shot 2016-07-25 at 2 39 40 pm](https://cloud.githubusercontent.com/assets/20117212/17118532/cb1974ba-5275-11e6-888a-d81430b41691.png)
Instead of saying "in" it should say "enable" and instead of "out"  it should say "sout" because thats how its put on the RFID reader.

Also In the code currently made in blockly:

`rfid = rfid_open(rfidEn, rfidSout);`

there is an error where the "rfidEn" and "rfidSout" Are switched which causes it not to enable, the code should look like this:

`rfid = rfid_open(rfidSout, rfidEn);`

And that started to work for me.-Blake

**Comment by PropGit** [comment]
Verified fixed.

**Comment by DarkmatterVale** [comment]
@zfi Can you please send a PR to the master branch with this fix?

**Comment by zfi** [comment]
RFID spec discussed here:
http://www.devx.com/enterprise/Article/32251
