### ISSUE TITLE
BlocklyProp Beta Demo Crash when Deleting Program

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#439]
I tried to delete a program today and BlocklyProp Beta Demo crashed.

On Save Delete Clone - I pressed Delete
A window asked me to Confirm - I did
BlocklyProp crashed - here is a partial (not all the info) screen capture
![blocklypropdelete](https://cloud.githubusercontent.com/assets/8891440/17153029/26d8be76-5340-11e6-9170-e2cbb6c36aca.PNG)

**Comment by PropGit** [comment]
@wstodghill - I just tried this.  It worked fine for me, so maybe I'm doing something different (such as deleting a mostly blank project as opposed to a bigger one, or maybe deleting one that was from a different account).  Can you give us more detail about the exact scenario?

**Comment by michel-cf** [comment]
The exception shown is quite clear: the project can't be deleted because it is shared using a sharing url.
I'll have to check, when deleting a project, if it is shared. And if so, first delete the share-url.

**Comment by PropGit** [comment]
@michel-cf - You must be joking about the clarity. ;-P

I'm glad you figured it out.

We'd prefer that the operation be:

1. User clicks Delete button
2. System checks if the project is shared
3. If project _is not shared_, prompt user with "Confirm delete - Are you sure you want to delete this project?"  (it does this already)
4. If project _is shared_. prompt user with "Confirm shared project delete - This project is shared via a sharing url.  Deleting it will break that shared link.  Are you sure you want to delete this shared project?"

**Comment by wstodghill** [comment]
@PropGit said "michel-cf -You must be joking about the clarity. ;-P I'm glad you figured it out."

I agree! Thanks - I did see the note about it being shared (but did not really understand what it meant) The rest of the page was way past me... ;-) Even though was there to an ordinary user - I thought it was a crash, because it closed BlocklyProp completely.

Glad to understand. I will keep trying and try to delete the share (not sure how that works either). I will play with it - Just wanted to make sure it was not a problem that was more critical. Thanks all!

**Comment by wstodghill** [comment]
Another comment about this...When moving around BlocklyProp Beta Demo - My natural tendency was to use the back arrow on my browser (I am mostly using Google Chrome. Occasionally, I encountered a problem. 

I have good luck (meaning no problems) when I use the BACK button on the Project Details page. Also using the the **Beta** BlocklyProp "Home",  "Community projects," "My projects," or "New project buttons on the toolbar to navigate. 

Is that a more accepted way to navigate sites? Is the problem I experienced others (like me) might also navigate using browser arrows too (especially without instruction)! 

Not a complaint really - just an observation for those of you more knowledgeable than me!

**Comment by wstodghill** [comment]
@kgracey - Might this be closed or are some of these comments still of value?

**Comment by michel-cf** [comment]
Still needs to be fixed

**Comment by wstodghill** [comment]
@michel-cf - Thanks!

**Comment by DarkmatterVale** [comment]
This needs to be fixed because this will confuse users when attempting to delete a shared project.

**Comment by PropGit** [comment]
Verified fixed!
