### ISSUE TITLE
S3 Now works

### ISSUE THREAD

**Issue by CarolHazlett** [parallaxinc/BlocklyProp#440]
Using 2 programs Whit wrote my S3 is now working fine with BlocklyProp demo version. I did do a driver update to it also.

**Comment by wstodghill** [comment]
Yay! I have lots of shared programs on the BlocklyProp Beta Demo - check them out some of the first ones lost some variable info when updated - some are works in progress, some finished on the S2 - checking on S3 and some are PASSED! (meaning I have now checked them on the S3 and they work fine) Notes are in the program descriptions. Have fun - please give them a try and let me know how they work further north!
