### ISSUE TITLE
Delay Start Button

### ISSUE THREAD

**Issue by CarolHazlett** [parallaxinc/BlocklyProp#444]
One of the features on the old GUI which I used a lot was the ability to add a function at the beginning of my program that kept the program from running until I pressed the reset button on the robot. I have tried to set that up with BlocklyProp but do not know enough about it to figure it out. Can anybody point me in the right direction?

**Comment by wstodghill** [comment]
Carol - take a look at this BlocklyProp code at the demo site. It is named **Reset Button Demo 1** Here is a link - http://demo.blockly.parallax.com/blockly/my/projects.jsp#126

It is a simple BlocklyProp example of the S3 monitoring the number of button presses at the last reset.
Based on the results the S3 light an corresponding number of LEDs.

It is interesting to watch the code run on the S3 - as you press the reset button (from the Scribbler Object - Button presses are counted (1-3, green (Right to Left), at 4-6 (R to L green goes to red), 7-8 (L to R red goes to off). That is the Object. 

The code above reads button press 1, 2, 3 and lights 1, 2, or 3 of the indicator LEDs in red (left to right). 

Let me know if it helps....

**Comment by kgracey** [comment]
@CarolHazlett and @wstodghill do you consider this closed?

**Comment by wstodghill** [comment]
@kgracey - I do! I have working code up on BlocklyProp! ;-)
