### ISSUE TITLE
C, rc_time(), block/s

### ISSUE THREAD

**Issue by mrodriguez-parallax** [parallaxinc/BlocklyProp#446]
This block of code generates wrong C code.

![image](https://cloud.githubusercontent.com/assets/20686764/17194330/581116ce-540c-11e6-8744-02f68d066194.png)

Here is the C code generated in the background.

```
/* SERIAL_TERMINAL USED */
#include "simpletools.h"

int RF_SENSOR;



int main()
{

    while (1)
    {
        pause(500);
        print("(rc_time(7, 0);) = % d\ n ",(rc_time(7, 0);
    ));
}

}

```

This is the error the compiler outputs when these blocks are used to get rc_time.

![image](https://cloud.githubusercontent.com/assets/20686764/17194406/ae9c72f4-540c-11e6-990d-a17680c9de66.png)

Here's how the code should be written.

```
/* SERIAL_TERMINAL USED */
#include "simpletools.h"


int main()
{

    while (1)
    {
        pause(500);
        print("rc_time(7, 0) = %d \n",(rc_time(7, 0)));
    }

}
```

This is the output from the corrected code in Simple IDE.

![image](https://cloud.githubusercontent.com/assets/20686764/17194556/6d67f320-540d-11e6-87e4-c9c589b8a6b2.png)

**Comment by kgracey** [comment]
@zfi I think that Miguel gave you all you need to make the RCTime output correct.

**Comment by DarkmatterVale** [comment]
This needs to be verified then a PR needs to be sent into the master branch

**Comment by kgracey** [comment]
Tested and verified.
