### ISSUE TITLE
Repeated definitions and setup code in propc files

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp#448]
It appears that if a group of blocks in a source file require a header file or some specific initialization it has to be done in each block definition within the source file. Would it make more sense to have one or more hook functions to register definitions and setups rather than forcing the duplication of code in each block? 

For example, in BlocklyProp/src/main/webapp/cdn/blockly/generators/propc/oledc.jsp, the following stub has to be included into each block defined.

    // We need the header file to compile.
    Blockly.propc.definitions_["oledtools"] = '#include "oledc.h"';  
    // Init the library before we call into the library
    Blockly.propc.setups_["oled"] = 'oledc_init(' + din_pin + ', ' + clk_pin + ', ' + cs_pin + ', ' + dc_pin + ', ' + res_pin + ', 2);';

**Comment by PropGit** [comment]
Absolutely!  Having all that duplicated code is begging for maintenance problems.  Thanks @zfi.

**Comment by DarkmatterVale** [comment]
I disagree with this change. I have talked with Michel about this previously and we decided that this change would cause more harm than good. The proposed changes create a problem for files such as ```sensors.js``` where multiple different "groupings" of blocks are included within the file and many different includes & setups are needed. Therefore, you would not be able to use this in files with multiple different "groups" of blocks. Further, adding this would add another level of complexity for developers when they are attempting to get up-to-speed on BlocklyProp (although it isn't very bad in of itself, lots of little things like this make developing more difficult).

**Comment by PropGit** [comment]
@DarkmatterVale - We certainly don't want to cause more harm than good, but I don't understand how we can't overcome even the multiple groupings of blocks situation in a way that eliminates duplicated initialization code.  The thing we're trying to avoid, of course, is a future need to change some initialization that really applies to a myriad of blocks spread out across files, as inevitably something will get forgotten.

Is there a solution we can devise that will support good programming methods as well as these scenarios you mentioned?  With a call to an initialization function in-place of duplicate initialization code, I still think a developer would simply use it as a template (like he would the initialization code itself) for future work (and can check out the underlying code for that function), so I don't think it adds any significant degree of difficulty to newcomers.

**Comment by DarkmatterVale** [comment]
Because blocks have no relationship to other blocks (within the code that I write), I do not believe that there is a solution to this within the block source files. The only solution I can think of is to add a HTML tag that is applied in framec.jsp within categories. This tag will add includes to the code if any of the blocks are used. I'm not sure if this is feasible, however, so @michel-cf will have to chime in here.

**Comment by DarkmatterVale** [comment]
Does anyone have any more thoughts to add or can we close this for now?

**Comment by zfi** [comment]
The underlying system appears to handle duplicate header file includes. Developers need to understand that each block that requires an include file, they need to register that file within the block implementation.


With that in mind, let's close the issue.
