### ISSUE TITLE
Light sensors do not work

### ISSUE THREAD

**Issue by RoxyH** [parallaxinc/BlocklyProp#449]
Here is the Blockly code I used. 
![capture](https://cloud.githubusercontent.com/assets/20117435/17227914/8f60ca7a-54c5-11e6-9073-03e55a4e3e20.PNG)
When I uploaded it, the numbers in the serial terminal did not change with different levels of light, as it should have. This is what was on the serial terminal. 
![capture 3](https://cloud.githubusercontent.com/assets/20117435/17228004/04ffd910-54c6-11e6-853b-e03fb90f84e9.PNG)

**Comment by kgracey** [comment]
@dcarrier-parallax this one is really odd - for some reason the light values don't change in the console. I verified it too and couldn't figure out why. We are wondering if it is something underneath in the wrapper somewhere. KG

**Comment by wstodghill** [comment]
@RoxyH  - Did anyone try it using the old Desktop Parallax Serial Terminal? Is this code saved to share? If I so, I will give it a try. If not, I will screen capture it and program it in myself. Gonna grab it - just in case! Let me know!

**Comment by wstodghill** [comment]
Works for me - See - **Test Issue #449 for RoxyH** Code is [http://demo.blockly.parallax.com/blockly/my/projects.jsp#141](url).

I did add a delay a the start, a "Working" message, and another delay - other than that the BlocklyProp Code is identical! Held the S3 under my desk lamp and rotated it around getting high 90s to 20s.

![449 start](https://cloud.githubusercontent.com/assets/8891440/17240315/4f215568-5530-11e6-8c3f-9e336bcf7e1d.PNG)

**Comment by wstodghill** [comment]
@RoxyH - Did it work for you?

**Comment by CarsonGracey** [comment]
I tested your project @wstodghill and it seemed to work just fine. I also created a new project that is slightly different just to make sure it works: http://demo.blockly.parallax.com/blockly/editor/blocklyspin.jsp?project=96 
I believe this issue is ready to be closed now.

**Comment by RoxyH** [comment]
I'll test it later today, I haven't had the chance yet.

**Comment by RoxyH** [comment]
Just tested it and it worked.
