### ISSUE TITLE
Autoconverter C code to Blocks

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/BlocklyProp#45]
This will be the same as the Spin code to blocks auto converter, just for C program files.

**Comment by DarkmatterVale** [comment]
I have created a tool in Python which does this.

@PropGit Is the ability to let the user create custom blocks something we want to have in the final version?

**Comment by PropGit** [comment]
@DarkmatterVale - Do we have one for Spin code to blocks?  If so, I wasn't aware of that.

We haven't discussed the possibility of this and I need to know more details before being sure.  One thing we don't want to do is allow a user to make a block which will fail to compile.

**Comment by DarkmatterVale** [comment]
My project supports converting both Spin and C blocks. You can view it on Github at https://github.com/DarkmatterVale/Blockly-Blocks-Converter

I agree; we will need to be careful how this is implemented. I think this should be something that we discuss later on after getting an initial version released.

**Comment by PropGit** [comment]
@DarkmatterVale - Thanks.  Yes, I agree; let's discuss it at a later time.
