### ISSUE TITLE
Move motor block does not work

### ISSUE THREAD

**Issue by RoxyH** [parallaxinc/BlocklyProp#451]
Similarly to the drive block problem, the code compiles and uploads but the robot does not move. 
![capture 5](https://cloud.githubusercontent.com/assets/20117435/17229213/8291c4ba-54cb-11e6-894d-d645ee59a246.PNG)

**Comment by kgracey** [comment]
@dcarrier-parallax

**Comment by kgracey** [comment]
@dcarrier-parallax it seems you have fixe this block, so this issue can be closed.
