### ISSUE TITLE
Unexpected interaction with repeat/do control

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp#452]
The repeat/do control loop is using the variable 'n' to control the loop in the following example. If the user changes the name of the variable 'item' to 'n' the variable will interact with the loop in an unintended way. The user may be completely unaware that the 'n' variable is being used.

My recommendation is to use either a double underscore for internal variables (__n) or underscores on either side of the variable (_n_). Before deciding, check to ensure that either naming convention is not a reserved format for the compiler or library internals.  The format should then be listed generically as a reserved variable construct.
    
![2016-07-28_14-43-49](https://cloud.githubusercontent.com/assets/8442260/17230596/e865883e-54d1-11e6-9b0d-3475a10e1bcf.png)

**Comment by zfi** [comment]
I should also include the generated code from the blocks:

#include "simpletools.h"
#include "oledc.h"

int item;

int main()
{
    oledc_init(7, 8, 9, 10, 11, 2);
    oledc_clear(0, 0, oledc_getWidth(), oledc_getHeight());
    item = 0;
    for (int n = 0; n < 30; n++)
    {
        oledc_drawPixel((item + 1), (item + 1), oledc_color565(51, 204, 0));
        item = item + 1;
    }
}

**Comment by PropGit** [comment]
@zfi - Good catch, and you're correct, this is a problem we don't want.

@michel-cf - Does Blockly have a feature to automatically make "temporary" variables unique?  I think I saw this in action in an example block program I tried a while ago, but can't remember for sure.  If not automatic, then is there a recommended way for us to do this?  I'm concerned about scope issues defeating our manual efforts to avoid variable name collisions.

**Comment by DarkmatterVale** [comment]
I have added a double underscore to the beginning of the variable, which I think will set it apart from user defined variables.

**Comment by DarkmatterVale** [comment]
bump

**Comment by zfi** [comment]
@PropGit it seems that using a double underscore is an appropriate solution. We need to reserve the construct and document it. It might also be useful to update the variable blocks to ensure that a double underscore cannot be used when defining a variable.

**Comment by PropGit** [comment]
@zfi - Good point.  I'll make an issue for that.

Can this issue be closed now?
