### ISSUE TITLE
XBee Setup Block in C: switch data labels

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#454]
@zfi I think this one is an easy one for you.

Could you make this simple switch on the XBee setup blocks so that the data labels DO and DI are switched? The **proper** block format is this:

![screen shot 2016-07-28 at 3 31 28 pm](https://cloud.githubusercontent.com/assets/9534148/17231409/85c10a64-54d6-11e6-8932-efafc88ecb72.png)

Now, I should note that a similar issue to this one has been opened and reopened mostly due to a lack of really clear communication on my part (probably). This time I will try to be clear. Don't change the way the code is generated - just switch the two labels in the block so that DO is first and DI is next. 

I suppose another way to look at this is that the the code generation could switch the location of the Tx/Rx, but it's best to switch the label location so that it follows nomenclature on the Propeller Activity Board.

**Comment by zfi** [comment]
Updated block as specified.

**Comment by DarkmatterVale** [comment]
The fix needs to be cleaned up...for users it should work, but for developers the naming scheme is backwards and needs to be fixed.

**Comment by zfi** [comment]
Agreed. The underlying code no longer matches the UI labels. Someone will eventually break this block trying to correct the anomaly. For the record, I was following orders.

**Comment by DarkmatterVale** [comment]
@zfi Can you push another commit to fix this (you don't have to send it to demo, just have it merged into master when you create a PR)? You will need to replace ```.appendField(new Blockly.FieldDropdown(profile.default.digital), 'DI_PIN')``` with ```.appendField(new Blockly.FieldDropdown(profile.default.digital), 'DO_PIN')``` and ```.appendField(new Blockly.FieldDropdown(profile.default.digital), 'DO_PIN')``` with ```.appendField(new Blockly.FieldDropdown(profile.default.digital), 'DI_PIN')```. Without this fix, the ```DI_PIN``` will still be first.

**Comment by DarkmatterVale** [comment]
bump

**Comment by zfi** [comment]
Code updated on the Demo site.

**Comment by kgracey** [comment]
@CarsonGracey please verify this for us.

**Comment by DarkmatterVale** [comment]
bump

**Comment by CarsonGracey** [comment]
Tested and Verified.
