### ISSUE TITLE
Sample arc block 

### ISSUE THREAD

**Issue by RoxyH** [parallaxinc/BlocklyProp#457]
[https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#5amf4u](url)

**Comment by PropGit** [comment]
@RoxyH - The link may not be persistent.  It is currently broken when I click on it.

You may have to screenshot design and results and paste that instead.

**Comment by wstodghill** [comment]
@RoxyH and @PropGit - I got it by cutting and pasting it. 
 
Just a "development" question - when you create a block like this do you or others determine the connection type? This one is a top and bottom, correct? What happens next in the process?

**Comment by DarkmatterVale** [comment]
@RoxyH or @wstodghill Can you please post the updated link? Thank you!

**Comment by PropGit** [comment]
@wstodghill - This one would need to be set to top+bottom connections, yes.

I recommend setting the connection types if you can determine what they should be, and specifically note the cases where you are not sure so we know to take care of that.

Yes, what is done with Block Factory is "Defining" the block, then the Language and Generator code that it creates is used by us to add the block to the system, and we have to create the target generator code (C or Spin).  Often in issues that post this block link, we'll also post the code we expect it to generate; that's _incredibly_ helpful if you can do that also.

Yes, it sounds like you understand.

**Comment by kgracey** [comment]
Addressed elsewhere.
