### ISSUE TITLE
How to handle color

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#459]
Since 3 of the devices we are likely to support in Blockly are "color" devices, we can standardize the color value as both a 24-bit RRGGBB integer and as three 8-bit components (red, green, blue) with some helper functions/blocks to manipulate, convert, and compare them.  This is critical to decide now as it will impact most of the OLED blocks, and will require edits to the ColorPal block.  I don't know where we are at with a block for the WS2812, but I would like to see that happen at some point, too.  I may have the connections backwards or shapes wrong on some of these blocks, so modify as necessary :)

For the ColorPal, I can pull a sample from stock plus some old ones we have laying around and figure out the scaling factors needed to convert their output to a somewhat consistent RRGGBB integer, and then modify its block to output a single 24-bit color value.  I'll update this issue once that's been done, and create a new one to modify the ColorPal block to something like this:
![image](https://cloud.githubusercontent.com/assets/19737272/17266659/ce214844-55af-11e6-9a7b-b7f96c6362e4.png)

_____________________________________________

![image](https://cloud.githubusercontent.com/assets/19737272/17266515/157db6c0-55ae-11e6-8518-1ea91556d362.png)
**Color Picker -> RRGGBB color (24-bit integer):**
https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#yimtje
_Any time the color picker is needed (many of the OLED drawing functions, eventually for the WS2812 LED, etc.), it should have this block defaulted into a variable input of that block_

![image](https://cloud.githubusercontent.com/assets/19737272/17266504/047bf3a0-55ae-11e6-9d50-4bfbd00d1c2b.png)
**Red, Green, and Blue component -> RRGGBB color (24-bit integer):**
_https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#4uqpcj
This would be the code to shift component values (ranged from 0-255) into their proper place:_
`output = ((redVal & 0xFF) << 16) | ((greenVal & 0xFF) << 8) | (blueVal & 0xFF);`

![image](https://cloud.githubusercontent.com/assets/19737272/17266496/ef76d34e-55ad-11e6-8576-801b1e4f812b.png)
**RRGGBB (24-bit integer) -> Red, Green, or Blue Component (8-bit integer):**
https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#kcb9ji
This would mask and shift the value depending on which component is asked for:
The dropdown values would be Red: 16, Green: 8, Blue: 0, and the code:
`output = (ColorVal & (0xFF << dropdownVal)) >> dropdownVal;`

![image](https://cloud.githubusercontent.com/assets/19737272/17266521/2d40ade4-55ae-11e6-879f-7d5e1c6b790b.png)
**Compare two RRGGBB colors (24-bit integers):**
https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#ijb3fx
_This would output the similarity (ranged from 0-255) between the two colors.  An absolute value function may be necessary for this - not sure that there is one available in simpletools or not)_
`output = 255 - ((abs((colorVal1 & 0xFF0000) >> 16 - (colorVal2 & 0xFF0000) >> 16) + abs((colorVal1 & 0xFF00) >> 8 - (colorVal2 & 0xFF00) >> 8) + abs(colorVal1 & 0xFF - colorVal2 & 0xFF)) / 3);`

**Comment by DarkmatterVale** [comment]
Can I get a verification from someone other than @MatzElectronics that we want this functionality enabled within Blockly?

**Comment by MatzElectronics** [comment]
How soon do you need to know?  I think almost everyone else is currently
out...

**Comment by PropGit** [comment]
This made sense to me when he proposed it.  I didn't object to it.

Is there any aspect of it that you're concerned about or want to propose a variation?

**Comment by DarkmatterVale** [comment]
@MatzElectronics I just wanted an acknowledgment that there has been discussion about this within parallax; thank you for the quick response @PropGit!

I think these blocks look great!

**Comment by MatzElectronics** [comment]
Thanks for taking it on!

**Comment by DarkmatterVale** [comment]
@MatzElectronics Where would you like to see these blocks? Does the "Values" category sound good?

**Comment by MatzElectronics** [comment]
Yes , it does for now.  We can always move them if Ken or the team have a
better idea.

**Comment by DarkmatterVale** [comment]
Gotcha.

**Comment by MatzElectronics** [comment]
Good afternoon,

Checking on this - is it possible to set the color as a quantity...instead of this:
![image](https://cloud.githubusercontent.com/assets/19737272/17834291/650aab8e-66ee-11e6-9656-be9a5a8b9ef7.png)

Do this:
![image](https://cloud.githubusercontent.com/assets/19737272/17834290/59136f3c-66ee-11e6-8bed-4e9571e98aab.png)

for each of the OLED blocks?  That way the color can be set programmatically, instead of with a bunch of conditionals.

It would then allow for better integration with the ColorPal.  

I'm also wondering about the ColorPal's blocks.  I gave Jim E. some equations for producing an approximate RRGGBB value with the ColorPal, since it's raw output is not white-balanced and in RRR, GGG, BBB format.  I think there is value in having the block that grabs those values, but labeling it as "RAW" or something that lets the user know those values are not adjusted in any way and in a 24-bit format.

Please let me know if anyone needs clarification on my ramblings :)

Thanks!
Matt

**Comment by DarkmatterVale** [comment]
@MatzElectronics Regarding your first point, yes it is possible. I will try to make that change today.

I'm a little confused by your second point...Would we be creating a new ColorPal block or modifying the current one?

**Comment by MatzElectronics** [comment]
A new one, and labelling the old one as "Raw" or something to that effect.

**Comment by MatzElectronics** [comment]
Found the math I was suggesting for this, realized I actually submitted it as a request to add a function in Simple Libraries, so that could be the hangup...

https://github.com/parallaxinc/Simple-Libraries/issues/29

**Comment by DarkmatterVale** [comment]
@MatzElectronics Can you create a new issue for the ColorPal block modifications please?

Thank you!

**Comment by MatzElectronics** [comment]
Done :)

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by DarkmatterVale** [comment]
Can I leave the colors in Hexadecimal format? Currently the color output by the color picker block is a hexadecimal number but I don't know if C will complain about this...

**Comment by MatzElectronics** [comment]
C does well with hex.  It hit needs to be preceeded by "0x", i.e.
"0xFE2C45".  If you do that you can use them interchangeably with decimal
integers.

**Comment by DarkmatterVale** [comment]
Thank you! I think the blocks have been updated and once the new functions are in SimpleLibraries we should be ready to go

**Comment by MatzElectronics** [comment]
Okay, I talked to Andy and I'll be authoring a new "color math" library.  I
hope to get it in by Friday.
Thanks!
Matt

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by zfi** [comment]
It looks like we deployed that library today. Updating labels.

**Comment by kgracey** [comment]
Verified and tested.
