### ISSUE TITLE
Bring back the bitwise math :)

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#460]
I think we should add:

**& (bitwise AND)
| (bitwise OR)
^ (bitwise XOR)
\>> (bitwise right shift)
\<< (bitwise left shift)**

back to the math operator block...  Just my opinion.  The reality is that there are some things you simply can't do without them.

**Comment by PropGit** [comment]
I agree with this.

**Comment by michel-cf** [comment]
They were present and have been removed on request

**Comment by MatzElectronics** [comment]
I know...but I'd I would like to bring it back up for discussion...

**Comment by DarkmatterVale** [comment]
@MatzElectronics What is your reasoning behind bringing these blocks back? What can beginners not do that they should be able to do?

**Comment by MatzElectronics** [comment]
When I started working with color, it quickly became apparent that some
things (isolating color components, mixing colors) are very hard to do
without these operators.  Also, single bit comparisons, masking,
shifting...all kinds of stuff...

On Aug 4, 2016 6:53 AM, "Vale" <notifications@github.com> wrote:

@MatzElectronics <https://github.com/MatzElectronics> What is your
reasoning behind bringing these blocks back? What can beginners not do that
they should be able to do?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/parallaxinc/BlocklyProp/issues/460#issuecomment-237559510>,
or mute the thread

**Comment by DarkmatterVale** [comment]
Beginners should never have to deal with color "operations" (which is why #459 is a necessary set of blocks). Can you give me a few use-cases for when a beginner would need to use bit comparisons, masking, or shifting?

**Comment by MatzElectronics** [comment]
Honestly, no.  Someone just starting out won't run I to the need for
Burnside math for a while, and you can use a number of tricks to get around
the need for it.

That being said, there are some things that could be done, specifically
game creation using the screen, that would make blockly surprisingly
capable.

If we bring them back...I would argue for them to go into a different
block, and not be added on to the current operator block.

**Comment by DarkmatterVale** [comment]
Interesting point...Game development would be something that people would be interested in. Do you have any ideas what the new block would look like? Similar to the current operator block, but only with the bitwise and shifting operations?

**Comment by MatzElectronics** [comment]
Exactly, yes.  And since they would be beginners, writing out the
operations in addition to having the symbols:

& (bitwise AND)
| (bitwise OR)

and so on...

On Aug 5, 2016 7:21 AM, "Vale" <notifications@github.com> wrote:

Interesting point...Game development would be something that people would
be interested in. Do you have any ideas what the new block would look like?
Similar to the current operator block, but only with the bitwise and
shifting operations?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/parallaxinc/BlocklyProp/issues/460#issuecomment-237848470>,
or mute the thread

**Comment by kgracey** [comment]
All operators have been implemented. We may find issues when using them in the future, and will need some useful examples from @MatzElectronics.
