### ISSUE TITLE
Log In / Keep Me Logged In

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#463]
What determines when a user gets logged out of BlocklyProp? It has been my experience that at times when I return that I am still logged in from a previous session. At other times, I have to Log In again.

Is is possible to have a "Keep Me Logged In" check box? Is this a bad idea for some reason? How does this currently work and is it intentional?

**Comment by PropGit** [comment]
@michel-cf - can you answer part of this?

@wstodghill - I've had the same experiences.  I think a Keep Me Logged In checkbox is a good idea.  The current behavior is intentional (I believe) but I don't know for sure how it works now that we've change the authentication system.

**Comment by michel-cf** [comment]
Although Shiro (our security framework) technically has a "remember me" feature, I've never been a big supporter of the feature.

- It often doesn't work: it depends on long term cookies
- I think most people these days either use form completion or a password manager, or working on a shared computer

**Comment by PropGit** [comment]
Even if it remembers them for only an extra couple days (with a long-term cookie as I expected) it would be a benefit.  Not looking for permanent solution; even Google logs me out from time to time, though I think they are doing it on purpose for security reasons.

**Comment by paragitadmin** [comment]
The current setting for session timeout is 8 hours. Note that the timer is reset when new traffic from that session appears on the web site. This seems to be enough time for most users.

**Comment by MatzElectronics** [comment]
I concur, let's close it.

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>  |  Licenses
<http://www.tspc.oregon.gov/lookup_application/LDisplay_Individual.asp?id=07080L3B270>
