### ISSUE TITLE
Optional Grid in Workspace

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#467]
Discussion Item (I have not figured our how to attach labels! Sorry)

Any interest or usefulness in an optional (set by user choice) grid in the workspace of BlocklyProp? 

I don't even know if this is possible... See this example from the S2 GUI - might just provide a wallpaper and organizing structure for blocks.

![grid](https://cloud.githubusercontent.com/assets/8891440/17329067/85310b22-5886-11e6-874b-779cdefb32dc.PNG)

**Comment by zfi** [comment]
This appears to be possible. 

https://developers.google.com/blockly/guides/configure/web/grid

**Comment by wstodghill** [comment]
Any body see any usefulness in this or even just the snap to? While I was looking, I saw the zoom - plans for that?

**Comment by DarkmatterVale** [comment]
I personally do not like the grid because I believe it clutters the workspace, which draws attention away from the blocks. @kgracey what do you think?

**Comment by wstodghill** [comment]
@DarkmatterVale - Thanks and thanks for adding the label. I was thinking of a very light color grid or even enable the snap for easier alignment of groups - I have no really strong conviction - just wondered. The blank canvas just looked a bit bare...

**Comment by CarsonGracey** [comment]
I agree that having the blockly prop logo would be helpful in place of a grid because yes the blank background is bare and it would be nice to have a static reference point as well that doesn't move.

**Comment by DarkmatterVale** [comment]
@wstodghill I think that's a great idea! The faded BlocklyProp logo adds a nice touch without distracting from the blocks. @michel-cf Is this feasible?

**Comment by wstodghill** [comment]
I also think the tools on the bottom right could be nice too. They are load from file, save (might add save as), undo, redo, copy, and trash.

**Comment by michel-cf** [comment]
The faded logo might be possible. The tools will be a little to much I think. Unless we do it as an overlay using html instead of vector graphics.

The hard thing about changing Blockly graphics is that it isn't plain html, css and javascript, but vector graphics on a canvas. Something I've never worked with.

**Comment by kgracey** [comment]
Good discussion and I'm going to close the issue. Let's get started with the tool - get people using it - and then revisit this in the future as desired.
