### ISSUE TITLE
Storing and Incrementing a variable

### ISSUE THREAD

**Issue by CarolHazlett** [parallaxinc/BlocklyProp#472]
How about a Control block which would act like a "for loop"? The ability to store a variable and increment it (or decrease it) by a given amount each time the loop executes.

**Comment by wstodghill** [comment]
See - http://demo.blockly.parallax.com/blockly/my/projects.jsp#175

See also Issue

**Comment by CarolHazlett** [comment]
Issue has been answered for me. thanks Whit!
