### ISSUE TITLE
Demo: category colors are gone in C

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/BlocklyProp#474]
Someone reverted the commit I made in the demo branch which included the updated colors.

**Comment by PropGit** [comment]
@DarkmatterVale - Not sure how that happened, but could be 1) due to mistake made in Git on their side, or 2) due to an apparent forced-merge that broke code... we had to go patch it to get Demo working again.  I don't know any more details than that.

**Comment by zfi** [comment]
The source file was littered with text that git uses to show two differing code blocks. We ran a diff between that file and the previous commit. I reverted the file And then used the output from the diff to guide use on repopulating the new code. 

It would appear that we missed a line or two.
