### ISSUE TITLE
Controlled acceleration

### ISSUE THREAD

**Issue by drpiccioni** [parallaxinc/BlocklyProp#479]
Will it be possible to control the acceleration rate of the S3?  For example, will a BlocklyProp user be able to specifiy: "accelerate at a constant rate from rest to 5.00 cm/s during a time interval of 2.00 seconds"?

Matt Greenwolfe has achieved this in the S2 (see [this article](https://drive.google.com/file/d/0B4jK7MFQKwm4Tm45VzNuSGRLcWM/view?usp=sharing))

**Comment by greenwolfe** [comment]
Hi,
Matt Greenwolfe here.  I'm the person who took advantage of the sum-mm accuracy of the encoders on the s2 to write a revised motor driver that controls speed to within mm/s, acceleration to within mm/s^2 and distance to within mm.  There were some pedagogical concepts about control of error inherent in the apparatus and optimal feedback inertia that meant a robot with these characteristics (along the GUI I wrote for students to program the robot by drawing kinematic graphs on their screen) would create spontaneous and more independent inquiry among the high school students.  It does!  I just completed my third summer workshop at NC State University where teachers have come to learn about the idea, purchase class sets of scribbler robots, and use them in their physics classrooms.  

Participants in this year's workshop are legitimately asking whether they should purchase s2's or s3's for this upcoming school year, which starts in a matter of weeks.  Richard has been keeping me up to date on his discussions with people on this form as well as Matt Matz.  If you can provide Richard and/or myself an s3 robot, we will be glad to test it and get to work on modifying the spin and assembly code for the motor driver if necessary.  If that wont' work, I would like to be able to give interested teachers from my workshop a timeline for when you might test the software yourself and get back to us.

Thanks!

Matt Greenwolfe

**Comment by kgracey** [comment]
Hello Richard and Matt - 

I’ve been out of town and catching up on these messages. I want to let you both know that we truly appreciate the contributions you have made to the S3. I’m aware of Matt’s S2 object and also desire to see it properly supported in the S3 Blockly code base. There are a couple of things we need to know about it to determine what and when we can implement your work, so a couple of questions:

Where can we download a copy of Matt’s work? I need David Carrier (above) to take a look at it for us. 
Sample S3s. Yes, I can provide them to each of you. Please send me your shipping address to kgracey@parallax.com <mailto:kgracey@parallax.com>. They are pre-production releases without the black tempo printing for hacker port and buttons (just a green shell) but I think we have stock of at least 170 full production versions at Parallax (need to check with my team). 

Thanks, 
 
Ken Gracey, Parallax Inc. 
graceyken@gmail.com

**Comment by greenwolfe** [comment]
Hi Ken,
I am sending you a separate e-mail with a download link and password for my software, and my full address.  Also, here's the link to my forum thread from a few years ago when I was developing it.  http://forums.parallax.com/discussion/140305/drive-s2-in-mm-s#latest .  To write it, I reverse engineered the original motor driver by Phil Pilgrim and then wrote my own based on his concept.  I designed it with the idea in mind that it could be integrated back into the original s2 object and used as a direct plug-in replacement for the motor driver, as well as having the additional functions.  In fact, participants at my workshops have been asking whether they could access the sensors and other features of the robot along with my motor driver.  I never got around to working on the integration, but don't see any major roadblocks to accomplishing that, especially if I have some collaborators on your end.

Matt

**Comment by kgracey** [comment]
We've agreed to make this part of the S3 Blockly tools and @greenwolfe will be doing the work.

**Comment by drpiccioni** [comment]
That's great news. If there is any way I or my minions can help, please let me know.
Richard (drP)

**Comment by MatzElectronics** [comment]
Hello all - I wanted to let you know that we have successfully ported the s3 over to Propeller C - and that there is a good spin2cpp conversion tool available as well.  Whatever work is done here will eventually to ported to c and integrated in - we won't be putting significantly more effort behind SPIN on the s3.  This allows us to simplify blockly under the hood since it will only have to generate 1 language instead of two, and gives us good control of things like the hacker port, etc.

**Comment by wstodghill** [comment]
@greenwolfe, @kgracey - Any updates on where this stands?

**Comment by MatzElectronics** [comment]
@drpiccioni @greenwolfe Any updates?

**Comment by paragitadmin** [comment]
It's been a year with no progress reported. Closing the issue.
