### ISSUE TITLE
cog_run issues

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/BlocklyProp#48]
Issue 1) ID declaration needs to be global not local

Issue 2) Instead of making a pointer, allow the user to create a pointer and add that pointer into the function

**Comment by DarkmatterVale** [comment]
https://github.com/parallaxinc/BlocklyProp/pull/49

**Comment by AndyLindsay** [comment]
Regarding issue 2, here is a test of the run block's New pointer... feature.  Although it successfully creates a pointer block in the Pointers list, it does not yet add global pointer declarations for the variable names that are created.  See comments in code.

![multicogwithnewpointer](https://cloud.githubusercontent.com/assets/11575415/6756782/6ab97086-cee9-11e4-805f-a700b573e1e8.png)

#include "simpletools.h"
{{$pointer_type_cogA}} cogA;          // Current code that is generated
int *cogA;                                         // Suggested code
{{$pointer_type_cogB}} cogB;          // Current code that is generated
int *cogB;                                         // Suggested code

void methodA() {
  while(1) {
  }
}

void methodB() {
  while(1) {
  }
}

int main() {
  cogA = int * cog_run(methodA, 128);
  cogB = int * cog_run(methodB, 128);
  cog_end( cogA );
  cog_end( cogB );
}

**Comment by DarkmatterVale** [comment]
This bug is not relevant anymore because of changes to the Cog system in BlocklyProp.
