### ISSUE TITLE
Reorganize blocks to be in the correct files

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/BlocklyProp#482]
This is a "backend" change that will not affect the user, but it is necessary for development. I believe that we should change the places that blocks are placed to reflect their place within the UI. For example, all blocks that are present in the "Values" category will now be located within the file "values.js". Only categories will be given a category (subcategories will not be given a separate file). This will make it much easier to maintain the blocks in the future (no confusing locations like the current system).

Thoughts?

**Comment by PropGit** [comment]
Sounds great to me for present and future maintenance.  My only concern would be that we're always chasing the next-best way to categorize blocks; but maybe the dust has already settled on that topic.

**Comment by DarkmatterVale** [comment]
This will settle the dust. This is by far the most logical way to organize the blocks, and it will only change when the organization of blocks on the front end changes

**Comment by MatzElectronics** [comment]
This has now been mostly taken care of - blocks were condensed into a handful of files.  This was largely done in #822, and will be completed as a part of #819
