### ISSUE TITLE
RGB OLED: Round Rectangle Enhancement

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#483]
After doing a bit of testing with the round rectangle block I figured it would be beneficial to be able to change the percent that the rectangle is rounded. Right now it is locked at 20% and it generates the code below

```C
oledc_fillRoundRect(int x, int y, int w, int h, (w+h)/20, oledc_color565(r, g, b));
```

So after messing around with the numbers, values anywhere between 4-100 work for the number that (w+h) is divided by. The block could be changed to look like this one here: https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#rguykw - where parameters of 4-100 could be put on the % rounded.

**Comment by zfi** [comment]
@CarsonGracey , please file the enhancement request as a separate issue. The bug fix is on the demo server, ready for verification.

**Comment by kgracey** [comment]
@zfi I attempted to test this one but the block is the same as before. @CarsonGracey is asking for an additional parameter that drops a value into the code to replace something we've calculated from user inputs. Basically, he's asking that in this line of code:

`oledc_fillRoundRect(int x, int y, int w, int h, (w+h)/20, oledc_color565(r, g, b));`

we replace the `(w+h)/20` be replaced with a value the user inputs in this block as a percentage:

https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#rguykw 

I've tested his proposal and it is far more funcational and a good enhancement.

**Comment by MatzElectronics** [comment]
Ditto to the above - instead of a checkbox, just default the value to zero (regular rectangle), and math should be (w+h)/(roundedness)

**Comment by MatzElectronics** [comment]
Tested - didn't like the end result, the math isn't quite right.  The function uses a "radius" for rounding the corners.  I think just that will work well.  As far as I remember, the function won't let you over-do it, so there doesn't need to be any error checking in blockly.  I'll work on it and submit a PR for it.

**Comment by kgracey** [comment]
Is this the same as allowing a user input for a percentage radius, without the calculation of LxW? In my simple testing your object was ideally suited for such a simple solution, for simple tools, for simple libraries, for a simple person [like me].

**Comment by MatzElectronics** [comment]
For some reason, when I tested it, it just didn't work like that...this is
actually simpler.  Put a "1" in, and it shaves 1 pixel off the corner.  Put
in a "2", and it shaves 2, etc.

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by kgracey** [comment]
Yeah, I like that too.

**Comment by MatzElectronics** [comment]
@PropGit @zfi Tested and verified - please close

**Comment by PropGit** [comment]
Closing.
