### ISSUE TITLE
Terminal Baud Rate

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#490]
@michel-cf - Can you make BlocklyProp's Terminal automatically use 9600 baud when we've downloaded a Scribbler 3 program, and stay at another (faster) fixed baud rate if it's not a Scribbler 3 program?

We need the terminal to work at 9600 baud for Scribbler because of some hardware constraints, but we'd rather not fix it to 9600 baud for _every_ board type.

**Comment by wstodghill** [comment]
@PropGit - good call!

**Comment by CarsonGracey** [comment]
Looks like its still displaying 115200 for me:

```C
'SERIAL_TERMINAL USED
CON
  _clkmode = xtal1 + pll16x
  _xinfreq = 5_000_000

VAR
  long Freq

OBJ
  serial    : "Parallax Serial Terminal"
  scribbler    : "Block_Wrapper"

PUB Setup
  serial.StartRxTx( 31, 30, 0, 115200 )
  Scribbler.Start
  Start


PUB Start

  serial.Char(serial#NL)

  Freq := 0

  Freq := Freq + 50

  Scribbler.SetVolume(0)
  Scribbler.PlayNote(0, 0, 0)
```

**Comment by PropGit** [comment]
@CarsonGracey Please try again with a new project.

I saw nearly the same thing happen... but first it worked fine for me and was 9600 baud, then after your post, I checked and it was definitely 115200, but now it's back to 9600.  I'm not sure what's going on.

Make sure to uninstall your current BlocklyProp Client software and get the latest installer from the Demo site too.

**Comment by CarsonGracey** [comment]
Looks like creating a new project solved this. What does it mean for older projects then?

**Comment by kgracey** [comment]
That they probably won’t work :)

But that’s okay because we’ve not really built any tutorials for the S3 which use Print yet (because it wasn’t *printing* until today.

**Comment by michel-cf** [comment]
It should work for all projects as the code is generated each time.

Make sure that you don't have a block where you initialize the serial connection.
Make sure your board type is S3. Even if you use spin, only the S3 type uses 9600 baud.

If there are any blocks that do initialize the baudrate wrong, please identify them.

**Comment by PropGit** [comment]
Verified fixed!
