### ISSUE TITLE
RGB OLED: Inline Block inputs

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#493]
@zfi is going to give some of the longer OLED blocks inline inputs and clean up their appearances.

**Comment by zfi** [comment]
Rectangle block is done.

**Comment by zfi** [comment]
Updated nearly all of the drawing blocks. I am not convinced that the pixel block required the same treatment.

**Comment by CarsonGracey** [comment]
They all look good now. Verified.
