### ISSUE TITLE
Rename Categories

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#494]
In the Activity Board WX menu rename
>Communicate
>>Print

to

>Communicate
>>Terminal

**Comment by PropGit** [comment]
I think the renaming was supposed to be assigned to @zfi, but the testing of terminal and spec of related blocks was to me, @PropGit.

**Comment by zfi** [comment]
@michel-cf or @DarkmatterVale , con some point me to where we filter the blocks available based on the hardware platform? I see hardware definitions in the cdn/blockly/generators/ but I'm not following the definitions to how the blocks are specified for each hardware platform.

**Comment by DarkmatterVale** [comment]
The filtering is done within the ```framec.jsp``` file, but this is a category name change which is located in the file ```translations.properties```

**Comment by CarsonGracey** [comment]
Verified.
