### ISSUE TITLE
GPS PAM7Q

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#497]
@zfi Hide this block until it is further worked on until completion.

**Comment by kgracey** [comment]
Verified!

**Comment by MatzElectronics** [comment]
Reopening to activate this block (in a more generalized form to support multiple GPS modules including a future replacement for the PAM-7Q ETA 4/1/17)

**Comment by MatzElectronics** [comment]
Tested and verified - to the extent that I could.  Blocks are reporting correctly, but I didn't get in the car and drive to see heading and velocity report more than 0.
