### ISSUE TITLE
D/A block revision request

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#502]
@zfi these are the revisions to the Voltage / DAC blocks.

1. First, there are two blocks - you can delete one of them. 
![screen shot 2016-08-11 at 11 55 26 am](https://cloud.githubusercontent.com/assets/9534148/17600419/40fb012c-5fb8-11e6-8aa8-5f3c2690f9a7.png)

2. The block needs an input for the channel, in the form of a drop-down menu choosing D/A 0 or D/A 1.
3. The block needs an input (variable or constant) for the voltage level, between 0 and 330. 
4. Example of text block is Change the text on the block to be "0-3.3V DAC output in Volts x 100". 

```
int item;

int main()
{
  while(1)
  {
    da0 = 050;                  //users blocks declare value on da0 (accepts 1 to 330)
    da0 = da0 * 256 / 330;	   //D/A Analog Out Block does this with da0 var
    da_out(0, da0);	
  }  
}
```

**Comment by kgracey** [comment]
@DarkmatterVale if you want to fix this one before @zfi gets to it please make yourself at home :)

**Comment by zfi** [comment]
The value (200 in this example) is not getting expressed in the generated code. The channel select appears to be working as specified.

![2016-08-18_15-03-41](https://cloud.githubusercontent.com/assets/8442260/17792331/0152965a-6555-11e6-9b9c-23df2b0f84e9.png)


#include "simpletools.h"
#include "abvolts.h"

int main()
{
    da_init(26, 27);
    da_out(0, (0 * 256 / 330));

}

**Comment by DarkmatterVale** [comment]
#554 fixed the issue you were seeing @zfi

**Comment by kgracey** [comment]
Tested both of these blocks with an OLED and they work as planned. Issue closed!
