### ISSUE TITLE
SQL Connection Timeout Error

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp#507]
If the app is idle for some period of time, the backing SQL connection is closed by the server [error message below]. The application does not appear to detect this when it attempts to communicate with the database. Can the app check for an open connection before attempting to use it? 

HTTP Status 500 - org.jooq.exception.DataAccessException: SQL [insert into `blocklyprop`.`session` (`idsession`, `startTimestamp`, `lastAccessTime`, `timeout`, `host`, `attributes`) values (?, ?, ?, ?, ?, ?)]; The last packet successfully received from the server was62229 seconds ago.The last packet sent successfully to the server was 62229 seconds ago, which is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.

**Comment by PropGit** [comment]
@zfi and @michel-cf - could this be the cause of Issue #509?

**Comment by zfi** [comment]
It is possible that these are related issues. The only common detail is that there are a number of hours between accesses when the errors occur. The issue reported in #509 should generate some interesting log data. We need a date and time of the occurrence to match it with log file activity.

**Comment by zfi** [comment]
Just ran into a similar issue where trying to load the site after a new .war deployment triggered a "Too many connections" error in the JODBC connector on a development VM. I also noted that there was about 3.4 GB of memory allocated on a 4 GB VM. Under normal operation, this value should be closer to 2.4 GB of RAM. 

Restarting tomcat released the excess memory but did not correct the too many connections issue. Restarting the MySQL service corrected the error but this should not be happening in a dev environment.

**Comment by PropGit** [comment]
@michel-cf - We expect this issue to impede use of the system (and our efforts to do more productive things other than reset the system) in Sep/Oct.

We think the code is trying to use a handle without first checking to see if it's still valid.  There should be a call to verify the connection still exists before usage to prevent this error, in theory.

**Comment by paragitadmin** [comment]
The DAO layer relies entirely on JooQ to manage the database connection pool. If we loose a connection to the database server, JooQ does not appear to attempt to reconnect. It also appears that JooQ  receives the initial connection from application code.

The options are to enable a watchdog on the database connection or, in true cloud service tradition, just die and let the infrastructure restart the application.

**Comment by zfi** [comment]
The session is expiring and the code at or above the DAO layer is not evaluating this possibility in some code path. This is related to issue #1556 and, I believe, the root cause.

Closing this ticket and continuing work on issue #1556.
