### ISSUE TITLE
Servo Block 

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#510]
![servo ramp](https://cloud.githubusercontent.com/assets/20099916/17632190/e3751514-607b-11e6-8f04-51f9915caa0f.PNG)

This block should be able to take a variable input where the 180 degrees are. The parameters would still be 0-180.

**Comment by kgracey** [comment]
Strangely, this block used to accept a constant or variable input.

**Comment by zfi** [comment]
The range checking is in place but I can't seem to figure out how to update the value displayed in the block. For example, if the user enters 181, the onchange event correctly identified the range error and throws up an alert box. If the use dismisses the alert, the errant value remains in the display. Note that the code generation block does ensure that the value provided by the UI is within the correct range in the emitted code.

Blockly.Blocks.servo_move = {
    init: function () {
        this.setColour(colorPalette.getColor('output'));
        this.appendDummyInput()
            .appendField("servo")
            .appendField("pin#")
            .appendField(new Blockly.FieldDropdown(profile.default.servo), "PIN");
        this.appendValueInput("ANGLE")
            .setCheck("Number");
        this.setInputsInline(true);
        this.setPreviousStatement(true, null);
        this.setNextStatement(true, null);
    },
    onchange: function(event) {
        if (event.type == Blockly.Events.CHANGE && event.element == 'field') {
            if ((event.newValue < 0) || (event.newValue > 180)) {
                alert("WARNING: The value for the angle must be between 0 and 180 degrees.");
            }
        }
    }
};


// Code generator
Blockly.propc.pwm_set = function () {
    var pin = this.getFieldValue("PIN");
    var channel = this.getFieldValue("CHANNEL");
    var duty_cycle = Blockly.propc.valueToCode(this, "DUTY_CYCLE", Blockly.propc.ORDER_NONE);

    if (Number(duty_cycle) < 0) {
        duty_cycle = '0';
    } else if (Number(duty_cycle) > 100) {
        duty_cycle = '100';
    }

    var code = 'pwm_start(' + pin + ', ' + channel + ', ' + duty_cycle + ');\n';
    return code;
};

**Comment by kgracey** [comment]
@DarkmatterVale could you get a look at this for us?

**Comment by zfi** [comment]
The code is live on Demo, PR #531.

**Comment by kgracey** [comment]
@CarsonGracey test this and report back.

**Comment by CarsonGracey** [comment]
![servo new](https://cloud.githubusercontent.com/assets/20099916/17675895/ae90054a-62e0-11e6-9fd1-8ed79501293f.PNG)

The block is working as intended except the text "degrees (0-180)" is missing.

**Comment by zfi** [comment]
Added the omitted text and included a default value block.

**Comment by zfi** [comment]
@CarsonGracey , updated code is now on Demo. Please close the issue if the work is complete.

**Comment by CarsonGracey** [comment]
Tested and Verified.
