### ISSUE TITLE
RGB OLED: Round Rectangle Bug

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#511]
There is currently a bug with this block where the percent the corners are rounded isn't (w+h)/20. For example this block here

![round rect](https://cloud.githubusercontent.com/assets/20099916/17531957/16310b70-5e33-11e6-96f8-8b0bc795b267.PNG)

generates this code

```C
 oledc_fillRoundRect(0, 0, 50, 50, 252.5, oledc_color565(255, 255, 255));
```

(50+50)/20 equals 5 not 252.5 I can't explain the reasoning other than a possible typo in a previous commit.

**Comment by zfi** [comment]
Possible a local browser caching issue? When I enter the same values, I get the code below, which calculates (50+50)/20 with a result of 5. 


int main()
{
    cpal = colorPal_open(cpSIO);
    cog_run(checkcolor, 128);
    while (1)
    {
        print("red = %d\n", red);
        oledc_fillRoundRect(0, 0, 50, 50, 5 oledc_color565(255, 0, 0));
    }
}

**Comment by CarsonGracey** [comment]
This appears to work now. Although there are still two other issues I've encountered with the round rectangle that I am currently submitting.
