### ISSUE TITLE
RGB OLED: Round Rectangle NaN

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#514]
So I found another error for the first time with round rectangles.

```C
#include "simpletools.h"
#include "oledc.h"



int main()
{
    oledc_init(4, 5, 6, 7, 8, 2);
    oledc_fillRoundRect(0, 0, oledc_getWidth(), oledc_getHeight(), NaNoledc_color565(204, 0, 0));
}
```

What is happening is ```NaNoledc_color565(204, 0, 0)```  is incorrectly adding ```NaN```  before the function. This is happening with ```oledc_drawRoundRectangle``` and ```oledc_fillRoundRectangle```. I have had it show up only in some projects.

![round rectangle](https://cloud.githubusercontent.com/assets/20099916/17635726/ed8d89ca-608d-11e6-896b-0c76725b9f82.PNG)

Project link: http://demo.blockly.parallax.com/blockly/editor/blocklyc.jsp?project=87# 

Here is the compile error:

Required libraries: oledc, simpletools
Library compile order: None needed
single.c: In function 'main':
single.c:9:5: warning: implicit declaration of function 'NaNoledc_color565' [-Wimplicit-function-declaration]
single.c:9:5: error: too few arguments to function 'oledc_fillRoundRect'
/opt/parallax/Workspace/Learn/Simple Libraries/Display/liboledc/oledc.h:265:6: note: declared here

**Comment by CarsonGracey** [comment]
Something I just realized after submitting this - the error is because the percent rounded comes from (w+h)/2. So whats happening is nothing, this is most likely because the compiler is interpreting the inputs as ```(getWidth()+getHeight())/2```. Without having actual number values, it results in a NaN. Do the getHeight and getWidth functions have underlying values in the library? @zfi and @matzelectronics, do you know an easy fix?

**Comment by zfi** [comment]
The exact code that is failing is here:
code += ((Number(width) + Number(height)) / 20) + ', ';

The width and height values are derived from this code:
var width = Blockly.propc.valueToCode(this, 'RECT_WIDTH', Blockly.propc.ORDER_NONE);
var height = Blockly.propc.valueToCode(this, 'RECT_HEIGHT', Blockly.propc.ORDER_NONE);

I do not know what is happening when the value block is replaced with the max_width or max_height block. I believe that they are returning a string that is the function call into the OLED library. We may need to change those blocks to return a simple numeric value. I am looking at that now in a sand boxed system.

**Comment by MatzElectronics** [comment]
I'm sorry I'm not really tracking what the problem is, but I'll try to help
in any way that I can.  Not sure why getWidth() and getHeight() are getting
used here, they aren't relevant to the block unless you ate trying to draw
it full screen.

**Comment by zfi** [comment]
The OLED Rectangle block can generate rounded corners. There is an extra parameter in the block when rounded corners are selected to compute the radius of the rounded corner. The original code was written before the max height and width blocks were introduced and relied on the value block returning a number. Once we use the new max* blocks - which return a string - the code breaks. The new code up on Demo should correct this issue.

**Comment by MatzElectronics** [comment]
Got it, thanks!

**Comment by zfi** [comment]
PR #521 submitted to master branch.
