### ISSUE TITLE
S3 block request: "Advanced" LED set block request

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#519]
This is an idea for an advanced LED set block ( for the the three bi-color indicator LEDs -maybe for later...)

![advanced led set](https://cloud.githubusercontent.com/assets/8891440/17638167/dfecc2d4-60ad-11e6-8758-383058acda58.JPG)

Here is the block factory link - https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#q9qdy8

These are the LED set options in the Scribbler Object for the bi-color red/green LEDs - David's latest S3 LED set block has many of these choices - as you can see in the screen capture below:

![led set blocks](https://cloud.githubusercontent.com/assets/8891440/17638210/2e206fa0-60ae-11e6-82ab-4bf1e8df8bf8.JPG)

Note how the larger selection of choices is for the block that sets each LED (left, center, or right). All three (not just one at a time) LEDs can be set with the Simpler LED set block - but with limited colors. 

Had a discussion with Ken about using the term "yellow" rather than "amber" - I gladly yield to y'all's call.

**Comment by wstodghill** [comment]
![advanced led set](https://cloud.githubusercontent.com/assets/8891440/17638157/d50f3824-60ad-11e6-8ba0-fcdc3b323e94.JPG)

**Comment by wstodghill** [comment]
@kgracey - I think we still need your input on this (even though it is lower priority - since it is an advanced S3 block.

**Comment by kgracey** [comment]
I'm in agreement and we'll produce this block. I'll assign it to David and we'll have it for release.

**Comment by wstodghill** [comment]
@kgracey - thanks Ken! Should we keep the commas? I noticed you removed them from another block for simplicity.

**Comment by kgracey** [comment]
No comments is best. We’re already violating some grammatical rules to keep things simple so we might as well remove commas too. 

Ken Gracey
graceyken@gmail.com

**Comment by wstodghill** [comment]
@kgracey - here it is then...

![set_leds_cap](https://cloud.githubusercontent.com/assets/8891440/17676324/aeaa1044-62f3-11e6-935e-203aaea78cd6.JPG)
https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#bqw6nc

**Comment by kgracey** [comment]
That’s perfect.

**Comment by kgracey** [comment]
It turns out that some of these intermediate colors are not readily distinguishable on the bi-color LEDs.

**Comment by wstodghill** [comment]
@kgracey - I remember it being subtle on the S2. Y'all decide - but let's get all we can really tell apart - especially the blinky and the alternating if possible. Is it chartreuse and orange that don't really work? How was David getting blink amber (which we could make blink yellow)? It was not one of original choices.

**Comment by kgracey** [comment]
We will delay this until November (yellow can't be blinked).
