### ISSUE TITLE
Local Usage support

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/BlocklyProp#52]
We need a way for people to use BlocklyProp locally on their machine without internet access. I have no idea how to do this or what it will take. But I don't think this is an issue to worry about now as we still need to get a lot of other more pressing matters done first.

**Comment by DarkmatterVale** [comment]
Qt has an embedded browser that could possibly contain BlocklyProp’s web interface. We could distribute a compiled version of BlocklyProp and have that runs inside of Qt’s browser, initiated from within the client.

**Comment by michel-cf** [comment]
For uniformity I would suggest keeping it running in the users normal browser, but hosted from within BlocklyPropClient

**Comment by paragitadmin** [comment]
We have essentially achieved this with the developer's VM.
