### ISSUE TITLE
Terminal mangles semicolon followed by less-than

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#523]
Terminal injects a new line after a semicolon if a less-than character immediately follows.  It also stretches the terminal height by one line, covering part of the Close button when this happens.

![image](https://cloud.githubusercontent.com/assets/1266318/17640059/4310480e-60ae-11e6-876c-690c56d5ade6.png)

Use this code to test:  http://demo.blockly.parallax.com/blockly/projectlink?id=206&key=2afe235f-40e8-4f1f-838b-e69f07ebc9b3

**Comment by PropGit** [comment]
Tested - This issue still exists.  Fix in #603 did not resolve it.  Please consider undoing the specific change thought to have fixed issue #523 (this one) __only__ if that change didn't fix something else too.

**Comment by PropGit** [comment]
@michel-cf - Maybe this is related to current assessment in #524 - need to base64-encode all data for websocket?

**Comment by MatzElectronics** [comment]
It mangles a few other things too - I noticed that hyphenating something does it as well.
