### ISSUE TITLE
Terminal - Visible Chars (ASCII 160 or Above) Make Terminal Unusable

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#524]
Visible Characters in the range ASCII 160 or above make the terminal unusable by blanking the display.  It remains in this state even on future downloads until the user refreshes the page without cache.

![image](https://cloud.githubusercontent.com/assets/1266318/17640206/18d17930-60b0-11e6-8f35-ebc6796b6a7d.png)

Use this code to test: http://demo.blockly.parallax.com/blockly/projectlink?id=204&key=23c2509b-8910-4846-85e4-ec6222c95f59

**Comment by michel-cf** [comment]
Refreshing the page is not required anymore. But there are still characters that don't work.

Current problem assesment: the problem is not with the terminal screen, but with the websockets.
A possible fix might be base64 encoding all data instead of sending them raw over the websocket.

**Comment by PropGit** [comment]
@michel-cf - Okay, this is a lower priority than the other items.  We'll address this sometime after public release.
