### ISSUE TITLE
S3 - wait block revision

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#526]
@kgracey and @dcarrier-parallax - In the dropdown menu of the wait block - the following error occurs (at least for me - running Google Chrome or Explorer in Windows. See screen capture. - David and I discussed this previously and think it is  uni-code error).

![wait block error](https://cloud.githubusercontent.com/assets/8891440/17641291/e9140148-60de-11e6-9bb3-b48da48d222e.JPG)

I propose these changes (which I think are technically more accurate too)

![wait block improved](https://cloud.githubusercontent.com/assets/8891440/17641296/0bb7c72a-60df-11e6-89a4-7ca3afa61e6d.JPG)

The block factory link is https://blockly-
demo.appspot.com/static/demos/blockfactory/index.html#f8baq3

**Comment by wstodghill** [comment]
@kgracey and @dcarrier-parallax - I've been thinking about this one too. It might be more concise and elegant to have only milliseconds (or second(s) and millisecond(s) ) see below:

![wait_block_sec_ms](https://cloud.githubusercontent.com/assets/8891440/17651562/57976afa-622f-11e6-8e29-1a266455e0f0.JPG)
https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#qoozzg

![wait_block_ms](https://cloud.githubusercontent.com/assets/8891440/17651593/10347774-6230-11e6-8a1d-17b76613d10b.JPG)
https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#gqb4qc

**Comment by kgracey** [comment]
@wstodghill - could you modify this block to have a title "S3: wait block revision" so we can easily identify the S3 blocks from the greater PropBlockly "ecosystem"?

**Comment by wstodghill** [comment]
kgracy - can you comment on the further revision?

**Comment by kgracey** [comment]
Agreed on the suggestions from Whit with a minor modification. Since the (s) for plural is so similar to the abbreviation for second (s) how about this:

seconds (s)
milliseconds (ms)

The abbreviation of (s) or (ms) would be referenced in the tutorial for consistency. What do you think @wstodghill?

**Comment by wstodghill** [comment]
@kgracey - perfect! ;-)

**Comment by wstodghill** [comment]
![s3_wait_block_sec_ms](https://cloud.githubusercontent.com/assets/8891440/17651712/70a71808-6232-11e6-9091-f9757b65c4ac.JPG)
https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#rpnvnz
