### ISSUE TITLE
BlocklyProp Beta Demo Down?

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#527]
Are others able to log on to http://demo.blockly.parallax.com/blockly/

I have been unable to reach the site this morning - though http://blockly.parallax.com/blockly/ is up.

**Comment by zfi** [comment]
The BlocklyProp app on the demo server failed earlier this morning. I have restarted the services and the app is available again.

**Comment by wstodghill** [comment]
Thanks! Just found it up!
