### ISSUE TITLE
S3 block revision: set motor speed

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#528]
@dcarrier-parallax regarding this block we need some revisions:
![screen shot 2016-08-14 at 10 34 00 am](https://cloud.githubusercontent.com/assets/9534148/17650687/b0dbe130-6208-11e6-850d-41ad7d5e28f4.png)
Revise as follows:

set left motor speed (-100 to 100)%
set right motor speed (-100 to 100)%
for a time of (1-5000) ms
use 0 ms for continuous operation

Review these changes carefully as they remove caps, removes commas, provides consistency between first and second lines, and remove the explanation at the bottom. The change from duration to time is to match D=rt.

We would like to have a range of 0-10000 ms but we found that bug at 8000 ms - do you know what is causing this and whether or not you can change the upper limit to 10000 ms?

Tag with "DEMO" when posted so I can test it.

**Comment by wstodghill** [comment]
@kgracey and @dcarrier-parallax  - I like this design and it is consistent with the GUI in function. Look forward to testing it too!

**Comment by kgracey** [comment]
Thanks @wstodghill - we will deal with block revisions one at a time, clearly and explicitly.

**Comment by wstodghill** [comment]
@kgracey and @dcarrier-parallax  - can we get a resolution on the duration time for this block per Ken's question above - I too would like the max a 10,000 ms.

**Comment by kgracey** [comment]
This is now fixed - just observed it at David’s desk. He is using a different method call that doesn’t have this bug.

**Comment by zfi** [comment]
Has this been pushed into the demo branch yet?

**Comment by wstodghill** [comment]
@zfi,  Not sure what that means - I am trying not to fowl things up here - I know that right now in BlocklyProp Beta Demo - we have a working and corrected block with a duration setting from 1 - 65,535.

**Comment by zfi** [comment]
I am just trying to verify that the block @kgracey viewed on the dev system actually made it up to the demo system.

@dcarrier-parallax: Which commit contains this update?
