### ISSUE TITLE
S3 block revision: drive distance

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#529]
@dcarrier-parallax for this block we need some revisions:
![screen shot 2016-08-14 at 12 55 38 pm](https://cloud.githubusercontent.com/assets/9534148/17651514/824e311e-621d-11e6-8780-e5fe6d112dac.png)
- Revise the pull-down menu to read:
in [millimeters (mm), inches (in), centimeters (cm), inches (in), tenths of an inch (1/10th in), encoder counts (1/507th of a full rotation]
- set the default as in 
- remove the encoder ticks per unit of measure
- remove commas
- remove the capital I in "In"
- remove the statement "and wait until the motors stop moving, before continuing to run blocks"
- change speed to (-100 to 100%) for both left and right

Push a new version to demo and I'll give it a look.

**Comment by wstodghill** [comment]
Love it!

**Comment by wstodghill** [comment]
@kgracey - To be consistent with Tutorial #3.2, this should be called a move distance block.

The tutorial also references max or maximum speed which I think is better, but at the least the block and Tutorial terms should match.

Please comment and you might need to update the info above.

**Comment by kgracey** [comment]
We've met on this one and came up with the current solution, so it's closed.
