### ISSUE TITLE
S3 block revision: change LEDs - (Fixed?) now works

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#530]
@kgracey - I would like to propose that revise this S3 LED block as noted. The current four color choices are perfect for this simplified block. I guess checked and black (off) would be the best defaults as current used.

![change_led_block](https://cloud.githubusercontent.com/assets/8891440/17655744/7fc3dbce-6277-11e6-9e6a-ca50d958f65a.JPG)

Check Box line should read:     change LEDs (ckbox) (ckbox) (ckbox)
Color Picker line should say:                     to (pkbox) (pkbox) (pkbox)

proposed appearance (I did not know exactly how to create this block with the modified color picker)

![change_led_cap](https://cloud.githubusercontent.com/assets/8891440/17655977/9af91f0a-627a-11e6-8267-e8ac0a08b0ca.JPG)

**Comment by wstodghill** [comment]
@kgracey and @dcarrier-parallax - looks like we have bug the the revised change these LEDs block - I get the following message when I try to compile:

![led block compile error](https://cloud.githubusercontent.com/assets/8891440/17717362/35a88a78-63d3-11e6-8ba1-db166e52f1bd.JPG)

I notice also that the yellow is amber now too. The offending color is ff7f00 - which is the amber. Don't know if the change was accidental or a decision. Whether we decide to use as on of the simple defaults yellow or amber - we will need to fix in on our Tutorial Ken. I sort of thought our LED looked more yellow. ;-) 

Please take a look and let me know...

**Comment by wstodghill** [comment]
Which of these LEDs from the new Scribbler Object are we trying to use in this block?

 ![led_constants_scribbler_object](https://cloud.githubusercontent.com/assets/8891440/17738093/7323a950-6455-11e6-8a3f-8dafd564ccdb.JPG)

**Comment by wstodghill** [comment]
@kgracey and @dcarrier-parallax - okay - The current block shown with the more amber/orange color picker WORKS now - David - did you fix this?

If you verify - I'll close this.

**Comment by kgracey** [comment]
This issue has settled too.
