### ISSUE TITLE
S3 block revision request: drive (simple by David)

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#532]
@kgracey - might we modify the S3 drive block (simple by David) as follows - drop-down menus woud remain unchanged

![simple_drive_block](https://cloud.githubusercontent.com/assets/8891440/17676457/40b12874-62f4-11e6-8b54-102523a27b67.JPG)

but, the text (with default drop-downs) would say...
drive (forward) going (straight) at (full) speed 

Note - all lowercase.

**Comment by kgracey** [comment]
OK, we just fixed this one but replaced “and go” with “and”. It should be live shortly.

**Comment by wstodghill** [comment]
Great! Just as clear!

**Comment by kgracey** [comment]
Another issue closed!
