### ISSUE TITLE
S3 block revision request: (was) Stop driving (simple by David)

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#533]
@kgracey - might we modify the Stop drive block (simple by David) as follows... Color remains the same.

![081416stop_block](https://cloud.githubusercontent.com/assets/8891440/17676739/7a737944-62f5-11e6-9d42-c2ad1d49589c.JPG)

block would become
drive stop

Note - all lower case

**Comment by kgracey** [comment]
This one we will keep as-is. Send over more revisions you have in mind since we are working on the source code now.

**Comment by wstodghill** [comment]
Got it! Thanks...

**Comment by wstodghill** [comment]
@kgracey and @PropGit - I think this Issue can be closed!
