### ISSUE TITLE
S3 block revision request: (was) Spin in place (simple by David)

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#534]
@kgracey - might we modify the Spin in place block as follows? Color remains the same - drop down for cw or ccw (symbols) remains unchanged, drop down for degree remains unchanged, drop down for speed remains unchanged, and drop down for stop or continue remains unchanged - I willing to eliminate this because I cannot figure out what it does - seems to function the same when I have tried it.

![081416spin_in_place_block](https://cloud.githubusercontent.com/assets/8891440/17676864/f5413256-62f5-11e6-975a-bebd11dbadab.JPG)

Text would be as follows with defaults shown -Ken please decide on version 1 or 2

Version 1 - spin (direction symbol) for (degrees) at (full) speed
or version 2 - spin (direction symbol) for (degrees) at (full) speed - then (stop)

**Comment by kgracey** [comment]
Done, to be visible shortly,

**Comment by wstodghill** [comment]
Great! When those are done I will integrate them into something I've been working on...

**Comment by kgracey** [comment]
Addressed!
