### ISSUE TITLE
S3 block revision request: Play a tone

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#535]
@kgracey - might we revise the Play a tone to two OR three blocks? Now it is as so...
![play_tone](https://cloud.githubusercontent.com/assets/8891440/17677796/095ec10a-62fa-11e6-8e43-3e8dd866102d.JPG)

Please see the following revisions

Choice One (with key for value inserts) Note - all lowercase
play a tone (1 to 10,000) Hz
for a duration of (1 to 8,000) ms
at a volume of (0 to 100) %

Choice Two (with key for value inserts) Note - all lowercase
play a tone (1 to 10,000) Hz
and play a tone (1 to 10,000) Hz
for a duration of (1 to 8,000) ms
at a volume of (0 to 100) %

Choice Three same as above removing volume and make a separate volume control with key for value insert - Note - all lowercase
set volume (0 to 100) %
I think we need a block like this anyway!

**Comment by wstodghill** [comment]
@kgracey - anyway to get the stand alone set volume block back - should I make a request as a separate issue. It would be restoring something we had... It allowed the possibility of a single volume adjustment at the "top" of a program with other variables - set one place - easy change.

**Comment by kgracey** [comment]
We have rolled the volume control into the block. We will close this issue.
