### ISSUE TITLE
S3 block requests: function blocks 

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#536]
@kgracey - may we please have the function blocks available for the S3 - they are elsewhere in BlocklyProp, but we lost them. They are perfect as is...

![function_blocks](https://cloud.githubusercontent.com/assets/8891440/17678339/510c11a4-62fc-11e6-9a82-8811dcaa8c3e.JPG)

**Comment by kgracey** [comment]
The function blocks are coming back, but only the first and fourth on your list below (no return blocks or keyed versions since our variables are global. Their omission was somewhat accidental.

**Comment by wstodghill** [comment]
Understood and very excited!

**Comment by kgracey** [comment]
I’m equally EXCITED about this!

**Comment by kgracey** [comment]
![screen shot 2016-08-24 at 10 43 09 am](https://cloud.githubusercontent.com/assets/9534148/17940728/39685ad6-69e5-11e6-829d-ccc2544fa881.png)

This issue is ALMOST resolved - we simply need to remove the "gear" which allows inputs to the block. @zfi can you figure this one out?

**Comment by kgracey** [comment]
Tested and verified. Thanks!
