### ISSUE TITLE
S3 block revision request: serial blocks

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#537]
@kgracey - Were we going to make the following block specific for the S3 by setting pins and baud rates? So for instance in the S3's blocks the following might just become serial init or serial initialization - we might also use the same format with text indicating pin settings and baud rate for educational purpose with no change menus.

![serial_init_block](https://cloud.githubusercontent.com/assets/8891440/17679385/d2f4c608-6300-11e6-8111-72cf97765ff6.JPG)
 
and can we revise all the following to our lowercase format? They function well otherwise in my opinion.
![serial_blocks](https://cloud.githubusercontent.com/assets/8891440/17679388/d633e7a4-6300-11e6-9abc-7467a8e7b9cc.JPG)

**Comment by kgracey** [comment]
David has these all under revision right now (as in TODAY), for XBee and Print purposes primarily. He’s working on these along with the Ping))) and Servo blocks (hacker port add-ons) for initial release.

**Comment by wstodghill** [comment]
@kgracey - the console provides nice feedback in example programs too!

**Comment by dcarrier-parallax** [comment]
For the Public Release #1 milestone, we are only including blocks that communicate with the Scribbler USB/XBee port.  (It is a single port in hardware.)  As of PR #670, these blocks match our goals for Public Release #1 milestone.  Please verify.

**Comment by PropGit** [comment]
Tested and verified through process of verifying other serial issues in this Public Release.  This set now fits our goals for this release.

![image](https://cloud.githubusercontent.com/assets/1266318/18184167/9bf6460a-704c-11e6-8a96-d630cabbdbce.png)
