### ISSUE TITLE
S3 block revision request and restore: loops

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#538]
@kgracey - can we revise the S3 loop blocks as follows... moving to all lowercase text.
![loop_blocks](https://cloud.githubusercontent.com/assets/8891440/17679909/4474a2b0-6303-11e6-9cfd-b5643bb559c3.JPG)

and restore to the S3 loop choices the following... which were removed
![loop_c_blocks](https://cloud.githubusercontent.com/assets/8891440/17679941/6068b1a0-6303-11e6-97e2-58b968cab77e.JPG)

These seemingly small issues (like font case) matter not in function, but in our ability to get final screen captures for our Learn Tutorial text.

**Comment by kgracey** [comment]
Yes, doing this one now too. The IF [ ] RETURN block is something we are trying to remove right now, as we don’t have parameter returns enabled (all variables are global). 

BTW we put a “Simple S3” menu at the top of the program. Big differences are that it has no variables, no function calls, and no boolean/integer conflict potential. I.e. Simple S3 will work with Simple S3 and the other stuff….works with the other stuff. You can mix/match but we’ll discourage that as much as possible. More on this when we talk.

**Comment by kgracey** [comment]
Issue has been addressed.
