### ISSUE TITLE
S3 block restoration: delay block

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#539]
@kgracey - just a reminder that we have discussed whether or not to restore the following block. It's function is (of course) the same as wait - but - we have featured both in our tutorials. Your call obviously!
![delay_block](https://cloud.githubusercontent.com/assets/8891440/17680088/1d370e80-6304-11e6-95e8-63033dad9ba3.JPG)

**Comment by kgracey** [comment]
delay we shall keep.

**Comment by wstodghill** [comment]
Bravo!

**Comment by wstodghill** [comment]
We have retained this function but under the wait title  - there are now two wait blocks - one a Simple Scribbler Control Block, the other an S3 Control Block that allows the use of a variable for the wait value.

Here they are 

![wait simple](https://cloud.githubusercontent.com/assets/8891440/17921972/33121af2-69a2-11e6-90f4-3e922d761e32.JPG)

![wait advanced](https://cloud.githubusercontent.com/assets/8891440/17921976/38da2042-69a2-11e6-821f-35d8255d3cfc.JPG)

I think that resolved the heart of the issue here.

**Comment by kgracey** [comment]
This issue has been resolved.
