### ISSUE TITLE
S3 block revision and request: play and play song

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#541]
@kgracey - one more we've been discussing - this may require more discussion. It the following block 
![play_note_block](https://cloud.githubusercontent.com/assets/8891440/17680287/09e53216-6305-11e6-9190-316c3668d680.JPG)
1. case police - request Play move to play
2. The unicode in the first drop down consistently gives this problem at least on my system/browser - don't know if it could be text whole note, half note, quarter note or .quarter note for example
3. Notes themselves are fine and should remain as is
4. Octive value (to technical in my opinion - have seen it elsewhere as a numerical (ordinal) value
5. Like very much the simplified volume for this block

My simplified wording with (default drop downs) would be

play (whole) note in the (first) octave at (medium) volume

**Comment by CarsonGracey** [comment]
@wstodghill, one thing this block would need is selectable or a locked BPM that is shown on the block.

**Comment by wstodghill** [comment]
@CarsonGracey - you musicians blow my mind! ;-) That was present in the old GUI as the tortoise and hare - slow down or speed up - Great call!

**Comment by kgracey** [comment]
Let me check with David and see if we can get the BPM in the Priority Release #1.

**Comment by kgracey** [comment]
We will wait on integrating the BPM feature into Priority #1 release, but leave it in Issue Tracker as a requested feature. 

First, we’d like to port over the S2 songs from the S2 GUI into Blockly.

**Comment by wstodghill** [comment]
I made this a while back - early - just an idea - might get us started.
![play song block](https://cloud.githubusercontent.com/assets/8891440/17684251/9dc1366e-631f-11e6-9544-a3dbfe7b23d6.JPG)
with this drop down...
![play song drop-down](https://cloud.githubusercontent.com/assets/8891440/17684255/a9772202-631f-11e6-9900-3373a31be08e.JPG)

https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#kuq4sk

**Comment by CarsonGracey** [comment]
I see what you mean, maybe it would be easier if we list a few tempos: https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#iemfqf 

![bpm](https://cloud.githubusercontent.com/assets/20099916/17715590/b1a19940-63b9-11e6-912e-5115983f1186.PNG)

**Comment by wstodghill** [comment]
@CarsonGracey - could we eliminate the for (0) (ms) and say something like this with dropdowns as shown and an insert value? I love the tempo idea - need a ) after 168 bpm.

play song (entertainer) (insert value) time at tempo (largo (60 bpm)

**Comment by MatzElectronics** [comment]
Closing this - doesn't really align with the project any more, plus adding full song to a block would increase the memory overhead to a dangerous point, especially now that we are using c.
