### ISSUE TITLE
Limit block needs case change

### ISSUE THREAD

**Issue by dcarrier-parallax** [parallaxinc/BlocklyProp#543]
The 'Limit' block, common to both 'C' and 'Spin' programs, needs the 'L' changed to lowercase, to match all of the other math operators.

![limit](https://cloud.githubusercontent.com/assets/11430907/17687091/dc4c699c-6326-11e6-96bd-6b7ac4cb4aca.png)

**Comment by wstodghill** [comment]
Anyway to find out block info like Name, OPTIONNAME, dropdown NAME, Colour, Input type? Is there something I don't know how to find?

That way I could build a block that was ready to go...

**Comment by DarkmatterVale** [comment]
I'm not sure the block factory has that functionality @wstodghill but I'll let you know if I find it...

**Comment by wstodghill** [comment]
Should this be able to connect with a if/do block? Right now it does not...

![if do](https://cloud.githubusercontent.com/assets/8891440/17895260/2a3cbe0e-6912-11e6-9f0b-7fe956bb6c56.JPG)

**Comment by DarkmatterVale** [comment]
I don't think it should; the limit function returns a float, not a boolean

**Comment by wstodghill** [comment]
Gotcha!

**Comment by CarsonGracey** [comment]
Verified.
