### ISSUE TITLE
Sony Remote Control: button text improvement discussion

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#546]
Here's an example of a Blockly command in Sensors that does so much, but looks so whimpy. Underneath the Sony infrared handheld remote is a library that sorts out a variety of IR pulses and turns them into nice decimal numbers. 

But our Blockly implementation text makes it look like a pushbutton. 

What's a better text explanation we could put in this block? The function is fine - it works - but we can do better with the text. 

Ideas?
![screen shot 2016-08-16 at 12 48 12 pm](https://cloud.githubusercontent.com/assets/9534148/17713034/b326efb0-63ad-11e6-98eb-d58f4ea9e18c.png)

**Comment by wstodghill** [comment]
get Sony remote input value at pin# (input)

**Comment by DarkmatterVale** [comment]
@kgracey would you like to see a change of the block text in release 1?

**Comment by kgracey** [comment]
Yes, we need to get this done. @zfi you can change the text to "Sony remote value received at pin#"

**Comment by zfi** [comment]
PR submitted. This update will be on Demo at 10:00 AM PST.

**Comment by kgracey** [comment]
Tested and verified!
