### ISSUE TITLE
S3 rotate the Scribbler robot block: ERROR

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#547]
@kgracey and @dcarrier-parallax,

If I understand how this block should work - we have an error - regardless of setting of the around a radius in "value" - my S3 spins in place at the top speed (both wheels) for the degrees set. 

The rotational degree setting seems to have a slight error too - but this could be a calibration issue - will we have a user calibration block (per the Scribbler Spin Object?

![rotate_the_scribbler_robot_block](https://cloud.githubusercontent.com/assets/8891440/17725403/b71984da-6410-11e6-8c7e-5bd8e46cafe7.JPG)

**Comment by wstodghill** [comment]
Anybody else tested this? As of yesterday, I still could not get it to work other that rotating in place.

**Comment by kgracey** [comment]
@dcarrier-parallax is looking at this today. It might be best that if he can't readily figure out the issue that we simply remove the second line "around a radius". We will either modify the block or make it work as intended today.

**Comment by dcarrier-parallax** [comment]
This was addressed by PR #670. Please Verify.

**Comment by kgracey** [comment]
Tested and verified!

**Comment by wstodghill** [comment]
Verified here too! Works great!

**Comment by wstodghill** [comment]
I do not believe this works properly in the current version (at least not on the live version of BlocklyProp.
