### ISSUE TITLE
S3 block request: comment block

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#548]
@kgracey and @dcarrier-parallax - might we add the comment block that is present in the C section of BlocklyProp to the S3 blocks - I know that commenting Blockly code is a bit busy - but, it might be very helpful for creating teaching code. A student could look at an example and see what the coder was thinking, doing, and why.

![comment_block](https://cloud.githubusercontent.com/assets/8891440/17727097/a0e09238-641c-11e6-8686-f9a879bcf49e.JPG)

If the block had no connections - could it be placed anywhere? Here is that idea and a link to the Block Factory code...

![comment_block_alt](https://cloud.githubusercontent.com/assets/8891440/17727200/572fe3b8-641d-11e6-932c-16210d8e9a9a.JPG)

https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#o5dqtw

**Comment by michel-cf** [comment]
I would at least put in a small text that indicates that it's a comment. Otherwise, once the text has been changed it might get confused with a string.

The second block could be placed anywhere (the same for the first one), except that you can't connect it to anything.

**Comment by DarkmatterVale** [comment]
The actual block has text (see https://github.com/parallaxinc/BlocklyProp/blob/master/src/main/webapp/cdn/blockly/generators/propc/base.js#L181). Must be another merge issue...

**Comment by wstodghill** [comment]
I originally made a comment block on the Block Factory with no color to distinguish it from the program - it looked like this.

![comment](https://cloud.githubusercontent.com/assets/8891440/17743409/411bd018-6469-11e6-92bc-72245c251dca.JPG)

https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#ztahue

**Comment by kgracey** [comment]
@dcarrier-parallax and I discussed. We will create this and call it a "Note".

**Comment by PropGit** [comment]
This was addressed by PR #649.  Please Verify.

**Comment by PropGit** [comment]
Tested and verified correct.
