### ISSUE TITLE
Reconfigure the MMA7455 sensor block to a virtical orientation

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp#557]
The MMA7455 block under the Sensor >> MMA7455 menu item is so wide as to scroll off of the work surface. Please change the orientation from horizontal to vertical.

**Comment by DarkmatterVale** [comment]
I got this done on my local branch but I need to test before pushing to demo

**Comment by CarsonGracey** [comment]
Tested and Verified.
