### ISSUE TITLE
Add terminal support for 9,600 baud, set default baud rate at or below 57,600 baud.

### ISSUE THREAD

**Issue by dcarrier-parallax** [parallaxinc/BlocklyProp#558]
The Scribbler 3 hardware does not differentiate between active USB UART and XBee module connections, and the XBee module defaults to 9,600 baud, so for compatibility reasons, the terminal needs to also support 9,600 baud.

The terminal currently only supports 115,200 baud, which due to the lack of slow control on our current products, is too fast for the FT231X buffer, and causes occasional missed characters, especially when the USB host is under a heavy processing load.

An quick and acceptable fix would be to default the terminal to 9,600 baud, simultaneously correcting both problems.  Ideally, the terminal would support a range of baud rates, defaulting to one assigned by the serial blocks in use.

**Comment by michel-cf** [comment]
Duplicate #490

**Comment by zfi** [comment]
Closing this issue. Please refer to issue #490 for further details.
