### ISSUE TITLE
Missing Blocks

### ISSUE THREAD

**Issue by AndyLindsay** [parallaxinc/BlocklyProp#56]
It looks like ActivityBot Library's drive speed and drive goto disappeared when the four blocks that are there now were added.

**Comment by AndyLindsay** [comment]
Actually, they are in another category called Drive.  The blocks in Drive and in ActivityBot Library should be combined into a single category.

**Comment by DarkmatterVale** [comment]
Mr. Lindsay,

Ok. I will update that. What category would you like them moved to?

**Comment by AndyLindsay** [comment]
Thanks Vale, ActivityBot, with blocks in this order.  Please note that the names have been adjusted slightly.  Drive speeds is now speeds.  ActivityBot Ramp Step is now Ramp Step.  
  * ActivityBot
    * Speeds
    * Distances
    * Ramp step
    * Set ramp step
    * Calibrate
    * Display calibration

**Comment by DarkmatterVale** [comment]
Yep. I see the name changes. I will update this over the weekend and push a commit to the master branch with the update.

**Comment by DarkmatterVale** [comment]
In the next commit, this is fixed. I will create a PR after fixing the other new issues.

**Comment by DarkmatterVale** [comment]
I believe this has been fixed.

@michel-cf do you agree? Can we close this issue?

**Comment by michel-cf** [comment]
The blocks need reorganization, so this is not important anymore.

**Comment by DarkmatterVale** [comment]
Ok. Do you have a plan to merge the Java version into the master branch anytime soon? Also, how can I see the new BlocklyProp in action? Is there a website that I can go to see it?
