### ISSUE TITLE
ColorPal Block modifications

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#561]
For the ColorPal, The current block needs to be modified to say "raw output" since it outputs three separate colors in a 24bit format with some funky ranges, and those outputs are not white balanced or adjusted in any way.  That being said, it's still valuable to have.

To bring the ColorPal in line with how we are "standardizing" color, we need to create a second ColorPal block that just outputs its color into a single variable that can then be used with other color blocks/values that have since been created.  For example, you can draw a square on the OLED screen who's color is determined by what the ColorPal sees.  Or the M&M sorter project can be easily accomplished with the color compare block.

The new ColorPal block should look something like this:
![image](https://cloud.githubusercontent.com/assets/19737272/17266659/ce214844-55af-11e6-9a7b-b7f96c6362e4.png)

A request to add a function was submitted to the SimpleLibraries ColorPal library here: https://github.com/parallaxinc/Simple-Libraries/issues/29.  This block would depend on this function (or at a minimum the math done by this function).  To be clear, this new function is not an exact representation of the color sensed by the ColorPal.  Variations between sensors and creating an exact curve make it nearly impossible to get it exactly right...but this approximation comes close enough :)

**Comment by DarkmatterVale** [comment]
Is it alright the new block will be dependent on https://github.com/parallaxinc/Simple-Libraries/issues/29? I'd prefer not to show all that math to a simple user...

**Comment by MatzElectronics** [comment]
Yes, I think Andy is aware and I'll let you know when that addition gets
made to Simple Libraries.  I don't want to expose that math either...it's a
bit ugly :)

**Comment by MatzElectronics** [comment]
Hi!

Andy just submitted this, so you should be able to include it - it may
require the server's simple libraries to be updated before it works,
however.  He's doing some other bug fixes too.  I'll make sure to let Jim
know it's coming.
Thanks,
Matt

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by zfi** [comment]
The updated library has been migrated to the deployment server and pushed to Demo. I think we can close this issue now.

**Comment by MatzElectronics** [comment]
Good morning,

I found a problem with some of the related blocks - specifically "color compare" and "get red/green/blue value from".  The math is being done in the Java, which is fine for preset colors, but not for programs.  Below is an example of a program where we want the Prop to do the math dynamically (I understand the math for this isn't pretty, so maybe we need to talk about a couple more simple libraries functions...I don't know)
There is also the problem (I think) of the prop not having a native ABS function.

Sorry this is so complicated and I'm being picky...

M&M sorter:
![image](https://cloud.githubusercontent.com/assets/19737272/17940506/55ec1310-69e4-11e6-91df-c68de9820df1.png)

**Comment by DarkmatterVale** [comment]
Ah, I see what you are saying...I think the best solution would be to add some more functions to the Simple Libraries so we do not have to present this math to the user. @MatzElectronics what do you think?

**Comment by MatzElectronics** [comment]
I'll get in touch with Andy...and get back to you soon.

**Comment by DarkmatterVale** [comment]
Once the new functions are in SimpleLibraries, I think this issue will be resolved

**Comment by MatzElectronics** [comment]
If anyone has the stuff to test this, here's a place to start:
http://demo.blockly.parallax.com/blockly/editor/blocklyc.jsp?project=302

**Comment by kgracey** [comment]
@MatzElectronics I tried to test this but encountered the following error from GCC:
Required libraries: colorpal, colormath, simpletools
Library compile order: None needed
single.c: In function 'main':
single.c:24:21: error: incompatible types when assigning to type 'char[128]' from type 'char *'
single.c:28:21: error: incompatible types when assigning to type 'char[128]' from type 'char *'
single.c:32:21: error: incompatible types when assigning to type 'char[128]' from type 'char *'
single.c:36:21: error: incompatible types when assigning to type 'char[128]' from type 'char *'
single.c:40:21: error: incompatible types when assigning to type 'char[128]' from type 'char *'

It seems that the libraries are present, but there's a problem with data types? The code created from Project 302 looks like this in case you can run it in SimpleIDE:

**Comment by MatzElectronics** [comment]
This might actually be a bigger problem... let me get to a PC and I can explain...

**Comment by kgracey** [comment]
We can always set it for a future release, like in November if it’s going to hang us up too long. I’m all for seeing it resolved, though, as I like the simplicity of what you proposed.

**Comment by DarkmatterVale** [comment]
Ok, so I looked this error up and I know what's the problem; we are attempting to set an array to a string which you can't do. I'm looking up how to fix this and I'll send a PR as soon as I figure it out...

**Comment by MatzElectronics** [comment]
@DarkmatterVale Off the top of my head, there are two possible things I can think of - the first is to initialize as char *varName; instead of char varName[128];  but I don't know if that will create other issues or work more than once.  The second is to use [strcpy](http://www.tutorialspoint.com/c_standard_library/c_function_strcpy.htm), but again, not 100% what the nest way to implement it without working it out first.

**Comment by DarkmatterVale** [comment]
I tested this in SimpleIDE, and using ```char *``` works fine. @MatzElectronics What would be the implications of changing all instances of ```char [128]``` to ```char *```?

**Comment by MatzElectronics** [comment]
@zfi - could you weigh in on this?  I'm not 100% sure if this is the best solution or not, because I don't know how memory is allocated, etc.  For example, does giving it a short string first, and a longer one later create an issue?:  I don't have an ActivityBoard in front of me, so can you try this:?

`char *varName;

#include "simpletools.h"

int main()
{
  
  varName = "Cheese";
  varName = "Cheese and Crackers";
  print("%s\n", varName);

  varName = "Yummy!";
  print("%s\n", varName);
}
`

If that works, we may be on to something...

**Comment by MatzElectronics** [comment]
@DarkmatterVale I just tried the above, and it seems to work, so the next trick is figuring out what blocks would be affected.

**Comment by DarkmatterVale** [comment]
All blocks that use strings will be affected because you are only able to set a char array once...I will send a PR with the changes that will hopefully resolve this issue

**Comment by DarkmatterVale** [comment]
@MatzElectronics I think #614 will fix the problem

**Comment by MatzElectronics** [comment]
Cool, we'll give it a shot when it get's pulled in!

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by zfi** [comment]
When the string gets longer,  the string function will allocate a new memory block large enough to hold the new string. You can get fragmented memory over time. There is a longer answer, maybe for Monday.

**Comment by MatzElectronics** [comment]
I think in this case, if *varName works, let's just use it.

**Comment by DarkmatterVale** [comment]
I agree with @MatzElectronics

**Comment by DarkmatterVale** [comment]
Has this issue been satisfied yet?

**Comment by MatzElectronics** [comment]
Mostly - the blockly end is taken care of and appears to be functional.  There is yet another glitch (sorry) in the colormath library that makes the color comparison block not work.

**Comment by MatzElectronics** [comment]
Tested and Verified 👍
