### ISSUE TITLE
Terminal - Position Cursor (y) [ASCII 15] - Uses Visible Position Instead of Buffered Position

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#569]
The Position Cursor (Y) control character sequence [ASCII 15] moves the cursor within the constraints of the visible text, but the intent is that it moves it within the buffered rows (the logical buffer for which the display window is only showing a small portion).

This means that if rows 0, 1, and 2 have scrolled off-screen, the sequence 15, 1 actually positions the cursor on logical row 3 (which is currently at the top of the visible display) instead of on logical row 1 (which is two rows above the top of the current display, and not visible until the user scrolls back; as intended).

Please make the Position Cursor (Y) control character sequence position the logical cursor within the receive buffer instead of strictly within the smaller visible display, and ensure that it _does not scroll_ the display.

[ Relates to Issue #321 ]

**Comment by michel-cf** [comment]
As far as I can determine with the used library, I don't have control over the buffer.

Every command works on the visible data.

**Comment by PropGit** [comment]
@michel-cf - that's what I was afraid of; however, the same behavior isn't true of Position Cursor (x) [ASCII 14]; it happily places the cursor and emits text beyond the boundaries of the visible display (as intended).

Run this program to see:  
http://demo.blockly.parallax.com/blockly/projectlink?id=285&key=68010fd0-1e0a-43f3-b5ce-73cfa3db9e80

**Comment by PropGit** [comment]
This is likely related to Issue #525 and we currently don't know how to fix it.  It is in the same classification- not expected to be a problem, yet, but in the near future it will be a more visible problem.
