### ISSUE TITLE
C Language Block Organization and Naming

### ISSUE THREAD

**Issue by AndyLindsay** [parallaxinc/BlocklyProp#57]
I just want to get the ball rolling on this subject so that we have a plan when block organization becomes an 

option.  Here is a first cut, along with some implicit function renaming suggestions.   

Remove: DigitalWrite, DigitalWrite, DigitalRead

## Function Outline

* Control
  * If
  * Repeat
  * Repeat # times

* Conditions
  * Is equal
  * This and/or that
  * Not
  * True/false

* Console
  * Print ""
  * Print
  * Scan (Currently missing)

* Functions
  * Function do
  * Function do return 

* Math
  * Value
  * Operation +, - , etc
  * Square root
  * Limit max/min
  * Increment/decrement

* Bit Math
  * Shift
  * AND/OR
  * NOT

* Variables
  * Variable item as value
  * Variable shared item as value
  * Item = 
  * = item
  * Pointer item as file/ value
  * Pointer set item = 
  * = pointer get item

* Pin
  * High
  * Low
  * Input
  * Toggle
  * Reverse
  * Set direction
  * Get direction
  * Set state
  * Get state
  * Set output
  * Get output
  * Set group directions
  * Get group directions
  * Set group states
  * Get group states
  * Set group outputs
  * Get group outputs

* Timed Operations
  * Pause
  * Frequency
  * Pulse out
  * Pulse in
  * RC charge
  * RC discharge

* Voltage
  * Measure A/D volts
  * Set D/A volts
  * Measure A/D
  * Set D/A

* Memory
  * EEPROM int to
  * EEPROM int from
  * EEPROM float to
  * EEPROM float from
  * EEPROM text to
  * EEPROM text from
  * SD card mount
  * SD file open
  * SD file close
  * SD card int to
  * SD card int from
  * SD card float to
  * SD card float from
  * SD card text to
  * SD card text from
  * ? get the inputted int
  * ? get the inputted float
  * ? get the inputted text

* Communicate
  * Shift in
  * Shift out
  * I2C new bus
  * I2C in
  * I2C out
  * Serial init
  * Serial transmit
  * Serial transmit ""
  * Serial read byte

* Audio
  * WAV Play
  * WAV Status
  * WAV Volume
  * WAV Stop

* Display
  * LCD init
  * LCD clear
  * LCD print
  * LCD print number
  * LCD action

* Sensor
  * ETape liquied level get
  * HMC5883 compass initialize
  * HMC5883 compass 3d read
  * Joystick X
  * Joystick Y
  * MX2125 rotation
  * MX2125 tilt
  * MX2125 Accelerometer X
  * MX2125 Accelerometer Y
  * MMA7455 
  * PAM7Q GPS start
  * PAM7Q GPS get latitude
  * PAM7Q GPS get longitude
  * PAM7Q GPS get velocity
  * PAM7Q GPS get heading
  * PAM7Q GPS get altitude
  * PAM7Q GPS get # of satellites tracked
  * Ping))) Distance
  * PIR Motion
  * RFID enable
  * RFID get
  * RFID disable
  * RFID close
  * SF02 laser range get
  * SONY remote button get
  * Sound impact run
  * Sound impact get
  * Sound impact end

* Motor
  * Servo angle
  * Servo speed
  * Servo set ramp
  * PWM start
  * PWM set
  * PWM stop

* Robot
  * ActivityBot
    * Speed
    * Distance
    * Ramp step
    * Set ramp step
    * Calibrate
    * Display calibration
  * Servo Differential Drive
    * Drive pins
    * Drive speeds
    * Drive setRamp
    * Drive sleep
    * Drive stop

**Comment by DarkmatterVale** [comment]
I will work on this and get the first cut done within the next week.

I will create a PR when I am done ( this will include the other 2 issues' fixes as well ).

**Comment by AndyLindsay** [comment]
This list is going to be revised significantly in a few weeks.

**Comment by DarkmatterVale** [comment]
I am going to close this issue since the revised version is in a Google doc.
