### ISSUE TITLE
Terminal - Position Cursor (y) [ASCII 15] - Row Index is off by 1

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#570]
The Position Cursor (Y) control character sequence [ASCII 15] places the cursor on the wrong row; it's off by 1.

The Receive Buffer's topmost rows are numbered 0 to 255, but sending 15, 1 to the terminal positions the cursor on row 0 (the first row) instead of on row 1 (the second row).  Incidentally, sending 15, 0 also places it on row 0, but I believe that is due to a different problem detailed in Issue #569.

[ Relates to Issue #321 ]

**Comment by michel-cf** [comment]
This was first 0 based and then I changed it to be 1 based. I believe that was to match the Parallax Serial Terminal.
Are you sure it needs to be 0 based?

**Comment by PropGit** [comment]
Yes, Parallax Serial Terminal is 0-based. In fact, a lot of the control I'm testing I first do so in Parallax Serial Terminal, then in Blockly Terminal, with the exception of rare features that we intentionally want to be different.

**Comment by PropGit** [comment]
Verified fixed.
