### ISSUE TITLE
Terminal - Position Cursor (x) [ASCII 14] - Column Index is off by 1

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#571]
The Position Cursor (X) control character sequence [ASCII 14] places the cursor on the wrong column; it's off by 1.

The Receive Buffer's columns are numbered 0 to 255, but sending 14, 2 to the terminal positions the cursor on column 1 (the second column) instead of on column 2 (the third column).

[ Relates to Issue #321 ]

**Comment by michel-cf** [comment]
This was first 0 based and then I changed it to be 1 based. I believe that was to match the Parallax Serial Terminal.
Are you sure it needs to be 0 based?

**Comment by PropGit** [comment]
Yes, Parallax Serial Terminal is 0-based.  In fact, a lot of the control I'm testing I first do so in Parallax Serial Terminal, then in Blockly Terminal, with the exception of rare features that we intentionally want to be different.

**Comment by PropGit** [comment]
Verified fixed.
