### ISSUE TITLE
Add copy/paste or local save/open support

### ISSUE THREAD

**Issue by dcarrier-parallax** [parallaxinc/BlocklyProp#578]
The Blockly documentation references copying and pasting blocks and some implementations of Blockly allow locally saving and opening files.

Supporting either one of these abilities will allow 3rd-party programs to integrate into Blockly and allows us to move projects between test and production servers.

**Comment by wstodghill** [comment]
That would really be a great addition.

**Comment by kgracey** [comment]
@michel-cf would this be something you could enable from their tool suite?

**Comment by michel-cf** [comment]
I could take a look. Please pass it to @PropGit to put it on my task list depending on priorities.

**Comment by MatzElectronics** [comment]
@kgracey @zfi @dcarrier-parallax @michel-cf Update: I have the download part of this working in my dev, and have a good start on the upload part.  I still need to test replacing the xml inside of the variable that contains it, and if that works, I just need to build the UI component to handle the upload.  The upload code I have so far even does a bit of validation to ensure that you don't load a garbage file into your program.

This would also allow someone to download something they built in demo and upload it to production.

**Comment by MatzElectronics** [comment]
@kgracey @zfi @dcarrier-parallax @michel-cf New update!!!  I stayed up too late :)
I have **download**, **upload** (both replace and append), and **clear workspace** working in my dev!!!
I'll submit a PR sometime mid-day tomorrow.  I have to comment out some other code in the same file and do a bit of cleanup before submitting.

![image](https://cloud.githubusercontent.com/assets/19737272/21521986/80b29c10-ccb6-11e6-92b4-430bfd1e7373.png)

![image](https://cloud.githubusercontent.com/assets/19737272/21521992/8b6653d6-ccb6-11e6-859e-4676df29c567.png)

**Comment by MatzElectronics** [comment]
In MatzElectronics-upDownLoad branch

**Comment by MatzElectronics** [comment]
Tested and verified
