### ISSUE TITLE
Block change/add

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#579]
The OLED block "text size ______" should also have font.  It should be "text size __dropdown__ font __dropdown__"

**Comment by MatzElectronics** [comment]
Just realized this might be because it was missing in documentation.  There is a PR in SimpleLibraries to fix it.

**Comment by zfi** [comment]
@MatzElectronics The function that the text size block calls has only one parameter:

    void oledc_setTextSize(char s);

Is there another function call that supports the size and font parameters, or should the block make calls to oledc_setTextSize() and oledc_setTextFont()?

**Comment by MatzElectronics** [comment]
It should make calls to both functions...

**Comment by zfi** [comment]
Updated code and issued PR #596

**Comment by kgracey** [comment]
Tested, verified! Works wonderfully.
