### ISSUE TITLE
S3: Wrapper fix for Servo, Ping))) 

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#580]
@dcarrier-parallax reminder to repair the block wrapper so we can use the Ping and Servo.

**Comment by PropGit** [comment]
This was addressed by PR #649.  Please Verify.

**Comment by zfi** [comment]
The commit is dependent on a Scribbler-3 library update that has not yet landed.

**Comment by dcarrier-parallax** [comment]
Scribbler-3 libraries are now up to date. Please Verify.

**Comment by kgracey** [comment]
Fixed and verified!
