### ISSUE TITLE
S3: Scribbler firmware "restore" block

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#581]
@dcarrier-parallax we need a block for this (like the "halo" on the S2 GUI).

**Comment by PropGit** [comment]
Pushing to the next release after this one.

**Comment by kgracey** [comment]
The name of the file scribbler_default.binary and it is part of the standard program file installation in the S3 GUI.

**Comment by wstodghill** [comment]
![simple restore s3 demo](https://cloud.githubusercontent.com/assets/8891440/18766517/3f3da6b6-80e0-11e6-96ed-a6f4e501b310.JPG)
See - https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#8f7p5r

My other idea was to have the block include this image.

**Comment by PropGit** [comment]
Another issue was created for this unknowingly: Issue #717.

@wstodghill - But without top and bottom connectors.  This block does not below with any other blocks; it should stand alone, like this:  https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#gra9ed

**Comment by wstodghill** [comment]
@PropGit - Exactly right about the connectors! Went looking for the other thread, but I guess I found this one.

**Comment by PropGit** [comment]
@wstodghill - I searched for and couldn't find this one before I created the other one. ;-P

**Comment by zfi** [comment]
This issue is addressed in #717. Work is proceeding on that issue, so we will close this one.
