### ISSUE TITLE
S3 Block Question

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#584]
@kgracey - Is anything like the GUI "flip a coin" anticipated for the S3

**Comment by kgracey** [comment]
We could implement a RANDOM block I believe - it’s already part of the S2.spin library (if it exists in the S2 GUI). 

Let me check with David and see if we can squeeze this into Priority Release #1. I realize we need it for getting out of corners, among other things!

**Comment by wstodghill** [comment]
@kgracey - Yep - I was looking at idea taking old  Scribbler or S2 GUI code screen captures...
 making the exact same program in BlocklyProp and doing a screen captuere... 
With a tiny intro - such a two page lesson would be a gold mine for teachers moving from the S2 to the S3!

**Comment by kgracey** [comment]
Closing this issue because it is addressed in https://github.com/parallaxinc/BlocklyProp/issues/589
