### ISSUE TITLE
S3 - Remove unsupported Serial control characters

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#585]
The S3 Block __send control character__ includes many control characters that the Terminal current does not support.
![image](https://cloud.githubusercontent.com/assets/1266318/17948609/669d1390-6a06-11e6-9ce5-5597b7190c99.png)

Please remove (for now):
- Bell
- Tab
- Escape
- Delete

They will be added back in when Terminal supports them.

The next two posts below can be ignored as they do not relate to this issue specifically.

**Comment by wstodghill** [comment]
@PropGit - Don't want to muddle this issue (but I could not find the previous issue regarding this). On the S3 the Carriage Return and/or Line Feed - are not creating a space between the lines on the terminal anymore. Could this be check when these revisions are made?

This is BlocklyProp Code example I am running - http://demo.blockly.parallax.com/blockly/editor/blocklyspin.jsp?project=113

Here is a partial screen capture of the code 

![partial_screen_cap](https://cloud.githubusercontent.com/assets/8891440/18027850/dfeedab0-6c33-11e6-8fb4-2688e6c41744.JPG)

and here is what shows up on the terminal 

![serial_terminal](https://cloud.githubusercontent.com/assets/8891440/18027854/f4a48a68-6c33-11e6-829f-7fa1bb747569.JPG)

**Comment by PropGit** [comment]
I think you're referring to Issue #588, which was fixed on Friday.  Now your code generates this output.

![image](https://cloud.githubusercontent.com/assets/1266318/18064406/20d58a2c-6de4-11e6-8730-1af357fbe311.png)

Is that what you were expecting?

**Comment by dcarrier-parallax** [comment]
I would like to add all of the control characters that Blockly's terminal does support.
Here's the remaining non-ASCII control characters that the Parallax Serial Terminal supports:

1	Home cursor
2	Position Cursor in x,y
3	Move cursor Left
4	Move cursor Right
5	Move cursor Up
6	Move cursor Down
11	Clear to end of line
12	Clear lines below
14	Position cursor in X
15	Position cursor in Y
16	Clear screen

Which of them does Blockly's terminal support?

**Comment by PropGit** [comment]
BlocklyProp currently supports 2, 14, 15, and 16 only (in addition to 10 and 13, of course).

**Comment by wstodghill** [comment]
@PropGit - YES!

**Comment by PropGit** [comment]
This was addressed by PR #649.  Please Verify.

**Comment by PropGit** [comment]
Tested - Failed.  

- Partly because of Issue #655
- Partly because [I blindly answered David's question](url
![image](https://cloud.githubusercontent.com/assets/1266318/18138359/2cab3d32-6f61-11e6-992d-5804e2527637.png) without pointing out that 2, 14, and 15 required 2, 1, and 1 additional position characters to follow it.  This block may not be the best implementation for positioning.  At the very least, 2, 14, and 15 (position x,y, position x, position y) should be removed from this block.

**Comment by dcarrier-parallax** [comment]
This was fully addressed in PR #670. Please Verify.

**Comment by PropGit** [comment]
Though the multi-character control codes were not removed, the intend was that special control characters can be sent with this block, followed by 0, 1 or 2 additional send character blocks.  I agree with this implementation under that conditions we have with the S3 Robot.

Tested and verified correct.
