### ISSUE TITLE
OLED Text and Number Blocks (three of them)

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#586]
@zfi I met with Matt and obtained the final details for the OLED. These are the blocks we need to create for the text functions:

**oledc_setCursor (x is between 0-95, and y is 0-63, but fix the char size to 0)**
The block could say "set cursor at (X, 0 to 95) and (Y, 0 to 63)
![screen shot 2016-08-24 at 2 41 50 pm](https://cloud.githubusercontent.com/assets/9534148/17948662/a0baa3ee-6a06-11e6-931a-4c2b75ec78db.png)

**oledc_drawText (just a plug in for a string)**
The block text could say "print text "[  ]" "
![screen shot 2016-08-24 at 2 47 00 pm](https://cloud.githubusercontent.com/assets/9534148/17948817/5105b40a-6a07-11e6-847d-493abafdb80b.png)

oleic_drawNumber (second parameter is a drop-down menu with DEC, BIN, OCT and HEX)
The block text could say "print number [  ]"
![screen shot 2016-08-24 at 2 52 40 pm](https://cloud.githubusercontent.com/assets/9534148/17948958/0eb57756-6a08-11e6-96f1-c8a1100e1edd.png)

Matt says that you already have the correct Simply Libraries on the server.

**Comment by zfi** [comment]
These blocks are addressed in PR #590 and #591.

**Comment by CarsonGracey** [comment]
Tested and Verified.

![oled print](https://cloud.githubusercontent.com/assets/20099916/18016880/82ca57fc-6b83-11e6-8f33-2da0d384fb43.PNG)

These two blocks just need the value input to be between the brackets [ ], I would put quotes around both brackets or neither.

**Comment by kgracey** [comment]
These blocks need a little change. The quotes should be around the keyed area - remove the [] as I only intended them to be indicators for you. Also, the text block needs to accept char strings.

**Comment by zfi** [comment]
Updated both blocks. The new code has been posted to the Demo site. Please verify and close if it's all good.

**Comment by kgracey** [comment]
Yep, verified that this is now fixed!
