### ISSUE TITLE
Issue with S3 blocks not loading

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#587]
This may be a demo.blockly.parallax.com error but every time I load this project: http://demo.blockly.parallax.com/blockly/editor/blocklyspin.jsp?project=54# only part of the single block loads causing it to look like this

![white](https://cloud.githubusercontent.com/assets/20099916/17949931/ca6ed60a-6a0c-11e6-8549-a11b9697f486.PNG)

I can't interact with it unless I go View-Spin then back to View-Blocks which then in turn causes the block to appear like this

![black block](https://cloud.githubusercontent.com/assets/20099916/17949966/f7e9234c-6a0c-11e6-95ad-23ae36bc4a6e.PNG)

I have cleared my cache and the problem persists. Anyone else having this problem with the particular block or project?

**Comment by CarsonGracey** [comment]
May just be an issue with place holders?

![black blocks](https://cloud.githubusercontent.com/assets/20099916/17950090/d59b6cb8-6a0d-11e6-9485-dab2881a4f21.PNG)

**Comment by PropGit** [comment]
@CarsonGracey - Please try a browser page refresh without cache and let us know

**Comment by CarsonGracey** [comment]
Ctrl + F5 still yields the same result.

**Comment by PropGit** [comment]
@CarsonGracey - I think you're just going to have to delete it and start over.  It appears to be using blocks that don't exist anymore after the recent updates.
