### ISSUE TITLE
New BPClient changed behavior for CR

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#588]
The new BlocklyProp Client produced for Issue #490 has a negative side-effect of changing the behavior of CR (ASCII 13).

Now CR moves the cursor only to the start of the current row (not to the start of the _next_ row, as it did before).

**Comment by wstodghill** [comment]
Bug verified by me too! Glad I saw this - it helped me see it when it happened.

**Comment by PropGit** [comment]
Thanks @wstodghill.

@michel-cf - to be clear, we need CR (ASCII 13) (aka '\r' in C) to move the cursor to the first column of the next row like it did before this BlocklyProp Client update.  

NOTE: It appears that LF (ASCII 10) (aka '\n' in C) is doing that behavior now, but I'm not sure if it was doing that before or not.  Maybe their behavior was somehow swapped by this update?

**Comment by PropGit** [comment]
Tested.  I'm happy to say this is working again!
