### ISSUE TITLE
S3 Block Request ( x 2) - make a test and random true / false

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#589]
Per a conversation with Ken - we are requesting these two blocks for the S3 - they will allow us to have a function like the old GUI and Scribbler Object function of "flip a coin" along with other possibilities.
Graphic of the block is correct (unless Ken has wording suggestion) construction on the block factory link may need tweeking...

![make_a_test](https://cloud.githubusercontent.com/assets/8891440/17973331/a24d062e-6aa7-11e6-9f8e-229809fb07e7.JPG)

https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#h56g5i

![random_truefalse](https://cloud.githubusercontent.com/assets/8891440/17973341/aa235506-6aa7-11e6-89e6-ffc96c2c56f3.JPG)

https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#rsrs2e

**Comment by kgracey** [comment]
Thanks Whit - we have assigned this to @dcarrier-parallax and it marks our last feature request before launch.

**Comment by wstodghill** [comment]
@kgracey and @dcarrier-parallax - wonder if top and bottom connector would be better?

**Comment by PropGit** [comment]
This was addressed by PR #649.  Please Verify.

**Comment by dcarrier-parallax** [comment]
Our implementation includes a the last block under the 'Simple Sensors' category and the fourth and fifth blocks in the middle of the 'Math' category, as addressed by PR #670. Please verify the blocks work as formed.

**Comment by kgracey** [comment]
Both of the blocks in Simple and and "complex" S3 work.
