### ISSUE TITLE
Remove '\r' and \'n' from some Terminal blocks

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#594]
Now that we have the [New Line](https://github.com/parallaxinc/BlocklyProp/issues/574) block and _some_ cursor positioning control, we need to remove the automatic '\r' or '\n' from certain blocks.

- Remove '\r' from the code generated by __print " "__
so that 
![image](https://cloud.githubusercontent.com/assets/1266318/17979565/11a2fdd2-6ab0-11e6-9644-cffb2fd97f2b.png)
generates
```
print("My text");
```

- Remove '\n' from the code generated by __print value__
so that 
![image](https://cloud.githubusercontent.com/assets/1266318/17979668/b6e5a9d4-6ab0-11e6-9e59-d73475dc8651.png)
generates
```
print("1234 = %d", 1234);
```

@kgracey - Shouldn't the __print value__ block only print the value, and not a text label too?  If we want text before the value, shouldn't we have a special block with a user-customizable text field plus the value field?

**Comment by DarkmatterVale** [comment]
I think that only the value should be printed as well now that we have better control over the terminal. I will remove that as well; @kgracey let me know if you would like it left in...

**Comment by PropGit** [comment]
Merged already.  It will be in Demo after 11:30 am.

**Comment by PropGit** [comment]
@DarkmatterVale - I thought the code of #595 looked wrong at first, then I backed off and thought it was fine, so I merged... but I should have stuck with my gut.  It's wrong.

Too much was removed for the __print value__ block.  In console.js, line 70:
```
return 'print("' + value + '");\n';
```
should have only be changed to:
```
return 'print("%d",' + value + ');\n';
```

**Comment by DarkmatterVale** [comment]
I apologize for making that mistake @PropGit , I made the changed requested in #597

**Comment by PropGit** [comment]
Thanks @DarkmatterVale.

Tested and verified correct.
