### ISSUE TITLE
Potential "Save As" Bug(s)

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#602]
I have been having multiple issues show up with the save as feature.

# Save As name doesn't change

My original project was named "Testing Operators" I clicked "Save As" and renamed the project to "OLED Blocks" then I saved it again. However, back in my projects it just copied the original project's name as well as the blocks that it contained.

![save as name](https://cloud.githubusercontent.com/assets/20099916/18016242/383ce4b4-6b80-11e6-9c1d-f725dfb93e83.PNG)

# Can't delete Save As project

After created the "Save As" project I found there was no button to delete it, even after editing it and re-saving the project.

![save as](https://cloud.githubusercontent.com/assets/20099916/18016199/040c3fd2-6b80-11e6-873c-04511f9c7fbf.PNG)

# Save as copies original project

This happened when I did "Save As" then renamed the project then clicked "Save" again, the new project just copied the original blocks, code, and project name. 

I lost the new "Save As" project but here is a quick example:

Created a project that looked like this

![oled broken](https://cloud.githubusercontent.com/assets/20099916/18016675/7321f9c8-6b82-11e6-99fb-49f0603b5461.PNG)

I saved it, added some blocks, renamed it (save as) then saved it again.

![oled change](https://cloud.githubusercontent.com/assets/20099916/18016709/a2b8403e-6b82-11e6-92e9-1f61c4c27731.PNG)

So I went back into my projects where a new one was created but as stated up above was exactly similar to the original project and when opening the new one it showed the same blocks again.

![oled broken](https://cloud.githubusercontent.com/assets/20099916/18016751/df780fcc-6b82-11e6-8b1f-73a96b8c2df1.PNG)

I'm not completely sure whether I'm using save as correctly as this is how it is used in all other programs I've used.

**Comment by michel-cf** [comment]
Duplicate #433

**Comment by PropGit** [comment]
Some of these items are duplicates of #433, but the hidden delete button is new; though I think someone else reported that on blank-named projects.

**Comment by wstodghill** [comment]
I have experience all these issues too...

**Comment by michel-cf** [comment]
The other Save-as bug ticket has been closed in the meanwhile can this one go the same way?

**Comment by wstodghill** [comment]
My experience of the issue and its current condition says yes!

**Comment by PropGit** [comment]
Yes.  Closing...
