### ISSUE TITLE
S3 Block Request - turn all LEDs off

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#607]
@kgracey - this is a request for the next wave of S3 blocks. Priority 2 

This block would set to off all of the S3 LEDs - unless turned on by the program. This would allow us to do time-lapse light scribbling! Check mark enables - the black box looks like a color picker but is for a visual clue only.

![turn all leds off](https://cloud.githubusercontent.com/assets/8891440/18025064/3827e42a-6be3-11e6-8b47-8c29b2114f54.JPG)

https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#idbvz4

**Comment by kgracey** [comment]
@dcarrier-parallax this one is really quite easy for you to do so I've labelled it with Public Release #1 this week. If it's more work than I know just reply and we'll move it to the second release.

**Comment by dcarrier-parallax** [comment]
I'm not entirely clear on what the request is for.  If the checkbox is unchecked would the block do nothing?

Also, the default behavior of the LED block is to turn off all of the LEDs, unless the user changes one of the colors unchecks a checkbox.

As for light painting, the S3 object doesn't have the control for it.  It PWMs the LEDs, and it turns them on and off one at a time. When I/O state support is added, possibly at the next release, it will provide the user with enough functionality to connect and control LEDs used for light painting.

**Comment by wstodghill** [comment]
@dcarrier-parallax - the idea was that by checking the box all the S3's LEDs could be turned off. The user would still have control of the bi-color indicator LEDs - they could be controlled with the change these LEDs block. The other LEDs battery charge, power and RX/TX would be turned off. This can be done in spin, but I was looking for a simple way to do this in BlocklyProp (we could not do this with the GUI)

As far as what this feature would allow us to do - You can also put an LED on top of the Scribbler and do some time-lapse photography light scribbling or use the indicator LEDs for dot matrix printing. 

See these threads for work done with the S2 - especially in this section of what is now a very long thread - http://forums.parallax.com/discussion/160957/nikos-fibonacci-spiral-challenge/p6 or add a line of LEDs and do some dot-matrix printing! http://forums.parallax.com/discussion/163960/the-s2-led-dot-matrix-printer-thread

We covered the other LEDs with black tape to darken them.

**Comment by kgracey** [comment]
Just spoke with @dcarrier-parallax and we can control the power LED but charge and USB data we cannot (however if you're not connected these are off anyway). It seems a bit confusing that the power LED could be off but it still runs. For the reason of being short on time we are going to shelf this request for a while (till next release).

**Comment by wstodghill** [comment]
@kgracey - Gotcha! We still have tape! or can turn it off in Spin! I want to try the dot matrix stuff from the S2 - I think these S3 LEDs are going to work way better that the old LEDs - less glare.

**Comment by kgracey** [comment]
It sounds like yes, it can be turned off in Spin. The only reason we can’t implement it now is because we have to finish other unfinished work. But, for the next release we can keep this in the queue.

**Comment by dcarrier-parallax** [comment]
As Ken mentioned, there is no software control over the charge LED, but we can disable the power LED, as well as dim it or set it to blink.

Would you like us to consider pursuing this option?

**Comment by wstodghill** [comment]
If there are any LEDs that can't be controlled with code - we might as well not worry about making a block. We can always tape over the lighted ones when doing our light scribbling.

**Comment by MatzElectronics** [comment]
Should this issue be closed?

**Comment by wstodghill** [comment]
Yes - I can alway do this in the Scribbler Object (Spin or C).
