### ISSUE TITLE
Rewrite server to java

### ISSUE THREAD

**Issue by michel-cf** [parallaxinc/BlocklyProp#61]

**Comment by DarkmatterVale** [comment]
Do we know what needs to be done to accomplish this? Specifically, what do we want to rewrite? Does the whole server need to be rewritten, and have the same functionality? Is there anything new that needs to be added?

**Comment by michel-cf** [comment]
I'll have to setup a framework with services and a database layer and have
to transfer all current functionality.


It should be easier afterwards to add more functionality. Care must be
taken as this will be a distributed system. (Saving session information in
the database instead of on the harddisk or in memory)

**Comment by DarkmatterVale** [comment]
Hmmm...Ok.

Let me know if you would like any assistance, Java is my preferred language to program so I might be more help than I was with PHP.

**Comment by michel-cf** [comment]
Server framework setup is coming along. Database with transactions, dao, services and servlets seem to work fine now.

Before implementation can be started a few things will still need to be done: the biggest being the setup of the security framework.

**Comment by michel-cf** [comment]
Multiple password hashing with salt finally works, only need to find out if the permissions system works then we should be ready to start implementing the current functionality.

**Comment by DarkmatterVale** [comment]
Awesome! Will I still be able to run my local server? Will I need to change some stuff?

**Comment by michel-cf** [comment]
Running locally should be possible, it only requires a tomcat 7 and mysql.

Maybe some other servers will be used in production, but are not required during development. An example of this is log analysis or metrics analytics server.
