### ISSUE TITLE
S3 Block Additons - Next Go Round

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#610]
@kgracey - could the following blocks be considered for the next S3 wave? They are currently available in the "C" group

In the control category...
![repeat_item](https://cloud.githubusercontent.com/assets/8891440/18027941/7672884a-6c36-11e6-82b6-c2eac6495ed7.JPG)

and these from the communication group seem to be more easy to understand for the terminal (console).
![terminal](https://cloud.githubusercontent.com/assets/8891440/18027948/99331462-6c36-11e6-9090-8a0d850434d8.JPG)

Lastly (as we discussed) - I would love to get this block for the S3 - if we can figure a way to actually use it! 
![sony](https://cloud.githubusercontent.com/assets/8891440/18027954/e414f16c-6c36-11e6-9dac-c5c2c43a8491.JPG)

**Comment by kgracey** [comment]
Agreed to all details of this proposal. The Sony block could be a challenge but we'll find out when we get there!

**Comment by MatzElectronics** [comment]
@wstodghill @kgracey Still interested in this?  We can arrange the C S3 blocks accordingly.

**Comment by wstodghill** [comment]
I am!

**Comment by MatzElectronics** [comment]
Hi @wstodghill!  I think these are all there now (finally!)

**Comment by MatzElectronics** [comment]
In and working in PropC (not SPIN), but the specifics of this issue are completed.
