### ISSUE TITLE
S3 block: Simple Scribbler rotate block needs a full 360 degrees

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#621]
On the Simple Scribbler rotate block we can't actually turn a full 360 degrees. The maximum we can get is 345 degrees. Maybe the best solution is to ditch the angle graphic and allow a user-entered value in a certain range? Anything that works here would be acceptable to me.
![2016-08-29_13-59-33](https://cloud.githubusercontent.com/assets/9534148/18067811/57cdeb5a-6df3-11e6-85d6-fe89f27ec417.png)

**Comment by PropGit** [comment]
For what it's worth, that graphic has always confused me. 

1. The solid red line makes me think that's where it ends... so it's sweeping (in the example above), in the wrong direction.
1. I've tried clicking and dragging it to change the value visually... doesn't work.  Is it supposed to?

**Comment by dcarrier-parallax** [comment]
The angle selection widget is part of the original Blockly code, so I cannot easily change it.  It allows angles from 0° up to, but not including, 360°.  The mouse interface uses 15° increments, but you can type in angles up to 359°.

If that is not sufficient, I can switch it to a number field that only supports typing.

**Comment by kgracey** [comment]
We will not need to rotate 360 degrees, in place, unless we are dancing. For the robot dance enthusiasts they can simply use two 180 degree blocks. Because we want to keep the simple stuff simple (and with this cool degree widget) we are closing this issue!
