### ISSUE TITLE
Expand password reset result page message

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp#624]
The password reset result page is quite terse. Please expand the message to explain to the user that the site has sent a reset email to the user's mailbox. Please follow the instructions contained within the email.  Or something similar.

![screen shot 2016-08-29 at 14 59 06](https://cloud.githubusercontent.com/assets/8442260/18069051/71969efa-6df9-11e6-8360-5a2c80302263.png)

**Comment by paragitadmin** [comment]
This has been completed. The email messages are all driven from a set of mustache template files.
