### ISSUE TITLE
Block Request: Seperate terminal print blocks for text and numbers

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#625]
Just like the OLED drawText and drawNumber blocks, we should have a "print text" and "print number" block.  Discovered this when trying to test serial terminal blocks.  For instance, this doesn't work:

![image](https://cloud.githubusercontent.com/assets/19737272/18069416/d777aab4-6dfb-11e6-9045-fe123da0edc5.png)

The "print number" block could also have a dropdown for "DEC, HEX, BIN, OCT".

**Comment by MatzElectronics** [comment]
Block factory example for print number: https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#vk9uya
Print text: https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#pcb3ed

**Comment by DarkmatterVale** [comment]
@MatzElectronics I'm not sure i understand what you are saying; the OLED blocks are not specifically for numbers or text; it is predetermined or value inputs (which can be text or numbers, not just numbers). With that information, do you still think this is necessary?

**Comment by MatzElectronics** [comment]
The OLED blocks are there and work well, it's just missing the third "dual" block - the Terminal needs similar blocks, separate ones for text and numbers.  It is necessary - if you try sending a variable containing a string to the current Terminal print block that takes a variable, it produces a garbage output.  It's fairly difficult to ask the propeller to determine the variable type and act accordingly.  It's a lot easier, and more educationally sound, to just have separate blocks.

**Comment by DarkmatterVale** [comment]
Ah, ok; I see what you mean thank you for the explanation.

**Comment by MatzElectronics** [comment]
Tested and verified for separate text and number blocks.  Closing this issue.  If a "dual" block is still desired, someone can create a new block request for it.
