### ISSUE TITLE
Display Connection Info at Top of Terminal

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#626]
It would be best to have the connection information display in a box above the receive pane of the Terminal like so:

![image](https://cloud.githubusercontent.com/assets/1266318/18069847/98f3489a-6dfe-11e6-94e7-287cadbb3209.png)

This was suggested by @MatzElectronics at the bottom of [this post](https://github.com/parallaxinc/BlocklyProp/issues/605#issuecomment-243273167).

**Comment by michel-cf** [comment]
This is in fact not very easy. As it's not something I put in using BlocklyProp.

It's actually the BlocklyPropClient that sends it through the websocket. (It should be quite easy once we change to the new BlocklyPropClient as I can use different event types to pass either data or meta info.)

**Comment by MatzElectronics** [comment]
@DarkmatterVale @zfi @PropGit I'm less inclined to fix this these days - All published projects either do (or will) clear the terminal before using it - this can just be a known thing with the terminal, and it seems best solved through documentation at this point.  Thoughts?

**Comment by PropGit** [comment]
@MatzElectronics - While I'd still love to see it enhanced, it's not practical all things considered and I agree with your analysis of it.  I'll close this issue.
