### ISSUE TITLE
Change "Console" to "Terminal"

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#627]
The top of the Terminal says "Console" but to get there you select Run > Serial Terminal.

![image](https://cloud.githubusercontent.com/assets/1266318/18069902/0304e680-6dff-11e6-845b-27283058810e.png)

We've named the category for the blocks that send characters to it "Terminal."

Please change "Console" at the top of the Terminal to "Terminal."

**Comment by wstodghill** [comment]
@kgracey - we need to catch this in our Tutorials for the S3!

**Comment by MatzElectronics** [comment]
@mrodriguez-parallax or @csavage-parallax could one of you quickly verify that this has changed?
Thanks!

**Comment by csavage-parallax** [comment]
I still see "Console" at the top left of the window.


*Chris Savage | *Engineering Tech | Main Office: (916) 624-8333 | Direct to
Tech Support: (888) 997-8267 | www.parallax.com |

**Comment by MatzElectronics** [comment]
Bummer.

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by MatzElectronics** [comment]
@csavage-parallax This is ready to try again.

**Comment by csavage-parallax** [comment]
It says, "Terminal" now, but the text part of the window appears to maybe drop into the lower portion of the form. 

![image](https://cloud.githubusercontent.com/assets/20691193/21197920/0c4f2204-c1f2-11e6-82b5-a259a033d37c.png)

**Comment by MatzElectronics** [comment]
Huh... Not sure it's the same issue, and I think this could get addressed with your serial glitch you noted earlier.  Pasting your image there so I can close this issue.
