### ISSUE TITLE
Terminal Cursor Position Varies

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#628]
Referring to [this post](https://github.com/parallaxinc/BlocklyProp/issues/605#issuecomment-243273167) from @MatzElectronics, the cursor positions appear to be relative to the connection information that appears at the top of the receive pane.

@MatzElectronics - It's been working fine for me, so I retested with your code, and once again it worked fine, but my display looked different too.
![image](https://cloud.githubusercontent.com/assets/1266318/18070034/04819480-6e00-11e6-9650-fc5501e2a95c.png)

Here's some things to note:  
- The positions are zero (0) based, so upper-left position is 0,0.
- The connection information in my display is a single line, whereas yours is two lines that looks like it wrapped at the edge of the pane.  This is probably why the positioning is off by more.

@michel-cf - Is my theory above correct?  Can this problem be fixed by Issue #626?  Some other way?
Also, I've noticed that connection information somethings appears until the first serial data arrives, and other times it stays indefinitely.  Maybe the underlying code I'm using actually clears it without me saying to clear it, I don't know, but the inconsistency is bothersome.  Either way Issue #626 is the best solution in our eyes.

**Comment by michel-cf** [comment]
What theory do you mean?

yes, the coordinate system is 0 based and the connection confirmation is indeed a single line.

**Comment by PropGit** [comment]
@michel-cf -  My theory here:
>The connection information in my display is a single line, whereas yours is two lines that looks like it wrapped at the edge of the pane. This is probably why the positioning is off by more.

**Comment by MatzElectronics** [comment]
For now, we can document/communicate to users that it is best practice to include a "Terminal clear screen" at the beginning of their programs, and that will avoid most issues they may otherwise have.
