### ISSUE TITLE
Dynamic Block Creation/Usage

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/BlocklyProp#63]
This is something I think will become vital to BlocklyProp if users would like to add their own blocks themselves without having to do any coding. Below is my outlined solution.

The idea would be to create a Python script that would be called from the server ( or from the local device ) on startup and would do the following:
1. Parse folders containing file containing blocks for blocks
2. Populate blocks and their information into an appropriate Frame file
3. Return control to the main server with the updated file created and being used
To add blocks, a user would simply have to drag and drop their block file into a specific directory before starting the server, then they could run the server and it would do the rest.

I will add some more in-depth information later once I get my C Parser up and running and can devote more time to this project.

**Comment by MatzElectronics** [comment]
Will be addressed with a "user code" block.  Closing this issue.
