### ISSUE TITLE
I2C Block change

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#634]
In the I2C new bus block - please remove the SCL drive parameter - make it default to open-collector.  For some rare instances of the EEPROM chip connected to a propeller, there are no pull-up resistors, requiring a the clock to be push-pull driven with another pin

**Comment by MatzElectronics** [comment]
The above edits work, but the block does not.  It is not setting up the I2C object correctly.

**Comment by PropGit** [comment]
In demo @ 4:30 pm.

**Comment by MatzElectronics** [comment]
Tested, failed.  Going to wait on #684.

**Comment by MatzElectronics** [comment]
Abandoning this for now - if we want to add a specific device, we can create a block for that device.
