### ISSUE TITLE
I2C out block update

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#637]
The I2C out block will not likely work properly.  It should only take 1 input, and possibly a dropdown if it can't auto-detect the type of input it is given (string, char/byte, int - possibly using typeof?).  The data count should be calculated using sizeof().

**Comment by MatzElectronics** [comment]
@kgracey - should we get the I2C stuff working now, or push it all to the november target?

**Comment by PropGit** [comment]
The dedicated I2C-based blocks (for EEPROM, ADC, etc.) work properly, right?  If that's the case, we can probably push this to November easily.

**Comment by kgracey** [comment]
November is best. KG

**Comment by PropGit** [comment]
In demo @ 4:30 pm.

**Comment by MatzElectronics** [comment]
Tested, failed.  Going to wait on #684.

**Comment by MatzElectronics** [comment]
Abandoning i2c for now - if we want to add a device, we can create a block specific to the device.
