### ISSUE TITLE
Forgot password returns error

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#64]
Forgot password function returns error after submitting.

![image](https://cloud.githubusercontent.com/assets/1266318/10592266/d8508868-766f-11e5-8062-b4db2f72e3b1.png)

>HTTP Status 500 - com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 28 path $
>
>type Exception report
>
>message com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 28 path $
>
>description The server encountered an internal error that prevented it from fulfilling this request.
>
>exception
>
>javax.servlet.ServletException: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 28 path $
>        org.apache.shiro.web.servlet.AdviceFilter.cleanup(AdviceFilter.java:196)
>        org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:148)
>        org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
>        org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
>        org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
>        org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
>        org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
>        org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
>        org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
>        org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
>        org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
>root cause
>
>com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 28 path $
>        com.google.gson.JsonParser.parse(JsonParser.java:65)
>        com.google.gson.JsonParser.parse(JsonParser.java:45)
>        com.parallax.client.cloudsession.CloudSessionLocalUserService.requestPasswordReset(CloudSessionLocalUserService.java:65)
>        com.parallax.server.blocklyprop.servlets.PasswordResetRequestServlet.doPost(PasswordResetRequestServlet.java:49)
>        javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
>        javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
>        com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:287)
>        com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:277)
>        com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:182)
>        com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
>        com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
>        com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
>        com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
>        com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
>        com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
>        org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
>        org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
>        org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
>        org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
>        org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
>        org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
>        org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
>        org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
>        org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
>        org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
>        org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
>        org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
>root cause
>
>com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 28 path $
>        com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1573)
>        com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1423)
>        com.google.gson.stream.JsonReader.doPeek(JsonReader.java:546)
>         com.google.gson.stream.JsonReader.peek(JsonReader.java:429)
>        com.google.gson.JsonParser.parse(JsonParser.java:60)
>        com.google.gson.JsonParser.parse(JsonParser.java:45)
>        com.parallax.client.cloudsession.CloudSessionLocalUserService.requestPasswordReset(CloudSessionLocalUserService.java:65)
>        com.parallax.server.blocklyprop.servlets.PasswordResetRequestServlet.doPost(PasswordResetRequestServlet.java:49)
>        javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
>        javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
>        com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:287)
>        com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:277)
>        com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:182)
>        com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
>        com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
>        com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
>        com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
>        com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
>        com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
>        org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
>        org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
>        org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
>        org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
>        org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
>        org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
>        org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
>        org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
>        org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
>        org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
>        org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
>        org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
>note The full stack trace of the root cause is available in the Apache Tomcat/7.0.52 (Ubuntu) logs.
> 
>Apache Tomcat/7.0.52 (Ubuntu)

**Comment by DarkmatterVale** [comment]
valid@email.com is not a valid address, correct?

Could it possibly be due to the fact that the email was never registered? Or have you already implemented a catch for that in your code Michel?

**Comment by michel-cf** [comment]
This failed because the mysql connection was broken from the Cloud-session server.

After restarting the tomcat it worked. The later reported problem with the email and the token not matching also could not be reproduced. For now

**Comment by michel-cf** [comment]
Improved the message shown to the user. Reopen if necessary
