### ISSUE TITLE
Disable 2 OLED blocks

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#643]
max height and max width are somewhat unnecessary - the library under the hood handles out-of-range values very well, so I think these just take up space.

**Comment by zfi** [comment]
I believe these were introduced to allow the code (user and OLED-specific) to determine the screen dimensions programmatically. I'd like a second opinion before I accept the PR.

**Comment by DarkmatterVale** [comment]
I agree with @zfi ; Although the blocks might not be necessary for many things, they are nice to have...

**Comment by MatzElectronics** [comment]
Voting to keep these blocks
