### ISSUE TITLE
Pulse Out block corrections

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp#647]
The pulse out 'C' block is missing a default value ( '0' ). The pulse length should also specify a unit of measure, currently micro-seconds.

**Comment by MatzElectronics** [comment]
Corrections don't appear to be in demo.

**Comment by zfi** [comment]
I committed the patch to the wrong branch. That has been corrected and the patch applied to the demo branch.

**Comment by MatzElectronics** [comment]
Code works - please change label from "u" to "(us)" - but keep the greek letter mu, not the u I just typed here - for microseconds.

**Comment by MatzElectronics** [comment]
Tested and verified
