### ISSUE TITLE
Make BlocklyProp check reserved words with language-sensitive case checks

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#654]
BlocklyProp currently checks the reserved words list in a case-sensitive way.

We need it to continue this for C projects, but for Spin projects, it should check reserved words in a case-insensitive way.

The Spin reserved words list was updated in Issue #437.

**Comment by PropGit** [comment]
__Update__: @michel-cf is looking into this one.

At this point, it appears that this is a Blockly-wide setting, not necessarily changeable based on the language being compiled (although that seems strange to me) through we've decided that simply setting it to perform case-insensitive checks against reserved words, regardless of language, will achieve what we need and will prevent the _different only by case_ issue from being a point of discussion for the intended audience of BlocklyProp.

**Comment by michel-cf** [comment]
As always, a Blockly upgrade will require quite a few changes. I'm working on a new version but need to take a look at all blocks so they keep working.

**Comment by michel-cf** [comment]
There is a bit of new styling

The variables toolbox category:

![image](https://cloud.githubusercontent.com/assets/5745991/18181690/abf830a0-708c-11e6-9f13-fc8065ba54b9.png)

**Comment by PropGit** [comment]
Well, that's strange.

Okay.  Because we're out of time on our deadline, I've moved this Issue to the next milestone (which will probably change to sooner, just not today).  So, this means you're fine to continue on this on your side and we'll get it into the system when it's ready, sometime after today.  All is well.

Are there mysteries involved, or do you know exactly what needs to happen and why it needs to happen?

**Comment by MatzElectronics** [comment]
Tested and verified.
