### ISSUE TITLE
S3: send control character block uses wrong object nickname

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#655]
The __send control character block__ references the Scribbler object nickname, but the Parallax Serial Terminal object was included with the nickname "serial."

![image](https://cloud.githubusercontent.com/assets/1266318/18138256/c825d4da-6f60-11e6-9968-2895233a688d.png)

![image](https://cloud.githubusercontent.com/assets/1266318/18138248/b119dd18-6f60-11e6-9255-0347e4f92937.png)

```
'SERIAL_TERMINAL USED
CON
  _clkmode = xtal1 + pll16x
  _xinfreq = 5_000_000

VAR

OBJ
  serial    : "Parallax Serial Terminal"

PUB Setup
  Scribbler.SerialStart(9600)
  Start


PUB Start

  Scribbler.SerialStr(String("Line 1"))
  Scribbler.SerialChar(Serial#NL)
  Scribbler.SerialStr(String("Line 2"))
  Scribbler.SerialChar(Serial#LF)
  Scribbler.SerialStr(String("Line 3"))
  Scribbler.SerialChar(Serial#BS)
  Scribbler.SerialStr(String("Line 4"))
  waitcnt(clkfreq / 1 * 3 + 1000 + cnt)
  Scribbler.SerialChar(Serial#CS)
  Scribbler.SerialStr(String("Line 5"))
```

**Comment by wstodghill** [comment]
Yes! Just experienced this too!

**Comment by dcarrier-parallax** [comment]
This issue is more so related to the https://github.com/parallaxinc/Scribbler-3_Library repository, but everything is in sync as of PR #670. Please Verify.

**Comment by PropGit** [comment]
Tested and verified correct.
