### ISSUE TITLE
Hide all I2C blocks

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#659]
The blocks are flawed, and there are other issues to get them corrected, but for now, they need to be hidden until they can get a longer, more involved look.

**Comment by DarkmatterVale** [comment]
See #663

**Comment by PropGit** [comment]
@MatzElectronics - Didn't you mean to also hide the blocks which generate I2C code for communicating to specific devices (like EEPROM) because of a lack of device ID?  Please advise which other specific blocks, if any, need to be hidden because of this issue.

**Comment by MatzElectronics** [comment]
No, device specific blocks all seem functional, so they should stay visible

**Comment by MatzElectronics** [comment]
Tested and verified that they are currently hidden.
