### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by michel-cf** [parallaxinc/BlocklyProp#66]

**Comment by DarkmatterVale** [comment]
I believe this has been satisfied with the creation of ```common``` and other similar internationalization features?

**Comment by DarkmatterVale** [comment]
bump

**Comment by zfi** [comment]
I did not see s stated goal for this so it is difficult to say that it is done. I believe the web site supports two languages but all of the blocks are still in English.

**Comment by DarkmatterVale** [comment]
If a specific goal is set we can create a new issue.
