### ISSUE TITLE
Terminal: Change print text to new form

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#664]
Change __Terminal print text " "__
![image](https://cloud.githubusercontent.com/assets/1266318/18150591/ff316dea-6f9c-11e6-8c52-88ad39ca85f1.png)

to this form:
![image](https://cloud.githubusercontent.com/assets/1266318/18150595/0976d330-6f9d-11e6-892b-44086f9f7408.png)

... but with a default input (text-type constant) included in the field.  The default should be ~~an empty string~~ "Hello".

BlockFactory Example:  https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#i2urx5

**Comment by MatzElectronics** [comment]
The default for text variable blocks has been "Hello"

**Comment by PropGit** [comment]
@MatzElectronics - Thanks!  The default shall be "Hello"

**Comment by zfi** [comment]
Are you guys sure? I already changed it once to be a blank field.

**Comment by MatzElectronics** [comment]
Yes, strings should default to "hello" to clearly denote that they are
strings.

**Comment by zfi** [comment]
I cloned the string_type_block to string_block and stripped out all the stuff we don't need.

**Comment by MatzElectronics** [comment]
Tested and verified.
