### ISSUE TITLE
Terminal: Add row+column block

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#666]
Add new Terminal block: __Terminal move to row column__
![image](https://cloud.githubusercontent.com/assets/1266318/18151071/d9bcf99a-6fa0-11e6-9c6c-1450dbd08460.png)

... but with default inputs (number-type constants) included in the fields. The defaults should be 0.

BlockFactory Example: https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#cd9z5u

It should generate the following code:
```term_cmd(CRSRXY, colValue, rowValue);```
where _colValue_ and _rowValue_ are the field input values or variable names.

NOTE: the block lists row, then column, but the term_cmd provides them as column, then row.

**Comment by MatzElectronics** [comment]
I'm assuming this means the current blocks change or get removed, right? - Just want to make sure nothing gets missed...

**Comment by zfi** [comment]
The current move_to_row and move_to_column blocks are going to be replaced by a single move_to_position block.

**Comment by MatzElectronics** [comment]
@zfi Failed.  Row and column are swapped.

**Comment by zfi** [comment]
Nearly everything references row, column but the underlying function call is uses column, row. Fixed.

**Comment by PropGit** [comment]
The first post said this "NOTE: the block lists row, then column, but the term_cmd provides them as column, then row."

**Comment by PropGit** [comment]
Tested and verified correct.
