### ISSUE TITLE
S3 - Change set cursor block text

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#667]
Change __set cursor position X Y__ block
![image](https://cloud.githubusercontent.com/assets/1266318/18151691/d181da70-6fa5-11e6-8f20-11ce0d083f6f.png)

to be __set cursor to row column__ similar to this form:
![image](https://cloud.githubusercontent.com/assets/1266318/18151710/f27526ec-6fa5-11e6-87ed-e31fc65e2e21.png)

**Comment by dcarrier-parallax** [comment]
This was addressed by PR #670. Please Verify.

**Comment by PropGit** [comment]
Tested.  Verified works, though row and column is backwards of the way I specified in the example above.

**Comment by zfi** [comment]
@dcarrier-parallax: Please submit a PR with the row and column labels arrayed as 'row' and 'column'.

**Comment by dcarrier-parallax** [comment]
Fixed in pull request 775.  Please verify.

**Comment by zfi** [comment]
Verified - Closing.
