### ISSUE TITLE
Update Documentation (readme.md)

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#67]
Once our new server system for BlocklyProp is released for public use, update public-facing documentation:
- Repo's readme.md
- Create wiki? (may prefer the item below instead)
- Create repo web page

Items to address:
- Introduction
  - System requirements (platforms)
  - Supported microcontroller
- Getting Started
  - How to get to BlocklyProp
  - Configuring system to run

**Comment by DarkmatterVale** [comment]
Can we close this?

**Comment by michel-cf** [comment]
With the OAuth changes I just wrote a configuration readme. (For all configurations, not only oauth).

Maybe we can use parts of the latest created Google docs to write the other readme's

**Comment by zfi** [comment]
User-land docs are available on the Learn web site. System docs are terse but functional. 

Closing.
