### ISSUE TITLE
S3: Serial data sent too soon does not show in Terminal 

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#676]
We need a 1 second delay upon "opening" the serial output pin in the wrapper object.

**Comment by dcarrier-parallax** [comment]
Addressed in a commit to the Scribbler-3 Library repository: https://github.com/parallaxinc/Scribbler-3_Library/commit/87058ecd70c8ce698265788372aef73f99333c51

Please verify

**Comment by PropGit** [comment]
Tested and verified correct.
