### ISSUE TITLE
BlocklyProp Editor Design Changes

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#68]
Previous discussion indicates there is very little that can be done to change the appearance of the BlocklyProp editor itself; perhaps limited only to the menu at the top.

Here is a draft of a proposed UI change (the graphic, color style, positioning in the menu).  

@michel-cf - Is this proposed styling possible?

![image](https://cloud.githubusercontent.com/assets/1266318/11083393/f6f9f2a6-87e3-11e5-8fd9-4cefba35c996.png)

**Comment by michel-cf** [comment]
The menu on top should not be a problem (although some items will be removed or changed)

The restyling of the Blockly toolbox is more difficult. I can take a look but I can't promise anything

**Comment by michel-cf** [comment]
Do you have the used colors and fonts?

**Comment by jeffam70** [comment]
Not yet, but I can get them once I know she's done with her suggestions.  I'll verify and get back on this one.

**Comment by michel-cf** [comment]
I've made some initial changes to approximate the design:

![image](https://cloud.githubusercontent.com/assets/5745991/11192970/41913ab2-8ca4-11e5-8da8-305b0410f0c5.png)

**Comment by PropGit** [comment]
I think this item is resolved.  We are pleased with the current menu in the system.
