### ISSUE TITLE
Serial LCD cursor positioning

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#683]
Block for cursor positioning on the LCD module just like the row/column block for the Terminal.

**Comment by zfi** [comment]
Can you provide a C code sample that the block should emit?

**Comment by MatzElectronics** [comment]
Sure, but my hesitation here is that this really should use a function that
doesn't exist yet in simple libraries: constrain().

writeChar(debug_lcd, (constrain(cursor_row, 0, 3) + (20 *
constrain(cursor_column, 0, 19))));

where constrain() doesn't allow a value to fall outside of the specified
range.

Andy is aware of the need and there is an issue in SimpleLibraries
requesting its addition.

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by PropGit** [comment]
@MatzElectronics and @zfi - Let's hold off on this one until the library is updated to provide the best solution.

@MatzElectronics - Jim had a good suggestion to me that we also provide symbolic constants in Simple Libraries for the LCD command characters, such as for clear screen and cursor placement.

**Comment by MatzElectronics** [comment]
Cool - I'm up for whatever is best.

**Comment by MatzElectronics** [comment]
Block is present, but I'm going to add constraints to it still.

**Comment by MatzElectronics** [comment]
@mrodriguez-parallax @csavage-parallax This just needs a quick verification.

**Comment by csavage-parallax** [comment]
I will test this one today.


*Chris Savage | *Engineering Tech | Main Office: (916) 624-8333 | Direct to
Tech Support: (888) 997-8267 | www.parallax.com |

**Comment by csavage-parallax** [comment]
I am still testing, however my initial test program can't be realized
because the position cannot be set via a variable. It can only be set to a
fixed position. IMHO this is a big limitation.


*Chris Savage | *Engineering Tech | Main Office: (916) 624-8333 | Direct to
Tech Support: (888) 997-8267 | www.parallax.com |

**Comment by csavage-parallax** [comment]
Testing complete. Everything seems to work using fixed positions. However I still recommend making it so you can use a variable to set the cursor position. =)

**Comment by csavage-parallax** [comment]
Hold the phone! Running the following program I see two issues:

http://demo.blockly.parallax.com/blockly/my/projects.jsp#479

The first is that the screen does not consistently clear when downloading the program (Loading to RAM).

Second is that if I precede my HEX value with another character, such as, "*" it shoes up before the value. However if I use, "%" as shown in the code it isn't displayed.

**Comment by MatzElectronics** [comment]
@csavage-parallax Okay, ready for testing again.  I'll probably go in and change the block like you described, but it might be a bit before I get there.  That request can be submitted as a separate issue.

**Comment by csavage-parallax** [comment]
% symbol now appears and the screen clears every restart as it should. Not
sure what other symbols/characters may have been affected to test those
specifically.


*Chris Savage | *Engineering Tech | Main Office: (916) 624-8333 | Direct to
Tech Support: (888) 997-8267 | www.parallax.com |

**Comment by MatzElectronics** [comment]
I did some research and I think only the % character needed escaping.
 thanks!
