### ISSUE TITLE
Category Request: Memory

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#684]
Build a new category for dealing with reading and writing to both EEPROM and SD card memory.

**Comment by MatzElectronics** [comment]
@DarkmatterVale how soon do you anticipate being able to make the memory category?  Once it's there, I can create the EEPROM blocks from the current i2c ones, and then improve the i2c ones, since the current version isn't a great solution for either purpose.

**Comment by DarkmatterVale** [comment]
@MatzElectronics I already have some basic blocks made; I just need to enable them. I apologize for the late reply I will try to send a PR later this morning.

**Comment by DarkmatterVale** [comment]
#706 Adds back the blocks that I had built for EEPROM and SD Card; although I believe they are broken so I (or someone else) will need to do some work on them...

**Comment by PropGit** [comment]
In demo after 4:45pm.

**Comment by MatzElectronics** [comment]
I worked on EEPROM, in #712.  I have some thoughts on SD card, so I'll dive into those when I can.

**Comment by MatzElectronics** [comment]
Will try to verify soon - updates in pending PR, going to abandon SD card blocks for now.

**Comment by MatzElectronics** [comment]
Tested, failed - will submit a fix.

**Comment by MatzElectronics** [comment]
Tested and verified!
