### ISSUE TITLE
List block color pallet

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#69]
@michel-cf - Please provide a list of the entire color pallete (and related information) allowed for the blocks in the editor.

**Comment by michel-cf** [comment]
Blockly documentation:

Blockly uses a [Hue-Saturation-Value](https://en.wikipedia.org/wiki/HSL_and_HSV) (HSV) colour model. Saturation and Value are hard-coded into Blockly, whereas the Hue is defined on each block. This ensures that developers have the freedom to choose from a wide range of colours, while still guaranteeing that all the blocks will fit together visually. It also allows the entire Blockly look and feel to be made brighter (for children) or more depressing (for businesses) by simply adjusting the two hard-coded Saturation and Value constants.

![image](https://cloud.githubusercontent.com/assets/5745991/11088298/88beb5d2-8861-11e5-83ad-e112fe4e4be2.png)

To find a good colour, visit this [HSV picker](http://www.rapidtables.com/web/color/color-picker.htm), enter Blockly's Saturation and Value constants (the defaults are 45% and 65% respectively), then slide the Hue as desired

Source: https://developers.google.com/blockly/custom-blocks/defining-blocks#setcolour

**Comment by michel-cf** [comment]
The image shows the different colors for the default values. I propose that we go a bit brighter.

**Comment by JenJacobs** [comment]
I agree. Brighter would be better.

**Comment by DarkmatterVale** [comment]
Has there been any progress on determining what colors should be used for which blocks @PropGit ?

**Comment by JenJacobs** [comment]
Is anyone working on this project able to get me a list or a screen capture of all the block colors we are currently using, please?

**Comment by PropGit** [comment]
@JenJacobs - Here's some screen captures.  I don't have the color codes for these but you should be able to grab them from the image.

We need as wide a set of _different_ hues as practical (not too close to each other) (see the [above post](https://github.com/parallaxinc/BlocklyProp/issues/69#issuecomment-155718917) for documentation) and I believe @michel-cf has already set the saturation and value to be brighter than the defaults but I don't know the values he used (see screenshots below) so we'll want to designate certain hues for certain categories of blocks.  For now @JenJacobs, lets at least decided on a set of hues that we deem _different_ enough from each other to be distinctive (at least when in close proximity to each other) and then we can decide which hue should apply to which category to derive a standard to stick to.

#### Sample
Here's the set of blocks (against the standard white editing background) that represents all the different colors we're currently using.
![image](https://cloud.githubusercontent.com/assets/1266318/14025589/0ef15700-f1ac-11e5-931a-6da18802cea2.png)

And for category reference, here's a set of screenshots showing the block menus individually opened.  Note that the colors will have more contrast when used in the editor (on the white background) than they appear in the menu (on the gray background).

#### Control
![image](https://cloud.githubusercontent.com/assets/1266318/14025683/88d5c4fc-f1ac-11e5-82a0-541d6861a68a.png)

#### Conditions
![image](https://cloud.githubusercontent.com/assets/1266318/14025709/ab375600-f1ac-11e5-8c31-9b329091ccdc.png)

#### Math
![image](https://cloud.githubusercontent.com/assets/1266318/14025723/b88ff1c2-f1ac-11e5-966e-3ba6d2b3f953.png)

#### Multicore
![image](https://cloud.githubusercontent.com/assets/1266318/14025729/c3b8c3f8-f1ac-11e5-8048-b74f0c2947ee.png)

#### Pin states
![image](https://cloud.githubusercontent.com/assets/1266318/14026235/274022de-f1af-11e5-82a6-e757a63e399d.png)

#### Timing
![image](https://cloud.githubusercontent.com/assets/1266318/14026241/2ea810cc-f1af-11e5-9c36-8b72583e24de.png)

#### Serial terminal
![image](https://cloud.githubusercontent.com/assets/1266318/14026249/3e3253cc-f1af-11e5-862f-14150ee7f01f.png)

#### Protocols
![image](https://cloud.githubusercontent.com/assets/1266318/14026255/44333e1c-f1af-11e5-8178-8f6a0edc3870.png)

#### Voltage
![image](https://cloud.githubusercontent.com/assets/1266318/14026265/4be0d0b6-f1af-11e5-9ab9-9cee0c9dd0f5.png)

#### Memory
< Currently Empty >

#### Audio
< Currently Empty >

#### ETape liquid level
![image](https://cloud.githubusercontent.com/assets/1266318/14026286/64f17d26-f1af-11e5-947a-22fb68fdda22.png)

#### HMC5883
< Currently Empty >

#### 2-axis Joystick
![image](https://cloud.githubusercontent.com/assets/1266318/14026306/7fc32eb0-f1af-11e5-9249-0e3f5151547c.png)

#### Memsic 2-axis
< Currently Empty >

#### MMA7455
< Currently Empty >

#### GPS PAM7Q
![image](https://cloud.githubusercontent.com/assets/1266318/14026327/93af6290-f1af-11e5-9b2d-5096b8bb9bb2.png)

#### Distance: PING)))
![image](https://cloud.githubusercontent.com/assets/1266318/14026546/9067b794-f1b0-11e5-9ce1-cd0bb04c59ce.png)

#### PIR Motion
![image](https://cloud.githubusercontent.com/assets/1266318/14026556/9fdf5c72-f1b0-11e5-8292-3192c51a9ee0.png)

#### RFID
< Currently Empty>

#### SF02 Laser
![image](https://cloud.githubusercontent.com/assets/1266318/14026565/a9e7c5a6-f1b0-11e5-9ab6-8af965164968.png)

#### Sony Remote
< Currently Empty >

#### Sound Impact Sensor
< Currently Empty >

#### Standard Servo
![image](https://cloud.githubusercontent.com/assets/1266318/14026384/d49d43a8-f1af-11e5-9b28-3d085644c374.png)

#### CR Servo
< Currently Empty >

#### Serial LCD
![image](https://cloud.githubusercontent.com/assets/1266318/14026399/f270c436-f1af-11e5-8a59-ede4539425fb.png)

#### ActivityBot
![image](https://cloud.githubusercontent.com/assets/1266318/14026403/f8898218-f1af-11e5-969f-12ab5ae68e9e.png)

#### Servo Differential Drive
< Currently Empty >

#### LED Control
![image](https://cloud.githubusercontent.com/assets/1266318/14026423/0ee549c0-f1b0-11e5-979d-8ff0b7b87a5c.png)

#### OLED
![image](https://cloud.githubusercontent.com/assets/1266318/14026432/1594ad38-f1b0-11e5-8e07-3ff500fd045e.png)

#### IR Communication
![image](https://cloud.githubusercontent.com/assets/1266318/14026439/1bae15a6-f1b0-11e5-80a4-375f880c2f9a.png)

#### EEPROM
![image](https://cloud.githubusercontent.com/assets/1266318/14026442/2251fbfc-f1b0-11e5-8e8d-c502aafc5d23.png)

#### Accelerometer
![image](https://cloud.githubusercontent.com/assets/1266318/14026452/2a8065ca-f1b0-11e5-9fcc-d46bfd785617.png)

#### Touchpad Control
![image](https://cloud.githubusercontent.com/assets/1266318/14026467/34cdbbd6-f1b0-11e5-8ce0-046ae9dbba3f.png)

#### Functions
![image](https://cloud.githubusercontent.com/assets/1266318/14026475/3dc9b028-f1b0-11e5-94e4-7c3cf98cb02d.png)

#### Variables
![image](https://cloud.githubusercontent.com/assets/1266318/14026497/57d2702c-f1b0-11e5-9689-d2b5aa9919c8.png)

**Comment by michel-cf** [comment]
I have not yet changed the 2 other (fixed) parameters. If a change needs to be made to those, please let me know what values should be used. (this is a change in the core Blockly code and as such we'll need to make a list of what changes or done for when we update the Blockly core)

**Comment by JenJacobs** [comment]
![newblocks](https://cloud.githubusercontent.com/assets/15825277/14030976/d13ecd40-f1c7-11e5-807b-f07e49c86dda.png)

Thank you for the screen shots, very helpful. For brighter blocks I propose green, aqua, blue, purple, and red. Mocked them up so you can see how they would look. Thoughts?

Green #2CB231
Aqua #2CA9B2
Blue #2C64B2
Purple #B22C91
Red #B22C2C

![blockly](https://cloud.githubusercontent.com/assets/15825277/14031035/217d237e-f1c8-11e5-8666-9a316c89d427.png)

**Comment by PropGit** [comment]
@JenJacobs - That's definitely more appealing to me.  

I'm concerned it may be a tiny bit too bright because a couple of the colors feel harder to look at than others.  It might just be my eyes.  This is a saturation of 75% and value of 70%.  What do you think of something like 70% and 65%, respectively?  Maybe that's too dark?

@cbradyatinquire - Since you have students (I don't know what age range), can you give us your opinion too?  Are we closer to the target?

@JenJacobs - Can you make a sample that adds more colors in-between?  Perhaps a set of 10 or 12 colors all-together?  I think that will give us more choices to apply to different categories of blocks and should still be distinct enough on-screen.

Thanks!

**Comment by michel-cf** [comment]
Please remember that Blockly uses the HSV model with saturation and value. So, could you please provide the fixed values and the selected Hue value for each color?

**Comment by PropGit** [comment]
@michel-cf - Okay.  What Jen provided was 75% Saturation, 70% Value, and Hues of 122, 184, 216, 316, and 0 degrees.

**Comment by JenJacobs** [comment]
@PropGit Here are some less bright options in the same family. I can add more colors, how many sets of blocks do we expect to have?

@michel-cf I can get you the HSV values, no problem.

![lessbright](https://cloud.githubusercontent.com/assets/15825277/14032662/a9cf15bc-f1d1-11e5-9b3e-ef8db4cd93af.png)

**Comment by PropGit** [comment]
@JenJacobs That _does_ look a little more dull; maybe washed-out is a better term.  I was hoping my suggestion would be less intense but not dingy.  You're original were more appealing to me.

>I can add more colors, how many sets of blocks do we expect to have?
This is hard to pinpoint and it has changed over time.  Right now we have about 10 categories and it's likely to increase, at least slightly.  Most human eyes can detect many hundreds (thousands?) of shades of color when they are right next to each other, but when there's distance involved between two shades of a color, the distinguishable count goes way down.  In practice, I'm guessing that around about 20 shades or more (not including the white editor background) is probably counter-productive in more ways than one.

So, unless someone ( @michel-cf, @cbradyatinquire, @DarkmatterVale, @AndyLindsay ) has a compelling opinion about this, let's try out 16 shades.

**Comment by JenJacobs** [comment]
Ok. If we go in increments of 25 for the 'H' value you can have 15 colors to choose from and nice round numbers that are easy to remember.

![blocklypropin25s](https://cloud.githubusercontent.com/assets/15825277/14033734/e9479e3c-f1d9-11e5-9be6-4ac215a03559.png)

**Comment by PropGit** [comment]
Thanks @JenJacobs.  Good choice.  I think that provides a nice range of colors without getting too wild.

**Comment by DarkmatterVale** [comment]
I like these colors as well.

**Comment by cbradyatinquire** [comment]
I agree in general.  I'm very glad to get the orangey and yellowey colors in play.  I do think that Row 1 column 4 is sub-optimal, and row 1 col 5 is too close to Row 2 col 1 & Row 2 col 2 to distinguish them  Same with Row 2 col 5 and Row 3 col 1; and Row 1 col 1 and Row 3 Col 4 & 5.  So we probably realistically have 9 or 10 fully distinguishable colors here.  

Also - does anyone know:  How do these do with Color Blind users?

-C

**Comment by JenJacobs** [comment]
@cbradyatinquire I had the same concern when we were working with just 5 colors. A palette of 15 is going to be tough on colorblind users - I'm not sure there's any way around that.

**Comment by michel-cf** [comment]
We might try http://colororacle.org/index.html to see how it looks for colorblind people.
Google gives plenty of results when searching for _colorblind safe palette_

**Comment by JenJacobs** [comment]
@michel-cf Additional color blind palettes could also be developed if it's possible to toggle between things like that in Blockly.

**Comment by michel-cf** [comment]
It's not built in, but I could create a system where we manage colors in a central place and the blocks request what color they should be instead of being hardcoded in each block. It would still only be the Hue that can changes due to the way Blockly is set up. Being able to change all 3 parameters or using a different color model will need investigation, and if possible, will require quite a bit of customization work in the core of Blockly. Which will make it hard to upgrade.

**Comment by michel-cf** [comment]
We could make the colorblindness type selection part of the profile page.
I need to know everything before initializing Blockly. I don't think I can change block colors after that. So, making the selection part of the profile makes sure I have the information beforehand and it eliminated the requirement for a selection on the editor screen. (We want this to be minimal, to have as much space for the editor as possible)
