### ISSUE TITLE
HEB: add terminal blocks

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#692]
The badge can communicate with the terminal...

**Comment by MatzElectronics** [comment]
Please add a "Terminal" category in the HEB to include all of the blocks from ActivityBoard WX > Protocols > Terminal.

**Comment by DarkmatterVale** [comment]
We do not need to make any changes to the actual blocks though, right?

**Comment by MatzElectronics** [comment]
Correct!

**Comment by PropGit** [comment]
In Demo after 5:15 pm.

**Comment by DarkmatterVale** [comment]
Verified?

**Comment by MatzElectronics** [comment]
Tested and verified.  Finally :)
