### ISSUE TITLE
Discussion: add new line checkbox on some blocks?

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#699]
Would this be worth doing on: Terminal print, OLED print, LCD print, etc.?
![image](https://cloud.githubusercontent.com/assets/19737272/18293170/01e17c6c-7446-11e6-804f-cf3f8a8a1211.png)

**Comment by PropGit** [comment]
Yes, I think so, if it's defaulted to checked since most uses will be for scrolling displays of output.

I don't know about the text "add new line"... it doesn't read as a pseudo-sentence in the context of this.  What about "then a new line" ?  Or something else?

**Comment by MatzElectronics** [comment]
funny, I actually started with "then a new line".  I like it :)  I'll get them drafted.

**Comment by PropGit** [comment]
In Demo after 12:30 pm.

**Comment by MatzElectronics** [comment]
Tested, failed - correction in #703

**Comment by PropGit** [comment]
Fix in #703 in demo after 1:15 pm

**Comment by PropGit** [comment]
@MatzElectronics - Please use \r (instead of \n) when new line is checkmarked... a Simple Libraries problem related to the things we discussed on Tuesday leads to two effective new lines when \n is used.

**Comment by MatzElectronics** [comment]
Got it - in #704

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by MatzElectronics** [comment]
Tested and verified
