### ISSUE TITLE
Proposed BlocklyProp Logo

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#70]
Here is the proposed BlocklyProp logo.  This is intended to be used in strategic places in the UI and related documenation.  @michel-cf - What do you think?

![blocklyproplogo](https://cloud.githubusercontent.com/assets/1266318/11083437/7fe3f2ba-87e4-11e5-96a6-b23668b6bbd4.png)

**Comment by michel-cf** [comment]
Looks nice, I resized it and added it

**Comment by DarkmatterVale** [comment]
I am going to close this issue since we have added the new logo.
