### ISSUE TITLE
S3: LED Block bug on main site (works in DEMO)

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#705]
@PropGit I need your assistance sorting this problem out. Here's the Blockly code:

http://demo.blockly.parallax.com/blockly/editor/blocklyspin.jsp?project=119#

This is the Spin source generated on the DEMO site:

```
CON
  _clkmode = xtal1 + pll16x
  _xinfreq = 5_000_000

VAR

OBJ
  scribbler    : "Block_Wrapper"

PUB Setup
  Scribbler.Start
  Start


PUB Start

  repeat
    if Scribbler.SimpleObstacle(Scribbler#IS_NOT, Scribbler#DETECTED)
      Scribbler.SetLED(Scribbler#LEFT, Scribbler#COLOR_00ff00)
      Scribbler.SetLED(Scribbler#CENTER, Scribbler#COLOR_00ff00)
      Scribbler.SetLED(Scribbler#RIGHT, Scribbler#COLOR_00ff00)
    if Scribbler.SimpleObstacle(Scribbler#IS, Scribbler#CENTER)
      Scribbler.SetLED(Scribbler#LEFT, Scribbler#COLOR_ff0000)
      Scribbler.SetLED(Scribbler#CENTER, Scribbler#COLOR_ff0000)
      Scribbler.SetLED(Scribbler#RIGHT, Scribbler#COLOR_ff0000)
    if Scribbler.SimpleObstacle(Scribbler#IS, Scribbler#LEFT)
      Scribbler.SetLED(Scribbler#LEFT, Scribbler#COLOR_ff0000)
      Scribbler.SetLED(Scribbler#CENTER, Scribbler#COLOR_00ff00)
      Scribbler.SetLED(Scribbler#RIGHT, Scribbler#COLOR_00ff00)
    if Scribbler.SimpleObstacle(Scribbler#IS, Scribbler#RIGHT)
      Scribbler.SetLED(Scribbler#LEFT, Scribbler#COLOR_00ff00)
      Scribbler.SetLED(Scribbler#CENTER, Scribbler#COLOR_00ff00)
      Scribbler.SetLED(Scribbler#RIGHT, Scribbler#COLOR_ff0000)
```

This is the Spin source generated on the main site:

```
CON
  _clkmode = xtal1 + pll16x
  _xinfreq = 5_000_000

VAR

OBJ
  scribbler    : "Block_Wrapper"

PUB Setup
  Scribbler.Start
  Start


PUB Start

  repeat
    if Scribbler.SimpleObstacle(Scribbler#IS, Scribbler#DETECTED)
      Scribbler.SetLED(Scribbler#LEFT, Scribbler#COLOR_00ff00)
      Scribbler.SetLED(Scribbler#CENTER, Scribbler#COLOR_00ff00)
      Scribbler.SetLED(Scribbler#RIGHT, Scribbler#COLOR_00ff00)
    if Scribbler.SimpleObstacle(Scribbler#IS, Scribbler#CENTER)
      Scribbler.SetLED(Scribbler#LEFT, Scribbler#COLOR_ff0000)
      Scribbler.SetLED(Scribbler#CENTER, Scribbler#COLOR_ff0000)
      Scribbler.SetLED(Scribbler#RIGHT, Scribbler#COLOR_ff0000)
    if Scribbler.SimpleObstacle(Scribbler#IS, Scribbler#LEFT)
      Scribbler.SetLED(Scribbler#LEFT, Scribbler#COLOR_ff0000)
      Scribbler.SetLED(Scribbler#CENTER, Scribbler#COLOR_00ff00)
      Scribbler.SetLED(Scribbler#RIGHT, Scribbler#COLOR_00ff00)
    if Scribbler.SimpleObstacle(Scribbler#IS, Scribbler#RIGHT)
      Scribbler.SetLED(Scribbler#LEFT, Scribbler#COLOR_00ff00)
      Scribbler.SetLED(Scribbler#CENTER, Scribbler#COLOR_00ff00)
      Scribbler.SetLED(Scribbler#RIGHT, Scribbler#COLOR_ff0000)
```

The two codes behave differently! The one on the DEMO site works as we would expect it to; the one on the main site does not. It seems to retain a red LED on the right or left long after the object has been removed from the field of view. Frustrating because I can't see what's going on underneath in the code - maybe you can?

**Comment by PropGit** [comment]
The difference is in the generated code
```
if Scribbler.SimpleObstacle(Scribbler#IS_NOT, Scribbler#DETECTED)
```
```
if Scribbler.SimpleObstacle(Scribbler#IS, Scribbler#DETECTED)
```

This must be something that was patched in Demo after Production was made live.  The update to Production we do on Monday should solve this.  I will notify you at that time.

**Comment by PropGit** [comment]
@kgracey - On second thought... is it possible the project on the Production site has the first __obstacle__ block set to "is" instead of "is not"?

**Comment by wstodghill** [comment]
@kgracey and @PropGit, 

Just thinking...Was the order of the pull-down menu ever changed on this block?

**Comment by zfi** [comment]
@kgracey: Can you verify that the generated code from the exact same set of blocks is different between Demo and Beta? As @PropGit  identified, the code does not match, but we do not know if the source blocks are assembled in the same way.

**Comment by MatzElectronics** [comment]
@kgracey @wstodghill Is this still an issue/bug?  Can someone please verify?

**Comment by wstodghill** [comment]
@MatzElectronics - Will check this out and let you know...

**Comment by wstodghill** [comment]
@MatzElectronics - This now appears to be resolved 

Here is the original code on the demo site - http://demo.blockly.parallax.com/blockly/editor/blocklyspin.jsp?project=119#
WORKS as expected!

Here is the same code on the the live BlocklyProp site - 
http://blockly.parallax.com/blockly/editor/blocklyspin.jsp?project=2427#
WORKS as expected!

I think we got this one solved and the CAN BE CLOSED.

**Comment by MatzElectronics** [comment]
No - I can't get it to work either, but it's not the LEDs.  It's the obstacle detection, so that deserves a new issue.

Thanks Whit!
