### ISSUE TITLE
Search doesn't work on Community or My Projects

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#707]
The Search field doesn't work on the Community or My Projects pages.  Typing into it causes a refresh, but it doesn't appear to filter the displayed rows.

The Community Projects list is growing quickly, we need this feature working properly very soon.

**Comment by PropGit** [comment]
We need search to match against the following fields/data, and in this order of importance if possible:

1. User
1. Name
1. Board
1. Description

For example, we have made "user" accounts that we will use to create and host official examples.  Parallax S3 is the screen name of the user account that we'll share lots of Scribbler 3 examples from.  I can foresee that one important technique we'll suggest people use is to come to the Community Projects page and type "Parallax S3" into the search field to see all the official Scribbler 3 examples appear at the top of the list (ie: it matched first to the exact User screen name field and priorities those matches above any matches on Name, Board, or Description.

**Comment by kgracey** [comment]
We should remove the search function and tag this a future enhancement unless @michel-cf has plans to make it work properly. Please advise.

**Comment by PropGit** [comment]
@DarkmatterVale - Can you remove (or assist with removing) the search function?  If you're unsure, just say so and we'll assign it to someone else.

**Comment by DarkmatterVale** [comment]
I will try...

**Comment by DarkmatterVale** [comment]
I just verified this has been successfully disabled in demo.

**Comment by PropGit** [comment]
Confirmed also.  Thanks @DarkmatterVale.

**Comment by DarkmatterVale** [comment]
No problem let me know if there is anything else I can do to help out.
