### ISSUE TITLE
Supporting Page Design

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#71]
For the supporting pages (all non-editor pages), the following are proposed samples of the style and assets.  The menu of Issue #68 and recently demonstrated menu (from @michel-cf) should be merged into this proposed design.

__Desktop Dimensions:__
![blocklyprop-desktop](https://cloud.githubusercontent.com/assets/1266318/11083539/5c987456-87e5-11e5-8c9c-cd5a195c9a3a.png)

__Tablet Dimensions:__
![blocklyprop-phone](https://cloud.githubusercontent.com/assets/1266318/11083541/5fb07094-87e5-11e5-9c73-aab8579dda9a.png)

__Phone Dimensions:__
![blocklyprop-phone](https://cloud.githubusercontent.com/assets/1266318/11083549/6ef2f3d8-87e5-11e5-891d-87e554ceb4ca.png)

**Comment by PropGit** [comment]
@michel-cf - Please consider and comment on the above design proposals.

**Comment by michel-cf** [comment]
Added the logo, and content, while keeping the menu that I already created

![image](https://cloud.githubusercontent.com/assets/5745991/11095023/5c892100-8893-11e5-8afa-7126d4dcdbc7.png)

**Comment by jeffam70** [comment]
Looks good, thanks!

**Comment by PropGit** [comment]
I'm closing this request as the majority is done and the Login/Register buttons are on the menu, which is deemed sufficient.
