### ISSUE TITLE
blockly.parallax.com needs a favicon!

### ISSUE THREAD

**Issue by bweir** [parallaxinc/BlocklyProp#710]
It's missing one!

**Comment by wstodghill** [comment]
![blocklyprop favicon](https://cloud.githubusercontent.com/assets/8891440/18416609/d6b60232-77de-11e6-89fb-36e29517e55c.JPG) - the logo would work well.

**Comment by bweir** [comment]
Second that! Also, omg, the new site looks amazing. I wanna start using
blockly now.

**Comment by MatzElectronics** [comment]
In demo - tested and verified, closing as it will propagate to production
