### ISSUE TITLE
Viewing project with shared link leaves user stuck if they want to Run/Save

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#714]
Projects shared via link are viewable, but not runable unless the user is logged in.  That is understood and desired; however, the user has no easy path to get logged in at the point he/she wants to run or save.

![image](https://cloud.githubusercontent.com/assets/1266318/18483687/fe90ee36-7999-11e6-84dd-fd42c7eaac36.png)

We need to either replace those Run/Save menus with a login/register link, or even better, make the action of clicking those menus cause the "You are not logged in" dialog appear.  

It's also desirable for the message to say "You must log in to Run or Save" in that case.

![image](https://cloud.githubusercontent.com/assets/1266318/18483750/57519598-799a-11e6-9be0-986097860e1c.png)

**Comment by zfi** [comment]
Currently, logging in after modifying a shared project will destroy any changes made prior to the login.

**Comment by MatzElectronics** [comment]
Ui has been updated considerably since this issue, and I believe there is a path now.  Closing.
