### ISSUE TITLE
Use style instead of <br> tag

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#715]
@DarkmatterVale - in PR #711, there's a ```<br>``` tag in __index.jsp__ line 33.

Please use a style (src/main/webapp/cdn/style.css?) instead of the HTML tag to create more space.

**Comment by DarkmatterVale** [comment]
I have a change ready to send but I want to test before I submit a PR. I will have it ready tomorrow afternoon...

**Comment by PropGit** [comment]
@DarkmatterVale - perfect, thank you.

**Comment by DarkmatterVale** [comment]
I'm going to close this issue since it has been verified by @PropGit
