### ISSUE TITLE
Create S3 Factory Reset Block

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#717]
[EDITED]

Add a __Factory Reset__ block for the Scribbler 3.

This should be a block with no connectors, similar to this: https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#gra9ed

It is not intended for use with any other blocks... just a blank project with this block added to it and then Loaded to EEPROM.  

The default (factory reset) code is very large and in fact fills most of the EEPROM space.  The best way to implement this block is to simply include the scribbler_default object and call it from a top object.  So...

The Full Spin code that should be generated for a project that includes this block is as follows.  The scribbler_default object, and all the objects it references will be added to the Scribbler-3-Library repo.
```
CON
  _clkmode = xtal1 + pll16x     
  _xinfreq = 5_000_000

OBJ
  Scribbler_Default      : "scribbler_default"
  
PUB Run
  Scribbler_Default.Start
```

**Comment by PropGit** [comment]
@zfi - I've updated the [Scribbler-3-Library repo](https://github.com/parallaxinc/Scribbler-3_Library/tree/master) to contain the proper files for this block to work.

**Comment by wstodghill** [comment]
@PropGit - has anyone suggest an an appearance for this block?

**Comment by MatzElectronics** [comment]
The OLED font loader is similar in function...  might be a good starting
point.

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by PropGit** [comment]
@MatzElectronics and @wstodghill - Exactly what we were thinking.  @zfi actually suggested the same thing to me in-person.

I expect that we'll have this feature working soon; we've been busy monitoring and correcting server-side issues during the ongoing class this week so that they have a good experience.

**Comment by PropGit** [comment]
@zfi - Now that we're past the _nervous parent_ moment of BlocklyProp usage, do you have time to work on your cool ideas to implement this block?

**Comment by PropGit** [comment]
Issue #581 and this one are asking for the same thing.

**Comment by zfi** [comment]
Need some help testing this. The block currently creates the code below. Note that there are two CON blocks. It appears that the base scribbler class generates the first CON block. Do we still need the second CON block within the Start function?

```
CON
  _clkmode = xtal1 + pll16x
  _xinfreq = 5_000_000

VAR

PUB Setup
  Start

 PUB Start
    CON
      clkmode = xtal1 + pll16x
      xinfreq = 5_000_000

  OBJ
    Scribbler_Default      : "scribbler_default"
  PUB Run
    Scribbler_Default.Start
```

**Comment by PropGit** [comment]
@zfi - thanks.  

No, the CON block in Start will not work (it shouldn't compile).  Also, all the PUB and OBJ blocks need to start in column 0.

If the CON and VAR blocks are specified by base object, that's fine.

I don't know why there's a PUB Setup method that calls Start.  Is the PUB Setup automatically created by the base object?  In the example code you provided, it'd be great the Setup and Start methods can be removed.

By convention, the OBJ block should be above the first PUB; but that's not a requirement.

**Comment by zfi** [comment]
The block creates all of the code beginning with the PUB Start line. I will remove the constants block and change the indent on the remain code. Do the Setup and Run block get executed in some default way in Spin?

**Comment by michel-cf** [comment]
The first PUB in the file gets executed first.

**Comment by zfi** [comment]
@michel-cf Thanks for the clarification. 
@PropGit, The indenting is happening under the scribbler block definition. The text I am passing in has no leading spaces for the PUB and OBJ lines. This leads me to updating the Scribbler3_Library/Bockly_Wrapper file and place the code in there.

**Comment by zfi** [comment]
Created a PR in the Scribbler3_Library Repo to address the leading spacing issue.

**Comment by zfi** [comment]
The latest code emits the code below.  If this looks right, I will proceed with a PR.

```
CON
  _clkmode = xtal1 + pll16x
  _xinfreq = 5_000_000

VAR

OBJ
  scribbler    : "Block_Wrapper"

PUB Setup
  Start


PUB Start

  Scribbler.RestoreS3Demo
```

**Comment by PropGit** [comment]
@zfi - Yes, that looks good.  If you can, remove the blank line between __PUB Start__ and __Scribbler.RestoreS3Demo__ then make a PR.

**Comment by wstodghill** [comment]
Cool!

**Comment by zfi** [comment]
The code underlying the reset block is adding the blank line after the PUB Start and cannot be easily altered to remove the extraneous blank line. The Scribbler object reference has been replaced with it's lower case sibling, scribbler.

**Comment by wstodghill** [comment]
A note of thanks to people way smarter than me working on this...
