### ISSUE TITLE
Create Block for System Counter

### ISSUE THREAD

**Issue by JonMcPhalen** [parallaxinc/BlocklyProp#719]
Create bock a that provides the current value in the system counter (cnt); block would be used like a read-only variable. Suggest adding block to Variables group.

**Comment by kgracey** [comment]
This is specifically what Jon is asking for:

A block similar to random that provides the system counter. In use it would look like:

![image](https://cloud.githubusercontent.com/assets/9534148/18573319/1d582ef4-7b77-11e6-8f03-07ae934e94d3.png)

For C the compiler would generate:

  timer1 = CNT;

I don't know if the C compiler has this kind of access which exists in Spin.

**Comment by MatzElectronics** [comment]
It does, and your code is exactly correct

**Comment by PropGit** [comment]
In Demo after 10:45 am.

**Comment by MatzElectronics** [comment]
Tested and verified
