### ISSUE TITLE
Oled Activity Lost

### ISSUE THREAD

**Issue by chipken** [parallaxinc/BlocklyProp#723]
Oled function fine before activating new processors , cogs.  Cogs seem to deactivate the Oled commands. Oled commands inside main program and not inside the cogs.

**Comment by MatzElectronics** [comment]
Can you tell me which program it is that's doing it @chipken?

**Comment by chipken** [comment]
Matt

UnsteadyStateHTControloled3
Thanks
Chuck

**Comment by MatzElectronics** [comment]
@chipken I've set this up on my board, but I can't replicate your problem.

**Comment by MatzElectronics** [comment]
I'm digging into this a bit further - and the problem is hard to track down, but I'm making some progress.  I'll keep updating as I learn more.

**Comment by zfi** [comment]
@MatzElectronics: Have you been able to reproduce the reported issue? If not, let's archive this until we see it again.

**Comment by MatzElectronics** [comment]
I can reproduce it, but I haven't had time to build up to the cause of it...

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by zfi** [comment]
Thanks for that update. This issue is deferred until the next release cycle.

**Comment by MatzElectronics** [comment]
This happens under VERY specific circumstances, and may not be fixable.  There have been workarounds to date.  Closing.
