### ISSUE TITLE
Production has no help system

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#724]
The help system changes we made may not have ever propagated to the Production System.

Clicking the Help link in blockly.parallax.com produces this page:
![image](https://cloud.githubusercontent.com/assets/1266318/18645293/68a88420-7e61-11e6-8d52-9a889953c5e7.png)

but in Demo it produces this page:
![image](https://cloud.githubusercontent.com/assets/1266318/18645306/7e7a8cc6-7e61-11e6-9a61-788edf564dd9.png)

**Comment by zfi** [comment]
There is an issue with file system permissions on the BlocklyProp Service instances. 

    Sep 15, 2016 7:38:07 PM  com.parallax.server.blocklyprop.utils.HelpFileInitializer$HelpFileConverter run
    SEVERE: null
    java.nio.file.AccessDeniedException: /usr/share/tomcat7/help-lucene

**Comment by zfi** [comment]
A secondary issue has been observed where the page fails to render one of the two images due to JVM heap exhaustion.

**Comment by PropGit** [comment]
What a crazy situation (JVM heap exhaustion on image load).  We don't have this problem on Demo, running the same source, so can we narrow it down to a difference between the host on Production vs. Demo?

**Comment by zfi** [comment]
It is likely that the error does not occur in Demo because the system has lower use and the app is restarted on every PR committed to the repo.

**Comment by DarkmatterVale** [comment]
I believe this has been fixed. I went to http://blockly.parallax.com/blockly/public/help and I can see the tutorials.

**Comment by MatzElectronics** [comment]
Seems to work consistently for me as well. Closing.
