### ISSUE TITLE
Remove If __ return block?

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#726]
These two things generate the same code - and from an educational standpoint, I question the need for a if __ return block.
![image](https://cloud.githubusercontent.com/assets/19737272/18730197/e0c74258-8009-11e6-8fba-bc51d724c536.png)
Thoughts?

**Comment by PropGit** [comment]
I agree, keep the __if do__ and remove the __if__ blank __return__.  Anyone else?

**Comment by DarkmatterVale** [comment]
I think removing the if blank return block wouldn't do any harm. Maybe keep it in the code for now until we can get users' opinions about having to use the if block with the return block (but remove from the UI)?

**Comment by MatzElectronics** [comment]
In PR #731

**Comment by PropGit** [comment]
In Demo after 10:45 am.

**Comment by MatzElectronics** [comment]
Tested and verified
