### ISSUE TITLE
Custom C Code block

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#727]
We could conceivably create a block that would allow a user to just add the C code of their choice, essentially taking all of the limits off :)

It might need an option menu that specifies whether it's a "setup" or code that goes in "main".

![image](https://cloud.githubusercontent.com/assets/19737272/18732228/7a4899f2-8016-11e6-8c86-a6b3216a65f3.png)

Thoughts?

**Comment by PropGit** [comment]
That's intriguing, but can you explain the intended use case / audience?  
[playing devil's advocate] Is there a chance this will negatively impact the student audience that BlocklyProp was meant for?  Will it help them?  Others?

**Comment by kgracey** [comment]
On the fence on this one. I notice that most teachers who attend our courses still have no programming experience of any kind. Also, by crossing the visual-to-text bridge within Blockly you introduce the ability to make non-compiling code. Do you want to do that? I don’t know if it matters or not - I personally love the feature you propose but I really don’t know how the target customer would feel about using it. 

This answer should probably be driven by a need. Is there a particular need to insert manual code? Something you discovered while creating a BPSK project?

Ken Gracey
graceyken@gmail.com

**Comment by MatzElectronics** [comment]
I wanted to share the idea when I thought of it - to be honest, I don't have an immediate thought about it - but it's something we should just keep on the back burner as a possibility.  I would truly take the brakes off for power users, but it has zero use for beginners.

**Comment by PropGit** [comment]
Good thoughts.  Let's keep it on the back burner for now and re-address when we feel there's an immediate need, or we run out of other fun stuff to do.

**Comment by MatzElectronics** [comment]
I'm going to create this but leave it hidden.

**Comment by kgracey** [comment]
Code junkie. Welcome to the developer team  MatzM. You're adding cool stuff.

**Comment by MatzElectronics** [comment]
Guilty as charged.

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by DarkmatterVale** [comment]
I agree with Mr. Gracey; adding this block should address a need. Since our target audience is kids who do not yet know how to program, I do not think there is a need for this block.
