### ISSUE TITLE
Make Undo/Redo button in editor

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#730]
Can an Undo/Redo function be added to BlocklyProp's Editor?  This may be a Blockly issue.

From @kgracey at a recent Educator's Course -
> Several teachers asked for an “undo” button in Blockly.

**Comment by DarkmatterVale** [comment]
This is already available; right click in the workspace and select "Undo" or "Redo".

**Comment by PropGit** [comment]
Great!  Then we'd like two added top-level menus (no drop downs), or two added buttons, called "Undo" and "Redo" (surprise!) that call the respective functions.  Maybe they can appear top and center on the header?

@kgracey - What do you think?

**Comment by PropGit** [comment]
__UPDATE__ - @zfi says "There is work being done in the base Blockly project to provide this functionality. We should be able to inherit it when it becomes available."

**Comment by wstodghill** [comment]
Neat! I like the "Clean up Blocks" right click too!

**Comment by zfi** [comment]
This will be released in the October 20, 2016 update.
Closing this issue.
