### ISSUE TITLE
Rename "rotate...around a radius" block

### ISSUE THREAD

**Issue by RoboTechie** [parallaxinc/BlocklyProp#735]
This block should be renamed to "**arc** the the Scribbler robot..." (Instead of "rotate...") to reduce confusion with the other rotate block, and to improve clarity, since most people will be using this block to draw an arc.

**Comment by MatzElectronics** [comment]
I'm in favor - but I don't know how much this affects documentation - can anyone else chime in so I know whether or not to fix this one? @kgracey @wstodghill?

**Comment by wstodghill** [comment]
I think we plan to have an arc block in the next round of blocks - Let's think about this a bit more and get some input from @kgracey

**Comment by dcarrier-parallax** [comment]
An arc is a rotation around a non-zero radius.  The block allows for rotation with a radius of zero, which is not an arc.  A rotation can have a zero or non-zero radius, so 'rotate' describes all uses of the block, while 'arc' does not.

**Comment by zfi** [comment]
Any further comments?

**Comment by RoboTechie** [comment]
David and I discussed this and the other issues related to this block the other day. It was/is my opinion that "arc" is more clear/easier to understand than "rotate around a point", even if that means that it's technically incorrect when r=0 (I also suggest separate zero radius turn (I would just call it "spin) block is created). However, David was/is in favor of keeping the block name as is. We ultimately agreed to disagree, so we'll need other "votes" to move either way.

**Comment by wstodghill** [comment]
Since the SIMPLE SCRIBBLER>SIMPLE ACTIONS block that "spins" the S3 in place is called rotate - I propose and "vote" (be glad when the campaign is over!) for keeping the ACTIONS>MOTORS block that rotates or spins the S3 for a number of degrees (+/-), around a radius (in units (+/-)), and at a top speed as rotate also. I just want it to work as advertised - then I will document it everywhere (and find all the old documentation and get it fixed. 

My name is Whit and I approve this message - ;-)

**Comment by zfi** [comment]
...Sponsored by the Rotate to a Better Arc SuperPAC. 

Assuming that we create a separate block to complete an arc, the rotate block could be greatly simplified to be a rotate on axis n degrees and x speed. The new arc block would inherit the features and function of the current rotate block with one important distinction. It would not accept a zero radius.

Does this work for all interested parties?

**Comment by wstodghill** [comment]
I am in! 

Glad the rotate (around a radius block is working live Beta BlocklyProp site (not sure when it was fixed). 

I have been studying all the methods in the Scribbler Object (especially the draw ones) to see what we might like to create block for (just moving slower than I planned!)

**Comment by RoboTechie** [comment]
That sounds great to me! The other thing to figure out is how direction (left turn vs right turn) will be specified in the block (I think a drop-down direction selector would be the way to go).

**Comment by wstodghill** [comment]
@RoboTechie - I agree - visual is good (especially in Blockly!)

**Comment by zfi** [comment]
Issue #737 addresses how we can handle rotational direction within the block.

**Comment by zfi** [comment]
Closing this issue and will continue work on #737 after October 20th.
