### ISSUE TITLE
Fix speed handling in "rotate...around a radius" block

### ISSUE THREAD

**Issue by RoboTechie** [parallaxinc/BlocklyProp#736]
When a negative speed is used (which I understand is not supposed to be, but the code allowed it), and a negative angle is provided, the S3 does not follow the input radius (follows a larger radius). This was at least true for radii less than that of the S3, untested for radii larger than the S3. It also drives slower than the absolute value of the provided speed.

For a negative speed, but positive angle values, the S3 does follow the correct radius, but still drives at a slower speed than the absolute value of the speed.

Based on how the "rotate...around a radius" block is structured, I would suggest simply taking the absolute value of any speed provided, so that negative speed values have not effect.

**Comment by dcarrier-parallax** [comment]
Negative speeds are not valid, as indicated on the block.  Blockly does not have any mechanism to alert the user that a value is out of range.  For consistency, when a value is out of range, the block wrapper uses the closest in-range value.  In this case, it is the slowest motor speed. 

This will be clarified in the documentation.
