### ISSUE TITLE
Add direction input to "rotate...around a radius" block

### ISSUE THREAD

**Issue by RoboTechie** [parallaxinc/BlocklyProp#737]
The "rotate...around a radius" block does not have any settings to allow a left-handed (driving forward, counter-clockwise) arc. I tried all four combinations of degree signs and speed signs, but all of the maintain a right-hand arc.

I suggest adding a drop-down direction selector as is used in the "rotate_for__at_speed" block.

**Comment by dcarrier-parallax** [comment]
To rotate around a radius to the left of the scribbler (i.e. forward and counter clockwise or reverse and clockwise) enter the radius as a negative number.  The axis for the distance of the radius is negative to the left and positive to the right.

The documentation is currently in process, but it will explain this more clearly than the text labels on the block.

Could you clarify the request at the end of your comment?  Is this an enhancement request for a block separate from the left-handed turning issue?  If not, please add another comment to this issue, with more details.  If it is a separate issue, please create a new issue for it.

**Comment by RoboTechie** [comment]
Thanks for that info. The issue was originally created because neither Ken no I could find any way to do a left hand turn. I now understand that it is possible to do so using a negative radius (yay!). 

However, it is my opinion that that is not intuitive (at least to beginners-I for one have never used negative radi in anything). Considering that one of our intentions in using blockly (as I understand it) is to make programming as intuitive and "smooth" as possible, I suggest we find a more intuitive way to program left-hand arcs. to be clear, the negative value is a fine stopgap solution (as long as it is properly documented) until a better solution can be developed.

**All of this considered, my revised request is that we add a user input to the "rotate around a ....radius" to specify the rotation direction (instead of using a negative radius value). I recommend using the style of drop-down direction selector used in the "rotate_for__at_speed" block.**

Since this is related to, but a _slight_ variation of the original request, I  will revise the issue title, and I request someone who has permissions to remove the "bug" tag and replace it with a more appropriate one.

**Comment by zfi** [comment]
Changing this issue from a bug to an enhancement. Now we can debate using negative and positive values vs a direction indicator with only positive values.

**Comment by MatzElectronics** [comment]
Will address this issue in the s3 PropC system

**Comment by MatzElectronics** [comment]
Any other discussion here?  If we add the direction drop-down, it would still allow negative values, so that it can be controlled programmatically.  For example, if it's being fed by a variable, we would want to allow that instead of using an abs() on the input.  Basically, the direction drop-down would just give it a *(-1) to reverse the direction.  Therefore, if you enter a negative value AND select CCW, it would just become CW movement.

**Comment by MatzElectronics** [comment]
Going to close this - only one person raised a concern and no agreement on follow up.
