### ISSUE TITLE
No WAITCNT?

### ISSUE THREAD

**Issue by JonMcPhalen** [parallaxinc/BlocklyProp#738]
PAUSE is easy to use and understand, and I understand why it is and should be available to newcomers. That said, WAITCNT is a powerful tool in the Propeller that should also be included -- especially since it's supported in simpletools.h.

Having advanced tools available does not hinder newcomers -- it gives them something to grow into.

**Comment by MatzElectronics** [comment]
Funny, I'm usually the one wanting more and more blocks - I think the others are probably sick of me asking for them :)
I realize that WAITCNT gets it done with a simple block, but the functionality can be achieved without it:
![image](https://cloud.githubusercontent.com/assets/19737272/18846419/a3a0a9f8-83da-11e6-9ae2-6e2f7bd24899.png)
Hopefully I got that right...
We'll keep it here, though, and if we see enough demand for it we can add it in.

**Comment by JonMcPhalen** [comment]
I would love to try this but I cannot find the SYSTEM COUNTER block.

**Comment by MatzElectronics** [comment]
Log in to HTTP://demo.blockly.parallax.com. it is our testing site where we
publish ahead of the production system.

**Comment by MatzElectronics** [comment]
You will have to set up a new account, demo and production don't share...

**Comment by JonMcPhalen** [comment]
Ugh... so much for this stuff being easy.

**Comment by MatzElectronics** [comment]
It will eventually propagate into the production system, but we are working
through a handful of improvements ahead of our mid-October release target
and making sure they aren't buggy first.

**Comment by MatzElectronics** [comment]
@JonMcPhalen did you get this to work?

**Comment by MatzElectronics** [comment]
Tested and verified

**Comment by JonMcPhalen** [comment]
Has there been any movement on things like WAITCNT and access to CTRx registers (including FRQx and PHSx)?

**Comment by MatzElectronics** [comment]
Part of the issue is where to bury it so that a novice student doesn't get
confused by it or use it in a way that breaks something, so I'm open to
suggestions here.

If we do these, which registers and commands specifically would you like to
have access to?

**Comment by JonMcPhalen** [comment]
If the goal is to get people into the Propeller, it seems to me that unique
Propeller features should be exposed. Nobody has to use them; there are
plenty of things in the Blockly system now that I find very confusing, and
I'm an experienced programmer.

Wishes:
-- Add a *waitcnt *block to the Control section. It would be structured
like *pause *with a numeric target. This would make synchronized loops
cleaner and more accurate.
-- Add access to CTRx, FRQx, and PHSx registers in the Values section
-- Provide CLKFREQ value in Values section

These simple additions would help me quite a lot, and allow me to create an
HC-8+ (http://www.efx-tek.com/topics/hc-8.html) template that our Halloween
and escape room customers could put to use. We have two 74x165 shift
registers on the board that I read in my 1ms background cog. I cannot find
access to shift_out() and shift_in() in Blockly. Is it there somewhere?

It took a frustratingly long time, but I did get a basic background process
running that increments a timer variable every millisecond. I will squeeze
other code into the background now that it's working. Still, think it would
be better with waitcnt versus using a while loop.

Jon

**Comment by MatzElectronics** [comment]
Okay, that helps, thanks.  CNT is available in values (I think...without it
in front of me) as "System counter".  Shift in and shift out where just
added to demo this week, so they will be in the public site by the end of
the week.

**Comment by MatzElectronics** [comment]
That being said, the block that is currently "System counter" could become
a drop-down and provide a list of register values, sun as CNT, CLKFREQ,
INA, etc...

**Comment by JonMcPhalen** [comment]
Since those are special registers, that would probably be okay.

**Comment by kgracey** [comment]
Can you also elaborate on the “confusing” blocks you see in Blockly, Jon?

**Comment by JonMcPhalen** [comment]
After cussing at my computer for an hour I worked my way through.

I think anything that is new to any person can be confusing. This is why I
continue to push for revealing Propeller features in Blockly. So what if a
feature like waitcnt is confusing to newcomers? A couple of good demos and
they won't be confused anymore. On top of that, they have access to
features not available on other processors and that's what is really
important.

I made my HC-8+ work program public so you can track the things I'm trying
to do. It has a background timer (runs at 1ms) and placeholders for
background processes (I need shift_in for one of them). The foreground loop
calls foreground processes that -- just for the moment -- blink LEDs. Two
are simple toggles, but the third shows how to do asymmetric blinking. This
programming style is a step up from simple LED blinkers, and shows new
Blockly programmers a means of doing many [simple] tasks in one cog.

J

**Comment by JonMcPhalen** [comment]
@Ken: One of the things that confuses me is why I don't have the Communicate blocks on my HC-8+ project. It's a generic Propeller board. I have been able to compile, download, and successfully run some simple code. What I don't understand is why the communications blocks are not available.

It seems that once a project is defined, one cannot change the board type. Why?

I really am trying to come up to speed with this so I can show my customers, but right now I would just look like an idiot doing it.

**Comment by MatzElectronics** [comment]
This is actually something that we discussed internally this week.  While
I'm not sure that we'll ever be able to allow someone to switch board types
once a project is created, it is possible to download a "blocks" file, then
re-upload it into a new project.  For now, select "FLiP/Project Board", as
it's the most fleshed-out block set that will work with a generic or custom
board.  Basically, the menu is defined in one file, and the board type
either includes or excludes categories in the menu.  The other type is
right now just what's left over, and hasn't been optimized as its own type
yet.  Feel free to raise this as an issue in github.

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by JonMcPhalen** [comment]
I tried that before seeing your note and found that it did in fact work.

Why would the Communicate group -- which is very generic -- be excluded from the "Other" board type? All of the blocks in the group allow the user to set which pins are used (excluding Terminal, which is common for every board).

How do we get the HC-8+ added to the boards list? Is there a way for me to create my own board type/rules for my projects?

**Comment by MatzElectronics** [comment]
No good reason, other than "other" has not been used at all in the menu
definition file, so what other gets as a menu is purely a product of the
inclusion/exclusion rules set for the defined board types.  "other" is a
board type, so it can be added to the file.

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by MatzElectronics** [comment]
Adding a board is Ken's call.

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by JonMcPhalen** [comment]
I don't *need* to have the HC-8+ on the list -- it would be fine to have a Generic Propeller board that provided access to all block groups and blocks within. It would be up to the programmer to decide what is useful and what isn't.
