### ISSUE TITLE
Add Cancel option for Log In prompt/page

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#74]
Add Cancel button for the Log In prompt/page.

When the user Cancels, the system takes them back to the main BlocklyProp landing page (or the current page visible under the Log In overlay if the Log In prompt is presented as an overlay as suggested in issue #72).

**Comment by michel-cf** [comment]
Where do you want this cancel button? Is this still required with the menu?
A cancel button under the form is not a good idea as users will accidentally click on it instead of submitting the form.

**Comment by PropGit** [comment]
Good point.  The menu allows the user to get back to other places (effectively cancelling out), so I'm removing this request.
