### ISSUE TITLE
Sound impact sensor block

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#742]
@kgracey @CarsonGracey has anyone tested the Sound Impact Sensor blocks?  I have some concerns about the init block - it asks the user to specify a processor to use...is there any way not to require the processor to be specified?  Will that require a library change?  I haven't researched this, but it looks like something that won't work...

**Comment by zfi** [comment]
Cores are supposed to be allocated without user interaction. Even if a cog block is specified, I don't believe we can say exactly which cog is going to be used. Prompting for a specific cog is counter to the design and should be corrected.

**Comment by MatzElectronics** [comment]
Yeah, that's what I thought - I fixed it because that's not really what was
happening.  Still need to test the fix

**Comment by MatzElectronics** [comment]
Tested and verified.
