### ISSUE TITLE
Block the compiles to getChar()?

### ISSUE THREAD

**Issue by JonMcPhalen** [parallaxinc/BlocklyProp#743]
I am trying to create a menu based app to control a simple serial MP3 player. It would be nice to have a block that compiles to something like

myKey = **getChar()**;

so that I can implement the menu through the terminal. The present terminal input only uses getStr().

**Comment by MatzElectronics** [comment]
I can modify the **Terminal receive number** block to do just that.  I'll change the "number" to a dropdown that allows you to select character as an option.  I'll try to do that today so that it ends up in demo hopefully today, if not by the end of the week.

**Comment by MatzElectronics** [comment]
I've used that in a couple other places (EEPROM/Serial) so the code already exists.

**Comment by MatzElectronics** [comment]
In PR #741

**Comment by MatzElectronics** [comment]
In demo.
