### ISSUE TITLE
XBee block improvements needed

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#745]
The XBee blocks were created before the Serial blocks were built in their current form.  Without some deeper research, I believe they do exactly the same thing, except that the serial blocks would actually allow the xbee modules to do more.

The only disadvantage is that currently, they serial block can only be used once...

There are two options - set up the serial blocks to establish multiple serial objects (hard, but better)
Or modify the XBee blocks to gain the functionality current had by the serial blocks.

**Comment by PropGit** [comment]
@MatzElectronics - I'm glad you're thinking of these things.  Make sure to pay careful attention to things like, can the XBee blocks send numerical values as ASCII digits and also as bytes, words, or longs... and can the XBee blocks receive and parse date from one form to the other?  Those are the things I remember Ken noticing to be a problem and resulted in some changes to the form I believe it's in now.

For the Terminal blocks, numbers need be sent and received only as ASCII digits, except for control characters to command the display.  For Serial and XBee, all options should probably be available, and it seems to me that the only reason to have specific XBee blocks is to provide some dedication towards specific configuration of that XBee device (AT codes, for example) along with normal data transfer use.  Whereas the Serial blocks should remain general purpose for use with every asynchronous serial device we don't directly support in BlocklyProp.

**Comment by MatzElectronics** [comment]
@PropGit The serial blocks do exactly what you describe - and seem to work very well.  The XBee blocks in their current iteration only send and recieve integers, and don't provide an option to change the baud rate - they aren't as evolved...that being said, since to code now exists for the serial blocks, it's an easy improvement to make.

**Comment by MatzElectronics** [comment]
Tested, partially failed.  I know how to fix, will submit a fix soon.

**Comment by csavage-parallax** [comment]
The following program:

![blockly_xbee_test1a](https://cloud.githubusercontent.com/assets/20691193/20729697/ffb6017c-b637-11e6-8546-28bc0a6ffa2f.jpg)

Results in the following error:

![blockly_xbee_test1b](https://cloud.githubusercontent.com/assets/20691193/20729706/0b9cedf2-b638-11e6-89b8-336d450c0229.jpg)

**Comment by csavage-parallax** [comment]
Correction, it seems to be working now...I will complete testing and follow up once again.

**Comment by csavage-parallax** [comment]
Okay, sending and receiving of text seems to be working properly. I am using an XStick on the PC and receiving strings into the PST as well as sending them back and being displayed in the console.

I want to do one more test tomorrow where I send values back and forth between two Propeller Boards to see how it handles that. Will follow up after that test.

**Comment by MatzElectronics** [comment]
Thanks!


*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by csavage-parallax** [comment]
Okay, I have completed testing sending and receiving with the XBee Blocks using text, byte and 32-bit values and they all seem to work perfectly. These weren't complex programs. Just send the value from one Activity Board WX to another and display it. However I did make subtle changes and start with various values and it all seems to function as expected.

**Comment by MatzElectronics** [comment]
Perfect, thanks!

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>
