### ISSUE TITLE
Update Windows Client installer links to indicate supported OS version

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#746]
Related to Issue #709 - The new installers are known to work on as low as Win 7; the 32-bit version (at least) does not work on Win XP or Win Vista, for example).  Since we stopped directly supporting XP or Vista in other software a while ago, we will treat this the same way.

Please update the __Windows 64-bit client installer__ link to say __Windows 7/8/8.1/10 (64-bit) client installer__, instead.

Please make the __Windows 32-bit client installer__ link say __Windows 7/8/8.1/10 (32-bit) client installer__.

Here's a sample of the current page (with all OS's showing).

![image](https://cloud.githubusercontent.com/assets/1266318/18963352/7f648ea0-8629-11e6-8e42-fd7536ed8066.png)

**Comment by PropGit** [comment]
Tested - noted problem.

This update (or something in #709) may have caused a problem.  The BlocklyPropClient dialog is now missing the links:
![image](https://cloud.githubusercontent.com/assets/1266318/18969875/e0d1e876-8643-11e6-9074-b4828799a25e.png)

But the BlocklyProp-client link (in the footer of the system pages, not editor) shows both links just fine:
![image](https://cloud.githubusercontent.com/assets/1266318/18969910/0490329a-8644-11e6-9597-7a4e84b62918.png)

**Comment by PropGit** [comment]
Education is seeing the same thing as noted above.  To test, I had them log into demo.blockly.parallax.com from _a Windows machine_, then go to any existing project, (make sure they do not have BlocklyPropClient running on their system), and then click the red "BlocklyPropClient not available" link...

**Comment by zfi** [comment]
It seems that the /public/clientdownload link is functioning correct and the /public/clientinstructions is failing to detect any clients. We are going to need some help deciphering how that works.

**Comment by PropGit** [comment]
@michel-cf - This is the item I alerted you to in email.  See previous post.

**Comment by zfi** [comment]
Updated the DIV tag construct and pushed to Demo.

**Comment by zfi** [comment]
Verified that the clients are listed correctly now. Closing the issue
