### ISSUE TITLE
Consider changing "BlocklyProp Client" name to "BlocklyProp Assistant" or "...Service"

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#75]
Can we (should we) change the name of _BlocklyProp Client_ to _BlocklyProp Assistant_ or _BlocklyProp Service_?

_Client_ implies something that the end-user interacts with directly, but the Client in our case is really a download driver (or assistant), right?

**Comment by michel-cf** [comment]
Service for me implies that there is no gui.

What about BlocklyProp Loader? Although that also is not applicable once we use it for an offline version. But I'm not sure if that is still the plan with the plans for the Chrome version

**Comment by kgracey** [comment]
The name BlocklyProp Client is now used in our documentation, so it's started to "stick". I'll close this issue.
