### ISSUE TITLE
S3 Block Request - Next Round

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#751]
@kgracey and @dcarrier-parallax 

I am working on a list of block requests for the next round of adds - based on the Scribbler Object Methods (especially for draw functions).

But - we need these two (if possible) in our math blocks...(the square block might not need all the choices on the drop-down menu - but square root, absolute, and e^ - would be the minimum)

![math square](https://cloud.githubusercontent.com/assets/8891440/18977530/b7ad4714-8680-11e6-9a5f-4771f42e1023.JPG)

![math trig](https://cloud.githubusercontent.com/assets/8891440/18977531/b99a86cc-8680-11e6-8501-93f5cea5c108.JPG)

I think this would let us do some great things with math that some of our educators are requesting.

**Comment by MatzElectronics** [comment]
I'm up for it!  Would like to see this for the PropC stuff too...
That being said - is this the best way to handle them when the system is forcing integer only math? Especially for the trig functions.  

With the trig functions - are they almost always multiplied by something?  If so, could that be made a part of the block somehow (because otherwise they will almost always truncate to zero.

**Comment by wstodghill** [comment]
I've just converted the decimal - for example for a 45-degree right triangle "a" (x) and "b" (y) are "c" (hypotenuse) divided by 1.41 approx. or a or b = (c x 100)/ (1.41x100).

**Comment by MatzElectronics** [comment]
Okay - do you have to multiplying it up to get it to work?  I think that kind of thing is what the blocks will need to do.

**Comment by wstodghill** [comment]
@MatzElectronics - I believe so... I think that fractions are rounded to whole numbers (but not positive).

**Comment by dcarrier-parallax** [comment]
We do not plan on adding floating-point support in the near future.  We may look into fractional units for some functions.

This does leave the integer-only negate, absolute value, and raise to a power operators as possible.  The latter could be added to the binary operator block, and the first two would need a new unary operator block.  These functions are not too difficult to implement with pre-existing blocks.

Does anyone feel it is worth implementing the integer-only operators?

**Comment by wstodghill** [comment]
The main thing I wanted was square root. The trig function would be nice too.

**Comment by MatzElectronics** [comment]
These are now available in demo and appear to be functional.
