### ISSUE TITLE
String Blocks

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#752]
Any serious objects to doing this? (I have it all ready to go...)
![image](https://cloud.githubusercontent.com/assets/19737272/19034211/2c1d83c8-8917-11e6-9e77-1eda12946b86.png)

**Comment by kgracey** [comment]
I think it's a fantastic proposal and would like to see it implemented. Be aware we introduce some possibilities of mixing these up with decimal numbers. After this, I think we must curb the feature addition and finish our documentation and BPSK using the Strings commands.

**Comment by pjewald** [comment]
Is there a string type defined internally for these blocks? 

Are the other blocks in the system prepared to accept / reject block connections that do not make sense, such as a string variable used in a comparison with an integer representation of the string ( "1" == 1)?

Perhaps you can issue a PR so we can see the code.

**Comment by MatzElectronics** [comment]
Yes, the blocks are set only to take strings where it expects strings and
numbers where it expects numbers, so I don't think it will let you try
something like "1" == 1.
I'm finishing up testing to make sure the generated code is sound, and I'll
submit a PR.
Would it be possible to pull the current PR I have soon?  That would save
me from having to create another branch in my local repo.

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by zfi** [comment]
The PR was approved. Let's see what this thing can do.

**Comment by MatzElectronics** [comment]
Appears to be working so far!  Will try to close this one out soon.

**Comment by MatzElectronics** [comment]
Tested, failed.  All but the "get substring" block worked.  Will submit a fix.

**Comment by MatzElectronics** [comment]
Tested and verified!
