### ISSUE TITLE
selecting more than one block at a time.

### ISSUE THREAD

**Issue by mrodriguez-parallax** [parallaxinc/BlocklyProp#755]
From a user point of view it would be nice if Blockly let you select more than one block at a time instead having to reopen a tab each time to select a block. I know there are other more pressing matters but I wanted to put this in here so we miss it later.

![image](https://cloud.githubusercontent.com/assets/20686764/19120614/39d07fe4-8ad8-11e6-9f06-36082667c1cb.png)

**Comment by MatzElectronics** [comment]
This functionality is part of blockly, and not possible for us to tweak that I can tell.  Closing.
