### ISSUE TITLE
Main page contains Multiple <html> tags

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp#759]
There are additional <html> and <head> tags on the home page where the index.textile content is injected. The extraneous <html>, <head> and <body> tags need to be removed.

```
            <html>
 <head></head>
 <body>
  <div class="jumbotron">
   <div class="logo">
    <h1 id="BlocklyProp">BlocklyProp</h1>
   </div>
   <p><strong>Blockly for Propeller Multicore:</strong> Making amazing projects and learning to code just became easier</p>
   <p><img class="cdn full-width" border="0" src="http://172.16.133.231:8080/blockly/cdn/images/home-banner.png"></p>
  </div>
 </body>
</html>


            <h2 class="pad-latest-projects">Latest projects</h2>
            <hr>
            <ul class="latest-projects"></ul>
        </div>

```

**Comment by zfi** [comment]
@michel-cf  There is a block of code in src/main/webapp/WEB-INF/servlet/index.jsp at lines 35-42 that appear to import the contents of the index.textile file. If I comment out these lines the extraneous HTML tags go away. But so does the text and the image provided by the index.textile file. Could you take a look to see what might be adding the extra tags?

**Comment by MatzElectronics** [comment]
This will be solved through file condensation.

**Comment by zfi** [comment]
Fixed. Closing.
