### ISSUE TITLE
Devise method to advertise and deliver platform-specific BlocklyProp Client

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#76]
Create way to deliver the platform-specific BlocklyProp Client to the user via a button click.  

Perhaps this can be exposed near the menu-bar message that indicates the BlocklyProp Client is not available?

Can we tell if the Client exists?  Or just that the client is not currently running (ie: it may not exist, or may exist but isn't running).

**Comment by michel-cf** [comment]
A download link should not be a problem, checking if it exists does.

The only way to know it is running is by frequently polling on the configured host and port.

**Comment by michel-cf** [comment]
Download page present
