### ISSUE TITLE
Add Favicon

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp#760]
Implement a favicon for the site. @MatzElectronics has provided all of the needed files.

[favicomatic.zip](https://github.com/parallaxinc/BlocklyProp/files/512591/favicomatic.zip)

**Comment by zfi** [comment]
@MatzElectronics I see a favicon on my safari browser on my iPhone and in the shortcut on the iPhone so it's working on at least two platforms.

**Comment by MatzElectronics** [comment]
Tested and verified!

**Comment by MatzElectronics** [comment]
@zfi - It is there for the main site, but as soon as you go into a project, it disappears.

**Comment by zfi** [comment]
This update has not been migrated to the beta site. You may be seeing is an artifact from browser caching. Open a private session or an incognito session to verify this.

**Comment by MatzElectronics** [comment]
Same with incognito window - favicon is present on the landing page, but
disappears when I'm in the blockly workspace.

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by paragitadmin** [comment]
Can you please try this test on another system, such as the dev VM. I have tried this on a number of mobile devices (iPhone, iPad, Android tablet) and on two more desktop systems and cannot reproduce the rouge favicon on the Demo site home page.

**Comment by zfi** [comment]
Can this issue be closed now?

**Comment by wstodghill** [comment]
@zfi - I get the favicon with the Demo Beta BlocklyProp (though when I go to project is disappears), but not get it at all with the Live Beta BlocklyProp (using Google Chrome). Went incognito too and no change... This is what I see...

![fav](https://cloud.githubusercontent.com/assets/8891440/19284501/c288b684-8fbb-11e6-9c45-0d7dd54596c6.JPG)

**Comment by zfi** [comment]
Good find on the favicon missing on the project page! It seems that there are multiple locations in code that are generating full pages without a global page template.

**Comment by wstodghill** [comment]
@zfi - thanks! Glad to be of help...

**Comment by zfi** [comment]
Favicon support files added to the header of remaining full pages. Result is available in Demo. 

Note: Including <Doctype HTML>  as the first line in some full pages breaks the CSS for that page. This was noted on pages that rely on the Google Blockly library. All pages seem to render correctly without the declaration.

Closing the issue.
