### ISSUE TITLE
Confusing or incorrect menus when creating new projects for the Scribbler robot

### ISSUE THREAD

**Issue by dcarrier-parallax** [parallaxinc/BlocklyProp#763]
The 'New project' menu lists 'S3 Robot' as an option, but BlocklyProp also supports S2 robots, so the option should change to the more generic 'Scribbler robot'.

The new project form at blockly/projectcreate.jsp, when lang = SPIN, gives many board type options, but it should only show the 'Scribbler Robot' option.  This will require JavaScript code that limits the menu when lang = SPIN.

**Comment by paragitadmin** [comment]
Moving second item to new issue.

**Comment by zfi** [comment]
Menu item updated. In Demo at 12:00 PM.

**Comment by MatzElectronics** [comment]
Verified.
