### ISSUE TITLE
Spin code doesn't compile if 'exit loop' block not inside a loop

### ISSUE THREAD

**Issue by dcarrier-parallax** [parallaxinc/BlocklyProp#764]
Blockly allows the 'exit loop' block to be placed anywhere, and doesn't seem to have the ability to require that it be inside a loop.  If it is not inside a loop, the compiler will fail with this message:

>This instruction is only allowed within a REPEAT block
>Line:
>  quit
>Offending Item: quit

Blockly cannot indicate which block causes the compile failure, and the message does not make it clear to the user.

The simplest solution may be, when generating code, to ensure that Blockly.Spin.scribbler_exit_loop is being called from Blockly.Spin.statementToCode, run a check to make sure the block is inside a loop, and generate a blank line if it is not.

**Comment by MatzElectronics** [comment]
Sounds good - can you implement that same effect on the PropC side, or show
me how?

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by dcarrier-parallax** [comment]
Worked around in pull request 775 by adding a comment to change the compiler fail message to this:

>This instruction is only allowed within a REPEAT block
>Line:
>quit '	The "exit loop" block must be placed inside a loop block!
>Offending Item: quit

**Comment by zfi** [comment]
I'm not sure this is working correctly. The blocks arranged like this:

![screen shot 2016-10-17 at 11 47 25](https://cloud.githubusercontent.com/assets/8442260/19450753/8531c070-945f-11e6-9806-598e6cf5a023.png)

generate this code:

CON
  _clkmode = xtal1 + pll16x
  _xinfreq = 5_000_000

VAR
  {{$var_type_item}} item

PUB Setup
  Start


PUB Start

  repeat
    waitcnt(clkfreq / 10 * 5 + 1000 + cnt)
    if item
      quit '	The "exit loop" block must be placed inside a loop block!


And the PropellerIDE returns this message:

An open-source compiler for Propeller Spin
Copyright © 2012-2015 Parallax, Inc.
Compiling /Users/jewald/Downloads/Blockly/Untitled.spin
/Users/jewald/Downloads/Blockly/Untitled.spin(6:22) : error : Expected BYTE, WORD, or LONG
Line:
  {{$var_type_item}} item
Offending Item: item

**Comment by zfi** [comment]
Further investigation reveals the the issue with the above example is in the undeclared variable.  The corrected block arrangement is operating as designed. 

![screen shot 2016-10-17 at 11 52 48](https://cloud.githubusercontent.com/assets/8442260/19450945/44656f28-9460-11e6-9fb3-d67c3e8e19cc.png)

```
CON
  _clkmode = xtal1 + pll16x
  _xinfreq = 5_000_000

VAR
  long item

PUB Setup
  Start


PUB Start

  item := 10
  repeat
    waitcnt(clkfreq / 10 * 5 + 1000 + cnt)
    if item
  quit '	The "exit loop" block must be placed inside a loop block!
```


An open-source compiler for Propeller Spin
Copyright © 2012-2015 Parallax, Inc.
Compiling /Users/jewald/Downloads/Blockly/Untitled.spin
/Users/jewald/Downloads/Blockly/Untitled.spin(18:3) : error : This instruction is only allowed within a REPEAT block
Line:
  quit '	The "exit loop" block must be placed inside a loop block!
Offending Item: quit

**Comment by zfi** [comment]
Closing issue.
