### ISSUE TITLE
Constrain board types based on language selected 

### ISSUE THREAD

**Issue by paragitadmin** [parallaxinc/BlocklyProp#765]
The new project form at blockly/projectcreate.jsp, when lang = SPIN, gives many board type options, but it should only show the 'Scribbler Robot' option. This will require JavaScript code that limits the menu when lang = SPIN.

**Comment by dcarrier-parallax** [comment]
To flesh this out, the inverse should be true.  The 'Scribbler Robot' option should not show up when lang=PROPC.

**Comment by zfi** [comment]
There are two ProjectTypes defined in projectcreation.js. The <select> tag at line 65 of projectcrreate.jsp might be modified such that the following options are set based upon the selected ProjectType.

**Comment by MatzElectronics** [comment]
Please hold on this issue - taking advantage of this bug to work through #824
