### ISSUE TITLE
Dynamic includes based on block/hardware context

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/BlocklyProp#77]
In C, all programs require specific libraries. For example, every C program requires simpletools.h to be included. If, however, every single block for a specific hardware platform or sensor "grouping" need a specific library to be included, that must be hardcoded into every block created in relation to said platform or sensor grouping. If there were multiple such includes, the code that every new block would require could get very long. Solve this, there needs to be a way to declare specific includes for different groups of blocks. This could be based on category, hardware, or other. The process/plan to creating something like this would be:

- [ ] Get hardware support first. The Parallax badge will require an additional library other than simpletools, so it makes sense that hardware be a way for grouping blocks created.
- [ ] Get category support. This is more complicated, and I really haven't thought this through very much yet but it would be very nice to have this ability.

**Comment by michel-cf** [comment]
I don't see the problem here. Any single block usually only takes 1 include, and you can hardcode the simpletools.h in the blockly/generators/propc.js

As the Parallax badge uses the Badgetools.h. It would be possible to add that one by default when selecting the badge as board type.

**Comment by DarkmatterVale** [comment]
I agree at the moment there is no need for this addition.
