### ISSUE TITLE
Private or shared (remove "default")

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#771]
Based on student feedback this morning we should remove the "default" button option from this menu. At present it is not clear what it does and it doesn't auto-select private or shared. It was a point of confusion for the students. 

![screen shot 2016-10-11 at 1 07 57 pm](https://cloud.githubusercontent.com/assets/9534148/19286686/702374ea-8fb3-11e6-8d53-47be83d25edf.png)

**Comment by wstodghill** [comment]
@kgracey - Good call! I did not know either. We need to remove the reference to this in our learn material. I'll send an email...

**Comment by michel-cf** [comment]
Once this becomes "Friends" this will probably become clear. Sadly, I haven't got the time to complete this because of other projects.

**Comment by kgracey** [comment]
It would be best to have Blockly be sensible and self-explanatory, and modify any Learn material as needed. It's a living, breathing system without printed paper. 

There's nothing quite like being in a class with teachers and students to see how the software should be changed. There's no arguing with 20 students that look at something and say "huh, what's that for?" while unexplained features start to dominate the learning process. I don't have any kids or interest in this class per se - I volunteer and test our products there to speed the improvement process. Here's a look at this morning. 
![img_9382](https://cloud.githubusercontent.com/assets/9534148/19289174/5fee8884-8fbe-11e6-8b0d-0359b7c23d91.JPG)

I certainly understand the desire to expand features, but if they're not there we need to cut them out and make what we have sensible.

**Comment by zfi** [comment]
Verified that the options have been updated. Closing the issue.
