### ISSUE TITLE
Mac downloading trouble - what causes this?

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#773]
Today I received an e-mail from an educator with a Mac. She's having trouble similar to other Macs I've encountered at our Educator's Courses. This is her message:
# 

Ken had asked me to run the S3 on my Mac and share any problems I have.
I have been using the S3 on a MacBook Air, version 10.10.5, and have been experiencing a fair amount of difficulty. I thought perhaps it was just me, so I loaded the software to my old HP, running Vista, and have not had any trouble. The problems I encounter with the Mac are:
I have to unplug the S3 from the Mac for it to run properly, otherwise the program sometimes doesn't run all the way through.

The programs that should write messages some times produce the correct response but typically don't display anything on the serial terminal.
In order to 'Load EEPROM' or 'Load RAM' I have to hit the blue reset button at just the right moment otherwise I get an error. Typically the error is 'resource is busy'. I have attached a screen shot of the various error codes that show up. 

I feel like it has taken me a while to get off the ground, but I've been going round and round with my Mac. As I said, it works fine with the Vista I have here, so I am still able to check the programs. If you think there is something I have done incorrectly in loading the software or if there is something else you think I may be doing wrong, please let me know. 

![no file](https://cloud.githubusercontent.com/assets/9534148/19291601/065c906a-8fcb-11e6-8272-997db043caca.png)
![no propeller chip](https://cloud.githubusercontent.com/assets/9534148/19291605/0a8269da-8fcb-11e6-8406-eb9df00a6c24.png)
![resource busy](https://cloud.githubusercontent.com/assets/9534148/19291608/0d72741e-8fcb-11e6-994d-741cbf36c70f.png)
# 

I don't know the cause of the problem, where to look to solve it, and why the Macs are so challenging. I'm hoping that one of you with familiarity with the GCC message log might know more about what causes this unreliable behavior.

**Comment by zfi** [comment]
The first screenshot looks like the wrong USB serial port was selected. The second and third screenshots indicate communication issues with the hardware. This could be timing or perhaps an undetected handshake failure. @PropGit might have some insight into what is happening here if he has a moment to opine.

**Comment by DarkmatterVale** [comment]
Hmmm the third one I get a lot on my mac as well. Perhaps there is something else going on here?

**Comment by DarkmatterVale** [comment]
To clarify I get this a lot using SimpleIDE communicating with any connected Parallax gear (most commonly I'm using the ActivityBoards so I have the most data points using that)

**Comment by michel-cf** [comment]
BlocklyProp (BlocklyPropClient in fact) uses PropellerLoad to send the binary over the serial port to the Propeller.
So, this has nothing to do with the compiler or BlocklyProp and as @DarkmatterVale suggests; this is something that also occurs with other systems. I don't know if SimpleIDE also uses PropellerLoad.

Maybe this is a bug we need to report to the developers of PropellerLoad. If they are aware of this problem, or there is already a newer version, we can build new versions of BlocklyPropClient that includes the new binaries.

**Comment by PropGit** [comment]
This may be due to not restarting the Mac after installing the FTDI drivers, though usually it doesn't work at all if a restart is required.  I know this only from first-hand experience at an educator event.

SimpleIDE does indeed use PropellerLoad, but the next version will use PropLoader instead.  We'll integrate that into BlocklyProp after the next enhancements we are making to PropLoader are done.

@DarkmatterVale (and all) - the third error may be due to the PropellerLoad leaving the port open after the second error occurred.  I've seen a similar thing with Propeller Tool and BASIC Stamp Editor in Windows and had to redesign portions to handle errors in a more robust way.  I'll look into that issue in PropLoader too.

**Comment by DarkmatterVale** [comment]
It might be an issue with not restarting after installing the FTDI drivers but from my experience it is a general problem that is not only caused by FTDI driver installation.

Is there any information I can provide @PropGit to help you figure out what is going on?

**Comment by MatzElectronics** [comment]
This is still an issue, but I think it's outside of the scope of the browser - this is something that we may have some luck addressing in the PropLoader, BPC, and/or BPL.
