### ISSUE TITLE
CR Servo block on Demo won't compile - gives null for speed parameter

### ISSUE THREAD

**Issue by Steph-Parallax** [parallaxinc/BlocklyProp#778]
It appears CR servo was updated to use a number block instead of a dropdown.  It won't compile. The C code is shown below; scroll down for the error message.   The generated C code is shown below. I get "null" regardless of the speed entered; I tried several values in the -100 to 100 range.

#include "simpletools.h"
#include "servo.h"

```
int main()
{

    servo_speed(17, null);

}

```
**Compiler error window message:** 

Required libraries: simpletools, servo
Library compile order: None needed
single.c: In function 'main':
single.c:9:21: error: 'null' undeclared (first use in this function)
single.c:9:21: note: each undeclared identifier is reported only once for each function it appears in

**Comment by MatzElectronics** [comment]
Tested and verified
