### ISSUE TITLE
Miscellaneous block issues

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/BlocklyProp#78]
Dr. Brady reported these bugs (I double-checked to make sure they existed on my machine as well).

1) Forever loop doesn't work. It only loops 10 times. We should use a while loop and not a for loop
2) The while loop doesn't accept the proper arguments
3) The if block doesn't accept a straight boolean value

**Comment by DarkmatterVale** [comment]
The forever loop should work fine now.

**Comment by DarkmatterVale** [comment]
@michel-cf Is it possible to use multiple ```.setCheck()``` statements? For example, can I do

```
for (var x = 1; x <= this.elseifCount_; x++) {
            this.appendValueInput('IF' + x)
                    .setCheck(Boolean)
                    .setCheck(Number)
                    .appendField(Blockly.LANG_CONTROLS_IF_MSG_ELSEIF);
```

where I added the

```
                    .setCheck(Number)
```

Does that work? If not, is there another way to set checks for multiple different kinds of values?

**Comment by DarkmatterVale** [comment]
bump

**Comment by michel-cf** [comment]
Until I'm home, I won't be able to test this, but I think an if statement should only accept a boolean. Never a number. Although the generated code might work, I think it's better to have to define explicitly that you want to check if a number is higher then 0 or something like that.

**Comment by PropGit** [comment]
I agree for a system meant for young and budding programmer; if should require clear indication of what is being checked for true/false.

**Comment by DarkmatterVale** [comment]
Ok.

We should clearly specify this limitation in the documentation then for blocks that apply to this.

**Comment by DarkmatterVale** [comment]
Since we are going to not use multiple different input values, I have verified that the issues are not relevant anymore.
