### ISSUE TITLE
Add "clear workspace" button or menu option

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#793]
Request to add a button or option in a dropdown menu that clears all blocks from the workspace (a "delete everything" option.

**Comment by MatzElectronics** [comment]
In MatzElectronics-upDownLoad branch

**Comment by paragitadmin** [comment]
The functionality is verified. Let's capitalize the 'confirm' button label and close this out.

![screen shot 2017-01-09 at 14 50 13](https://cloud.githubusercontent.com/assets/1985746/21786858/fe3cd5ec-d67a-11e6-925b-46b71c416b81.png)
