### ISSUE TITLE
log4j warning during app startup

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp#796]
The following warning is logged during the BlocklyProp app startup.  Which file is getting parsed when these warning are encountered?

```
INFO: Deploying web application archive /var/lib/tomcat7/webapps/blockly.war
log4j:WARN Continuable parsing error 13 and column 70
log4j:WARN Element type "Logger" must be declared.
log4j:WARN Continuable parsing error 14 and column 23
log4j:WARN The content of element type "log4j:configuration" must match "(renderer*,throwableRenderer?,appender*,plugin*,(category|logger)*,root?,(categoryFactory|loggerFactory)?)".
log4j:WARN Unrecognized element Logger
```

**Comment by PropGit** [comment]
"Logger" appears in 7 JavaScript files.  This, from my old, unupdated BlocklyProp Repo; the latest may be different.

![image](https://cloud.githubusercontent.com/assets/1266318/19739768/21d82654-9b71-11e6-91e9-504291bb9609.png)

**Comment by michel-cf** [comment]
The problem is probably in https://github.com/parallaxinc/BlocklyProp/blob/master/src/main/config/default/log4j.xml

Actually, if it's on the production server. The actual used file is not in the BlocklyProp repository as it includes the production Sentry DSN.

**Comment by zfi** [comment]
It appears that the only log4j.xml is the default file, located in ./WEB-INF/classes/log4j.xml on the production server. Taking this offline while we work out the details. Will report back when we have a generic XML file that we can include in the repo.

**Comment by zfi** [comment]
Updated the dependencies to use newer version of log4j. Updated the default log4j configuration file to comply with new DTD.

**Comment by zfi** [comment]
Resolved with replacement logging package.
