### ISSUE TITLE
Missing tool tips

### ISSUE THREAD

**Issue by Steph-Parallax** [parallaxinc/BlocklyProp#797]
**Missing tool tips in these C blocks:** 
in/decrement
system counter
check PIN (programmable)
check PIN (dropdown)

**Comment by zfi** [comment]
I can drop the text into the messages file for the omissions  if someone will provide it.

**Comment by Steph-Parallax** [comment]
I'm not sure if the problem is missing text, or a missing/incorrect call
from the block to the file, or both?

Stephanie Lindsay
Product & Docs Manager
Parallax Inc.

916-625-3077
www.parallax.com
learn.parallax.com

**Comment by Steph-Parallax** [comment]
I verified this has been corrected.
