### ISSUE TITLE
Add new links to Learn web site to help page

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp#800]
Reference the URL http://demo.blockly.parallax.com/blockly/public/help, add a link under the current picture and link for each platform to point to a body of reference material on the Learn web site.

Under the S3 photo, add a second link
Link text: Scribbler 3 Block Reference
URL: learn.parallax.com/s3-blocks

Under the Activity Board Photo, add a second link
Link text: Activity Board WX Block Reference
URL: learn.parallax.com/ab-blocks

**Comment by Steph-Parallax** [comment]
Verified in Demo, thank you!

**Comment by wstodghill** [comment]
@zfi - this is everything I would have hoped for and envisioned. FANTASTIC work all! When will this (and the other block mods) go live?

**Comment by zfi** [comment]
Added two anchor tags to the index.textile page.

**Comment by wstodghill** [comment]
@zfi - might we add a similar sort of help (third link) for BlocklyProp features? Example - items in the right-click options with explanations of what each does? Should this be a new issue? I would be happy to get the text underway...

**Comment by zfi** [comment]
The pop-up menu that appears when right-clicking on a block contains a 'Help' option. This menu option opens a new browser tab and pulls details on the block from the Learn site. If you have something else in mind, then yes, please open a new issue for that.
