### ISSUE TITLE
Help/Help on Right Click to include help on the Right-Click Options Themselves - Discussion

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#802]
Currently right-click in BlocklyProp (live and Demo) opens a window of options - help brings up block description help files or learn info.

Could help also describe the function of the right-click options (like Disable Block)? Or should we include updated info on the learn site for these functions?

Anyone have opinions about  this. I have learned what they do by trial and error and playing with them, but it seems like some info could be useful.

Thanks...

**Comment by zfi** [comment]
I looked up the 'External Input' menu item and this is the detail that the Blockly Project provides:

Inline vs. External

Block inputs can render as either external or internal.

![set-inputs-inline](https://cloud.githubusercontent.com/assets/8442260/19880826/cee1ab22-9fbd-11e6-98b9-5603eddc4286.png)

The block definition can specify an optional Boolean controlling whether inputs are inline or not. If false then any value inputs will be external (such as the left block). If true then any value inputs will be inline (such as the right block above).

The explanation is targeted to developers and is not overly useful for the target audience. The 'External Input' is really just a toggle that changes the behavior of the block as it related to connecting inputs (external) or the inputs are supplied (internal or inline). Even that is an over simplification of what is happening but it's close enough.

Trying to explain just this one item within the context of a pop-up menu is going to be messy. My sense is that we should provide information on the menu items within the general help system.

**Comment by wstodghill** [comment]
@zfi - I think that is fine too! I just want that help available somewhere. General Help for individual blocks and Help for "system" tools could be there too. It could be in a category that makes it easy to find. 

I think there are features that could be documented about how BlocklyProp system tools work that could be really helpful to folks and that would be more accessible if we could document them - I just noticed that "undo," "redo" had been added! Explaining "Clean up Blocks" - great feature - with an explanation in help somewhere makes it more usable.

**Comment by Steph-Parallax** [comment]
From a block, the right-click Help needs to go to the individual block listing; it is in the Learn Reference section now, divided into different sections by board type.

This information could go in the Getting Started tutorials, but those are separate tutorials, aimed at supporting specific boards.  I would be duplicating the information, but that is not difficult to do.

As an alternative, we could make a generic Using BlocklyProp section in Reference, that would not be board specific, to include this information. We could refer to it from each Getting Started tutorial.

Or, we could possibly work on getting this into the Blockly system's Textile files, though I want to minimize developer-level work.

**Comment by zfi** [comment]
We can use HTML bookmarks to navigate to a specific topic on a page in the Learn site if that site can use the 'name' attribute in the anchor tags. There might be an issue with how the pages on the Learn site are constructed that prevents this or just makes it extraordinarily difficult.

**Comment by MatzElectronics** [comment]
Anchor tags should be easy - but I'd rather not implement them - that would require a unique HelpUrl for each block - making the messages.js larger yet.  I don't think it's unreasonable for a user to just scroll down a bit - we don't have too many blocks on each page :)

**Comment by Steph-Parallax** [comment]
I'm for higher-priority work at the moment.

Stephanie Lindsay
Product & Docs Manager
Parallax Inc.

916-625-3077
www.parallax.com
learn.parallax.com

**Comment by wstodghill** [comment]
Agreed!

**Comment by zfi** [comment]
@MatzElectronics We could avoid placing all of those messages in a .js file if we implemented a round-trip to the server for that message with Ajax or similar technology. That would be my preference if or when the time comes.

**Comment by wstodghill** [comment]
We could probably close this - any objections?

**Comment by MatzElectronics** [comment]
Let me sure we have what we need in the help system.  not sure we actually
do yet...

On Dec 29, 2016 12:08 PM, "Whit" <notifications@github.com> wrote:

We could probably close this - any objections?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/parallaxinc/BlocklyProp/issues/802#issuecomment-269686041>,
or mute the thread

**Comment by Steph-Parallax** [comment]
I'm working on documenting those features in the Learn site Help.   But
since there is nothing to be done in Blockly iteself, let's close this
issue here; I'll track it internal with other Parallax documentation.

Stephanie Lindsay
Product & Docs Manager
Parallax Inc.

916-625-3077
www.parallax.com
learn.parallax.com

**Comment by MatzElectronics** [comment]
These are now documented on learn.
