### ISSUE TITLE
Rename C Return block; move blocks to new category

### ISSUE THREAD

**Issue by Steph-Parallax** [parallaxinc/BlocklyProp#804]
I propose renaming the "return" block, since functions return to the main program flow automatically.  If this block is to be used to exit a function early, I'd suggest naming it "exit function" or just "exit" instead.

I also propose moving this return/exit block, and the "new processor" block, to the Functions menu. Since this menu gets auto-populated with user-created function names, I'm not sure that's possible - it may take @DarkmatterVale to look into this.

**Comment by zfi** [comment]
My opinion is that the use of 'return' is a legitimate construct to leave a function. An 'exit' verb is more applicable to that circumstance where the code need to leave a looping construct.

Moving the 'new processor' block to the Function menu is understandable since it is not a control structure. The 'how' to move it there can be determined if we decide to go there.

**Comment by Steph-Parallax** [comment]
The issue with Return is that it is not needed in order to return from a
function at the end of its process (as was originally assumed.) It would
only be used in order to escape the function early, without processing all
of the code in that block. The other issue with Return is the impression
that we can build a return value into a custom function, which we cannot do.

Other solutions?

Stephanie Lindsay
Product & Docs Manager
Parallax Inc.

916-625-3077
www.parallax.com
learn.parallax.com

**Comment by PropGit** [comment]
I see your point.  I just wanted to say that return has been an optional end-of-function command in the written language too; it's implied by the end of the function definition itself so it's often not used except in the optional places where an early return is needed (as mentioned) or to return a specific value (which we removed as a feature back in August I think).

Maybe a different term other than __return__ or __exit__ can be found?

**Comment by Steph-Parallax** [comment]
We considered escape (prounounced "ess-caw-peh" by trigger fish...)

Stephanie Lindsay
Product & Docs Manager
Parallax Inc.

916-625-3077
www.parallax.com
learn.parallax.com

**Comment by Steph-Parallax** [comment]
**OK, to conclude, let's do this now:**
Don't try moving this block nor New Function block, as it makes Blockly fundamentally unhappy.
Rename "Return" to Escape"
Update tooltip to read: "Escape: quit executing the function early and return to the main program."  

**Questions for the near future:** 
How does a core shut down and become available to use if called with New Processor Function? Return is not required to return program execution from a function to the main program. Does Return help release the core? What happens when Return is used conditionally in the middle of a function, from the main program or from a New Processor call?

**Comment by Steph-Parallax** [comment]
Andy: Currently, once a cog is launched in Blockly with New Processor block, it cannot be shut down because it does not store the process identifier pointer variable (int* my lcdcog = cogrun blah blah).

When a sensor or accessory uses an additional core, it has an built-in stop to release its resource. For example, PWM, RFID, Sound Impact Sensor. Question: Any that don't? Yes, Servo, uses 1 core for up to 14 servos.  

Will doc this in Reference and in tutorials. - Steph
