### ISSUE TITLE
Block menu: alphabetize subcategories

### ISSUE THREAD

**Issue by Steph-Parallax** [parallaxinc/BlocklyProp#812]
The list of block categories in the sub-menus for sensors and communication is going to keep growing as we add supported devices.  Could we keep those lists alphabetized, so it is easier to find items? I can likewise re-order the Help TOC.

**Comment by wstodghill** [comment]
Great idea Stephanie!

**Comment by zfi** [comment]
Updated sort order for the Communicate and Sensor menus. Do any other menus need this sorting treatment?

**Comment by MatzElectronics** [comment]
I'd also update the Communicate one - those are the only two with longer
subcategories

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by zfi** [comment]
The Communicate menu was one of the two menus I updated in the PR. Is there another Communicate menu that I missed?

**Comment by Steph-Parallax** [comment]
Nope, there are not two Communications menus.

I think it would be best practices for all subcategories really, though
only Sensor and Communicate are likely to see repeated growth.

For consistency, the other ones to update would be Analog/Pulses and
Audio.  They will pretty much stay done after that.  Memory is likely to
grow in time, so we can just be conscious of alphabetizing there when we
make additions.

Stephanie Lindsay
Product & Docs Manager
Parallax Inc.

916-625-3077
www.parallax.com
learn.parallax.com

**Comment by MatzElectronics** [comment]
Still open because the next PR alphabetizes the Analog/Pulses menu, and once that is verified, we can close this.

**Comment by zfi** [comment]
All PRs have been processed. Please verify the patch and close the issue.

**Comment by MatzElectronics** [comment]
Verified

**Comment by MatzElectronics** [comment]
Does Jenkins go to bed?  I'm not seeing the last round in Demo...

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by pjewald** [comment]
It runs every 15 minutes 24x7. I'll take a look.

Jim Ewald
IT Manager
Parallax Inc.
916.624.8333 ext 3065

**Comment by pjewald** [comment]
It ran 28 minutes ago with these changes from the repo:


   1. Fixed erronious call to s3 c library (commit: abb72ab
   <https://github.com/parallaxinc/BlocklyProp.git/commit/abb72abf4c367eceab8b7a21fd2ba88892a3b1f6>)
   (details
   <http://jenkins.parallax.com:8080/job/BlocklyProp-Demo/271/changes#abb72abf4c367eceab8b7a21fd2ba88892a3b1f6>
   )
   2. Turn on leds during Activitybot-calibrate (commit: 75f28fd
   <https://github.com/parallaxinc/BlocklyProp.git/commit/75f28fdec275f57d997a48491d1b7627beff47ee>)
   (details
   <http://jenkins.parallax.com:8080/job/BlocklyProp-Demo/271/changes#75f28fdec275f57d997a48491d1b7627beff47ee>
   )
   3. Fix misspelled word (commit: 5ca4a37
   <https://github.com/parallaxinc/BlocklyProp.git/commit/5ca4a37042475f4a8322e16a2eb2ad0b96811fec>)
   (details
   <http://jenkins.parallax.com:8080/job/BlocklyProp-Demo/271/changes#5ca4a37042475f4a8322e16a2eb2ad0b96811fec>
   )


Jim Ewald
IT Manager
Parallax Inc.
916.624.8333 ext 3065
