### ISSUE TITLE
Add LSM9DS1 IMU blocks

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#817]
Add blocks to support the upcoming LSM9DS1 IMU module

**Comment by MatzElectronics** [comment]
This will require a library addition in SimpleLibraries.  Library drafted and currently in testing

**Comment by zfi** [comment]
The library updates are automatically pushed to the Demo server now. Let's make sure that the library is updated before you issue a PR for the blocks. That will ensure that the library is updated before the new blocks arrive.

**Comment by MatzElectronics** [comment]
sounds good.  I'm testing the library as we speak.  I'll send you a zip of
it (I can't put it in simple-libraries) when I finish if that's okay.  I
hope to get there tonight, but if I don't it might be early next week.

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by MatzElectronics** [comment]
@mrodriguez-parallax I'm getting these all to work - I'm going to close the issue.

**Comment by MatzElectronics** [comment]
I'm reopening this one - the blocks were changed slightly, and need to be retested.  I want to verify that they hold their configuration after being saved, closed, and reopened.

**Comment by mrodriguez-parallax** [comment]
Blocks hole their configuration after being saved closed and reopened. Also tested blocks all blocks in the IMU section and each worked as expected including magnetometer calibration.
