### ISSUE TITLE
Add blocks for WS2812B RGB LEDs

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#821]

**Comment by csavage-parallax** [comment]
First test with the follow program:

![blockly_ws2812_test1a](https://cloud.githubusercontent.com/assets/20691193/20727949/50a07ba6-b630-11e6-8775-728956980056.jpg)

Result was:

![blockly_ws2812_test1b](https://cloud.githubusercontent.com/assets/20691193/20727958/5d3384e4-b630-11e6-8fe5-ae04f58aaf3d.jpg)

**Comment by MatzElectronics** [comment]
Thanks, I'll get it fixed and let you know!

**Comment by MatzElectronics** [comment]
Thank you, I found the error and will submit with my next PR.  I'll let you
know when it's available to be retested.

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by csavage-parallax** [comment]
Awesome. Board's still set up. When it's ready let me know.

**Comment by MatzElectronics** [comment]
Should be ready to try again now. Thanks!

**Comment by csavage-parallax** [comment]
When I run a program that just sets 4 LEDs and loops forever, it seems to work. However when I added a delay and tried to change the LEDs using the following program I got the error shown below that.

![blockly_ws2812_test2a](https://cloud.githubusercontent.com/assets/20691193/20768505/291f7d3e-b6f3-11e6-9953-8b906f7ef3a6.jpg)

![blockly_ws2812_test2b](https://cloud.githubusercontent.com/assets/20691193/20768520/30706c92-b6f3-11e6-9a97-bf402c9d2c46.jpg)

Also, when I drag new blocks down the color of the pin parameter has changed. It is no longer cyan in color, but rather now it is purple. Any idea what causes that? See the following image:

![blockly_ws2812_test2c](https://cloud.githubusercontent.com/assets/20691193/20768577/4f3a15a6-b6f3-11e6-9a8b-70b7d2a64b35.jpg)

**Comment by csavage-parallax** [comment]
Using the proper pause block from the second control menu everthing now works.

![blockly_ws2812_test2e](https://cloud.githubusercontent.com/assets/20691193/20772257/a4fd8744-b701-11e6-82a2-d3496da754e3.jpg)


Okay, so we have success using 4 LEDs. If you'd like me to test with more just let me know.

That said, I do have one question and/or possible feature request. When setting the LEDs to the preset colors they were too bright to look at. The JW SPIN driver allows you to optionally set a brightness level for each LED. Should we consider adding this feature or are we going for absolute simplicity?

**Comment by MatzElectronics** [comment]
I'll close the issue for now, but let me ponder the idea of turning down the brightness - because yes, they are blinding!
