### ISSUE TITLE
PWM Block Issue?

### ISSUE THREAD

**Issue by csavage-parallax** [parallaxinc/BlocklyProp#826]
A customer reports that for the following Blocks:

![blocklyprop blocks](https://cloud.githubusercontent.com/assets/20691193/20678086/532026d8-b54a-11e6-9637-4a500bdfc757.PNG)

The compiled code reads as:

![compiled c code](https://cloud.githubusercontent.com/assets/20691193/20678237/cf686c28-b54a-11e6-89cf-25dbb480fd9c.PNG)

Shouldn't it read: pwm_set(0, 0, 50) ?

**Comment by MatzElectronics** [comment]
@csavage-parallax This should be ready to be tested as well.  Thanks!

**Comment by zfi** [comment]
I see that this issue has a 'fixed' label. Can we close this issue now?

**Comment by MatzElectronics** [comment]
Let's test it first - I'll wait with that label :)

**Comment by csavage-parallax** [comment]
This seems to compile properly now. Please let me know when it goes live and I will follow up with the customer.

**Comment by MatzElectronics** [comment]
Will do - I'm not sure when our next push from demo to production is, but
I'll keep you informed.
Thanks!
Matt

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>
