### ISSUE TITLE
Parallax to provide introduction block text

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#83]
Parallax needs to provide introduction block text to include on home page (.../Blockly/):
![image](https://cloud.githubusercontent.com/assets/1266318/12276996/e00e3144-b92d-11e5-857c-6f52c94a3e8a.png)

**Comment by michel-cf** [comment]
Reminder

**Comment by PropGit** [comment]
The following block of text is being proposed and reviewed by Parallax staff.  This, or a variation of it, will be noted as official as soon as we've approved it.

#### BlocklyProp
Visually program the Parallax Propeller microcontroller with BlocklyProp.  Based on Google's Blockly library, the BlocklyProp system of web-based visual programming is easy to learn and fun to use.  Create entire applications using movable "blocks" that naturally represent executable Propeller code - automatically translated behind-the-scenes to Propeller's Spin or C languages for downloading to the microcontroller.

Make sure to select the Login/Register link for an account to save and share your visual applications and install the BlocklyProp-client (link below) to enable downloading your code to the Propeller microcontroller.

**Comment by PropGit** [comment]
@michel-cf - Here's the official Introduction paragraph we want to start out with.  The **bold text** is not intended to be bold, but rather linked to the appropriate item.  If that can not be done, please keep it plain text and put ", linked below, " right after it.  The text that's already linked goes to the open source project; if it can't be linked in the intro, just leave that as plain text.

#### BlocklyProp
Visually program the Parallax Propeller microcontroller with BlocklyProp.  This web-based programming tool is easy to learn and fun to use.  Build entire applications using movable, configurable blocks.  Executable Propeller Spin or C language code is automatically generated behind the scenes.  

Click Login/Register to create an account. Then, you can save and share your BlocklyProp programs.  Install the **BlocklyProp Client** to download code to the Propeller microcontroller. 

[BlocklyProp is an open-source project](https://github.com/parallaxinc/BlocklyProp) based on Google's Blockly library.

**Comment by michel-cf** [comment]
introduction text moved to textile page. And text added
