### ISSUE TITLE
Add utility/values blocks

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#838]
Request to add the following blocks:
- binary value
- hex value
- string to int
- int to string
- constrain value

**Comment by MatzElectronics** [comment]
Possibly additional math functions (trig, abs, power, etc.)? See #751

**Comment by wstodghill** [comment]
Square root, please...

**Comment by MatzElectronics** [comment]
What about:
![image](https://cloud.githubusercontent.com/assets/19737272/20856888/fbf078c4-b8d0-11e6-96c7-f0b28c5f2b31.png)

It forces you to add a multiplier, but that allows them to be recast as floats so we don't loose as much when it's converted back to an int.

Abs and Negate can be an attachment (or added to the NOT block, and then the arccos/arcsin/arctan could be done like this:
![image](https://cloud.githubusercontent.com/assets/19737272/20856916/e4b5ae58-b8d1-11e6-91e9-d3ef056dd076.png)

Let me know if that won't work...

**Comment by MatzElectronics** [comment]
@wstodghill When this goes into Demo - would you be willing to test it and the s3 PropC system as a whole and let me know if anything needs to be fixed?  The advanced math blocks will not go into the s3 SPIN system (I don't know how to write proper SPIN code...)

**Comment by wstodghill** [comment]
@MatzElectronics - Of course! The multiplier is a great simple solution IMO. Simple way to handle this and we can explain why in "help" and our tutorials.

**Comment by MatzElectronics** [comment]
The multiplier effectively determines the accuracy, but it's a little more complex than that.  Once the user puts their numbers in, they get the full range, because everything is first cast as floats.  After the math is done, then the result is turned back into an int.  So yes, the user in a way does set their precision.

**Comment by MatzElectronics** [comment]
Trig functions failing in one block.  The radian to degree conversion is inverted.  Math is hard :)
Will submit a PR to fix soon.

All other blocks are testing okay so far.

**Comment by MatzElectronics** [comment]
Tested and verified
