### ISSUE TITLE
Serial LCD Cursor Positioning Request

### ISSUE THREAD

**Issue by csavage-parallax** [parallaxinc/BlocklyProp#844]
Currently this only supports hard-coding the row/column positions, however it is common in our demo code and in applications to need to be able to move the cursor programmatically. It would be nice if we could use variables for the row/column positions as well.

**Comment by MatzElectronics** [comment]
@csavage-parallax This one is updated now.  Give it a whirl and let me know how it works.  Thanks!

**Comment by csavage-parallax** [comment]
Testing complete! Feedback submitted! =)


*Chris Savage | *Engineering Tech | Main Office: (916) 624-8333 | Direct to
Tech Support: (888) 997-8267 | www.parallax.com |
