### ISSUE TITLE
Modified On date is not updated when project is saved

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#846]
After a bit of surfing, I discovered that the modified column is not getting updated when a user saved their project.  It is only updated when the project is created.  Not sure how to pin this one down, but it will need to be addressed ahead of #805.

**Comment by MatzElectronics** [comment]
Tested and verified.

**Comment by paragitadmin** [comment]
Project page prompts for the new fields are broken.
![screen shot 2016-12-14 at 11 53 17](https://cloud.githubusercontent.com/assets/1985746/21198899/0a0c2c54-c1f6-11e6-89ff-921ef212291d.png)

**Comment by paragitadmin** [comment]
Updated language file to include new field prompts.

**Comment by MatzElectronics** [comment]
All better now :)
