### ISSUE TITLE
Invalid ProjectType error when creating a new project

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp#852]
Reported issued with creating a new project. The interface reports an 'Invalid ProjectType' error and will not allow the user to create a new project. No other details available at this time.

**Comment by zfi** [comment]
The code that is attempting to create the project is getting a request from the client browser. The data passed in from the browser includes the project type. The code then compares that project type with the two it knows and fails. There are two identical error messages (not helping) to deal with this. So I am concluding that there is something going wrong - possibly a browser with old JavaScript code in the cache.

**Comment by PropGit** [comment]
I must not be trying the options that cause the error.  On the demo site, New Project > Scribbler Robot and New Project > Propeller C did not result in any errors.

**Comment by paragitadmin** [comment]
We are pushing out a change to the production site that will change the exact working of the error message previously reported. The new error message should tell us more about the nature of the error.

**Comment by MatzElectronics** [comment]
@zfi Status on this one?

**Comment by MatzElectronics** [comment]
This hasn't come up in some time, and with everything now being C, I think it's safe to close this.
