### ISSUE TITLE
Motor block outputs error.

### ISSUE THREAD

**Issue by mrodriguez-parallax** [parallaxinc/BlocklyProp#854]
Block Below found in Action-Motors outputs and error.

![image](https://cloud.githubusercontent.com/assets/20686764/21408193/7b994036-c788-11e6-897e-bd7f8f548b1e.png)

Below is the C code generated by the block shown above.
![image](https://cloud.githubusercontent.com/assets/20686764/21408238/c6759136-c788-11e6-974e-c5d6567091f6.png)

This is the error output.
![image](https://cloud.githubusercontent.com/assets/20686764/21408255/e6145914-c788-11e6-8388-6eb0a4805867.png)

**Comment by MatzElectronics** [comment]
@mrodriguez-parallax this one is ready for retesting as well.

**Comment by mrodriguez-parallax** [comment]
This one is not compiling either. 
![image](https://cloud.githubusercontent.com/assets/20686764/21458909/2dbeccba-c8ef-11e6-969d-7639cdfd9e51.png)


![image](https://cloud.githubusercontent.com/assets/20686764/21458922/44a0bba0-c8ef-11e6-8bd3-fe192f9ba143.png)


![image](https://cloud.githubusercontent.com/assets/20686764/21458945/6577744a-c8ef-11e6-9bf5-0a7a1951922d.png)

**Comment by mrodriguez-parallax** [comment]
Issue solved. Block/code compiles and works as expected.

**Comment by wstodghill** [comment]
Good work all - I know this is tough slogging!
