### ISSUE TITLE
Scribbler motor motion block outputs error.

### ISSUE THREAD

**Issue by mrodriguez-parallax** [parallaxinc/BlocklyProp#855]
Motor block below will not run. Outputs an error. 
![image](https://cloud.githubusercontent.com/assets/20686764/21410649/29433206-c797-11e6-86d9-458b446f44e3.png)

C code produced by block
![image](https://cloud.githubusercontent.com/assets/20686764/21410657/3aa93cf2-c797-11e6-947b-6350134654c1.png)

Output error.
![image](https://cloud.githubusercontent.com/assets/20686764/21410664/505d37ba-c797-11e6-87d7-6dffb6d49385.png)

**Comment by MatzElectronics** [comment]
@mrodriguez-parallax this is ready to be retested too!

**Comment by mrodriguez-parallax** [comment]
This block is not compiling after retest.
![image](https://cloud.githubusercontent.com/assets/20686764/21458742/ede8448c-c8ed-11e6-80be-e5585687b149.png)

C code generated
![image](https://cloud.githubusercontent.com/assets/20686764/21458757/026f0efe-c8ee-11e6-8e8c-83cae2025994.png)

Compiling error.
![image](https://cloud.githubusercontent.com/assets/20686764/21458778/2489c768-c8ee-11e6-911f-71c57061dfc0.png)

**Comment by mrodriguez-parallax** [comment]
Issue solved. Code block compiles and works as expected.
