### ISSUE TITLE
S3 motor motion block outputs an error.

### ISSUE THREAD

**Issue by mrodriguez-parallax** [parallaxinc/BlocklyProp#856]
Scribbler 3 motor motion block does not compile and outputs an error.
![image](https://cloud.githubusercontent.com/assets/20686764/21410732/dcea934e-c797-11e6-8bf4-242206cf8548.png)

C code generated by the block above.
![image](https://cloud.githubusercontent.com/assets/20686764/21410741/ec5c56c8-c797-11e6-860f-cd21deff049d.png)

Error output.
![image](https://cloud.githubusercontent.com/assets/20686764/21410751/fc7aae6a-c797-11e6-8b06-170c107d26d7.png)

**Comment by MatzElectronics** [comment]
@mrodriguez-parallax this is ready to be restested.

**Comment by mrodriguez-parallax** [comment]
This block is still giving an error. Does not compile
![image](https://cloud.githubusercontent.com/assets/20686764/21458666/496c31ac-c8ed-11e6-94f3-c3091a4cfbbf.png)

C code generated.
![image](https://cloud.githubusercontent.com/assets/20686764/21458671/5901cc1c-c8ed-11e6-9d0a-56cbcb3f7107.png)

Error output
![image](https://cloud.githubusercontent.com/assets/20686764/21458690/70175228-c8ed-11e6-8e0f-a4a3d49b7289.png)

**Comment by mrodriguez-parallax** [comment]
Issue solved block working as expected.
