### ISSUE TITLE
S3 LED block not turning off

### ISSUE THREAD

**Issue by mrodriguez-parallax** [parallaxinc/BlocklyProp#858]
I was able to turn each led on but could not get them to turn off  as shown below. The leds would turn off only if I downloaded a single led block that made the led turn off. my intention with this loop is to turn all 3 leds on, wait a second, then turn them all off at once. They came on but never turned off. 
![image](https://cloud.githubusercontent.com/assets/20686764/21441235/d51313e4-c84b-11e6-8e43-f62e4f88b13b.png)

Code generated in blockly. Notice that the block that turns the leds "off" doesn't not show up in the code. I can't see any comand that tells the S3 to turn off its lights
![image](https://cloud.githubusercontent.com/assets/20686764/21441248/ebda2568-c84b-11e6-993d-e2bc6bb0f9e2.png)

**Comment by MatzElectronics** [comment]
Try checking all 3 boxes and setting the colors to black to turn them off.

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by mrodriguez-parallax** [comment]
I tried that too.
![image](https://cloud.githubusercontent.com/assets/20686764/21441782/c1483e0e-c84e-11e6-8b77-357febd07371.png)

There's supposed to be a command between the two pause below. Those pauses are separated by the block command that turns the lights off but it's missing in the code.
![image](https://cloud.githubusercontent.com/assets/20686764/21441802/de4ed9f4-c84e-11e6-82cb-088b6ce62cb1.png)

**Comment by MatzElectronics** [comment]
Make sure all of the checks are checked above the black swatches

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by mrodriguez-parallax** [comment]
OK! that worked. Thanks non-problem solved!

**Comment by wstodghill** [comment]
@mrodriguez-parallax - Thanks for helping people like me feel better about ourselves! Good to know it happens to the best!
