### ISSUE TITLE
Changelog on homepage

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#863]
A request to just simply link it to the GitHub closed PR list...instead of trying to constantly update it...
@kgracey @DarkmatterVale @zfi thoughts?

**Comment by DarkmatterVale** [comment]
I agree that sounds like a better idea. It is a lot of work to constantly update the changelog...

**Comment by MatzElectronics** [comment]
If we go this route, we could use labels (and maybe create one) to clearly indicate at what points the public (production) system was updated.

**Comment by paragitadmin** [comment]
We use a tag to indicate when a production release occurs.

**Comment by MatzElectronics** [comment]
Setting the changelog to this link:
[https://github.com/parallaxinc/BlocklyProp/releases](https://github.com/parallaxinc/BlocklyProp/releases), opening in new/blank tab.
