### ISSUE TITLE
Utils.prompt modal does not display description text

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#871]

**Comment by MatzElectronics** [comment]
...and apparently it never will:
http://bootboxjs.com/documentation.html

So we either stop trying to pass a message or build out own modal...

**Comment by MatzElectronics** [comment]
utils.prompt is only called 3 times - modified titles will eliminate the need for additional dialog/messages.

**Comment by zfi** [comment]
@MatzElectronics Where is this called in the code and what is it supposed to do? I think we've already established that whatever that is is broken.

**Comment by MatzElectronics** [comment]
It's a function called by blocklyc.jsp, and it is just a wrapper for
bootbox.prompt, which is a bootstrap add-on.  bootbox.prompt doesn't
support the message parameter, so we are restricted to all instructional
text being in the title/header of the prompt it generates.  I reviewed what
calls it, and it so far is only used to enter a file name when the user
wants to download.

I think we can just re-tool what we say in the boxes and close this one out.
