### ISSUE TITLE
Scribbler speaker frequency & volume cap

### ISSUE THREAD

**Issue by Steph-Parallax** [parallaxinc/BlocklyProp#879]
Update C blocks that target the Scribbler to cap volume at 50% and frequency around 1000 Hz.  Changes to underlying resources for handling music generation planned.

(Currently Blockly setting can go to 10 kHz.  If keeping this desired for physics games, I suggest a separate C (not Scribbler-specific) block that also brings out the option for sine, square, and sawtooth waves in a drop-down.)

Need not immediate, perhaps Feb 17.

**Comment by MatzElectronics** [comment]
Can probably test this along with #914.  Ready for testing.

**Comment by MatzElectronics** [comment]
Merged issue with #914.  Closing.
