### ISSUE TITLE
Array blocks

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#883]
I think I just figured out how to do this...

**Comment by Steph-Parallax** [comment]
I'm testing the Array blocks in Demo.  
I intentionally tried using the Array fill block followed by a repeat loop to print the values, without using the Array initialize block first.  I got a compiler error as expected. I went back and added an Array initialize block to the code, but I still get a compiler error:

http://demo.blockly.parallax.com/blockly/editor/blocklyc.jsp?project=649#

**Comment by mrodriguez-parallax** [comment]
There's compiling error with array Blocks. see below.

![image](https://cloud.githubusercontent.com/assets/20686764/23670837/e2fa21e8-031d-11e7-8b65-6858817b28f7.png)



![image](https://cloud.githubusercontent.com/assets/20686764/23670866/00da0b2e-031e-11e7-8e28-480546cbe31e.png)

**Comment by MatzElectronics** [comment]
@mrodriguez-parallax This is ready to be tested again.  Your example program above may not work.  Try this:
![image](https://cloud.githubusercontent.com/assets/19737272/23695627/08d701d4-0395-11e7-83bd-9e2a6cbac8db.png)

**Comment by mrodriguez-parallax** [comment]
All 5 Array blocks pass testing and worked as expected. This was my test harness below. One block is missing here but was tested in Array blocks test number 2.


![image](https://cloud.githubusercontent.com/assets/20686764/23724816/063f7c9e-0403-11e7-97e9-9329c380a12c.png)
