### ISSUE TITLE
Offending item in S3 

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#885]
New error introduced the S3 code base - please fix immediately @dcarrier-parallax :

![2017-01-16_18-00-44](https://cloud.githubusercontent.com/assets/9534148/22005150/e753a4b4-dc15-11e6-9d8f-fe4477587b81.png)

```
Propeller Spin/PASM Compiler 'OpenSpin' (c)2012-2014 Parallax Inc. DBA Parallax Semiconductor.
Version 1.00.71 Compiled on Nov 15 2014 08:45:10
Compiling...
/tmp/tmpINXyFU/single.spin
|-Block_Wrapper.spin
  |-scribbler.spin
  |-FullDuplexSerial.spin
  |-Servo32v7.spin
    |-Servo32_Ramp_v2.spin
/tmp/tmpINXyFU/single.spin(17:13) : error : Expected a subroutine name
Line:
  Scribbler.MoveXY(24 * 10_000 / 491, 24 * 10_000 / 491, 60)
Offending Item: MoveXY
```

**Comment by zfi** [comment]
The missing function, MoveXY() is in the latest Scribbler-3 library. This is likely a deployment error on the production cloud compiler.

**Comment by MatzElectronics** [comment]
SPIN right?  I have the C version in S3-propC (untested, but it's not
throwing compiler errors...)

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by zfi** [comment]
Yes, this is an issue related to the SPIN library used in BlocklyProp.

**Comment by kgracey** [comment]
@dcarrier-parallax please address.

**Comment by zfi** [comment]
The Cloud Compiler servers are using an older copy of the Scribbler-3 library. Working on replacing that library on the production servers now.

**Comment by zfi** [comment]
Updated library has been deployed to all Cloud Compiler servers. Verified that the compile error has been resolved.
