### ISSUE TITLE
Pin states on PAB should be 0-17 (currently 0-13)

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#886]
![2017-01-16_21-05-20](https://cloud.githubusercontent.com/assets/9534148/22008379/97aec4ba-dc2f-11e6-880f-a6e1c8c9255e.png)

Unable to do certain activities in C Learning system, like controlling the 7-segment LED on P8-P15. 

Let me know if this fix can get done by Wednesday morning (webinar).

**Comment by mrodriguez-parallax** [comment]
Group pin state block goes from P0 through P17
![image](https://cloud.githubusercontent.com/assets/20686764/23228698/5a50da4c-f8f2-11e6-841e-0687197f94b6.png)


This block covers pin P0 through P17, and P26, P27
![image](https://cloud.githubusercontent.com/assets/20686764/23228848/e054ed2c-f8f2-11e6-9fd0-c26493dc7b67.png)


This block covers pin P0 through P17, and P26, P27.
![image](https://cloud.githubusercontent.com/assets/20686764/23228880/0ebfa012-f8f3-11e6-8f10-7cba016faa9a.png)

**Comment by MatzElectronics** [comment]
Thanks @mrodriguez-parallax !
