### ISSUE TITLE
Download to RAM on S3: questionable on latest release

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#887]
I have several S3s and none of them accept a download to RAM in the new release of Blockly. @mrodriguez-parallax could you also check this on a few robots and validate or discount this issue?

**Comment by zfi** [comment]
This is the correct behavior. The download to RAM feature was removed because the programming disappears when the device is powered off.

**Comment by wstodghill** [comment]
@kgracey - this is one of many items that I think we need to update and clarify in our tutorials!

You guys have made some really fast progress lately! FUN stuff too!

**Comment by PropGit** [comment]
Whoa... Is the removal of RAM-only downloads only applied to the S3 board type?

**Comment by PropGit** [comment]
And why is it still a menu item? I'm assuming it is, based on Ken's post.

**Comment by zfi** [comment]
The menu item is unavailable only for the S3 hardware.
