### ISSUE TITLE
C and Spin: serial transmit number

### ISSUE THREAD

**Issue by michel-cf** [parallaxinc/BlocklyProp#89]

**Comment by DarkmatterVale** [comment]
Is this a block addition to allow simple serial transmit of a number? Can you provide some additional details?

**Comment by DarkmatterVale** [comment]
bump

**Comment by DarkmatterVale** [comment]
I am going to close this issue because it is not clear and no one has explained this. @kgracey @PropGit please reopen the issue if this is something you would like to see.
