### ISSUE TITLE
Open project causing a runtime exception

### ISSUE THREAD

**Issue by pjewald** [parallaxinc/BlocklyProp#891]
The application logs are reporting an occasional NullPointerException being thrown at 
ProjectDaoImpl.getProject(ProjectDaoImpl.java:82). It appears to be triggered by a malformed JSON payload from the client browser.

**Comment by pjewald** [comment]
Update: This exception is triggered when editing a project that does not contain any code. Adding error handling to trap this issue.

**Comment by zfi** [comment]
Issued PR #897 to detect nulls and handle them gently.

**Comment by MatzElectronics** [comment]
@zfi Status on this one?

**Comment by MatzElectronics** [comment]
Tested and verified.
