### ISSUE TITLE
Untrapped user authorization error

### ISSUE THREAD

**Issue by pjewald** [parallaxinc/BlocklyProp#892]
The call to com.parallax.server.blocklyprop.services.impl.ProjectServiceImpl.getProject() correctly throws an Unauthorized exception when an attempt is made to retrieve a project that is not owned by the current user. 

The caller in this case is:
com.parallax.server.blocklyprop.rest.RestSharedProject.get(RestSharedProject.java:81) 
This method should trap the exception and return the correct response value to the client browser.

**Comment by zfi** [comment]
This issue was addressed during a sweep through the Services and DB classes to implement better try...catch blocks to prevent these errors fro bubbling up into UI code.
