### ISSUE TITLE
Block request: MCP3202/4/8

### ISSUE THREAD

**Issue by Steph-Parallax** [parallaxinc/BlocklyProp#894]
Would love a block for the ADC0831.  
OR another DIP ADC. Selecting parts to recommend.

**Comment by MatzElectronics** [comment]
The ADC0831 needs a 5V supply, making a bit of a non-starter for the FLiP.  Changed to MCP3201-MCP3208

**Comment by MatzElectronics** [comment]
Also need to add support for MCP300X (or verify that the MCP320X protocol works with it)

**Comment by JonMcPhalen** [comment]
The MCP300x are 10-bit parts, the MCP320x are 12-bit parts.

**Comment by MatzElectronics** [comment]
Correct, but it might be possible for them to be compatible protocol-wise,
with the 10 bit ones always reporting 0's for the last two bits.

**Comment by MatzElectronics** [comment]
Tested against MCP3204 - Failed:
 - Function is trying to bring data in on the IN pin - switch to out.
 - The channel selection binary does not seem to change appropriately

**Comment by MatzElectronics** [comment]
Tested and verified
