### ISSUE TITLE
Code download icons active when the BlocklyPropClient is not loaded

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp#900]
The buttons to load the program to RAM of EEPROM should be disabled if the BlocklyProp Client has not been detected.

![screen shot 2017-01-30 at 16 21 25](https://cloud.githubusercontent.com/assets/8442260/22447609/3b624036-e708-11e6-81e4-c70ea4884f37.png)

**Comment by CarsonGracey** [comment]
Verified.
