### ISSUE TITLE
Remove mis-spelling highlights from Description field

### ISSUE THREAD

**Issue by Steph-Parallax** [parallaxinc/BlocklyProp#904]
When writing a description for my new projects, I often see a mess of red highlighting on numbers as well as some words. I am guessing that there is an associated dictionary that is unfamiliar with our Parallax vernacular.

**Comment by MatzElectronics** [comment]
Not entirely sure how to fix this.... :(

**Comment by MatzElectronics** [comment]
@zfi @PropGit @Steph-Parallax @kgracey Found out how to implement this - do we want to?  I'd like a little discussion on it.

Here's are the attributes to place in the textarea tag (HTML5, limited browser support):
**autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false"**

**Comment by PropGit** [comment]
That's how we can disable the spellcheck (and other auto features).  That would certainly get rid of the red underlines.

Unless there's a way for us to update the dictionary in use (and assuming we have time to do it among all other things), I think turning that feature off is a good idea.

**Comment by MatzElectronics** [comment]
Tested and verified.
