### ISSUE TITLE
Add blocks for Shift-in/Shift-out functions

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#905]
WIll allow for users to roll their own I/O expansion, SPI, and possibly I2C.

**Comment by dcarrier-parallax** [comment]
The shift-out block doesn't have an option for which clock edge to sample on, but the shift-in block does have an option of whether to sample before or after driving the clock, which would effectively choose which clock edge to expect the output to change, although it doesn't indicate which clock edge it is sampling before/after.

For consistency, could we either set shift-in to always sample after a rising edge (a.k.a. before a falling edge) or have an option on the shift-out block to specify the edge?

For clarity, can we specify which edge it is sampling on?

Also, the help url is set to: http://learn.parallax.com/ab-blocks/protocols, but the page appears to be at: http://learn.parallax.com/support/reference/activity-board-wx-block-reference/communicate/protocols

**Comment by MatzElectronics** [comment]
If the c function under the hood supported it, I'd be all for it - the way that I believe it was designed, however, was that if you needed it on the trailing edge, you throw a "dummy" bit in.  See this example on Learn:
http://learn.parallax.com/tutorials/language/propeller-c/propeller-c-simple-protocols/spi-example/how-spi-test-works

**Comment by MatzElectronics** [comment]
With some testing to make sure that it worked (I'd have to find an IC or two that would be good for this, or simulate it with a second Prop), I'd be up for "faking it" by having the block automatically add a dummy bit in...

**Comment by dcarrier-parallax** [comment]
The URL issue was a missing redirect that is now in place, and all functions works as written.  This should be revisited at a later date to allow specifying rising vs falling edge on both input and output blocks.

I also recommend making  blocks specific to the 74x595 and 74x165 shift registers.
