### ISSUE TITLE
Add blocks for the Fingerprint Scanner module

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#906]

**Comment by MatzElectronics** [comment]
@mrodriguez-parallax @dcarrier-parallax these are ready to be tested.

**Comment by mrodriguez-parallax** [comment]
Blockly skips over the Finger print add block shown here. As if it's not even there.

![image](https://cloud.githubusercontent.com/assets/20686764/23624004/034aef06-0259-11e7-929d-f4a2e17fab0e.png)

I ran it in both demo Blockly and Simple IDE and observed the same result.

**Comment by MatzElectronics** [comment]
@mrodriguez-parallax Try deleting user 1 first.  If there already is a user 1, it won't let you try to save a new fingerprint to it.

I also realized that what I thought was "allow overwrite" is something else entirely.
Basically, when you check "allow overwrite", it lets you save the same fingerprint to more than one user.  Since that isn't what I thought it was, I'm deleting that from the init block.

**Comment by MatzElectronics** [comment]
@mrodriguez-parallax This is ready to be tested again

**Comment by mrodriguez-parallax** [comment]
Finger print scanner count the number of IDs block is broken. See error, blocks and code below.
![image](https://cloud.githubusercontent.com/assets/20686764/23759968/14dcf47a-04a3-11e7-9f3a-43710f825250.png)




![image](https://cloud.githubusercontent.com/assets/20686764/23759949/07022974-04a3-11e7-8613-6bd35d4fc59d.png)


`
/* SERIAL_TERMINAL USED */
#include "simpletools.h"
#include "fingerprint.h"

fpScanner * fpScan;
int fingerScanner(int __u)
{
    int r;
    fingerprint_scan(fpScan, __u, & r);
    if (__u != 0 && r != 0) return 1;
    else return r;
}
int item;
int number_of_users[
{
    {
        $var_length_number_of_users
    }
};];



int main()
{
    fpScan = fingerprint_open(7, 8);
    fingerprint_deleteUser(fpScan, 0);
    pause(1000);
    fingerprint_add(fpScan, 15, 3, 0);
    pause(3000);
    fingerprint_add(fpScan, 20, 3, 0);
    for (int __n = 0; __n < 3; __n++)
    {
        item = fingerScanner(0);
        pause(500);
        print("%d\r", item);
    }
    number_of_users = fingerprint_countUsers(fpScan);
    print("%d\r", number_of_users);

}
`

**Comment by mrodriguez-parallax** [comment]
All blocks tested and perform as expected
