### ISSUE TITLE
BlocklyProp MacOS client distribution change

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp#909]
The BlocklyProp client installer for MacOS has changed from a .dmg file to a .pkg file. Update the UI to support the new file naming convention.

**Comment by zfi** [comment]
Code for this is ready to go. Holding off on PR for this until @PropGit can release the completed MacOS installer.

**Comment by zfi** [comment]
@PropGit - Is the new BlocklyProp Client for MacOS going to be distributed as a .pkg or a .dmg file?

**Comment by PropGit** [comment]
@zfi - It is naturally a .pkg because of the build process.  If we can distribute it as a .pkg without issue, that's how I'd like it to be, instead of the added need to convert it to a .dmg.

**Comment by zfi** [comment]
Looks like we are distributing this as a .pkg file now. Closing the issue.
