### ISSUE TITLE
Register link provides unstyled page

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#91]
From the _Login/Register_ page, the _Register Now!_ link provides an unstyled page.

![image](https://cloud.githubusercontent.com/assets/1266318/13186385/d24ff0d4-d6fa-11e5-8a72-ff6b9ad1d1b9.png)

**Comment by michel-cf** [comment]
https pages require https resources. Reworking cdn url calculation

**Comment by michel-cf** [comment]
Fixed

**Comment by PropGit** [comment]
@michel-cf  - Confirmed; this is fixed.
