### ISSUE TITLE
COM port list is populated when BlocklyProp Client is not detected

### ISSUE THREAD

**Issue by paragitadmin** [parallaxinc/BlocklyProp#912]
The project canvas displays a drop-down list of COM ports (COM1,COM3,COM4) even though the BlocklyProp Client not detected message is displayed. The COM port selection is ineffective until the Client is detected and has been able to enumerate the ports that are actually available. The defaults presented are for a Windows system and make no sense at all on MacOS or Linus systems.

**Comment by MatzElectronics** [comment]
@paragitadmin if it's not connected, should we have it say something like "No client found" (if that's an option) or leave it completely blank.  I vote for some test in the box to keep it from looking strange.

**Comment by MatzElectronics** [comment]
Just checked - we can add text here...

**Comment by zfi** [comment]
The drop down could have a single selection that says something like 'Searching...' . I don't know where the COMx items were coming from but they only apply to the Windows platform, so it is odd to see them enumerated on MacOS. A third option would be to hide the drop down until one or more ports have been detected, in which case the drop down would be populated and made visible. That would be my preference followed by the 'Searching...' text.

**Comment by MatzElectronics** [comment]
OK, I'll see what I can do.

**Comment by MatzElectronics** [comment]
Tested and verified
