### ISSUE TITLE
two dependancies cannot be found when building.

### ISSUE THREAD

**Issue by tinywinds** [parallaxinc/BlocklyProp#919]
[INFO] Scanning for projects...
    [INFO] 
    [INFO] ------------------------------------------------------------------------
    [INFO] Building BlocklyProp 1.0-SNAPSHOT
    [INFO] ------------------------------------------------------------------------
    [WARNING] The POM for com.parallax.client:Cloud-Session-java-client:jar:1.0-SNAPSHOT is missing, no dependency information available
    [WARNING] The POM for com.parallax.client:Cloud-Compiler-java-client:jar:1.0-SNAPSHOT is missing, no dependency information available
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 1.946 s
    [INFO] Finished at: 2017-02-23T17:55:12-08:00
    [INFO] Final Memory: 9M/31M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal on project BlocklyProp: Could not resolve dependencies for project com.parallax:BlocklyProp:war:1.0-SNAPSHOT: The following artifacts could not be resolved: com.parallax.client:Cloud-Session-java-client:jar:1.0-SNAPSHOT, com.parallax.client:Cloud-Compiler-java-client:jar:1.0-SNAPSHOT: Failure to find com.parallax.client:Cloud-Session-java-client:jar:1.0-SNAPSHOT in http://bits.netbeans.org/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of netbeans.maven2.repository has elapsed or updates are forced -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by zfi** [comment]
Be sure to include the [Cloud-Session-java client](https://github.com/parallaxinc/Cloud-session-java-client.git) and the [Cloud-Compiler-java-client](https://github.com/parallaxinc/Cloud-Compiler-java-client.git) projects in your build process. Maven should pick up the fact that the BlocklyProp project depends on these two client projects.

**Comment by tinywinds** [comment]
thanks for you help, I have finished  building  and got the .war file,   I rename it to "blockly.war" and use Tomcat Web Application Manager to deploy it, when I start it , always get message "FAIL - Application at context path /blockly could not be started" .  what should I do now ？

**Comment by zfi** [comment]
Adding the dependencies to your project resolved the initial reported error. The new error can be caused by a number of issues. Review the catalina.out log file for errors during application startup. The usual suspects are a misconfigured tomcat server.xml file or the blocklyprop.properties file is missing or contains an error.

**Comment by tinywinds** [comment]
Still cannot be start from tomcat, catalina.out file show below:
```
log4j:WARN Continuable parsing error 9 and column 14
log4j:WARN Element type "loggers" must be declared.
log4j:WARN Continuable parsing error 10 and column 100
log4j:WARN Element type "Logger" must be declared.
log4j:WARN Continuable parsing error 11 and column 40
log4j:WARN Element type "AppenderRef" must be declared.
log4j:WARN Continuable parsing error 13 and column 28
log4j:WARN Attribute "level" must be declared for element type "root".
log4j:WARN Continuable parsing error 17 and column 23
log4j:WARN The content of element type "log4j:configuration" must match "(renderer*,throwableRenderer?,appender*,plugin*,(category|logger)*,root?,(categoryFactory|loggerFactory)?)".
log4j:WARN Unrecognized element loggers
Looking for blocklyprop.properties in: /root
log4j:WARN No appenders could be found for logger (org.apache.commons.configuration.DefaultConfigurationBuilder).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Sat Feb 25 04:15:08 PST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Sat Feb 25 04:15:08 PST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Looking for help files in: /opt/tomcat/bin/help
Looking for help files in: /root/help
25-Feb-2017 04:15:09.631 SEVERE [http-nio-8080-exec-69] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
25-Feb-2017 04:15:09.640 SEVERE [http-nio-8080-exec-69] org.apache.catalina.core.StandardContext.startInternal Context [/Blocklypro] startup failed due to previous errors
25-Feb-2017 04:15:09.647 WARNING [http-nio-8080-exec-69] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [Blocklypro] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
 com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:43)
25-Feb-2017 04:15:09.861 SEVERE [http-nio-8080-exec-69] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [Blocklypro] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@8690646]) and a value of type [org.jooq.impl.DefaultDSLContext] (value [DefaultConfiguration [
	connected=true,
	transactional=false,
	dialect=MYSQL,
	data={},
	settings=
		<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
		<settings xmlns:ns2="http://www.jooq.org/xsd/jooq-runtime-3.6.0.xsd">
		    <ns2:renderSchema>true</ns2:renderSchema>
		    <ns2:renderNameStyle>QUOTED</ns2:renderNameStyle>
		    <ns2:renderKeywordStyle>AS_IS</ns2:renderKeywordStyle>
		    <ns2:renderFormatted>false</ns2:renderFormatted>
		    <ns2:renderScalarSubqueriesForStoredFunctions>false</ns2:renderScalarSubqueriesForStoredFunctions>
		    <ns2:backslashEscaping>DEFAULT</ns2:backslashEscaping>
		    <ns2:paramType>INDEXED</ns2:paramType>
		    <ns2:statementType>PREPARED_STATEMENT</ns2:statementType>
		    <ns2:executeLogging>true</ns2:executeLogging>
		    <ns2:executeWithOptimisticLocking>false</ns2:executeWithOptimisticLocking>
		    <ns2:attachRecords>true</ns2:attachRecords>
		    <ns2:updatablePrimaryKeys>false</ns2:updatablePrimaryKeys>
		    <ns2:reflectionCaching>true</ns2:reflectionCaching>
		    <ns2:fetchWarnings>true</ns2:fetchWarnings>
		</settings>
]]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
25-Feb-2017 04:15:09.862 SEVERE [http-nio-8080-exec-69] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [Blocklypro] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@5928f5d9]) and a value of type [org.jooq.impl.DefaultConnectionProvider] (value [org.jooq.impl.DefaultConnectionProvider@4d92c556]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

```

**Comment by tinywinds** [comment]
@zfi  Could you offer me a short guide for deploying BlocklyProp on my server. (Ubuntu 16) .

**Comment by tinywinds** [comment]
Problem solved, missing a jar file in the WEB-INFO/lib folder. Thank you Jim. @zfi
