### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#92]
Though unregistered accounts clearly show an "Login was unsuccessful!" error message...

![image](https://cloud.githubusercontent.com/assets/1266318/13186464/3a600042-d6fb-11e5-8b74-bf61993daf46.png)

using a previously registered account does not show an error and, in fact, doesn't give any kind of feedback, even if the password is surely wrong:

![image](https://cloud.githubusercontent.com/assets/1266318/13186495/5457f2b6-d6fb-11e5-8f78-fd6baa485c5c.png)

This makes it difficult for anyone to, 1) realize there is something wrong, or 2) fix it (ie: there's not "Forgot password" or "Unconfirmed email address" option.

**Comment by michel-cf** [comment]
During testing, it didn't appear that there was a problem with the form, but with the connection with Cloud-session

As such they are more related to:
#93 and #94

**Comment by PropGit** [comment]
@michel-cf - To ensure a response to the user for their action, please add a catch-all error response that displays something like "Error: unable to log in at this time; please try again later or contact the system administrator."  Without this, the user doesn't know if 1) they didn't click the button properly, 2) their browser is working properly or not, 3) their Internet connection is at fault or not.

**Comment by PropGit** [comment]
The issue at the bottom of the [first post](https://github.com/parallaxinc/BlocklyProp/issues/92#issue-134951685) and the solution suggested in the [prior post](https://github.com/parallaxinc/BlocklyProp/issues/92#issuecomment-187280938) still applies.  Today I tried to log in and get no response from the system upon clicking Login; the result appears just as if I had not clicked Login.  We need some kind of response from the system indicating there was a problem (with the system) and it's unable to log the user in.

**Comment by michel-cf** [comment]
I added a popup that will show:"An unexpected error occured. Please try again later or contact the webmaster."
