### ISSUE TITLE
error occurs after clicking the verify code button or compile button.

### ISSUE THREAD

**Issue by tinywinds** [parallaxinc/BlocklyProp#924]
```
Propeller Spin/PASM Compiler 'OpenSpin' (c)2012-2013 Parallax Inc. DBA Parallax Semiconductor.
Compiled on Oct 21 2013
Compiling...
/tmp/tmp6i3tNi/single.spin
|-Block_Wrapper.spin
Block_Wrapper.spin : error : Can not find/open file.
```
How to trace this error ?

**Comment by zfi** [comment]
The compiler cannot locate the Blockly_Wrapper.spin file in the location designated in the cloud compiler.properties file used by the Cloud Compiler server. Find the location of the Blockly_Wrapper.spin file and use the path to that file in your properties file.

I should also note that development happens on the demo branch of the BlocklyProp projects. You should work from that if you want the latest code.

**Comment by zfi** [comment]
Anything further on this issue?
