### ISSUE TITLE
Block request - Get/Set States (binary)

### ISSUE THREAD

**Issue by Steph-Parallax** [parallaxinc/BlocklyProp#927]
Requesting a Get States block based on the get_states function of simpletools.h.

Need is not immediate, but early summer would be very nice.

**Comment by zfi** [comment]
Can we get a brief description of the block being requested. Asking readers to track down the library file seems at bit daunting.

**Comment by MatzElectronics** [comment]
The binary get/set states blocks will allow pins to be set or read in a single execution by specifying a binary number that corresponds with a group of pins.  For example, if you want PIN 4 high, PIN 3 low, PIN 2 high, and PIN 1 low, you can feed it 0b1010 and set them all at once.  With the binary read block, you can read a set of contiguous pins simultaneously as well.  These blocks will work well in conjunction with the existing binary value block, and use functions that are designed for this purpose in Simpletools (prop c library).  These blocks may be necessary for applications like the QTI line following kit on the Activitybot, as well as a few other published examples.

**Comment by mrodriguez-parallax** [comment]
Set State and Get States blocks pass testing. P0 - P17 can be set to High or Low and to input or output.
