### ISSUE TITLE
Block request - switch-case

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#928]
Per forum member request: http://forums.parallax.com/discussion/166158/blockly-activitybot-with-whiskers-and-sirc-tv-remote#latest

**Comment by zfi** [comment]
Can we get a brief description of the proposed block functionality posted to this issue? The reference to a forum thread is good to have but we should not require readers to wade through thread to understand the block request.

**Comment by MatzElectronics** [comment]
Sure - SWITCH/CASE will be a block that is similar to the IF/DO block in that you can mutate it to provide a series of conditions that results in code that looks like this:

switch (argument) {
  case condition_1:
    //code to execute if argument == condition_1
    break;
  case condition_2:
    //code to execute if argument == condition_2
    break;
  case default:
    //code to execute if a 'default' catch-all is specified
}

The mutator will allow you to add as many conditions as you'd like, and a checkbox can be used to specify whether the user wants a "break" at the end of the condition.  If there is no break, the switch will jump to that case, evaluate it, and then continue to the next case.  There are some situations where that is the preferred behavior, so there's an argument for making the break optional with a checkbox.

**Comment by mrodriguez-parallax** [comment]
Switch Case Block will not break out of loop. In the block code below only the first hello should of printed and then exit the loop. Instead it printed the rest of the following hellos.

![image](https://cloud.githubusercontent.com/assets/20686764/23669785/4b969104-031a-11e7-8954-2d5acd3f092a.png)

result:
![image](https://cloud.githubusercontent.com/assets/20686764/23669854/86992410-031a-11e7-8992-3a7447728e58.png)

**Comment by zfi** [comment]
Can you post the C source code generated by these blocks?

**Comment by MatzElectronics** [comment]
@mrodriguez-parallax This is ready to be tested again

**Comment by mrodriguez-parallax** [comment]
The Switch Case block and Break command is fixed and fully functional.
