### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#929]
On both Production and Demo, I can't get a download to occur... there are no error messages when downloading to RAM or EEPROM, it simply appears that the download process never even started.

I'm testing on macOS Sierra.

**Comment by PropGit** [comment]
UPDATE: The BlocklyProp Editor's COM port updates properly, I can see that the FTDI driver loaded and is connected to the plugged-in PAB, but when I try to download, nothing seems to happen except a compilation, then the dialog stays there with no further status.

**Comment by zfi** [comment]
Verified that the behavior described on a MacOS system is specific to the packaged version of the client. With logging enabled, it appears that the packaged client is attempting to fork the propeller-load executable with an incorrect relative path. The correct behavior is for the propeller-load to be launched using a full path to the executable.

**Comment by PropGit** [comment]
I don't think (or know for sure) that the Mac packaging changes are a direct culprit in creating this problem, but rather I think it's a factor of those changes occurring concurrent with enhancements in the internal operation of the client but too late for use in testing during those enhancements (from a "real" installation scenario).

I think macOS is "changing the rules" somehow about what the application has access to when it's run from the Applications folder as opposed to elsewhere.  Some sort of sandboxing, perhaps, that's working its way into thwarting our code's efforts.

In case it matters; however, the previous packaging used a flatter application bundle scheme (which may not have even been "proper" by Apple's bundle specifications) where the executable and library files were like this:

- Application Bundle (BlocklyPropClient.app)
  - executables
  - libraries (.so)
  - some other resources
    - include (subfolder)
      - other libraries
    - propeller-tools (subfolder)
      - propeller-load

And the new package follows "proper" bundle specs as defined by Apple which is something like this (this is by memory... may not be 100% accurate on some deeper items):

- Application Bundle (BlocklyPropClient.app)
  - Contents (subfolder)
    - icon file
    - bundle description (Info.plist)
    - MacOS (subfolder)
      - executables
      - include (subfolder symbolic link)
      - propeller-tools (subfolder symbolic link)
    - Resources (subfolder)
      - libraries (.so)
      - some other resources
      - include (subfolder symbolic link)
          - other libraries
      - propeller-tools (subfolder symbolic link)
        - propeller-load

**Comment by PropGit** [comment]
This turned out to be a problem with the BlocklyPropClient itself; something that went unnoticed because of issues with the Mac application packager in relation to development time spent on logging and correcting other issues within the client.  It has been resolved with client v0.5.4
