### ISSUE TITLE
Can't exercise "Forgot Password" feature

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#94]
Just like with Issue #93, the _Forgot Password_ feature can not be used because of a server error:

HTTP Status 500 - com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 28 path $

type Exception report

message com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 28 path $

description The server encountered an internal error that prevented it from fulfilling this request.

exception

javax.servlet.ServletException: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 28 path $
	org.apache.shiro.web.servlet.AdviceFilter.cleanup(AdviceFilter.java:196)
	org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:148)
	org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
root cause

com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 28 path $
	com.google.gson.JsonParser.parse(JsonParser.java:65)
	com.google.gson.JsonParser.parse(JsonParser.java:45)
	com.parallax.client.cloudsession.CloudSessionLocalUserService.requestPasswordReset(CloudSessionLocalUserService.java:75)
	com.parallax.server.blocklyprop.servlets.PasswordResetRequestServlet.doPost(PasswordResetRequestServlet.java:50)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:287)
	com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:277)
	com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:182)
	com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
	com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
	com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
	com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
	com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
	org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
root cause

com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 28 path $
	com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1573)
	com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1423)
	com.google.gson.stream.JsonReader.doPeek(JsonReader.java:546)
	com.google.gson.stream.JsonReader.peek(JsonReader.java:429)
	com.google.gson.JsonParser.parse(JsonParser.java:60)
	com.google.gson.JsonParser.parse(JsonParser.java:45)
	com.parallax.client.cloudsession.CloudSessionLocalUserService.requestPasswordReset(CloudSessionLocalUserService.java:75)
	com.parallax.server.blocklyprop.servlets.PasswordResetRequestServlet.doPost(PasswordResetRequestServlet.java:50)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:287)
	com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:277)
	com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:182)
	com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
	com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
	com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
	com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
	com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
	org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
note The full stack trace of the root cause is available in the Apache Tomcat/7.0.52 (Ubuntu) logs.

Apache Tomcat/7.0.52 (Ubuntu)

**Comment by michel-cf** [comment]
Partially fixed, need to tackle root cause

**Comment by PropGit** [comment]
@michel-cf - Confirmed: This error does not occur anymore with the Forgot Password feature.
