### ISSUE TITLE
Define block menus for "other" board type

### ISSUE THREAD

**Issue by JonMcPhalen** [parallaxinc/BlocklyProp#943]
Why are the Communicate Blocks not available when the board type is set to "Other"? My board of choice is the insanely awesome (yes, I designed it) HC-8+ from EFX-TEK. I have to "lie" and say I'm using a PAB-WX in order to get the Communicate blocks.

HC-8+ Features:
-- 8 high-current (open-drain) outputs
-- 8 5V (active-high) inputs (via 74x165 shift register
-- 9 position DIP switch (e.g. DMX address -- uses 74x165 shift register and one direct IO pin)
-- 4 bit option buss (each IO pulled up) with 4-pos DIP switch
-- full-duplex RS-485 port
-- TTL level serial (for half-duplex or full-duplex with board mod)
-- Red/Green LED
-- 4-bit "x-port" (bits are not contiguous)

I write Spin code for this board every single day. It was originally designed for Disneyland (originals PCBs are still there) and gets used in a wide variety of applications, especially now in the Escape Rooms business. I want to show those customers how to write simple puzzle programs in Blockly.

Right now I am failing miserably -- things I was doing 20 years ago with the BS1 seem like impossible tasks... 

Help.

[Follow-up]

I created a new file using the PAB-WX type. I saved the Blocks file and the opened that into a new project with a custom board. The Terminal output is present in the new file, though the Communicate group is gone.

This the project. I get the TTL inputs working, as well as the RG LED.
-- http://blockly.parallax.com/blockly/projectlink?id=4183&key=4f566790-66bf-494c-825c-a32fc76c87b9

**Comment by MatzElectronics** [comment]
I'd be especially interested in a DMX object if it were a c library.
If you're interested in taking a stab at combing through the menus to make
them suitable for use with "generic" Prop boards, the file that defines the
menu is here:
https://github.com/parallaxinc/BlocklyProp/blob/demo/src/main/webapp/frame/framec.jsp

Look for the coding in the boards in the "include" and "exclude" attributes
in the category tags.  Although it is not currently used in the file, you'd
use "other" along with "s3", "activity-board", "heb", and "flip".

If the "FLiP/Project Board" type meets your needs, it's easy to just add
"other" to it and call it good.

Let me know if you have questions, I'm happy to work with you on getting it
cleaned up.


*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by JonMcPhalen** [comment]
I have DMX RX and TX objects in Spin, though the PASM sections are C-friendly (no *poking* values before launching cog). I am re-learning C so that I can start translating some of my projects; I'm curious about code density versus performance.

There is a David (Betz?) in the forums who has translated some of my objects to C. I will ask him about the DMX objects. They were designed in consultation with Disney (if we can meet their needs, others tend to be happy). The receiver object has a loss-of-signal indication which is critical to the things they do in the park.

What is a FliP board? I've never heard of it.

**Comment by MatzElectronics** [comment]
Cool!  Spin2cpp has been good, especially lately - but setting it up and
using it is a bit out of my wheelhouse.  The FLiP is still in prototype -
it was used in this tweet:
https://twitter.com/ParallaxKen/status/826634707592835072

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by MatzElectronics** [comment]
@JonMcPhalen this should be better now in demo - let me know if there is anything that still needs to be tweaked.

**Comment by MatzElectronics** [comment]
Tested and verified
