### ISSUE TITLE
Error on null password

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#95]
The _Register_ page allows the user to leave the password field(s) blank, causing an ugly error upon clicking _Register_.

HTTP Status 500 - java.lang.NullPointerException: Password cannot be null

type Exception report

message java.lang.NullPointerException: Password cannot be null

description The server encountered an internal error that prevented it from fulfilling this request.

exception

javax.servlet.ServletException: java.lang.NullPointerException: Password cannot be null
	org.apache.shiro.web.servlet.AdviceFilter.cleanup(AdviceFilter.java:196)
	org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:148)
	org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
root cause

java.lang.NullPointerException: Password cannot be null
	com.google.common.base.Preconditions.checkNotNull(Preconditions.java:226)
	com.parallax.server.blocklyprop.services.impl.SecurityServiceImpl.register(SecurityServiceImpl.java:79)
	com.adamlewis.guice.persist.jooq.JdbcLocalTxnInterceptor.invoke(JdbcLocalTxnInterceptor.java:63)
	com.parallax.server.blocklyprop.servlets.RegisterServlet.doPost(RegisterServlet.java:58)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:287)
	com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:277)
	com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:182)
	com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
	com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
	com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
	com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
	com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
	org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
note The full stack trace of the root cause is available in the Apache Tomcat/7.0.52 (Ubuntu) logs.

Apache Tomcat/7.0.52 (Ubuntu)

**Comment by michel-cf** [comment]
Validation was in place, but the generated exception was not caught and shown as a warning message.

**Comment by PropGit** [comment]
Verified working.
