### ISSUE TITLE
Simple Sensors blocks produce compile error

### ISSUE THREAD

**Issue by mrodriguez-parallax** [parallaxinc/BlocklyProp#951]
All 5 blocks in Simple Sensors produce a compiling error. The blocks do work in demo but not in regular Blockly.

![image](https://cloud.githubusercontent.com/assets/20686764/24016684/5f0248d2-0a4a-11e7-8aa9-d27a905cc54f.png)

![image](https://cloud.githubusercontent.com/assets/20686764/24016708/70665852-0a4a-11e7-84ac-d9cd28b1e2e9.png)

![image](https://cloud.githubusercontent.com/assets/20686764/24016727/83bb4246-0a4a-11e7-8762-9a89fdb6fc48.png)

**Comment by zfi** [comment]
@MatzElectronics Is this a case where the beta site should still generate SPIN for S3 blocks?

**Comment by MatzElectronics** [comment]
Is the s3 library in the production server... this might be another case
where we need conditional code to turn off a feature in
production...although we are so close it might not be worth it...

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by paragitadmin** [comment]
The S3 C library is loaded on the Demo server. Let's test it there first and then I can move the library to the production servers.

@mrodriguez-parallax  Could you please retest the block error that was reported above and verify that is has been corrected?

**Comment by mrodriguez-parallax** [comment]
The Scribbler 3 blocks are now compiling on both Demo and regular Blockly.
