### ISSUE TITLE
Block Requests: advanced blocks (WAITCNT, register read/write, 'eval')

### ISSUE THREAD

**Issue by JonMcPhalen** [parallaxinc/BlocklyProp#952]
For reasons I don't understand, my previous request for a waitcnt() block was closed -- though there is no waitcnt() block. Yes, it can be simulated with a repeat-while loop, but this generates clunky code and is not precise. The value of waitcnt() in real-time control applications cannot be overstated, and it's part of what sets the Propeller apart from the Arduino, et al.

The block would look like this:

![waitcnt_block](https://cloud.githubusercontent.com/assets/4042568/24064918/9c9c0f72-0b24-11e7-9f78-322632ace4bc.png)

During a conversation with Ken he suggested that I could help the process by using the Block Factory to build the block the way I think matches what works in Blockly and the Propeller. As you can see, the block is identical to pause() in that it accepts an inline numeric value. This is what the creation side of the block looks like.

![waitcnt_block_definition](https://cloud.githubusercontent.com/assets/4042568/24065001/32dd5784-0b25-11e7-8939-361c99a8d901.png)

I exported an XML file from the Block Factory -- hopefully this is what you need so that you don't have to re-create the block manually. I don't know how the implementation aspect works. That said, I believe the generated code should be:

  **__builtin_propeller_waitcnt(target, 0);**

...where target is the user variable or numeric value from the block.

[jm_waitcnt_proposal.zip](https://github.com/parallaxinc/BlocklyProp/files/851911/jm_waitcnt_proposal.zip)

**Comment by MatzElectronics** [comment]
Propose adding only to the 'other' board type initially - feels like a safe place to take the brakes off the system.  Thoughts?

**Comment by MatzElectronics** [comment]
@JonMcPhalen for the register read/write blocks, I may need a little assistance in getting them right - if you just do screen caps of block factory results, that's enough for me to work from.

**Comment by zfi** [comment]
There is an "other" board type?

**Comment by MatzElectronics** [comment]
Yes.  It's always been there, and until recently, relatively neglected.

**Comment by JonMcPhalen** [comment]
@MatzElectronics I don't know why you would want to hide intrinsic features of the Propeller -- features that make it stand out from the Arduino, et al.

Since I use my own board (HC-8+), most of the time I will be using "other." That said, I'm worried that some blocks are limited by board type due to fixed configuration. 

I think the cnt register should remain separate from the "cog regsiters" as the former is read-only. The cog register drop-down should have this list:

ina
outa
dira
ctra
frqa
phsa
ctrb
frqb
phsb

All of these registers are read/write, so the block would have to be setup to allow that (I'm still very new with Block Factory, so I don't know how to set that up).

I'm on the road this week and may be doing BlocklyProp demos fro EFX-TEK customers. Long-term, we need to be able to access Propeller features without restrain in order to provide templates for our customers that have the features that I create for them in Spin.

**Comment by MatzElectronics** [comment]
The reason for "hiding" them initially is simply a matter of audience.  We
have to build a system that isn't going to overwhelm a middle school
student, which we are already on the edge of...

I'm working on a way to create a menu option that does something to the
effect of "enable advanced features" for all board types, but I'm a little
stuck on how to alter the block menu after it's already been loaded.

I (hopefully) fixed the "other" board type to make sure it has everything
that the Flip/Project board does , which is all blocks except those
specific to additional hardware on the Activity Board.  I have not tested
it yet, so if you find something is missing, let me know.

**Comment by MatzElectronics** [comment]
@JonMcPhalen thanks!  So the next challenge - let's give things names.  None of the blocks have the code itself in the text.  ie. CNT becomes "System Counter".  CTRA could become "Counter A register".

So for the get value block, we could have:

![image](https://cloud.githubusercontent.com/assets/19737272/24125513/49765d02-0d86-11e7-8d0e-7876c5ac6bcb.png)
 resulting in:
![image](https://cloud.githubusercontent.com/assets/19737272/24125521/51b043c0-0d86-11e7-9754-6ce5cfaf481e.png)

As for WAITCNT, it could be:
![image](https://cloud.githubusercontent.com/assets/19737272/24125648/fb3c172a-0d86-11e7-91fd-f3d8748aae7e.png)

**Comment by JonMcPhalen** [comment]
The problem is that there is no system ctra, it's a cog register. The cnt
register is system based, but can be accessed from any cog. Accuracy must
take priority over "pretty."

On Mar 20, 2017 6:05 PM, "Matthew Matz" <notifications@github.com> wrote:

@JonMcPhalen <https://github.com/JonMcPhalen> thanks! So the next challenge
- let's give things names. None of the blocks have the code itself in the
text. ie. CNT becomes "System Counter". CTRA could become "Counter A
register".

So for the get value block, we could have:

[image: image]
<https://cloud.githubusercontent.com/assets/19737272/24125513/49765d02-0d86-11e7-8d0e-7876c5ac6bcb.png>
resulting in:
[image: image]
<https://cloud.githubusercontent.com/assets/19737272/24125521/51b043c0-0d86-11e7-9754-6ce5cfaf481e.png>

As for WAITCNT, it could be:
[image: image]
<https://cloud.githubusercontent.com/assets/19737272/24125648/fb3c172a-0d86-11e7-91fd-f3d8748aae7e.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/parallaxinc/BlocklyProp/issues/952#issuecomment-287925667>,
or mute the thread

**Comment by JonMcPhalen** [comment]
Also, "pause" is the name of a method and shouldn't be used in the
description for waitcnt.

**Comment by MatzElectronics** [comment]
Fair enough - so should there be a "system" block with system-wide
registers and a "cog" block for cog-centric registers?  Educationally sound
language and visuals and full functionality can both be achieved, we just
need to work through it.  I'm okay with "wait until system clock =".  The
"until" could be a dropdown, with another option being "while", which would
generate less accurate but safer code (know this from quadcopter not
stopping for 53 seconds experience...

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by JonMcPhalen** [comment]
It's fine to have a system block as the CNT register is part of the SPR group. Each cog has one, with the CNT register being the same in each cog due to a single source.

I wish we could have a less verbose version of Blocks for experienced programmers. My only other Blocks experience is with MIT App Inventor -- using it now for a trade show demo that sends commands from an Android phone to a Propeller via Bluetooth SPP.

I think long-winded blocks with more than one or two "support words" very cumbersome and begin to defeat the purpose of the appearance of simplicity. I don't understand why the waitcnt block cannot be "waitcnt (target)" as I suggested; the pause block is "pause (ms)" so there is an existing precident. The help text is where the verbose descriptions should be -- not in the block itself. Reserve that space for keywords, or text that is succinct and meaningful.

**Comment by MatzElectronics** [comment]
Duly noted - I'll keep it short, but it will be language in line with the rest of the BlocklyProp system.  There is a very specific grammar employed (similar to German) for text on the blocks, and only rarely is the command rendered by the block on the block itself (usually when the command (high, low, pause), is already the best verb or noun to describe the block's action or effect.

I'll be implementing a "System" category for the "other" board type, and these blocks will go there, and the System counter/Clock Frequency block will appear in that menu in that board type (it will stay where it is in the others).

I will also implement an "eval" block, that will allow you to inject Propeller C into your project when there isn't a block already available.  It will also go into the "System" category.

**Comment by MatzElectronics** [comment]
I'll see what's possible for the PLL settings.

**Comment by JonMcPhalen** [comment]
I'm still confused because I modeled the style/verbiage of the waitcnt block exactly like the pause block. Have you seen MIT App Inventor? Their blocks a concise, yet useful. Most of blocks experience is with MIT AI2 for simple Android apps.

**Comment by MatzElectronics** [comment]
@JonMcPhalen drafted blocks will be available in demo now.  Take them for a drive, let me know if/how their functionality might need to edited.  They are only available in the "other" board type.  I haven't done any testing on them, nor do I know enough about using them to know if the code they are generating is correct or if all of the options presented are appropriate. 

I haven't had a chance to research PLL settings.

**Comment by MatzElectronics** [comment]
@JonMcPhalen nevermind - it's broken.  I'll let you know when it's fixed.

**Comment by MatzElectronics** [comment]
@JonMcPhalen They should now be working.  I'll be moving the menu to the end of the list and recoloring them, but their functionality won't change unless something needs to be fixed.  Let me know.
Thanks!

**Comment by MatzElectronics** [comment]
Tested and verified - will change the text to say "wait" instead of pause.

**Comment by JonMcPhalen** [comment]
Thank you, Matt.

Now that I'm am home and have a bit of time to myself, I'm working on
creating demos that take advantage of the System blocks. These will be for
older or advanced Blockly users, say high school and college students who
want to experience the real power of the Propeller.

Did you get a chance to run my RTC/timer demo?

If you'll point me to a document that I can use as a style guide, I will
write support material for my demos.

Jon

**Comment by MatzElectronics** [comment]
Thanks @JonMcPhalen - closing this issue as it stands.  There is still a bit more work to be done with the "User code/user defined blocks", but the rest are ready for prime time.
