### ISSUE TITLE
Block Request: RGB-LED set multiple LEDs

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#953]
Per @kgracey a request for a block that allows you to set multiple RGB LEDs with a single block.

**Comment by kgracey** [comment]
Thank you - this isn't block creep but a massive code overhead reduction.

**Comment by zfi** [comment]
This is another stealth block. Can someone explain it so the rest of us know what we're committing to the repo?

**Comment by MatzElectronics** [comment]
Sure, Ken was working on a tutorial and found out that if you are using a
strip of these type of LEDs (the most common configuration for these) the
code quickly becomes cumbersome if you have to set each LED in the chain
one at a time (or even in a loop).  I had the code already for the work I
did on the Array blocks, so it was quick to implement.

**Comment by MatzElectronics** [comment]
Tested, failed.  Submitted fix in #957

**Comment by MatzElectronics** [comment]
@kgracey can we close this?

**Comment by MatzElectronics** [comment]
Tested and verified.
