### ISSUE TITLE
Download error "[object Object]"

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#955]
Has anyone witnessed this upon downloading (to RAM in this case)?  If so, do we know what causes it?

![image](https://cloud.githubusercontent.com/assets/1266318/24175112/ab3de9d0-0e51-11e7-9dd1-322041a8ab40.png)

**Comment by MatzElectronics** [comment]
Something is being passed to the alert that isn't a string.  There's only a
handful of places that use alerts...I've been trying to put a header in
front of them lately so we at least know which one it's coming from.

**Comment by MatzElectronics** [comment]
There is another issue referencing this in more detail - closing this one.
