### ISSUE TITLE
Previous Projects appear blank

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#96]
After being unable to log in because of issues #92, #93, and #94, I tried just viewing previous projects "My New Spin Project" and "My First C Project" but both appear blank.

![image](https://cloud.githubusercontent.com/assets/1266318/13187294/3720a306-d6ff-11e5-83e0-9839bb8f84b7.png)

In fact, when first appearing, the scroll bars indicate I'm looking all the way down to the extreme lower right of the block editing area.  When scrolling all the way back to the top-left, it's still blank:

![image](https://cloud.githubusercontent.com/assets/1266318/13187286/2b46a04e-d6ff-11e5-803b-489e19880133.png)

**Comment by michel-cf** [comment]
Because of the redesign of the blocks projects that use old versions of block's or blocks that don't exist anymore show up empty.

**Comment by michel-cf** [comment]
"Blinky new" owned by michell seems to work:  /blockly/demo/blocklyc.jsp?project=7 

![image](https://cloud.githubusercontent.com/assets/5745991/13204798/08a31bea-d8d9-11e5-84a8-e4d4ea84c989.png)

**Comment by PropGit** [comment]
Understood.  I'll delete and create new projects.
