### ISSUE TITLE
Feature request: auto-expanding arithmetic block

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#967]
Make the math_artihmatic block auto expand to include more terms.  For example, after you've placed two terms, a third new one pops up (it doesn't need to be used) when it's not connected to anything else.  As soon as it's placed into or connected to another block, the expanding term hides.

**Comment by CarsonGracey** [comment]
Is this the block you are talking about? If so it has been tested and verified.

![capture5](https://user-images.githubusercontent.com/20099916/28895881-042f82aa-778f-11e7-88d0-76917e6c69b0.PNG)

**Comment by MatzElectronics** [comment]
Yes and thanks!

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>
