### ISSUE TITLE
"You are not logged in" dialog has "Log in" and "Register" too close to each other

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#97]
When not logged in, but trying out the editor, clicking _Save_ displays this dialog that has "Log in" and "Register" right next to each other with no apparent difference in context between them (ie: they appear to be all one link until you mouse over them).

![image](https://cloud.githubusercontent.com/assets/1266318/13187456/eea4cc64-d6ff-11e5-9d07-e798113d1d1a.png)

**Comment by michel-cf** [comment]
Changed the text and layout:

![image](https://cloud.githubusercontent.com/assets/5745991/13204131/32c8fa2c-d8c8-11e5-8147-4da195d3d781.png)

Please reopen if not satisfactory.

**Comment by PropGit** [comment]
This is satisfactory.  Thank you.
