### ISSUE TITLE
Adding a block to another menu.

### ISSUE THREAD

**Issue by CarolHazlett** [parallaxinc/BlocklyProp#975]
Is there a way to move or use a block from one menu to another? I would like to be able to use the "increment" block with the Scribbler 3.

**Comment by MatzElectronics** [comment]
Sort of.  We can create new blocks that are like blocks elsewhere in the system, but there isn't a way for a user to simply take a block and move it to a different part of the system.  This functionality will come when the scribbler is switched over to Propeller C in about a month - the C version does have this (and some other math) blocks.
