### ISSUE TITLE
Invalid "Register" link on "You are not logged in" dialog

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#98]
The __You are not logged in__ dialog's _Register_ link is invalid

![image](https://cloud.githubusercontent.com/assets/1266318/13187538/79572cbc-d700-11e5-94ec-178a48940d04.png)

Clicking it presenting the following page:

![image](https://cloud.githubusercontent.com/assets/1266318/13187546/8aa72468-d700-11e5-8deb-4534d4001087.png)

**Comment by michel-cf** [comment]
Url fixed

**Comment by PropGit** [comment]
Verified fixed.  Also noticed the built-in Login fields.  Great!
