### ISSUE TITLE
Improve generated C code

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#983]
Currently functions are placed ahead of main() in the generated C.  Best practice is for them to be declared in front of main(), and defined after it.

**Comment by paragitadmin** [comment]
I agree that this is a best practice, but does implementing this provide any tangible benefit to how the system functions? Modern compilers are quite happy to use the function signatures found in the implementation.

**Comment by MatzElectronics** [comment]
Probably not, but since we are in the teaching business...

**Comment by MatzElectronics** [comment]
Tested and verified - hasn't caused any problems that we know of, so closing this.
