### ISSUE TITLE
Enable awareness of BlocklyPropClient software and updates

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#984]
[@Steph-Parallax @MatzElectronics @pjewald - Need input and action from anyone able to do so.  This issue is for discussion; action will likely deserve other issues for individual solutions.  Items below originated from a talk @Steph-Parallax and @PropGit had.]

Currently, the BlocklyPropClient software is available from the landing page's footer:
![image](https://cloud.githubusercontent.com/assets/1266318/24769582/de69f954-1abb-11e7-86ed-3994cef32008.png)

or the editor's header (only when the BlocklyPropClient is not running and connected):
![image](https://cloud.githubusercontent.com/assets/1266318/24769362/15a772bc-1abb-11e7-9d1d-f279f0d7dddd.png)

We need to make people more aware of the need for BlocklyPropClient, how to get it, and where to get it.  Also, when there's an update, awareness of that update is needed.

__Suggestions Welcome!__

### Notable problems that need solutions:
These are items that need addressing and may deserve their own individual issues to track them.
- [x] The need to download, install, run, and "connect" BlocklyPropClient is not made very clear, except on the second page of the learn-based help links.  Those are great, but we should also make it more self-evident in the browser landing page and editor so that people are naturally led to discover it easily.
  - [x] Add a visually distinct "Getting Started" image/link to the main landing page.  Perhaps the information presented by that link is project agnostic (tells people how to get the system set up; ie: create account, log in, install, run, connect BlocklyPropClient) and provides advertisement leading afterward to the existing learn-based project-centric getting started tutorials.
- [x] The editor's _pink_ error message also doubles as a convenient link to download the client software; however, it doesn't indicate that it, itself, is the solution.  ie: no one knows it's a link unless they happen to mouse over it.
  - [x] Suggestion: Enhance the error message to say, "BlocklyProp-Client is not running.  Click here for instructions." and make the download link provide helpful background details, tips, and the downloads themselves.
- [x] The editor's _pink_ error message is technically wrong.  The client may indeed be running, but not connected... or may be running and connected but not visible to the browser-based system.
  - [x] Suggestion: Enhance the error message to say, "BlocklyProp-Client not found.  Click here for instructions."
- [x] The informational message when searching for the BlocklyPropClient may also need to be a link for instructions.  This is because, at times, that message gets "stuck" on-screen and doesn't progress to the success or error message.
  - [x] Suggestion: Enhance the information message to say, "Looking for BlocklyPropClient.  Click here for instructions."  And have the instructions page also list (in the future) troubleshooting tips we are currently forming from [this BlocklyPropClient Issue](https://github.com/parallaxinc/BlocklyPropClient/issues/84).
- [x] When a newer BlocklyPropClient version is available (relative to the detected one the user may be running) there is no indication of that.  
  - [x] The BlocklyPropClient shares its version number with the BlocklyProp Editor... perhaps we can have the editor automatically provide a notice in the header that indicates an update is available (and is a link to see instructions and downloads).

**Comment by MatzElectronics** [comment]
Tested and Verified
