### ISSUE TITLE
Update Project Details Behavior for Project Links

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#985]
It's unfortunately easy to irreversibly destroy a project's shared link.

Every change made on the Project Details page applies _only_ when the __Save__, __Delete__, or __Clone__ buttons are pressed... _except_ for the "Share project using link" field.  This checkbox and read-only field provides our very valuable auto-generated project link; however, if during a later edit the author unchecks the box, the link is destroyed immediately, is not recoverable, and thereafter doesn't work for anyone it's already been shared with.  The recheck of the checkbox generates a new link instead.

Suggestion: If the checkbox was unchecked, make the previous link persist _until_ the __Save__, __Delete__, or __Clone__ button is pressed (at which point it is only then officially "destroyed"), or, if the author rechecks the box (before clicking __Save__, __Delete__, or __Clone__ buttons) have the previous link "restored" in the field so that an accidental uncheck/recheck action by the author doesn't strand any existing shared link.

I don't know at this time whether the database is immediately updated by the uncheck action, but care needs to be taken to determine that when fixing this issue.

**Comment by MatzElectronics** [comment]
Again, I kind of want to just dump that shared link thing...again, another issue related to it...

**Comment by PropGit** [comment]
What alternative do we have for sharing projects to anonymous users?

**Comment by MatzElectronics** [comment]
The blocks files can be opened with a browser (chrome), so they can see
them.
If we clean up the demo/try it stuff, anonymous users could potentially use
the site with out an account by uploading (since that just means pulling it
into the browser) and editing - they just couldn't save or compile or
load...

**Comment by MatzElectronics** [comment]
Tested, working.
