### ISSUE TITLE
Add helpful "Starting download process..." message

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#994]
### Problem
When BlocklyProp requests to download to the Propeller, it does not receive interactive results in real time; instead, there's a _sometimes long_ delay (while all the work is being done) where it appears nothing is happening, then it receives all result messages at once and display them.

The user experience is seeing something like this (below) for up to 10 seconds:
![image](https://cloud.githubusercontent.com/assets/1266318/24935146/ea703dfe-1ed4-11e7-8ccd-9b4bb843c85c.png)

Then finally the display is updated to be this:
![image](https://cloud.githubusercontent.com/assets/1266318/24935147/eda606ac-1ed4-11e7-9d80-f9c490398853.png)

### Solution
Ideally, an animated activity indicator would appear in the overlay (and would disappear when the screen update occurs); however, a very simple solution that will help the user realize that there _really is something more happening_ is to __display the message "Starting download process..." on the status overlay right before calling BlocklyPropClient to download the application image.__

The "...download..." message will satisfy user concerns like, "Is that it?  Is there something more?" and will shorten the apparent delay; a little psychological trick.

**Comment by JohnKauffman** [comment]
I request this be changed from enhancement to bug and given high priority to fix.  Although from a programmer's perspective it is only an enhancement, from the customer perspective it is a bug because it causes so many failures. Which perspective do we want to use? 

Every user of BlocklyProp has to figure out this problem. Only a few customers get to the device-specific or advanced issues that are labeled here as bugs. Getting it fixed will solve the problem of people walking away from BlocklyProp in the first hour due to failures from pulling cable after message says "Done."

Seems it would not take much programmer time to change that single text line in the underlying code.

**Comment by MatzElectronics** [comment]
Got it - it's a small challenge because I'll have to hijack the serial stream coming in, but I should be able to get it.

**Comment by zfi** [comment]
All the text after 'Compile Successful' is coming from the BlocklyProp client. Adding a 'Downloading' message is relatively trivial. 

The original issue is more complex in that we need to implement a series of asynchronous methods to monitor the loading process and report that back to the browser window.

**Comment by PropGit** [comment]
@MatzElectronics - Isn't BlocklyProp Proper calling the Cloud Compiler, receiving a response, and then calling the BlocklyPropClient?   You shouldn't need to hijack the serial stream; what I requested is that BlocklyProp Proper output the message "Starting download process..." on the status overlay right after it receives and displays the successful compiler response and before it calls upon the BlocklyPropClient to download the application image.

**Comment by JohnKauffman** [comment]
From instructor's perspective, I agree with Matt. For us, no need for
anything dynamic. Just modify literal "Done" to something like: "Done
compile, standby for load" or add a line "Now beginning load..."

n.b. Ensure any additional lines appear in the status overlay within
original frame of text, not after some CRs that would push it below the
default visible lines and require a scroll to see the message.

Feel free to have my students test before general release - we are at your
service with turn-around of one afternoon.

Thanks.

**Comment by MatzElectronics** [comment]
@JohnKauffman Can you verify that this is now there?  This will be greatly improved with the ChromeApp as we bring that online, but I did insert a "for now" solution.  Let me know and if it is working, I'll close this ticket.
Thanks!
